### ISSUE TITLE
In autocomplete, an error occurs when I enter open brackets

### ISSUE THREAD

**Issue by sh2** [continuedev/continue#1038]
### Before submitting your bug report

- [X] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [X] I've seen the [troubleshooting guide](https://continue.dev/docs/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS: Windows 10
- Continue: 0.9.96(preview)
- IDE: VSCode 1.87.2
- LLM: Ollama 0.1.28 on WSL2, starcoder2:15b
```

### Description

When using autocomplete in JavaScript, an error occurs when  I enter open brackets.
Autocomplete itself is working in my environment ;-)

### To reproduce

1. Open a new folder and create a test1.js file.
2. Enter the following string into the file
```
console.log(
```
Windows itself:
![popup_local](https://github.com/continuedev/continue/assets/1710774/6cd86cc3-d132-4214-a3a3-2aaa840c2e8e)

Remote SSH from Windows to Linux:
![popup](https://github.com/continuedev/continue/assets/1710774/fc3fcf45-660f-4167-8509-2f31ce18ecba)

### Log output

```Shell
Windows Logs:
workbench.desktop.main.js:sourcemap:148 [Extension Host] Error generating autocompletion:  Error: Unable to resolve resource c:%5CUsers%5Ctaira%5Cdev%5Collama%5Ctest1.js
    at a.r (vscode-file://vscode-app/c:/Users/taira/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2412:25870)
    at a.r (vscode-file://vscode-app/c:/Users/taira/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2412:25856)
    at async C.acquire (vscode-file://vscode-app/c:/Users/taira/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:37:3392)
    at async u.createModelReference (vscode-file://vscode-app/c:/Users/taira/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2412:27205)

Remote SSH Logs:
console.ts:137 [Extension Host] Error generating autocompletion:  Error: Unable to read file '\taira\nfs\work\20240328_continue\ollama\test1.js' (Error: Unable to resolve nonexistent file '\taira\nfs\work\20240328_continue\ollama\test1.js')
    at n.F (vscode-file://vscode-app/c:/Users/taira/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:653:19968)
    at n.D (vscode-file://vscode-app/c:/Users/taira/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:653:19763)
    at async d.M (vscode-file://vscode-app/c:/Users/taira/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2423:42865)
    at async d.readStream (vscode-file://vscode-app/c:/Users/taira/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2423:42622)
    at async T.Cb (vscode-file://vscode-app/c:/Users/taira/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2412:13526)
    at async T.resolve (vscode-file://vscode-app/c:/Users/taira/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2412:11973)
    at async r.W (vscode-file://vscode-app/c:/Users/taira/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2423:39016)
    at async a.r (vscode-file://vscode-app/c:/Users/taira/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2412:25628)
    at async C.acquire (vscode-file://vscode-app/c:/Users/taira/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:37:3392)
    at async u.createModelReference (vscode-file://vscode-app/c:/Users/taira/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2412:27205)
```

**Comment by mariusgau** [comment]
I can confirm the exact same error.
```
- OS: Windows 11
- Continue: 0.9.103(preview)
- IDE: VSCode 1.87.2
```

**Comment by nwesterhausen** [comment]
Happens for me as well:

```
- OS: Windows 11
- Continue: v0.9.119 (pre-release)
- IDE: VSCode 1.89.0-insider
- LLM: Ollama 0.1.32(on windows) running starcoder2 for autocomplete
```

```
console.ts:137 [Extension Host] Error generating autocompletion:  Error: Unable to resolve resource g:%5Crepos%5Celementalist%5Cgame%5Csrc%5Cresources%5Cplugin.rs
    at d.r (vscode-file://vscode-app/c:/Users/nwest/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2190:27489)
    at d.r (vscode-file://vscode-app/c:/Users/nwest/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2190:27475)
    at async k.acquire (vscode-file://vscode-app/c:/Users/nwest/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:37:3350)
    at async f.createModelReference (vscode-file://vscode-app/c:/Users/nwest/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2190:28824) (at console.<anonymous> (c:\Users\nwest\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:143:59509))
w @ console.ts:137
$logExtensionHostMessage @ mainThreadConsole.ts:39
S @ rpcProtocol.ts:458
Q @ rpcProtocol.ts:443
M @ rpcProtocol.ts:373
L @ rpcProtocol.ts:299
(anonymous) @ rpcProtocol.ts:161
y @ event.ts:1156
fire @ event.ts:1187
fire @ ipc.net.ts:650
H.onmessage @ localProcessExtensionHost.ts:378
```

**Comment by wuchaojsyz** [comment]
use  vscode.Uri.file instead of  vscode.Uri.parse?
