### ISSUE TITLE
RangeError after launching vscode

### ISSUE THREAD

**Issue by Niqnil** [continuedev/continue#1043]
### Before submitting your bug report

- [X] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [X] I've seen the [troubleshooting guide](https://continue.dev/docs/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS: Ubuntu 22.04.4
- Continue: v0.8.22
- IDE: vscode
```

### Description

Message:
```
Error loading submenu items from file: RangeError: path should be a `path.relative()`d string, but got "..."
```

### To reproduce

1. Launch vscode
2. Notifications appear at bottom right
3. Check logs using Toggle Developer Tools

![image](https://i.ibb.co/gvhXHXm/image.png)

### Log output

Logs (username redacted):
```
notificationsAlerts.ts:42 Error loading submenu items from folder: RangeError: path should be a `path.relative()`d string, but got "..."
c @ notificationsAlerts.ts:42
notificationsAlerts.ts:42 Error loading submenu items from file: RangeError: path should be a `path.relative()`d string, but got "..."
c @ notificationsAlerts.ts:42
console.ts:137 [Extension Host] rejected promise not handled within 1 second: RangeError: path should be a `path.relative()`d string, but got "..."
p @ console.ts:137
console.ts:137 [Extension Host] stack trace: RangeError: path should be a `path.relative()`d string, but got "..."
    at throwError (/home/[redacted]/.vscode/extensions/continue.continue-0.8.22-linux-x64/out/extension.js:328157:13)
    at checkPath (/home/[redacted]/.vscode/extensions/continue.continue-0.8.22-linux-x64/out/extension.js:328171:16)
    at Ignore._test (/home/[redacted]/.vscode/extensions/continue.continue-0.8.22-linux-x64/out/extension.js:328259:9)
    at Ignore.ignores (/home/[redacted]/.vscode/extensions/continue.continue-0.8.22-linux-x64/out/extension.js:328286:21)
    at traverseDirectory (/home/[redacted]/.vscode/extensions/continue.continue-0.8.22-linux-x64/out/extension.js:328344:32)
    at traverseDirectory (/home/[redacted]/.vscode/extensions/continue.continue-0.8.22-linux-x64/out/extension.js:328406:24)
    at traverseDirectory (/home/[redacted]/.vscode/extensions/continue.continue-0.8.22-linux-x64/out/extension.js:328406:24)
    at traverseDirectory (/home/[redacted]/.vscode/extensions/continue.continue-0.8.22-linux-x64/out/extension.js:328406:24)
    at _VsCodeIdeUtils.getDirectoryContents (/home/[redacted]/.vscode/extensions/continue.continue-0.8.22-linux-x64/out/extension.js:328697:26)
    at VsCodeIde.listWorkspaceContents (/home/[redacted]/.vscode/extensions/continue.continue-0.8.22-linux-x64/out/extension.js:329033:18)
    at VsCodeIde.getStats (/home/[redacted]/.vscode/extensions/continue.continue-0.8.22-linux-x64/out/extension.js:328994:23)
    at CodebaseIndexer.refresh (/home/[redacted]/.vscode/extensions/continue.continue-0.8.22-linux-x64/out/extension.js:187557:25)
    at _VsCodeExtension.refreshCodebaseIndex (/home/[redacted]/.vscode/extensions/continue.continue-0.8.22-linux-x64/out/extension.js:329944:26)
p @ console.ts:137
mainThreadExtensionService.ts:81 [Continue.continue]path should be a `path.relative()`d string, but got "..."
$onExtensionRuntimeError @ mainThreadExtensionService.ts:81
mainThreadExtensionService.ts:82 RangeError: path should be a `path.relative()`d string, but got "..."
    at throwError (vscode-file://vscode-app/home/[redacted]/.vscode/extensions/continue.continue-0.8.22-linux-x64/out/extension.js:328157:13)
    at checkPath (vscode-file://vscode-app/home/[redacted]/.vscode/extensions/continue.continue-0.8.22-linux-x64/out/extension.js:328171:16)
    at Ignore._test (vscode-file://vscode-app/home/[redacted]/.vscode/extensions/continue.continue-0.8.22-linux-x64/out/extension.js:328259:9)
    at Ignore.ignores (vscode-file://vscode-app/home/[redacted]/.vscode/extensions/continue.continue-0.8.22-linux-x64/out/extension.js:328286:21)
    at traverseDirectory (vscode-file://vscode-app/home/[redacted]/.vscode/extensions/continue.continue-0.8.22-linux-x64/out/extension.js:328344:32)
    at traverseDirectory (vscode-file://vscode-app/home/[redacted]/.vscode/extensions/continue.continue-0.8.22-linux-x64/out/extension.js:328406:24)
    at traverseDirectory (vscode-file://vscode-app/home/[redacted]/.vscode/extensions/continue.continue-0.8.22-linux-x64/out/extension.js:328406:24)
    at traverseDirectory (vscode-file://vscode-app/home/[redacted]/.vscode/extensions/continue.continue-0.8.22-linux-x64/out/extension.js:328406:24)
    at _VsCodeIdeUtils.getDirectoryContents (vscode-file://vscode-app/home/[redacted]/.vscode/extensions/continue.continue-0.8.22-linux-x64/out/extension.js:328697:26)
    at VsCodeIde.listWorkspaceContents (vscode-file://vscode-app/home/[redacted]/.vscode/extensions/continue.continue-0.8.22-linux-x64/out/extension.js:329033:18)
    at VsCodeIde.getStats (vscode-file://vscode-app/home/[redacted]/.vscode/extensions/continue.continue-0.8.22-linux-x64/out/extension.js:328994:23)
    at CodebaseIndexer.refresh (vscode-file://vscode-app/home/[redacted]/.vscode/extensions/continue.continue-0.8.22-linux-x64/out/extension.js:187557:25)
    at _VsCodeExtension.refreshCodebaseIndex (vscode-file://vscode-app/home/[redacted]/.vscode/extensions/continue.continue-0.8.22-linux-x64/out/extension.js:329944:26)
$onExtensionRuntimeError @ mainThreadExtensionService.ts:82
```

**Comment by sestinj** [comment]
@Niqnil A couple of small pieces of information that might help me figure out what's going on: are you on SSH or anything, or just a local workspace? And then is there any file/folder that has "..." in it, or something that you think could plausibly lead to escaping issues?

**Comment by Niqnil** [comment]
It is a local workspace.
Folder and file names do not have "..." but there are comment lines in various .py for documentation, for example:
```
        #              "update":{
        #                 "asks":[
        #                    [
        #                       "43755.46",
        #                       "0.10000",
        #                       "1"
        #                    ],
        #                    ...
        #                 ],
        #                 "bids":[
        #                    [
        #                       "43737.46",
        #                       "0.14096",
        #                       "1"
        #                    ],
        #                    ...
        #                 ]
        #              },
```

I noticed that Indexing is stuck at 1% and does not progress. That seems to be the only unusual thing. Tab autocomplete and chat are working.

I tried changing embeddingsProvider and restarted but still got the error.

From
```
  "embeddingsProvider": {
    "provider": "transformers.js"
  }
```
to
```
"embeddingsProvider": {
    "provider": "openai",
    "model": "text-embedding-3-small"
  }
```

**Comment by RomneyDa** [comment]
@Niqnil if possible could you verify if you're still having this issue on the current release of Continue?

**Comment by Niqnil** [comment]
@RomneyDa no issue on version 0.8.68. I think you can close this.
