### ISSUE TITLE
Rider plugin 0.0.40 startup error

### ISSUE THREAD

**Issue by DJ4ddi** [continuedev/continue#1058]
### Before submitting your bug report

- [X] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [X] I've seen the [troubleshooting guide](https://continue.dev/docs/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS: Windows 11 Pro 10.0.22631
- Continue: 0.0.40
- IDE: JetBrains Rider 2023.3.2
```

### Description

When starting Rider with the latest version of the Continue plugin, an error is thrown (see attached log). The UI launches, but no configuration is loaded. No logs are written to `~/.continue/core.log`.

Downgrading to 0.0.39 works without issues. Available on [Discord](https://discord.com/channels/1108621136150929458/1224708844538564761) for feedback.

### To reproduce

1. Install affected versions.
2. Open any solution in Rider.

### Log output

```Shell
2024-04-02 15:09:46,703 [  10647]   INFO - STDOUT - Core process exited with output: C:\snapshot\continue-deploy\binary\out\index.js:13134
2024-04-02 15:09:46,703 [  10647]   INFO - STDOUT -             throw e2;
2024-04-02 15:09:46,703 [  10647]   INFO - STDOUT -             ^
2024-04-02 15:09:46,703 [  10647]   INFO - STDOUT - 
2024-04-02 15:09:46,703 [  10647]   INFO - STDOUT - Error: \\?\C:\Users\aha\AppData\Roaming\JetBrains\Rider2023.3\plugins\continue-intellij-extension\core\build\Release\node_sqlite3.node is not a valid Win32 application.
2024-04-02 15:09:46,703 [  10647]   INFO - STDOUT - 
2024-04-02 15:09:46,703 [  10647]   INFO - STDOUT - \\?\C:\Users\aha\AppData\Roaming\JetBrains\Rider2023.3\plugins\continue-intellij-extension\core\build\Release\node_sqlite3.node
2024-04-02 15:09:46,703 [  10647]   INFO - STDOUT -     at process.dlopen (pkg/prelude/bootstrap.js:2251:28)
2024-04-02 15:09:46,703 [  10647]   INFO - STDOUT -     at Module._extensions..node (node:internal/modules/cjs/loader:1196:18)
2024-04-02 15:09:46,703 [  10647]   INFO - STDOUT -     at Module.load (node:internal/modules/cjs/loader:988:32)
2024-04-02 15:09:46,703 [  10647]   INFO - STDOUT -     at Module._load (node:internal/modules/cjs/loader:834:12)
2024-04-02 15:09:46,703 [  10647]   INFO - STDOUT -     at Module.require (node:internal/modules/cjs/loader:1012:19)
2024-04-02 15:09:46,703 [  10647]   INFO - STDOUT -     at Module.require (pkg/prelude/bootstrap.js:1851:31)
2024-04-02 15:09:46,703 [  10647]   INFO - STDOUT -     at require (node:internal/modules/cjs/helpers:102:18)
2024-04-02 15:09:46,703 [  10647]   INFO - STDOUT -     at bindings (C:\snapshot\continue-deploy\binary\out\index.js:13127:52)
2024-04-02 15:09:46,703 [  10647]   INFO - STDOUT -     at ../core/node_modules/sqlite3/lib/sqlite3-binding.js (C:\snapshot\continue-deploy\binary\out\index.js:13199:41)
2024-04-02 15:09:46,703 [  10647]   INFO - STDOUT -     at __require (C:\snapshot\continue-deploy\binary\out\index.js:18:51) {
2024-04-02 15:09:46,703 [  10647]   INFO - STDOUT -   code: 'ERR_DLOPEN_FAILED'
2024-04-02 15:09:46,703 [  10647]   INFO - STDOUT - }
2024-04-02 15:09:46,703 [  10647]   INFO - STDOUT - 
2024-04-02 15:09:46,703 [  10647]   INFO - STDOUT - Node.js v18.5.0
```

**Comment by sestinj** [comment]
@DJ4ddi @iandeveseleer @mikelfried This has been solved and confirmed by a number of users in 0.0.41. Thank you for the quick report!
