### ISSUE TITLE
Continue plugin hangs when tried from corporate laptop.  Likely need any IP / Host whitelisting information to avoid the issue.

### ISSUE THREAD

**Issue by sureshnomura** [continuedev/continue#1140]
### Before submitting your bug report

- [X] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [X] I've seen the [troubleshooting guide](https://continue.dev/docs/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS:Windows 10
- Continue:0.0.43
- IDE:Intellij 2024.1
```

### Description

Plugin hangs when tried to attempt basic chat from plugin.  

![image](https://github.com/continuedev/continue/assets/147630826/5e25f47f-030e-4523-9a84-5dfc5ae57f0a)

### Log output

```Shell
[info] Starting Continue core... 
FetchError: request to https://proxy-server-blue-l6vsfbzhba-uw.a.run.app/stream_chat failed, reason: connect ETIMEDOUT 216.239.32.53:443 
Error running handler for "llm/streamChat":  FetchError: request to https://proxy-server-blue-l6vsfbzhba-uw.a.run.app/stream_chat failed, reason: connect ETIMEDOUT 216.239.32.53:443
FetchError: request to https://proxy-server-blue-l6vsfbzhba-uw.a.run.app/stream_chat failed, reason: connect ETIMEDOUT 216.239.32.53:443 
FetchError: request to https://proxy-server-blue-l6vsfbzhba-uw.a.run.app/stream_chat failed, reason: connect ETIMEDOUT 216.239.32.53:443 
Error running handler for "llm/streamChat":  FetchError: request to https://proxy-server-blue-l6vsfbzhba-uw.a.run.app/stream_chat failed, reason: connect ETIMEDOUT 216.239.32.53:443
FetchError: request to https://proxy-server-blue-l6vsfbzhba-uw.a.run.app/stream_chat failed, reason: connect ETIMEDOUT 216.239.32.53:443 
FetchError: request to https://proxy-server-blue-l6vsfbzhba-uw.a.run.app/stream_chat failed, reason: connect ETIMEDOUT 216.239.32.53:443 
Error running handler for "llm/streamChat":  FetchError: request to https://proxy-server-blue-l6vsfbzhba-uw.a.run.app/stream_chat failed, reason: connect ETIMEDOUT 216.239.32.53:443
FetchError: request to https://proxy-server-blue-l6vsfbzhba-uw.a.run.app/stream_chat failed, reason: connect ETIMEDOUT 216.239.32.53:443 
[info] Exiting Continue core...
```

**Comment by sestinj** [comment]
@sureshnomura We have a new version on the way (0.0.45) that should be accepted to the JetBrains store tomorrow. This will fix known issues with local certificate authority.

Just in case that doesn't solve your problem, can you share more about what you expect to be needed related to IP / Host whitelisting?

**Comment by sureshveda** [comment]
If the plugin is making API calls to some central service for suggestions, we need to whitelist those endpoints at the corporate firewall end to make this work.  I am just looking for the host / endpoint that should be whitelisted by my company.

**Comment by sestinj** [comment]
@sureshveda I understand now, thanks for clarifying. While you are using the free trial models, the hosts you'll want to whitelist are:
- `proxy-server-blue-l6vsfbzhba-uw.a.run.app`
- `proxy-server-green-l6vsfbzhba-uw.a.run.app`

and the endpoints used for both are /stream_complete, /stream_chat, /embeddings, and /rerank (all POST requests). We rotate between green and blue when we make updates.

If you end up configuring any other non-local models beyond the free trial you'll have to whitelist the host for whichever service you set up.

**Comment by sestinj** [comment]
Hi @sureshveda, I wanted to check in on this—have you had any luck setting up Continue, or is there anything else I can do to help? If it would ever be helpful to talk this through live, I do weekly "Office Hours" on Discord on Wednesdays at 10am PST

**Comment by tongrenjie** [comment]
@sestinj Hi, I'm having this issue as well, but I don't understand how to fix it. So can you explain a little bit more specifically?

**Comment by sestinj** [comment]
@tongrenjie this is likely a network-specific problem. If you can share your logs I can try to give more guidance, but more than likely there is something specific you need to configure in your network environment (e.g. an allow-list) that will stop that particular URL from being stopped by a firewall

**Comment by tongrenjie** [comment]
Hello, the following is the log file. It is worth noting that after installing on Pycharm, I was able to use it at first. The "continue"  told me that I needed to install Git, and after installing Git, it became unusable.
java.lang.NullPointerException: Cannot invoke "com.intellij.openapi.Disposable.dispose()" because the return value of "com.intellij.openapi.util.Ref.get()" is null
	at com.github.continuedev.continueintellijextension.editor.InlineEditActionKt$openInlineEdit$diffStreamHandler$1.invoke(InlineEditAction.kt:151)
	at com.github.continuedev.continueintellijextension.editor.InlineEditActionKt$openInlineEdit$diffStreamHandler$1.invoke(InlineEditAction.kt:150)
	at com.github.continuedev.continueintellijextension.editor.DiffStreamHandler.reject(DiffStreamHandler.kt:158)
	at com.github.continuedev.continueintellijextension.editor.DiffStreamService.register(DiffStreamService.kt:12)
	at com.github.continuedev.continueintellijextension.editor.InlineEditActionKt.openInlineEdit(InlineEditAction.kt:156)
	at com.github.continuedev.continueintellijextension.editor.InlineEditAction.actionPerformed(InlineEditAction.kt:245)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.doPerformActionOrShowPopup(ActionUtil.java:333)
	at com.intellij.openapi.keymap.impl.ActionProcessor.performAction(ActionProcessor.java:47)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher$1.performAction(IdeKeyEventDispatcher.java:585)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.lambda$doPerformActionInner$9(IdeKeyEventDispatcher.java:707)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:105)
	at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:94)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.lambda$doPerformActionInner$10(IdeKeyEventDispatcher.java:707)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performDumbAwareWithCallbacks(ActionUtil.java:356)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.doPerformActionInner(IdeKeyEventDispatcher.java:704)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:648)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:596)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processActionOrWaitSecondStroke(IdeKeyEventDispatcher.java:480)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.inInitState(IdeKeyEventDispatcher.java:469)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.dispatchKeyEvent(IdeKeyEventDispatcher.java:225)
	at com.intellij.ide.IdeEventQueue.dispatchKeyEvent(IdeEventQueue.kt:598)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.kt:568)
	at com.intellij.ide.IdeEventQueue.access$_dispatchEvent(IdeEventQueue.kt:68)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:349)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:348)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:787)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:348)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:343)
	at com.intellij.ide.IdeEventQueueKt.performActivity$lambda$1(IdeEventQueue.kt:994)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:113)
	at com.intellij.ide.IdeEventQueueKt.performActivity(IdeEventQueue.kt:994)
	at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$4(IdeEventQueue.kt:343)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:831)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.kt:385)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
