### ISSUE TITLE
[CON-231] Autocomplete cannot read file on Windows SSH to Linux

### ISSUE THREAD

**Issue by sestinj** [continuedev/continue#1194]
### Before submitting your bug report

- [X] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [X] I've seen the [troubleshooting guide](https://continue.dev/docs/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS:Windows, SSH to Linux
- Continue:*
- IDE:VS Code
```

### Description

Happens after opening parenthesis is typed, caused by attempting to use LSP to find the definition of the file

### To reproduce

*No response*

### Log output

```Shell
Error generating autocompletion:  Error: Unable to read file '\path\to\file' (Error: Unable to resolve nonexistent file '\path\to\file')
    at n.F (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:657:19968)
    at n.D (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:657:19763)
    at async l.M (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2370:42596)
    at async l.readStream (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2370:42353)
    at async L.Cb (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2359:13615)
    at async L.resolve (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2359:12062)
    at async s.W (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2370:38746)
    at async u.r (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2359:25720)
    at async k.acquire (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:37:3320)
    at async d.createModelReference (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2359:27297)
```

<sub>From [SyncLinear.com](https://synclinear.com) | [CON-231](https://linear.app/continue/issue/CON-231/autocomplete-cannot-read-file-on-windows-ssh-to-linux)</sub>

**Comment by MichelePrimavera** [comment]
Same issue "Error loading submenu items from file: EntryNotFound (FileSystemError): Unable to resolve nonexistent file 'vscode-remote://wsl/home/gianluca/projects/srm/workspace/directus/api/extensions/hooks/init-config-data/data/1#srm_types'"
