### ISSUE TITLE
authentication header not picked up for ollama provider

### ISSUE THREAD

**Issue by jopdorp** [continuedev/continue#1331]
### Before submitting your bug report

- [X] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [X] I've seen the [troubleshooting guide](https://docs.continue.dev/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS: Ubuntu 22.04
- Continue: v0.9.138
- IDE: VSCode 1.89.1
```

### Description

I think this is probably due to the requestOptions.headers are not being picked up somehow.

### To reproduce

1. configure an ollama provider with basic auth like so:
```
"models": [
    {
      "title": "llama3",
      "provider": "ollama",
      "model": "llama3:instruct",
      "apiBase": "https://ollama.myinstance.cloud",
      "requestOptions": {
        "headers": {
          "Authorization":"Basic somebase64encodedauth"
        }
      }
    }
  ]
```
2. say hi to your continue chat.

### Log output

```Shell
mountTo @ workbench.desktop.main.js:sourcemap:1237
workbench.desktop.main.js:sourcemap:152 [Extension Host] Error: Error: HTTP 401 Unauthorized from https://ollama.llm.domains.leaf.cloud/api/chat

<html>
<head><title>401 Authorization Required</title></head>
<body>
<center><h1>401 Authorization Required</h1></center>
<hr><center>nginx</center>
</body>
</html>

	at customFetch (/home/jopdorp/.vscode/extensions/continue.continue-0.9.138-linux-x64/out/extension.js:35834:19)
	at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
	at async withExponentialBackoff (/home/jopdorp/.vscode/extensions/continue.continue-0.9.138-linux-x64/out/extension.js:35608:26)
	at async Ollama._streamChat (/home/jopdorp/.vscode/extensions/continue.continue-0.9.138-linux-x64/out/extension.js:45444:26)
	at async Ollama.streamChat (/home/jopdorp/.vscode/extensions/continue.continue-0.9.138-linux-x64/out/extension.js:35962:30)
	at async llmStreamChat (/home/jopdorp/.vscode/extensions/continue.continue-0.9.138-linux-x64/out/extension.js:333836:23)
	at async a.value (/home/jopdorp/.vscode/extensions/continue.continue-0.9.138-linux-x64/out/extension.js:334102:29)
workbench.desktop.main.js:sourcemap:656   ERR [Extension Host] Error handling webview message: {
  "msg": {
    "messageId": "dee3d486-35df-463a-b929-e53a3d332baf",
    "messageType": "llm/streamChat",
    "data": {
      "messages": [
        {
          "role": "user",
          "content": [
            {
              "type": "text",
              "text": "hi"
            }
          ]
        }
      ],
      "title": "llama3",
      "completionOptions": {}
    }
  }
}
workbench.desktop.main.js:sourcemap:152 [Extension Host] Error handling webview message: {
  "msg": {
    "messageId": "dee3d486-35df-463a-b929-e53a3d332baf",
    "messageType": "llm/streamChat",
    "data": {
      "messages": [
        {
          "role": "user",
          "content": [
            {
              "type": "text",
              "text": "hi"
            }
          ]
        }
      ],
      "title": "llama3",
      "completionOptions": {}
    }
  }
}
```

**Comment by CollinCashio** [comment]
I am encountering this as well

**Comment by sestinj** [comment]
@jopdorp @CollinCashio I believe I coincidentally just merged an update to the pre-release this morning that should solve this. I've tested in debug mode with this model in my config.json


```json
{
      "title": "Llama3-8b",
      "model": "llama3-8b",
      "requestOptions": {
        "headers": {
          "Authorization": "Basic xxx"
        }
      },
      "provider": "ollama"
    }
    ```
    
    And the fix was here: https://github.com/continuedev/continue/commit/e150f7d26fb076bcdfb1832013ecbff2b93b060d
    
 Let me know if this solves it for you or not!

**Comment by jopdorp** [comment]
That solved it, thanks!

**Comment by CollinCashio** [comment]
Yes - it is working now. Thank you! @sestinj
