### ISSUE TITLE
Can't load continue plugin in Android Studio IDE

### ISSUE THREAD

**Issue by edeuser** [continuedev/continue#1348]
### Before submitting your bug report

- [X] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [X] I've seen the [troubleshooting guide](https://docs.continue.dev/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS:Mac M2
- Continue:0.0.42
- IDE:Android Studio

Install Continue in Android studio IDE, error report:
java.lang.IllegalStateException: JCEF is not supported in this env or failed to initialize
	at com.intellij.ui.jcef.JBCefApp.getInstance(JBCefApp.java:122)
	at com.intellij.ui.jcef.JBCefBrowserBase.lambda$new$3(JBCefBrowserBase.java:157)
	at com.intellij.util.ObjectUtils.notNull(ObjectUtils.java:121)
	at com.intellij.ui.jcef.JBCefBrowserBase.<init>(JBCefBrowserBase.java:157)
	at com.intellij.ui.jcef.JBCefBrowser.<init>(JBCefBrowser.java:190)
	at com.intellij.ui.jcef.JBCefBrowser.create(JBCefBrowser.java:140)
	at com.intellij.ui.jcef.JBCefBrowserBuilder.build(JBCefBrowserBuilder.java:127)
	at com.github.continuedev.continueintellijextension.toolWindow.ContinueBrowser.<init>(ContinueBrowser.kt:66)
	at com.github.continuedev.continueintellijextension.toolWindow.ContinueBrowser.<init>(ContinueBrowser.kt:21)
	at com.github.continuedev.continueintellijextension.toolWindow.ContinuePluginToolWindowFactory$ContinuePluginWindow$browser$2.invoke(ContinuePluginToolWindowFactory.kt:56)
	at com.github.continuedev.continueintellijextension.toolWindow.ContinuePluginToolWindowFactory$ContinuePluginWindow$browser$2.invoke(ContinuePluginToolWindowFactory.kt:51)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at com.github.continuedev.continueintellijextension.toolWindow.ContinuePluginToolWindowFactory$ContinuePluginWindow.getBrowser(ContinuePluginToolWindowFactory.kt:51)
	at com.github.continuedev.continueintellijextension.toolWindow.ContinuePluginToolWindowFactory$ContinuePluginWindow.getContent(ContinuePluginToolWindowFactory.kt:66)
	at com.github.continuedev.continueintellijextension.toolWindow.ContinuePluginToolWindowFactory.createToolWindowContent(ContinuePluginToolWindowFactory.kt:20)
	at com.intellij.openapi.wm.impl.ToolWindowImpl.createContentIfNeeded(ToolWindowImpl.kt:594)
	at com.intellij.openapi.wm.impl.ToolWindowImpl.scheduleContentInitializationIfNeeded$intellij_platform_ide_impl(ToolWindowImpl.kt:573)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl.doShowWindow(ToolWindowManagerImpl.kt:1035)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl.showToolWindowImpl(ToolWindowManagerImpl.kt:969)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl.activateToolWindow$intellij_platform_ide_impl(ToolWindowManagerImpl.kt:672)
	at
```

**Comment by edeuser** [comment]
Android Studio version:
![Uploading image.png…]()

**Comment by kolgx** [comment]
https://github.com/continuedev/continue/issues/596#issuecomment-1789327178
