### ISSUE TITLE
[IntelliJ Plugin] Unauthorised when using Mistral Codestral (despite proper config which work for VSCode)

### ISSUE THREAD

**Issue by tajchert** [continuedev/continue#1396]
### Before submitting your bug report

- [X] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [X] I've seen the [troubleshooting guide](https://docs.continue.dev/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS: macOS 14.5
- Continue: 0.0.49
- IDE: IntelliJ IDEA 2024.2 EAP (Community Edition) also Android Studio Jellyfish | 2023.3.1 Patch 1
- Model: Mistral Codestral
```

### Description

Continue.dev plugin doesn't seems to correctly work with Mistral Codestral, same model config works perfectly for Continue.dev plugin for VSCode but results in `HTTP 401 Unauthorized  from https://codestral.mistral.ai/v1/chat/completions`

Continue plugin config I'm using is:
```
    {
      "title": "Codestral - Mistral",
      "provider": "mistral",
      "model": "codestral-latest",
      "apiKey": "[API_KEY]"
    },
```
Where API_KEY is replaced with proper key. Seems like plugin for IntelliJ doesn't work proper (yet) with Mistral Codestral.

### To reproduce

1. Configure Mistral Codestral according to https://docs.continue.dev/walkthroughs/set-up-codestral
2. Open IntelliJ or Android Studio
3. Use latest Continue.dev plugin (0.0.49) for IntelliJ
4. Use it ex. CMD+J with highlighted code, add message 
Result is : `HTTP 401 Unauthorized  from https://codestral.mistral.ai/v1/chat/completions` even as same steps but in VSCode with same config works fine.

### Log output

```Shell
[2024-05-30T14:02:03] Error: HTTP 401 Unauthorized from https://api.mistral.ai/v1/chat/completions

{
  "message":"Unauthorized",
  "request_id":"b123a93ebdd331585f834d5832bd087f"
}

Code: undefined
Error number: undefined
Syscall: undefined
Type: undefined

Error: HTTP 401 Unauthorized from https://api.mistral.ai/v1/chat/completions

{
  "message":"Unauthorized",
  "request_id":"b123a93ebdd331585f834d5832bd087f"
}
    at customFetch (/snapshot/continue-deploy/binary/out/index.js:334480:17)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async withExponentialBackoff (/snapshot/continue-deploy/binary/out/index.js:334269:22)
    at async _Mistral._streamChat (/snapshot/continue-deploy/binary/out/index.js:334998:22)
    at async _Mistral.streamChat (/snapshot/continue-deploy/binary/out/index.js:334673:26)
    at async llmStreamChat (/snapshot/continue-deploy/binary/out/index.js:359857:19)
    at async /snapshot/continue-deploy/binary/out/index.js:360324:30 
[2024-05-30T14:02:03] Error running handler for "llm/streamChat":  Error: HTTP 401 Unauthorized from https://api.mistral.ai/v1/chat/completions

{
  "message":"Unauthorized",
  "request_id":"b123a93ebdd331585f834d5832bd087f"
}

Code: undefined
Error number: undefined
Syscall: undefined
Type: undefined

Error: HTTP 401 Unauthorized from https://api.mistral.ai/v1/chat/completions

{
  "message":"Unauthorized",
  "request_id":"b123a93ebdd331585f834d5832bd087f"
}
    at customFetch (/snapshot/continue-deploy/binary/out/index.js:334480:17)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async withExponentialBackoff (/snapshot/continue-deploy/binary/out/index.js:334269:22)
    at async _Mistral._streamChat (/snapshot/continue-deploy/binary/out/index.js:334998:22)
    at async _Mistral.streamChat (/snapshot/continue-deploy/binary/out/index.js:334673:26)
    at async llmStreamChat (/snapshot/continue-deploy/binary/out/index.js:359857:19)
    at async /snapshot/continue-deploy/binary/out/index.js:360324:30
[2024-05-30T14:02:03] Error: HTTP 401 Unauthorized from https://api.mistral.ai/v1/chat/completions

{
  "message":"Unauthorized",
  "request_id":"b123a93ebdd331585f834d5832bd087f"
}

Code: undefined
Error number: undefined
Syscall: undefined
Type: undefined

Error: HTTP 401 Unauthorized from https://api.mistral.ai/v1/chat/completions

{
  "message":"Unauthorized",
  "request_id":"b123a93ebdd331585f834d5832bd087f"
}
    at customFetch (/snapshot/continue-deploy/binary/out/index.js:334480:17)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async withExponentialBackoff (/snapshot/continue-deploy/binary/out/index.js:334269:22)
    at async _Mistral._streamChat (/snapshot/continue-deploy/binary/out/index.js:334998:22)
    at async _Mistral.streamChat (/snapshot/continue-deploy/binary/out/index.js:334673:26)
    at async llmStreamChat (/snapshot/continue-deploy/binary/out/index.js:359857:19)
    at async /snapshot/continue-deploy/binary/out/index.js:360324:30
```

**Comment by sestinj** [comment]
@tajchert They recently changed the API endpoint to codestral.mistral.ai instead of api.mistral.ai, and our updated JetBrains extension is waiting on approval from the store. In the meantime, you will have to specify apiBase: "https://codestral.mistral.ai/v1" in config.json. We will update the docs with this info

**Comment by sestinj** [comment]
Your assumption should have been safe, just the last second change caught us off guard. Docs are updated and look out for a new version later this week!

**Comment by zboyles** [comment]
I received a similar error in vscode but no variation of "https://codestral.mistral.ai/v1" or "https://api.mistral.ai/v1" would work when the provider was set to `mistral`. Specifying the following seems to have resolved the issues for the moment.

```json
    {
      "title": "Codestral",
      "model": "codestral-latest",
      "contextLength": 32000,
      "provider": "openai",
      "apiBase": "https://api.mistral.ai/v1",
      "apiKey": "..."
    }
    ```

and
```json

  "tabAutocompleteModel": {
    "title": "Codestralcomplete",
    "provider": "openai",
    "model": "codestral-latest",
    "apiBase": "https://api.mistral.ai/v1",
    "apiKey": "..."
  }
```

**Comment by Malakof** [comment]
It seems that either your API key or your apiBase is not right. If you use the API key from free Codestral preview https://console.mistral.ai/codestral the endpoint will be https://codestral.mistral.ai/v1. If you use a normal API key the usage will be paid and the endpoint will be the normal api.mistral.ai

**Comment by sestinj** [comment]
Sounds like this has been resolved, so I'm going to close the issue. Let me know if there are still any issues!

**Comment by agarwalsourabh55** [comment]
I faced the same issue then I have defined the endpoint as "https://codestral.mistral.ai/v1/chat/completions" and it resolved the unauthorized access issue.
Now I am facing different issue that is "Error 404 Message {"details": "Not FOund"}. Not sure why its coming as I have defined everything correctly.
<img width="650" alt="codemistral" src="https://github.com/continuedev/continue/assets/44107625/7af942e8-e8f9-4e4c-9eda-0fb885c24c41">

**Comment by rsandler00** [comment]
It seems like it changed again. Now need to add

```
https://codestral.mistral.ai/v1/fim/completions
```
