### ISSUE TITLE
Constant notifications... 

### ISSUE THREAD

**Issue by devinschumacher** [continuedev/continue#1427]
### Before submitting your bug report

- [X] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [ ] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [ ] I've seen the [troubleshooting guide](https://docs.continue.dev/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS: mac
- Continue: v0.8.39
- IDE: vscode
```

### Description

Constant annoying notifications (and ive even 'disabled notifications')

See:

![Screenshot 2024-06-05 at 20 32 42](https://github.com/continuedev/continue/assets/45643901/91da3e5e-baf1-4720-b04d-2b4842067988)

![Screenshot 2024-06-05 at 20 32 45](https://github.com/continuedev/continue/assets/45643901/5f0d692b-c898-460c-9b8f-98f624984f79)

### To reproduce

Not sure

### Log output

```Shell
console.ts:137 [Extension Host] Error generating autocompletion:  Error: HTTP 429 Too Many Requests from https://proxy-server-blue-l6vsfbzhba-uw.a.run.app/stream_fim

You have exceeded the maximum number of requests for the free trial.
    at customFetch (/Users/devin/.vscode/extensions/continue.continue-0.8.39-darwin-arm64/out/extension.js:37238:19)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at withExponentialBackoff (/Users/devin/.vscode/extensions/continue.continue-0.8.39-darwin-arm64/out/extension.js:36983:26)
    at FreeTrial._streamFim (/Users/devin/.vscode/extensions/continue.continue-0.8.39-darwin-arm64/out/extension.js:69394:22)
    at FreeTrial.streamFim (/Users/devin/.vscode/extensions/continue.continue-0.8.39-darwin-arm64/out/extension.js:37289:26)
    at ListenableGenerator._start (/Users/devin/.vscode/extensions/continue.continue-0.8.39-darwin-arm64/out/extension.js:41212:28)
w @ console.ts:137
console.ts:137 [Extension Host] HTTP 429 Too Many Requests from https://proxy-server-blue-l6vsfbzhba-uw.a.run.app/stream_fim

You have exceeded the maximum number of requests for the free trial.

Code: undefined
Error number: undefined
Syscall: undefined
Type: undefined

Error: HTTP 429 Too Many Requests from https://proxy-server-blue-l6vsfbzhba-uw.a.run.app/stream_fim

You have exceeded the maximum number of requests for the free trial.
    at customFetch (/Users/devin/.vscode/extensions/continue.continue-0.8.39-darwin-arm64/out/extension.js:37215:21)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at withExponentialBackoff (/Users/devin/.vscode/extensions/continue.continue-0.8.39-darwin-arm64/out/extension.js:36983:26)
    at FreeTrial._streamFim (/Users/devin/.vscode/extensions/continue.continue-0.8.39-darwin-arm64/out/extension.js:69394:22)
    at FreeTrial.streamFim (/Users/devin/.vscode/extensions/continue.continue-0.8.39-darwin-arm64/out/extension.js:37289:26)
    at ListenableGenerator._start (/Users/devin/.vscode/extensions/continue.continue-0.8.39-darwin-arm64/out/extension.js:41212:28)
w @ console.ts:137
console.ts:137 [Extension Host] Error generating autocompletion:  Error: HTTP 429 Too Many Requests from https://proxy-server-blue-l6vsfbzhba-uw.a.run.app/stream_fim

You have exceeded the maximum number of requests for the free trial.
    at customFetch (/Users/devin/.vscode/extensions/continue.continue-0.8.39-darwin-arm64/out/extension.js:37238:19)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at withExponentialBackoff (/Users/devin/.vscode/extensions/continue.continue-0.8.39-darwin-arm64/out/extension.js:36983:26)
    at FreeTrial._streamFim (/Users/devin/.vscode/extensions/continue.continue-0.8.39-darwin-arm64/out/extension.js:69394:22)
    at FreeTrial.streamFim (/Users/devin/.vscode/extensions/continue.continue-0.8.39-darwin-arm64/out/extension.js:37289:26)
    at ListenableGenerator._start (/Users/devin/.vscode/extensions/continue.continue-0.8.39-darwin-arm64/out/extension.js:41212:28)
w @ console.ts:137
console.ts:137 [Extension Host] HTTP 429 Too Many Requests from https://proxy-server-blue-l6vsfbzhba-uw.a.run.app/stream_fim

You have exceeded the maximum number of requests for the free trial.

Code: undefined
Error number: undefined
Syscall: undefined
Type: undefined

Error: HTTP 429 Too Many Requests from https://proxy-server-blue-l6vsfbzhba-uw.a.run.app/stream_fim

You have exceeded the maximum number of requests for the free trial.
    at customFetch (/Users/devin/.vscode/extensions/continue.continue-0.8.39-darwin-arm64/out/extension.js:37215:21)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at withExponentialBackoff (/Users/devin/.vscode/extensions/continue.continue-0.8.39-darwin-arm64/out/extension.js:36983:26)
    at FreeTrial._streamFim (/Users/devin/.vscode/extensions/continue.continue-0.8.39-darwin-arm64/out/extension.js:69394:22)
    at FreeTrial.streamFim (/Users/devin/.vscode/extensions/continue.continue-0.8.39-darwin-arm64/out/extension.js:37289:26)
    at ListenableGenerator._start (/Users/devin/.vscode/extensions/continue.continue-0.8.39-darwin-arm64/out/extension.js:41212:28)
w @ console.ts:137
console.ts:137 [Extension Host] Error generating autocompletion:  Error: HTTP 429 Too Many Requests from https://proxy-server-blue-l6vsfbzhba-uw.a.run.app/stream_fim

You have exceeded the maximum number of requests for the free trial.
    at customFetch (/Users/devin/.vscode/extensions/continue.continue-0.8.39-darwin-arm64/out/extension.js:37238:19)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at withExponentialBackoff (/Users/devin/.vscode/extensions/continue.continue-0.8.39-darwin-arm64/out/extension.js:36983:26)
    at FreeTrial._streamFim (/Users/devin/.vscode/extensions/continue.continue-0.8.39-darwin-arm64/out/extension.js:69394:22)
    at FreeTrial.streamFim (/Users/devin/.vscode/extensions/continue.continue-0.8.39-darwin-arm64/out/extension.js:37289:26)
    at ListenableGenerator._start (/Users/devin/.vscode/extensions/continue.continue-0.8.39-darwin-arm64/out/extension.js:41212:28)
w @ console.ts:137
console.ts:137 [Extension Host] HTTP 429 Too Many Requests from https://proxy-server-blue-l6vsfbzhba-uw.a.run.app/stream_fim

You have exceeded the maximum number of requests for the free trial.

Code: undefined
Error number: undefined
Syscall: undefined
Type: undefined

Error: HTTP 429 Too Many Requests from https://proxy-server-blue-l6vsfbzhba-uw.a.run.app/stream_fim

You have exceeded the maximum number of requests for the free trial.
    at customFetch (/Users/devin/.vscode/extensions/continue.continue-0.8.39-darwin-arm64/out/extension.js:37215:21)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at withExponentialBackoff (/Users/devin/.vscode/extensions/continue.continue-0.8.39-darwin-arm64/out/extension.js:36983:26)
    at FreeTrial._streamFim (/Users/devin/.vscode/extensions/continue.continue-0.8.39-darwin-arm64/out/extension.js:69394:22)
    at FreeTrial.streamFim (/Users/devin/.vscode/extensions/continue.continue-0.8.39-darwin-arm64/out/extension.js:37289:26)
    at ListenableGenerator._start (/Users/devin/.vscode/extensions/continue.continue-0.8.39-darwin-arm64/out/extension.js:41212:28)
w @ console.ts:137
console.ts:137 [Extension Host] Error generating autocompletion:  Error: HTTP 429 Too Many Requests from https://proxy-server-blue-l6vsfbzhba-uw.a.run.app/stream_fim

You have exceeded the maximum number of requests for the free trial.
    at customFetch (/Users/devin/.vscode/extensions/continue.continue-0.8.39-darwin-arm64/out/extension.js:37238:19)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at withExponentialBackoff (/Users/devin/.vscode/extensions/continue.continue-0.8.39-darwin-arm64/out/extension.js:36983:26)
    at FreeTrial._streamFim (/Users/devin/.vscode/extensions/continue.continue-0.8.39-darwin-arm64/out/extension.js:69394:22)
    at FreeTrial.streamFim (/Users/devin/.vscode/extensions/continue.continue-0.8.39-darwin-arm64/out/extension.js:37289:26)
    at ListenableGenerator._start (/Users/devin/.vscode/extensions/continue.continue-0.8.39-darwin-arm64/out/extension.js:41212:28)
```

**Comment by priyashpatil** [comment]
Not sure about the notifications. Give a try to Codestral - https://docs.continue.dev/walkthroughs/tab-autocomplete

**Comment by sestinj** [comment]
@devinschumacher I'm sorry this is happening, I'll have a fix very soon. In the meantime, you can either turn off all notifications from Continue, try another tab autocomplete model as suggested by priyash, or disable autocomplete by clicking "Continue" in the bottom right corner of VS Code on the status bar

**Comment by sestinj** [comment]
@devinschumacher I've made a fix and triple-checked that this same problem won't happen. Let me know how it goes when you get the chance to give Continue another try!

Also, because the error message here was misleading I want to clarify: we do not have a hard limit on the free trial for autocomplete. This was happening by mistake, so when you try again you won't be limited, only for chat requests

**Comment by devinschumacher** [comment]
thanks @sestinj il see if it stops with the update. 

This might be the wrong place to say this, but since I'm here I wanted to drop it to you --- the one thing I've noticed with every tool or LLM or API that is trying to improve the coding experience is that the LLM will sometimes change random things in your code that have nothing to do with the request and that don't need changing....

Somebody needs to come up with the solution for this would be the perfect source and it's already integrated with the vs code --- that starts with first showing a DIFF, like:

![Screenshot 2024-06-08 at 16 16 50](https://github.com/continuedev/continue/assets/45643901/34df3cdc-39ba-4385-a879-d68b543f0dcc)

This would help you quickly identify anything that it might have have changed that is totally irrelevant....

I noticed them a lot of the problems that I have occur when you're just copying and pasting new code in or using the functionality to just replace it by clicking a button and you don't notice that was changed because you don't look for it since it has nothing to do with your request and then next thing you know your debugging a problem you didn't even have.

**Comment by sestinj** [comment]
I appreciate the feedback here! It's definitely something we've taken time to try and address. More recently our new "Apply" button and algorithm make it more likely that you'll get well-scoped changes in chat, and then you can usually instantly apply these to your open files

Going to close as the original issue has been solved
