### ISSUE TITLE
Offline & install by .vsix file, had error about sqlite3

### ISSUE THREAD

**Issue by lcwxz1989** [continuedev/continue#1428]
### Before submitting your bug report

- [ ] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [ ] I've seen the [troubleshooting guide](https://docs.continue.dev/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS: ubuntu 22.04.4 LTS
- Continue: Continue.continue-0.9.149@linux-arm64.vsix
- IDE: code_1.90.0-1717531825_amd64.deb
```

### Description

Install continue extension by .vsix in offline network. Get error below, I opened developer tools and find error
continue-xxxx/out/build/Release/node_sqlite3.node: cannot open shared object file: No such file or directory.

**Comment by fry69** [comment]
Try again with 0.8.40 or pre-release version 0.9.152 (both just released), according to the commit log there might be a SQLite build fix in it.

**Comment by priyashpatil** [comment]
Might be related issue facing M2:

```
(node:29658) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
[info] Downloading node-sqlite3
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  963k  100  963k    0     0   560k      0  0:00:01  0:00:01 --:--:-- 2439k
x build/Release/node_sqlite3.node
node:fs:3015
  binding.copyFile(
          ^

Error: ENOENT: no such file or directory, copyfile 'bin/darwin-arm64/node_sqlite3.node' -> 'build/node_sqlite3.node'
    at Object.copyFileSync (node:fs:3015:11)
    at /Users/priyash/projects/continue/binary/build.js:226:10
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'copyfile',
  path: 'bin/darwin-arm64/node_sqlite3.node',
  dest: 'build/node_sqlite3.node'
}

Node.js v22.2.0

 *  The terminal process "/bin/zsh '-l', '-c', './scripts/install-dependencies.sh'" terminated with exit code: 1. 
 *  Terminal will be reused by tasks, press any key to close it. 
```

**Comment by sestinj** [comment]
@fry69 Did the file actually not exist, or was this a permissions issue?

**Comment by lcwxz1989** [comment]
> @lcwxz1989 I think they are right that this should be fixed in the latest version, but if you find that it isn't, it would be useful to know: does file actually not exist, or isthis a permissions issue?

I have check the file and it exists, my hardware is M2

**Comment by lcwxz1989** [comment]
> Might be related issue facing on M2:
> 
> ```
> (node:29658) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
> (Use `node --trace-deprecation ...` to show where the warning was created)
> [info] Downloading node-sqlite3
>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                  Dload  Upload   Total   Spent    Left  Speed
>   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
> 100  963k  100  963k    0     0   560k      0  0:00:01  0:00:01 --:--:-- 2439k
> x build/Release/node_sqlite3.node
> node:fs:3015
>   binding.copyFile(
>           ^
> 
> Error: ENOENT: no such file or directory, copyfile 'bin/darwin-arm64/node_sqlite3.node' -> 'build/node_sqlite3.node'
>     at Object.copyFileSync (node:fs:3015:11)
>     at /Users/priyash/projects/continue/binary/build.js:226:10
>     at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
>   errno: -2,
>   code: 'ENOENT',
>   syscall: 'copyfile',
>   path: 'bin/darwin-arm64/node_sqlite3.node',
>   dest: 'build/node_sqlite3.node'
> }
> 
>  *  The terminal process "/bin/zsh '-l', '-c', './scripts/install-dependencies.sh'" terminated with exit code: 1. 
>  *  Terminal will be reused by tasks, press any key to close it. 
> ```

yes My hardware is M2

**Comment by lcwxz1989** [comment]
Tks a lot , the latest version has already solve this problem

**Comment by anmol242** [comment]
> @lcwxz1989 I think they are right that this should be fixed in the latest version, but if you find that it isn't, it would be useful to know: does file actually not exist, or isthis a permissions issue?

I am still getting this error in while. I believe this was introduced by this [line](https://github.com/continuedev/continue/pull/1430/files#diff-dc2950379708345a74f3dc6d8b68a6943d54f70958e9acdf8d134cc5d6778b42R228) in the [PR](https://github.com/continuedev/continue/pull/1430). I have raised a [PR](https://github.com/continuedev/continue/pull/1454) to fix this 😄 . Thanks

**Comment by sestinj** [comment]
@lcwxz1989 good to hear! Does that mean it's safe to close this issue?
