### ISSUE TITLE
running the core unit tests fails

### ISSUE THREAD

**Issue by zivshapiraintel** [continuedev/continue#1451]
### Before submitting your bug report

- [X] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [X] I've seen the [troubleshooting guide](https://docs.continue.dev/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS: Ubuntu 
- Continue: main branch (core 1.0.6)
- IDE: N/A (running in command line)
```

### Description

running the core unit tests fails (expected vs. actual results)
Why are they failing?

### To reproduce

npm run test in the /core directory. 
Tests fail on the diff.test.ts file 

**core/package.json**
```
  "scripts": {
    "test": "NODE_OPTIONS=\"$NODE_OPTIONS --experimental-vm-modules\" jest ./test/diff.test.ts",
    "build:npm": "tsc -p ./tsconfig.npm.json"
  },
```

### Log output

```Shell
+ npm run test

> @continuedev/core@1.0.6 test
> NODE_OPTIONS="$NODE_OPTIONS --experimental-vm-modules" jest ./test/diff.test.ts

console.log
    + C
    + D
    - A
    - B

      at Object.<anonymous> (test/diff.test.ts:119:15)

  console.log
    + D
    + E
    - A
    - B
      C
    + F
    + C

      at Object.<anonymous> (test/diff.test.ts:119:15)

  console.log
    - A
    - B
      C
    - A
      B
    - B
      A
    + B
    + A
    + C

      at Object.<anonymous> (test/diff.test.ts:119:15)

  console.log
    - function mergeSortAlgorithm() {
    + function mergeSortAlgorithm(arr: number[]): number[] {
    +   if (arr.length <= 1) {
    +     return arr;
    -     // TODO: implement
    - }
    +   }
    + 
    +   const middle = Math.floor(arr.length / 2);
    +   const left = arr.slice(0, middle);
    +   const right = arr.slice(middle);
    + 
    +   return merge(mergeSortAlgorithm(left), mergeSortAlgorithm(right));
    + }
    + 
    + function merge(left: number[], right: number[]): number[] {
    +   let resultArray = [], leftIndex = 0, rightIndex = 0;
    + 
    +   while (leftIndex < left.length && rightIndex < right.length) {
    +     if (left[leftIndex] < right[rightIndex]) {
    +       resultArray.push(left[leftIndex]);
    +       leftIndex++;
    +     } else {
    +       resultArray.push(right[rightIndex]);
    +       rightIndex++;
    +     }
    +   }
    + 
    +   return resultArray
    +     .concat(left.slice(leftIndex))
    +     .concat(right.slice(rightIndex));
    + }

      at Object.<anonymous> (test/diff.test.ts:119:15)

  console.log
    - function mergeSortAlgorithm() {
    + function mergeSortAlgorithm(array) {
    +   if (array.length <= 1) {
    +     return array;
    -     // TODO: implement
    - }
    +   }
    + 
    +   const mid = Math.floor(array.length / 2);
    +   const left = array.slice(0, mid);
    +   const right = array.slice(mid);
    + 
    +   return merge(mergeSortAlgorithm(left), mergeSortAlgorithm(right));
    + }
    + 
    + function merge(left, right) {
    +   let resultArray = [], leftIndex = 0, rightIndex = 0;
    + 
    +   while (leftIndex < left.length && rightIndex < right.length) {
    +     if (left[leftIndex] < right[rightIndex]) {
    +       resultArray.push(left[leftIndex]);
    +       leftIndex++;
    +     } else {
    +       resultArray.push(right[rightIndex]);
    +       rightIndex++;
    +     }
    +   }
    + 
    +   return resultArray
    +           .concat(left.slice(leftIndex))
    +           .concat(right.slice(rightIndex));
    + }
    +

      at Object.<anonymous> (test/diff.test.ts:119:15)

(node:4378) ExperimentalWarning: VM Modules is an experimental feature and might change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
FAIL test/diff.test.ts
  streamDiff
    ✕ outputs valid diff #0 (19 ms)
    ✕ outputs valid diff #1 (3 ms)
    ✕ outputs valid diff #2 (1 ms)
    ✕ outputs valid diff #3 (2 ms)
    ✕ outputs valid diff #4 (1 ms)

  ● streamDiff › outputs valid diff #0

    Found red 'A' immediately after green line 'D

    [0m [90m 139 |[39m       [36mfor[39m ([36mlet[39m i [33m=[39m [35m1[39m[33m;[39m i [33m<[39m diff[33m.[39mlength[33m;[39m i[33m++[39m) {
     [90m 140 |[39m         [36mif[39m (diff[i][33m.[39mtype [33m===[39m [32m"old"[39m [33m&&[39m diff[i [33m-[39m [35m1[39m][33m.[39mtype [33m===[39m [32m"new"[39m) {
    [31m[1m>[22m[39m[90m 141 |[39m           [36mthrow[39m [36mnew[39m [33mError[39m(
     [90m     |[39m                 [31m[1m^[22m[39m
     [90m 142 |[39m             [32m`Found red '${diff[i].line}' immediately after green line '${[39m
     [90m 143 |[39m [32m              diff[i - 1].line[39m
     [90m 144 |[39m [32m            }`[39m[0m

      at Object.<anonymous> (test/diff.test.ts:141:17)

  ● streamDiff › outputs valid diff #1

    expect(received).toEqual(expected) // deep equality

    Expected: 3
    Received: 0

    [0m [90m 133 |[39m
     [90m 134 |[39m       [90m// Check that every line is represented[39m
    [31m[1m>[22m[39m[90m 135 |[39m       expect(oldLines[33m.[39mlength)[33m.[39mtoEqual(numOld [33m+[39m numSame)[33m;[39m
     [90m     |[39m                               [31m[1m^[22m[39m
     [90m 136 |[39m       expect(newLines[33m.[39mlength)[33m.[39mtoEqual(numNew [33m+[39m numSame)[33m;[39m
     [90m 137 |[39m
     [90m 138 |[39m       [90m// Check that there are no red lines immediately following green (they should always be above)[39m[0m

      at Object.<anonymous> (test/diff.test.ts:135:31)

  ● streamDiff › outputs valid diff #2

    expect(received).toEqual(expected) // deep equality

    Expected: 7
    Received: 0

    [0m [90m 133 |[39m
     [90m 134 |[39m       [90m// Check that every line is represented[39m
    [31m[1m>[22m[39m[90m 135 |[39m       expect(oldLines[33m.[39mlength)[33m.[39mtoEqual(numOld [33m+[39m numSame)[33m;[39m
     [90m     |[39m                               [31m[1m^[22m[39m
     [90m 136 |[39m       expect(newLines[33m.[39mlength)[33m.[39mtoEqual(numNew [33m+[39m numSame)[33m;[39m
     [90m 137 |[39m
     [90m 138 |[39m       [90m// Check that there are no red lines immediately following green (they should always be above)[39m[0m

      at Object.<anonymous> (test/diff.test.ts:135:31)

  ● streamDiff › outputs valid diff #3

    expect(received).toEqual(expected) // deep equality

    Expected: 3
    Received: 0

    [0m [90m 133 |[39m
     [90m 134 |[39m       [90m// Check that every line is represented[39m
    [31m[1m>[22m[39m[90m 135 |[39m       expect(oldLines[33m.[39mlength)[33m.[39mtoEqual(numOld [33m+[39m numSame)[33m;[39m
     [90m     |[39m                               [31m[1m^[22m[39m
     [90m 136 |[39m       expect(newLines[33m.[39mlength)[33m.[39mtoEqual(numNew [33m+[39m numSame)[33m;[39m
     [90m 137 |[39m
     [90m 138 |[39m       [90m// Check that there are no red lines immediately following green (they should always be above)[39m[0m

      at Object.<anonymous> (test/diff.test.ts:135:31)

  ● streamDiff › outputs valid diff #4

    expect(received).toEqual(expected) // deep equality

    Expected: 3
    Received: 0

    [0m [90m 133 |[39m
     [90m 134 |[39m       [90m// Check that every line is represented[39m
    [31m[1m>[22m[39m[90m 135 |[39m       expect(oldLines[33m.[39mlength)[33m.[39mtoEqual(numOld [33m+[39m numSame)[33m;[39m
     [90m     |[39m                               [31m[1m^[22m[39m
     [90m 136 |[39m       expect(newLines[33m.[39mlength)[33m.[39mtoEqual(numNew [33m+[39m numSame)[33m;[39m
     [90m 137 |[39m
     [90m 138 |[39m       [90m// Check that there are no red lines immediately following green (they should always be above)[39m[0m

      at Object.<anonymous> (test/diff.test.ts:135:31)

Test Suites: 1 failed, 1 total
Tests:       5 failed, 5 total
Snapshots:   0 total
Time:        4.034 s
Ran all test suites matching /.\/test\/diff.test.ts/i.
```

**Comment by sestinj** [comment]
@zivshapiraintel thanks for bringing this up. I just pushed a commit that should resolve the problem, but I'll wait to hear back before closing this issue

Here is the commit: https://github.com/continuedev/continue/commit/8f675407a0c9908154df72c09dbdd6b9b7fe0326

**Comment by zivshapiraintel** [comment]
Hi @sestinj thanks for the quick reply. I am running the same command, after applying the patch and get this error

```
> @continuedev/core@1.0.6 test
> NODE_OPTIONS="$NODE_OPTIONS --experimental-vm-modules" jest ./test/diff.test.ts

/data/workspace/e-to-codesign_zshapira-add-tests/codesign/core/jest.config.js:1
export default {
^^^^^^

SyntaxError: Unexpected token 'export'
    at internalCompileFunction (node:internal/vm:128:18)
    at wrapSafe (node:internal/modules/cjs/loader:1279:20)
    at Module._compile (node:internal/modules/cjs/loader:1331:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1426:10)
    at Module.load (node:internal/modules/cjs/loader:1205:32)
    at Module._load (node:internal/modules/cjs/loader:1021:12)
    at Module.require (node:internal/modules/cjs/loader:1230:19)
    at require (node:internal/modules/helpers:179:18)
    at requireOrImportModule (/data/workspace/e-to-codesign_zshapira-add-tests/codesign/core/node_modules/jest-util/build/requireOrImportModule.js:44:28)
    at readConfigFileAndSetRootDir (/data/workspace/e-to-codesign_zshapira-add-tests/codesign/core/node_modules/jest-config/build/readConfigFileAndSetRootDir.js:112:66)
```

**Comment by sestinj** [comment]
@zivshapiraintel are you on the latest `preview` branch? I notice that the command here is `.test/diff.test.ts`, but I changed it to `./test` with a recent update

**Comment by sestinj** [comment]
Also I see that you are asking not just about them potentially not running, but that they are failing. These tests are largely outdated and not used, which I had written for the sake of experimentation. Best would be for me to clean them up, but in the meantime I tried to just set it up so that you can at least write tests of your own if that's what you are looking to do

**Comment by zivshapiraintel** [comment]
@sestinj they were running just fine, only failing in the expected result not matching the actual result. Now I understand that they are outdated, so I will not expect them to pass, just to run and not fail on any configuration. 
I am working on end to end tests using vscode-test, which I don't see examples for in the repo, so I will do my own experimentations.
Thank you for your support :)

**Comment by sestinj** [comment]
@zivshapiraintel Good to know! There is some code in `extensions/vscode/src/test` that should be useful for end-to-end tests that you are trying to write. This is already scaffolded to spawn an instance of VS Code and run the tests inside of the test-suites folder

**Comment by zivshapiraintel** [comment]
@sestinj - are you running these end to end tests? if so, are you able to share how they are executed (commands, environment)?
I'll check you reference in any case
Thanks!

**Comment by sestinj** [comment]
@zivshapiraintel `npm run test` from `extensions/vscode` will do it: https://github.com/continuedev/continue/blob/preview/extensions/vscode/package.json#L478-L479

These are also slightly out of date, but if the set up doesn't work it should mostly be just a matter of getting the native dependencies in the correct folders. Let me know if you run into anything

**Comment by zivshapiraintel** [comment]
@sestinj getting this error, does this mean anything to you? I am not importing vitest at all in the repo. I added it to the DevDeps because initially it could not find it - maybe it is required by mocha?


```
Error: Vitest cannot be imported in a CommonJS module using require(). Please use "import" instead.

If you are using "import" in your source code, then it's possible it was bundled into require() automatically by your bundler. In that case, do not bundle CommonJS output since it will never work with Vitest, or use dynamic import() which is available in all CommonJS modules.
	at Object.<anonymous> (/data/workspace/xxxxxxx/extensions/vscode/node_modules/vitest/index.cjs:1:7)
	at Module._compile (node:internal/modules/cjs/loader:1256:14)
	at Module._extensions..js (node:internal/modules/cjs/loader:1311:10)
	at Module.load (node:internal/modules/cjs/loader:1098:32)
	at Module._load (node:internal/modules/cjs/loader:945:12)
	at c._load (node:electron/js2c/node_init:2:13672)
	at E._load (/data/workspace/xxxxx/extensions/vscode/.vscode-test/vscode-linux-x64-1.90.0/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:176:5901)
	at n._load (/data/workspace/xxxxx/codesign/extensions/vscode/.vscode-test/vscode-linux-x64-1.90.0/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:173:30787)
	at t._load (/data/workspace/xxxxx/extensions/vscode/.vscode-test/vscode-linux-x64-1.90.0/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:138:33074)
	at Module.require (node:internal/modules/cjs/loader:1122:19)
	at require (node:internal/modules/helpers:130:18)
	at Object.<anonymous> (/data/workspace/xxxxx/extensions/vscode/out/node_modules/@vscode/test-electron/out/download.test.js:7:18)
	at Module._compile (node:internal/modules/cjs/loader:1256:14)
	at Module._extensions..js (node:internal/modules/cjs/loader:1311:10)
	at Module.load (node:internal/modules/cjs/loader:1098:32)
	at Module._load (node:internal/modules/cjs/loader:945:12)
	at c._load (node:electron/js2c/node_init:2:13672)
	at E._load (/data/workspace/xxxxx/extensions/vscode/.vscode-test/vscode-linux-x64-1.90.0/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:176:5901)
	at n._load (/data/workspace/xxxxx/codesign/extensions/vscode/.vscode-test/vscode-linux-x64-1.90.0/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:173:30787)
	at t._load (/data/workspace/xxxxx/extensions/vscode/.vscode-test/vscode-linux-x64-1.90.0/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:138:33074)
	at Module.require (node:internal/modules/cjs/loader:1122:19)
	at require (node:internal/modules/helpers:130:18)
	at /data/workspace/xxxxx/extensions/vscode/node_modules/mocha/lib/mocha.js:414:36
	at Array.forEach (<anonymous>)
	at Mocha.loadFiles (/data/workspace/xxxxx/extensions/vscode/node_modules/mocha/lib/mocha.js:411:14)
	at Mocha.run (/data/workspace/xxxxx/extensions/vscode/node_modules/mocha/lib/mocha.js:972:10)
	at /data/workspace/xxxxx/extensions/vscode/out/test-runner/mochaRunner.js:2397:13
	at new Promise (<anonymous>)
	at Object.run (/data/workspace/xxxxx/extensions/vscode/out/test-runner/mochaRunner.js:2395:10)
	at /data/workspace/xxxxx/extensions/vscode/.vscode-test/vscode-linux-x64-1.90.0/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:159:16075
	at new Promise (<anonymous>)
	at u.sb (/data/workspace/xxxxx/extensions/vscode/.vscode-test/vscode-linux-x64-1.90.0/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:159:15769)
	at async u.$extensionTestsExecute (/data/workspace/xxxxx/extensions/vscode/.vscode-test/vscode-linux-x64-1.90.0/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:159:15437)
Error: Vitest cannot be imported in a CommonJS module using require(). Please use "import" instead.

```

**Comment by sestinj** [comment]
I haven't seen this before, and don't see it even after uninstalling and re-installing node_modules. There must be some environment difference. I would double check a) you're using the npm version defined in .nvmrc by running `nvm use` from the root of the `continue` repository, b) you're on latest preview, c) uninstall and re-install extensions/vscode/node_modules.

Otherwise, it may be prudent for me to set up a devcontainer so we can avoid problems like this in the future

**Comment by zivshapiraintel** [comment]
I figured it out, thanks :) this issue can be closed, since the tests are outdated. Highly appreciate the quick response.
