### ISSUE TITLE
Constantly asks for ollama

### ISSUE THREAD

**Issue by yggdrasil75** [continuedev/continue#1460]
### Before submitting your bug report

- [ ] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [X] I've seen the [troubleshooting guide](https://docs.continue.dev/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS:Linux Mint 21
- Continue:0.8.40
- IDE: VSCode 1.89.1
Kobold 1.67
```

### Description

Randomly continue will pop up with "unable to connect to ollama instance" even though ollama is not set up as the backend. I even removed ollama from the backend json list because when I first installed it, it would pop up every second saying that it couldnt connect. after removing it, it will randomly pop up still, but not nearly as often.
I use koboldcpp because it is by far the easiest to set up and use. I would like to continue to use this without having to have an ollama instance set up to stop error messages.

### To reproduce

install.
dont set up ollama, instead set up kobold.
see errors pop up constantly.

### Log output

```Shell
console.ts:137 [Extension Host] rejected promise not handled within 1 second: CodeExpectedError: custom request failed
w @ console.ts:137
console.ts:137 [Extension Host] stack trace: CodeExpectedError: custom request failed
    at vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:1728:14861
w @ console.ts:137
log.ts:439   ERR custom request failed: CodeExpectedError: custom request failed
    at vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:1728:14861
console.ts:137 [Extension Host] No corresponding diffInfo found for newFilepath
log.ts:439   ERR Unable to read file '/gits/tag2/taggui/utils/settings.py' (Error: File not modified since): Error: Unable to read file '/gits/tag2/taggui/utils/settings.py' (Error: File not modified since)
    at s.F (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:658:19970)
    at s.D (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:658:19858)
    at async a.M (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:2201:42594)
    at async a.readStream (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:2201:42351)
    at async T.Cb (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:2190:15142)
    at async T.resolve (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:2190:13589)
    at async vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:2201:38462
console.ts:137 [Extension Host] No corresponding diffInfo found for newFilepath
console.ts:137 [Extension Host] request to http://127.0.0.1:11434/api/generate failed, reason: connect ECONNREFUSED 127.0.0.1:11434

Code: ECONNREFUSED
Error number: ECONNREFUSED
Syscall: connect
Type: system

FetchError: request to http://127.0.0.1:11434/api/generate failed, reason: connect ECONNREFUSED 127.0.0.1:11434
	at ClientRequest.<anonymous> (/home/yggdrasil75/.vscode/extensions/continue.continue-0.8.40-linux-x64/out/extension.js:36606:14)
	at ClientRequest.emit (node:events:529:35)
	at Socket.socketErrorListener (node:_http_client:501:9)
	at Socket.emit (node:events:517:28)
	at emitErrorNT (node:internal/streams/destroy:151:8)
	at emitErrorCloseNT (node:internal/streams/destroy:116:3)
	at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
w @ console.ts:137
console.ts:137 [Extension Host] Error generating autocompletion:  Error: Failed to connect to local Ollama instance. To start Ollama, first download it at https://ollama.ai.
	at customFetch (/home/yggdrasil75/.vscode/extensions/continue.continue-0.8.40-linux-x64/out/extension.js:37234:21)
	at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
	at async withExponentialBackoff (/home/yggdrasil75/.vscode/extensions/continue.continue-0.8.40-linux-x64/out/extension.js:36981:26)
	at async Ollama._streamComplete (/home/yggdrasil75/.vscode/extensions/continue.continue-0.8.40-linux-x64/out/extension.js:70183:26)
	at async Ollama.streamComplete (/home/yggdrasil75/.vscode/extensions/continue.continue-0.8.40-linux-x64/out/extension.js:37335:26)
	at async ListenableGenerator._start (/home/yggdrasil75/.vscode/extensions/continue.continue-0.8.40-linux-x64/out/extension.js:41348:28)
w @ console.ts:137
notificationsAlerts.ts:42 Failed to connect to local Ollama instance. To start Ollama, first download it at https://ollama.ai.
c @ notificationsAlerts.ts:42
console.ts:137 [Extension Host] request to http://127.0.0.1:11434/api/generate failed, reason: connect ECONNREFUSED 127.0.0.1:11434

Code: ECONNREFUSED
Error number: ECONNREFUSED
Syscall: connect
Type: system

FetchError: request to http://127.0.0.1:11434/api/generate failed, reason: connect ECONNREFUSED 127.0.0.1:11434
	at ClientRequest.<anonymous> (/home/yggdrasil75/.vscode/extensions/continue.continue-0.8.40-linux-x64/out/extension.js:36606:14)
	at ClientRequest.emit (node:events:529:35)
	at Socket.socketErrorListener (node:_http_client:501:9)
	at Socket.emit (node:events:517:28)
	at emitErrorNT (node:internal/streams/destroy:151:8)
	at emitErrorCloseNT (node:internal/streams/destroy:116:3)
	at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
w @ console.ts:137
console.ts:137 [Extension Host] Error generating autocompletion:  Error: Failed to connect to local Ollama instance. To start Ollama, first download it at https://ollama.ai.
	at customFetch (/home/yggdrasil75/.vscode/extensions/continue.continue-0.8.40-linux-x64/out/extension.js:37234:21)
	at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
	at async withExponentialBackoff (/home/yggdrasil75/.vscode/extensions/continue.continue-0.8.40-linux-x64/out/extension.js:36981:26)
	at async Ollama._streamComplete (/home/yggdrasil75/.vscode/extensions/continue.continue-0.8.40-linux-x64/out/extension.js:70183:26)
	at async Ollama.streamComplete (/home/yggdrasil75/.vscode/extensions/continue.continue-0.8.40-linux-x64/out/extension.js:37335:26)
	at async ListenableGenerator._start (/home/yggdrasil75/.vscode/extensions/continue.continue-0.8.40-linux-x64/out/extension.js:41348:28)
w @ console.ts:137
console.ts:137 [Extension Host] request to http://127.0.0.1:11434/api/generate failed, reason: connect ECONNREFUSED 127.0.0.1:11434

Code: ECONNREFUSED
Error number: ECONNREFUSED
Syscall: connect
Type: system

FetchError: request to http://127.0.0.1:11434/api/generate failed, reason: connect ECONNREFUSED 127.0.0.1:11434
	at ClientRequest.<anonymous> (/home/yggdrasil75/.vscode/extensions/continue.continue-0.8.40-linux-x64/out/extension.js:36606:14)
	at ClientRequest.emit (node:events:529:35)
	at Socket.socketErrorListener (node:_http_client:501:9)
	at Socket.emit (node:events:517:28)
	at emitErrorNT (node:internal/streams/destroy:151:8)
	at emitErrorCloseNT (node:internal/streams/destroy:116:3)
	at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
w @ console.ts:137
console.ts:137 [Extension Host] Error generating autocompletion:  Error: Failed to connect to local Ollama instance. To start Ollama, first download it at https://ollama.ai.
	at customFetch (/home/yggdrasil75/.vscode/extensions/continue.continue-0.8.40-linux-x64/out/extension.js:37234:21)
	at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
	at async withExponentialBackoff (/home/yggdrasil75/.vscode/extensions/continue.continue-0.8.40-linux-x64/out/extension.js:36981:26)
	at async Ollama._streamComplete (/home/yggdrasil75/.vscode/extensions/continue.continue-0.8.40-linux-x64/out/extension.js:70183:26)
	at async Ollama.streamComplete (/home/yggdrasil75/.vscode/extensions/continue.continue-0.8.40-linux-x64/out/extension.js:37335:26)
	at async ListenableGenerator._start (/home/yggdrasil75/.vscode/extensions/continue.continue-0.8.40-linux-x64/out/extension.js:41348:28)
w @ console.ts:137
console.ts:137 [Extension Host] request to http://127.0.0.1:11434/api/generate failed, reason: connect ECONNREFUSED 127.0.0.1:11434

Code: ECONNREFUSED
Error number: ECONNREFUSED
Syscall: connect
Type: system

FetchError: request to http://127.0.0.1:11434/api/generate failed, reason: connect ECONNREFUSED 127.0.0.1:11434
	at ClientRequest.<anonymous> (/home/yggdrasil75/.vscode/extensions/continue.continue-0.8.40-linux-x64/out/extension.js:36606:14)
	at ClientRequest.emit (node:events:529:35)
	at Socket.socketErrorListener (node:_http_client:501:9)
	at Socket.emit (node:events:517:28)
	at emitErrorNT (node:internal/streams/destroy:151:8)
	at emitErrorCloseNT (node:internal/streams/destroy:116:3)
	at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
w @ console.ts:137
console.ts:137 [Extension Host] Error generating autocompletion:  Error: Failed to connect to local Ollama instance. To start Ollama, first download it at https://ollama.ai.
	at customFetch (/home/yggdrasil75/.vscode/extensions/continue.continue-0.8.40-linux-x64/out/extension.js:37234:21)
	at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
	at async withExponentialBackoff (/home/yggdrasil75/.vscode/extensions/continue.continue-0.8.40-linux-x64/out/extension.js:36981:26)
	at async Ollama._streamComplete (/home/yggdrasil75/.vscode/extensions/continue.continue-0.8.40-linux-x64/out/extension.js:70183:26)
	at async Ollama.streamComplete (/home/yggdrasil75/.vscode/extensions/continue.continue-0.8.40-linux-x64/out/extension.js:37335:26)
	at async ListenableGenerator._start (/home/yggdrasil75/.vscode/extensions/continue.continue-0.8.40-linux-x64/out/extension.js:41348:28)
w @ console.ts:137
console.ts:137 [Extension Host] request to http://127.0.0.1:11434/api/generate failed, reason: connect ECONNREFUSED 127.0.0.1:11434

Code: ECONNREFUSED
Error number: ECONNREFUSED
Syscall: connect
Type: system

FetchError: request to http://127.0.0.1:11434/api/generate failed, reason: connect ECONNREFUSED 127.0.0.1:11434
	at ClientRequest.<anonymous> (/home/yggdrasil75/.vscode/extensions/continue.continue-0.8.40-linux-x64/out/extension.js:36606:14)
	at ClientRequest.emit (node:events:529:35)
	at Socket.socketErrorListener (node:_http_client:501:9)
	at Socket.emit (node:events:517:28)
	at emitErrorNT (node:internal/streams/destroy:151:8)
	at emitErrorCloseNT (node:internal/streams/destroy:116:3)
	at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
w @ console.ts:137
console.ts:137 [Extension Host] Error generating autocompletion:  Error: Failed to connect to local Ollama instance. To start Ollama, first download it at https://ollama.ai.
	at customFetch (/home/yggdrasil75/.vscode/extensions/continue.continue-0.8.40-linux-x64/out/extension.js:37234:21)
	at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
	at async withExponentialBackoff (/home/yggdrasil75/.vscode/extensions/continue.continue-0.8.40-linux-x64/out/extension.js:36981:26)
	at async Ollama._streamComplete (/home/yggdrasil75/.vscode/extensions/continue.continue-0.8.40-linux-x64/out/extension.js:70183:26)
	at async Ollama.streamComplete (/home/yggdrasil75/.vscode/extensions/continue.continue-0.8.40-linux-x64/out/extension.js:37335:26)
	at async ListenableGenerator._start (/home/yggdrasil75/.vscode/extensions/continue.continue-0.8.40-linux-x64/out/extension.js:41348:28)
w @ console.ts:137
console.ts:137 [Extension Host] request to http://127.0.0.1:11434/api/generate failed, reason: connect ECONNREFUSED 127.0.0.1:11434

Code: ECONNREFUSED
Error number: ECONNREFUSED
Syscall: connect
Type: system

FetchError: request to http://127.0.0.1:11434/api/generate failed, reason: connect ECONNREFUSED 127.0.0.1:11434
	at ClientRequest.<anonymous> (/home/yggdrasil75/.vscode/extensions/continue.continue-0.8.40-linux-x64/out/extension.js:36606:14)
	at ClientRequest.emit (node:events:529:35)
	at Socket.socketErrorListener (node:_http_client:501:9)
	at Socket.emit (node:events:517:28)
	at emitErrorNT (node:internal/streams/destroy:151:8)
	at emitErrorCloseNT (node:internal/streams/destroy:116:3)
	at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
w @ console.ts:137
console.ts:137 [Extension Host] Error generating autocompletion:  Error: Failed to connect to local Ollama instance. To start Ollama, first download it at https://ollama.ai.
	at customFetch (/home/yggdrasil75/.vscode/extensions/continue.continue-0.8.40-linux-x64/out/extension.js:37234:21)
	at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
	at async withExponentialBackoff (/home/yggdrasil75/.vscode/extensions/continue.continue-0.8.40-linux-x64/out/extension.js:36981:26)
	at async Ollama._streamComplete (/home/yggdrasil75/.vscode/extensions/continue.continue-0.8.40-linux-x64/out/extension.js:70183:26)
	at async Ollama.streamComplete (/home/yggdrasil75/.vscode/extensions/continue.continue-0.8.40-linux-x64/out/extension.js:37335:26)
	at async ListenableGenerator._start (/home/yggdrasil75/.vscode/extensions/continue.continue-0.8.40-linux-x64/out/extension.js:41348:28)
w @ console.ts:137
console.ts:137 [Extension Host] request to http://127.0.0.1:11434/api/generate failed, reason: connect ECONNREFUSED 127.0.0.1:11434

Code: ECONNREFUSED
Error number: ECONNREFUSED
Syscall: connect
Type: system

FetchError: request to http://127.0.0.1:11434/api/generate failed, reason: connect ECONNREFUSED 127.0.0.1:11434
	at ClientRequest.<anonymous> (/home/yggdrasil75/.vscode/extensions/continue.continue-0.8.40-linux-x64/out/extension.js:36606:14)
	at ClientRequest.emit (node:events:529:35)
	at Socket.socketErrorListener (node:_http_client:501:9)
	at Socket.emit (node:events:517:28)
	at emitErrorNT (node:internal/streams/destroy:151:8)
	at emitErrorCloseNT (node:internal/streams/destroy:116:3)
	at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
w @ console.ts:137
console.ts:137 [Extension Host] Error generating autocompletion:  Error: Failed to connect to local Ollama instance. To start Ollama, first download it at https://ollama.ai.
	at customFetch (/home/yggdrasil75/.vscode/extensions/continue.continue-0.8.40-linux-x64/out/extension.js:37234:21)
	at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
	at async withExponentialBackoff (/home/yggdrasil75/.vscode/extensions/continue.continue-0.8.40-linux-x64/out/extension.js:36981:26)
	at async Ollama._streamComplete (/home/yggdrasil75/.vscode/extensions/continue.continue-0.8.40-linux-x64/out/extension.js:70183:26)
	at async Ollama.streamComplete (/home/yggdrasil75/.vscode/extensions/continue.continue-0.8.40-linux-x64/out/extension.js:37335:26)
	at async ListenableGenerator._start (/home/yggdrasil75/.vscode/extensions/continue.continue-0.8.40-linux-x64/out/extension.js:41348:28)
w @ console.ts:137
webviewElement.ts:482 An iframe which has both allow-scripts and allow-same-origin for its sandbox attribute can escape its sandboxing.
```

**Comment by sestinj** [comment]
@yggdrasil75 We can of course do a much better job of communicating this, but the pop ups are showing up because Ollama is the default model for tab autocomplete, which I think you must have enabled. Let me know if I'm wrong here, and we'll look to fix this in a release soon

**Comment by sestinj** [comment]
@yggdrasil75 Most backends do not support autocomplete, hence the need for a separate one, and we wish to avoid silently sending users' code to a cloud API, hence Ollama.

I'm going to close the issue because it seems to be resolved, but I'll of course be improving the messaging around this as well
