### ISSUE TITLE
autoCompletion: deepseek - Stop string array too long

### ISSUE THREAD

**Issue by robwilkes** [continuedev/continue#1513]
### Before submitting your bug report

- [X] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [ ] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [ ] I've seen the [troubleshooting guide](https://docs.continue.dev/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
autoCompletion with DeepSeek API:
Error: HTTP 400 Bad Request from https://api.deepseek.com/chat/completions

{"detail":"Stop string array too long"}
```

### Description

I believe it's building too big of an array of stop tokens. I think there needs to be an ability to users to override the list and not simply append more tokens.

```
   const stop = [
      ...(completionOptions?.stop || []),
      ...multilineStops,
      ...commonStops,
      ...(llm.model.toLowerCase().includes("starcoder2")
        ? STARCODER2_T_ARTIFACTS
        : []),
      ...(lang.stopWords ?? []),
      ...lang.topLevelKeywords.map((word) => `\n${word}`),
    ];
```

### To reproduce

```
  "tabAutocompleteOptions": {
    "template": "<｜fim▁begin｜>{{{prefix}}}<｜fim▁hole｜>{{{suffix}}}<｜fim▁end｜>",
    "useCache": true,
    "maxPromptTokens": 1024
  },
  "tabAutocompleteModel": {
    "title": "DeepSeek-v2",
    "model": "deepseek-coder",
    "apiKey": “removed”,
    "contextLength": 4096,
    "apiBase": "https://api.deepseek.com",
    "completionOptions": {
      "maxTokens": 2048,
      "temperature": 0,
      "topP": 1,
      "presencePenalty": 0,
      "frequencyPenalty": 0
    },
    "provider": "openai”,
    "useLegacyCompletionsEndpoint": false
  },
  ```

### Log output

```Shell
[Extension Host] Error generating autocompletion:  Error: HTTP 400 Bad Request from https://api.deepseek.com/chat/completions

{"detail":"Stop string array too long"}
	at customFetch (/Users/rob/.vscode/extensions/continue.continue-0.9.163-darwin-arm64/out/extension.js:82177:19)
	at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
	at async withExponentialBackoff (/Users/rob/.vscode/extensions/continue.continue-0.9.163-darwin-arm64/out/extension.js:81920:26)
	at async OpenAI._streamChat (/Users/rob/.vscode/extensions/continue.continue-0.9.163-darwin-arm64/out/extension.js:82683:26)
	at async OpenAI._streamComplete (/Users/rob/.vscode/extensions/continue.continue-0.9.163-darwin-arm64/out/extension.js:82637:26)
	at async OpenAI.streamComplete (/Users/rob/.vscode/extensions/continue.continue-0.9.163-darwin-arm64/out/extension.js:82274:26)
	at async ListenableGenerator._start (/Users/rob/.vscode/extensions/continue.continue-0.9.163-darwin-arm64/out/extension.js:86684:28)
```
```

**Comment by XieJiSS** [comment]
Hi there,

We've increased the limit at our side, and the new limit for the stop string array is now 16. However, please note that the 236B model does not support FIM yet, and the feature is still work-in-progress. I built a prompt that seems to work to replace FIM special tokens, and maybe you can give it a try:

```json
{
  "models": [],
  "tabAutocompleteOptions": {
    "template": "Please teach me what I should write in the `hole` tag, but without any further explanation and code backticks, i.e., as if you are directly outputting to a code editor. It can be codes or comments or strings. Don't provide existing & repetitive codes. If the provided prefix and suffix contain incomplete code and statement, your response should be able to be directly concatenated to the provided prefix and suffix. Also note that I may tell you what I'd like to write inside comments. \n{{{prefix}}}<hole></hole>{{{suffix}}}\n\nPlease be aware of the environment the hole is placed, e.g., inside strings or comments or code blocks, and please don't wrap your response in ```. You should always provide non-empty output.\n",
    "useCache": true,
    "maxPromptTokens": 2048
  },
  "tabAutocompleteModel": {
    "title": "DeepSeek-V2",
    "model": "deepseek-coder",
    "apiKey": REDACTED,
    "contextLength": 8192,
    "apiBase": "https://api.deepseek.com",
    "completionOptions": {
      "maxTokens": 4096,
      "temperature": 0,
      "topP": 1,
      "presencePenalty": 0,
      "frequencyPenalty": 0
    },
    "provider": "openai",
    "useLegacyCompletionsEndpoint": false
  }
}
```

**Comment by sestinj** [comment]
@XieJiSS Thanks so much for your support here! I've [updated our code](https://github.com/continuedev/continue/commit/efc185902a674c8421c86889ea7982d348754142) to reflect the 16 stop word limit.

I'll start forwarding people toward your prompt here when they are interested in Deepseek, but I'll also be patiently awaiting /fim support (or raw /completions, which would allow us to handle it as well). There are many users who are excited about Deepseek, and I'm sure they'll be very happy once this is ready : )

**Comment by XieJiSS** [comment]
Hi @sestinj, we are now [providing experimental FIM support for DeepSeek-Coder-V2](https://platform.deepseek.com/api-docs/news/news0725#new-api-completions) via a new "beta" base url. We can expect the feature to be stabilized and officially launched to all users after a relatively short period of time, while during this interim phase, interested users can manually change their base url to our "beta" base url to try this test feature. Hope this helps!
