### ISSUE TITLE
The continue plugin has been initializing......

### ISSUE THREAD

**Issue by shuaiFLYINTHESKY** [continuedev/continue#1514]
### Before submitting your bug report

- [X] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [X] I've seen the [troubleshooting guide](https://docs.continue.dev/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS: macos 14.4.1
- Continue: 0.8.27
- IDE: vs code 1.90.1
- Ollama 0.1.44

I use VS Code + Ubuntu server, remote ssh mode of development.
The project is huge, according to incomplete statistics there are 30579 directories, 184726 files. 

  "models": [
    {
      "title": "ollama-codeqwen:7b-chat-v1.5-q8_0",
      "provider": "ollama",
      "model": "codeqwen:7b-chat-v1.5-q8_0",
      "contextLength": 8192,
      "temperature": 0
    }]

  "embeddingsProvider": {
    "provider": "ollama",
    "model": "nomic-embed-text",
    "apiBase": "http://localhost:11434"
  }
```

### Description

The continue plugin has been initializing... No files in any of the project directories are actually indexed, so features like @folder and @files are not available. 

The official document method similar to exclude https://docs.continue.dev/walkthroughs/codebase-embeddings#customizing-which-files-are-indexed mentioned way, there is no include method.

I'm trying to ~/continue/index/index.splite looked at the indexfile, some files have not been indexed, regardless of the file size.

<img width="724" alt="image" src="https://github.com/continuedev/continue/assets/98887892/9fafe2b3-7b05-4a68-bbc0-e793272a24d4">

### Log output

```Shell
workbench.desktop.main.js:sourcemap:152 [Extension Host] EntryNotFound (FileSystemError): Unable to resolve nonexistent file 'vscode-remote://ssh-remote/home/ubuntu/gerde/it17.main/.prompts'
	at y.e (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:152:6797)
	at Object.readDirectory (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:152:4081)
	at async traverseDirectory (/Users/chr/.vscode/extensions/continue/out/extension.js:369145:17)
	at async _VsCodeIdeUtils.getDirectoryContents (/Users/chr/.vscode/extensions/continue/out/extension.js:369442:26)
	at async VsCodeIde.listWorkspaceContents (/Users/chr/.vscode/extensions/continue/out/extension.js:369825:18)
	at async getPromptFiles (/Users/chr/.vscode/extensions/continue/out/extension.js:344431:19)
	at async Promise.all (index 0)
	at async serializedToIntermediateConfig (/Users/chr/.vscode/extensions/continue/out/extension.js:344579:24)
	at async loadFullConfigNode (/Users/chr/.vscode/extensions/continue/out/extension.js:344845:22)
	at async ConfigHandler.loadConfig (/Users/chr/.vscode/extensions/continue/out/extension.js:344969:28)
	at async ConfigHandler.getSerializedConfig (/Users/chr/.vscode/extensions/continue/out/extension.js:344952:30)
	at async /Users/chr/.vscode/extensions/continue/out/extension.js:366811:18
	at async a.value (/Users/chr/.vscode/extensions/continue/out/extension.js:367260:32)
w @ workbench.desktop.main.js:sourcemap:152
workbench.desktop.main.js:sourcemap:152 [Extension Host] stack trace: EntryNotFound (FileSystemError): Error: ENOENT: no such file or directory, stat '/home/ubuntu/gerde/it17.main/na/res/CN/BE'
	at y.e (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:152:6797)
	at Object.stat (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:152:3892)
	at async /Users/chr/.vscode/extensions/continue/out/extension.js:369790:25
	at async Promise.all (index 16549)
	at async VsCodeIde.getStats (/Users/chr/.vscode/extensions/continue/out/extension.js:369788:9)
	at async CodebaseIndexer.refresh (/Users/chr/.vscode/extensions/continue/out/extension.js:345105:25)
	at async _VsCodeExtension.refreshCodebaseIndex (/Users/chr/.vscode/extensions/continue/out/extension.js:370658:26)
```

**Comment by shuaiFLYINTHESKY** [comment]
Add: ssh way development, file path is valid, the file exists.

**Comment by LeoLiuYan** [comment]
+1

**Comment by trathailoi** [comment]
+1

**Comment by shuaiFLYINTHESKY** [comment]
> +1 <img alt="截图 2024-06-23 18 53 15" width="418" src="https://private-user-images.githubusercontent.com/16256608/342062337-24338c0c-9c81-458b-87b2-186bdcf88e80.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkyOTIzOTUsIm5iZiI6MTcxOTI5MjA5NSwicGF0aCI6Ii8xNjI1NjYwOC8zNDIwNjIzMzctMjQzMzhjMGMtOWM4MS00NThiLTg3YjItMTg2YmRjZjg4ZTgwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI1VDA1MDgxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY0NjYxZTI0MzRjYzYzNDUxOTRkYzFhMWUzNGUzNDUwMjg1YjIyNWUyYWI3NTU0NjBjNDVhMTA5MjY0MjRlYWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.QFFZILExgoloF5HXDo884tRUwlhGbsIdkSgollHbQ_8">

hello, which version are you using?
