### ISSUE TITLE
ReadableStream.from is not a function error

### ISSUE THREAD

**Issue by umutcanoner** [continuedev/continue#1649]
### Before submitting your bug report

- [X] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [x] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [x] I've seen the [troubleshooting guide](https://docs.continue.dev/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS: Windows 11 Pro 24H2
- Continue: v0.9.171 (pre-release)
- IDE: VSCode Insiders 1.91.0-insider (system setup)
- Model: any (Ollama, OpenAI, Anthropic)
- config.json:
  
{
  "allowAnonymousTelemetry": true,
  "contextProviders": [
    {
      "name": "codebase",
      "params": {
        "nFinal": 5,
        "nRetrieve": 25,
        "useReranking": true
      }
    },
    {
      "name": "problems"
    }
  ],
  "customCommands": [
    {
      "description": "Write unit tests for highlighted code",
      "name": "test",
      "prompt": "{{{ input }}}\n\nWrite a comprehensive set of unit tests for the selected code. It should setup, run tests that check for correctness including important edge cases, and teardown. Ensure that the tests are complete and sophisticated. Give the tests just as chat output, don't edit any file."
    }
  ],
  "embeddingsProvider": {
    "apiBase": "https://api.voyageai.com/v1/",
    "apiKey": "<API_KEY_OMITTED>",
    "model": "voyage-code-2",
    "provider": "openai"
  },
  "models": [
    {
      "apiKey": "<API_KEY_OMITTED>",
      "contextLength": 128000,
      "model": "gpt-4o",
      "provider": "openai",
      "systemMessage": "You are an expert software developer. You give helpful and concise responses.",
      "title": "GPT-4o"
    },
    {
      "apiKey": "<API_KEY_OMITTED>",
      "contextLength": 128000,
      "model": "gpt-4o",
      "provider": "openai",
      "systemMessage": "You are an expert software developer. You give helpful and concise responses.",
      "title": "GPT-4o (1)"
    },
    {
      "apiKey": "<API_KEY_OMITTED>",
      "completionOptions": {},
      "model": "claude-3-opus-20240229",
      "provider": "anthropic",
      "title": "Claude 3 Opus"
    },
    {
      "apiKey": "<API_KEY_OMITTED>",
      "contextLength": 200000,
      "model": "claude-3-5-sonnet-20240620",
      "provider": "anthropic",
      "title": "Claude 3.5 Sonnet"
    }
  ],
  "reranker": {
    "enabled": true,
    "name": "voyage",
    "params": {
      "apiKey": "<API_KEY_OMITTED>",
      "model": "rerank-lite-1"
    }
  },
  "tabAutocompleteOptions": {
    "enabled": false,
    "maxSuggestions": 5
  }
}
```

### Description

I'm getting `ReadableStream.from is not a function` error. I use pre-release by default, but I had to use the release version of `.continue` for a few days because of this. And as of today, the release version is giving me the same error.

I tried purging all installation files, configurations, etc. Tried using the default configuration, local models, OpenAI, and Anthropic to no avail.

### To reproduce

![image](https://github.com/continuedev/continue/assets/75980518/76592263-0c18-4a59-bbab-b8303054b17a)

### Log output

```Shell
mainThreadExtensionService.ts:78 [Continue.continue]Parsing failed
$onExtensionRuntimeError	@	mainThreadExtensionService.ts:78
mainThreadExtensionService.ts:79 Error: Parsing failed
    at _Parser.parse (c:\Users\redli\.vsco…tension.js:94930:81)
    at _ImportDefinitionsService._getFileInfo (c:\Users\redli\.vsco…tension.js:95827:28)
    at PrecalculatedLruCache.initKey (c:\Users\redli\.vsco…tension.js:93786:25)
console.ts:137 [Extension Host] TypeError: ReadableStream.from is not a function
    at streamResponse (c:\Users\redli\.vscode-insiders\extensions\continue.continue-0.9.171-win32-x64\out\extension.js:102623:36)
    at streamResponse.next (<anonymous>)
    at streamSse (c:\Users\redli\.vscode-insiders\extensions\continue.continue-0.9.171-win32-x64\out\extension.js:102661:20)
    at streamSse.next (<anonymous>)
    at OpenAI2._streamChat (c:\Users\redli\.vscode-insiders\extensions\continue.continue-0.9.171-win32-x64\out\extension.js:137956:26)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at OpenAI2.streamChat (c:\Users\redli\.vscode-insiders\extensions\continue.continue-0.9.171-win32-x64\out\extension.js:102515:30)
    at llmStreamChat (c:\Users\redli\.vscode-insiders\extensions\continue.continue-0.9.171-win32-x64\out\extension.js:427963:23)
    at n.value (c:\Users\redli\.vscode-insiders\extensions\continue.continue-0.9.171-win32-x64\out\extension.js:434394:29) (at console.<anonymous> (c:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:144:47509))
log.ts:439   ERR [Extension Host] Error handling webview message: {
  "msg": {
    "messageId": "d1c35308-38cd-4a69-8d47-5aeeaa6746b0",
    "messageType": "llm/streamChat",
    "data": {
      "messages": [
        {
          "role": "user",
          "content": [
            {
              "type": "text",
              "text": "hello"
            }
          ]
        }
      ],
      "title": "GPT-4o",
      "completionOptions": {}
    }
  }
}

TypeError: ReadableStream.from is not a function
console.ts:137 [Extension Host] Error handling webview message: {
  "msg": {
    "messageId": "d1c35308-38cd-4a69-8d47-5aeeaa6746b0",
    "messageType": "llm/streamChat",
    "data": {
      "messages": [
        {
          "role": "user",
          "content": [
            {
              "type": "text",
              "text": "hello"
            }
          ]
        }
      ],
      "title": "GPT-4o",
      "completionOptions": {}
    }
  }
}

TypeError: ReadableStream.from is not a function (at console.<anonymous> (c:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:144:47509))
notificationsAlerts.ts:42 ReadableStream.from is not a function
c	@	notificationsAlerts.ts:42
```

**Comment by sestinj** [comment]
@umutcanoner can you share the version of Node.js that VS Code is running on for you? This can be found in the top left about menu for VS Code

**Comment by umutcanoner** [comment]
Thanks for the fast reply! I'm pretty sure I wrote that when opening the issue but it got deleted somehow I guess.
Version: 1.91.0-insider (system setup)
Commit: aea213b7fcc7de5c24ad797ac1af209b159d451f
Date: 2024-06-28T05:56:20.804Z
Electron: 29.4.0
ElectronBuildId: 9728852
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0
OS: Windows_NT x64 10.0.26120

**Comment by umutcanoner** [comment]
Looks like it's working when https://marketplace.visualstudio.com/items?itemName=nicepkg.gpt-runner is disabled.

**Comment by sestinj** [comment]
Good to know. I'm going to close this issue given the conversation here and in Discord seems to indicate that is a proper resolution

**Comment by eladamittai** [comment]
I have the same issue with pretty much the same configuration, but in a different environment without gpt-runner.
vscode: v1.88.0
Continue: v0. 9.167
Os: linux mint
