### ISSUE TITLE
[error] Error: Parsing failed

### ISSUE THREAD

**Issue by jyomu** [continuedev/continue#1732]
### Before submitting your bug report

- [X] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [X] I've seen the [troubleshooting guide](https://docs.continue.dev/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS: Windows 11
- Continue: v0.9.182 (pre-release)
- IDE: vscode 1.91.0
- Model:
- config.json:
```

### Description

```js
// at _Parser.parse (c:\Users\jyomu\.vscode\extensions\continue.continue-0.9.182-win32-x64\out\extension.js:89096:81)
              parse(e4, t4, r4) {
                if ("string" == typeof e4)
                  currentParseCallback = (t5, r5, _4) => e4.slice(t5, _4);
                else {
                  if ("function" != typeof e4)
                    throw new Error("Argument must be a string or a function");
                  currentParseCallback = e4;
                }
                this.logCallback ? (currentLogCallback = this.logCallback, C._ts_parser_enable_logger_wasm(this[0], 1)) : (currentLogCallback = null, C._ts_parser_enable_logger_wasm(this[0], 0));
                let _3 = 0, s4 = 0;
                if (r4 && r4.includedRanges) {
                  _3 = r4.includedRanges.length, s4 = C._calloc(_3, SIZE_OF_RANGE);
                  let e5 = s4;
                  for (let t5 = 0; t5 < _3; t5++)
                    marshalRange(e5, r4.includedRanges[t5]), e5 += SIZE_OF_RANGE;
                }
                const n2 = C._ts_parser_parse_wasm(this[0], this[1], t4 ? t4[0] : 0, s4, _3);
                if (!n2)
                  throw currentParseCallback = null, currentLogCallback = null, new Error("Parsing failed");//:89096
                const a2 = new Tree(INTERNAL, n2, this.language, currentParseCallback);
                return currentParseCallback = null, currentLogCallback = null, a2;
              }

// 	at _ImportDefinitionsService._getFileInfo (c:\Users\jyomu\.vscode\extensions\continue.continue-0.9.182-win32-x64\out\extension.js:90002:28)
      async _getFileInfo(filepath) {
        const parser = await getParserForFile(filepath);
        if (!parser) {
          return {
            imports: {}
          };
        }
        const ast = parser.parse(await this.ide.readFile(filepath), void 0, {//:90002
          includedRanges: [
            {
              startIndex: 0,
              endIndex: 1e4,
              startPosition: { row: 0, column: 0 },
              endPosition: { row: 100, column: 0 }
            }
          ]
        });

//	at async PrecalculatedLruCache.initKey (c:\Users\jyomu\.vscode\extensions\continue.continue-0.9.182-win32-x64\out\extension.js:87952:25)
      async initKey(key) {
        const index2 = this.items.findIndex((item) => item[0] === key);
        if (index2 < 0) {
          const value = await this.calculateValue(key);//:87952
          this.items.push([key, value]);
          if (this.items.length > this.N) {
            this.items.shift();
          }
        } else {
          const [item] = this.items.splice(index2, 1);
          this.items.push(item);
        }
      }

```
https://github.com/continuedev/continue/blob/ed37dcfb7ab98d7a70759991cbf4abe868beea89/core/util/LruCache.ts#L8-L25

### Log output

```Shell
2024-07-14 11:21:07.632 [error] Error: Parsing failed
	at _Parser.parse (c:\Users\*\.vscode\extensions\continue.continue-0.9.182-win32-x64\out\extension.js:89096:81)
	at _ImportDefinitionsService._getFileInfo (c:\Users\*\.vscode\extensions\continue.continue-0.9.182-win32-x64\out\extension.js:90002:28)
	at async PrecalculatedLruCache.initKey (c:\Users\*\.vscode\extensions\continue.continue-0.9.182-win32-x64\out\extension.js:87952:25)
```

**Comment by sestinj** [comment]
@jyomu Does this error just silently appear in the logs, or does it have further effects? If you are able to share an example of a file that causes parsing to fail that would be very helpful in debugging

**Comment by steventsvetkov** [comment]
I keep encountering the same issue (126 errors in the past 4 hours, impressive) 


This is what appears in the chrome devtools console:

```
mainThreadExtensionService.ts:78 [Continue.continue]Parsing failed
$onExtensionRuntimeError @ mainThreadExtensionService.ts:78
mainThreadExtensionService.ts:79 Error: Parsing failed
    at _Parser.parse (vscode-file://vscode-app/home/steve/.vscode/extensions/continue.continue-0.8.43-linux-x64/out/extension.js:94675:81)
    at _ImportDefinitionsService._getFileInfo (vscode-file://vscode-app/home/steve/.vscode/extensions/continue.continue-0.8.43-linux-x64/out/extension.js:95581:28)
    at PrecalculatedLruCache.initKey (vscode-file://vscode-app/home/steve/.vscode/extensions/continue.continue-0.8.43-linux-x64/out/extension.js:93531:25)
```

My configuration is:


```
- OS: Pop!_OS 22.04 LTS x86_64
- Continue: 0.8.42
- IDE: 1.91.0
- Model: gpt-4o
- config.json:
```


```json
{
  "customCommands": [
    {
      "description": "Write unit tests for highlighted code",
      "name": "test",
      "prompt": "{{{ input }}}\n\nWrite a comprehensive set of unit tests for the selected code. It should setup, run tests that check for correctness including important edge cases, and teardown. Ensure that the tests are complete and sophisticated. Give the tests just as chat output, don't edit any file."
    },
    {
      "description": "Explain a concept",
      "name": "explain",
      "prompt": "You are a knowledgeable tutor that can teach me about machine learning, data science, and software development, providing clear explanations and practical examples. Before answering, double check my work and your work rigorously. Avoid being too verbose unless specifically asked to. Explain the concepts in simple words, while also providing the technical jargon in parentheses. Treat the student as a beginner data scientist with solid programming experience. Prefer shorter responses and explain jargon you use. \n\n{{{ input }}}"
    },
    {
      "description": "Learn a concept",
      "name": "learn",
      "prompt": "You are a knowledgeable tutor that can teach me about machine learning, data science, and software development, providing clear explanations, practical examples, and guiding me through exercises and projects to enhance my understanding and skills. Always always responds in the Socratic style and explain any jargon that you use. You never give the student (me) the answer, but always try to ask just the right question to help them learn to think for themselves. You should always tune your question to the knowledge of the student, breaking down the problem into simpler parts until it's at just the right level for them, but always assume that they’re having difficulties and you don’t know where yet. Before providing feedback, double check my work and your work rigorously. Avoid being too verbose unless specifically asked to. Keep asking follow up questions that will help the student learn. \n\n{{{ input }}}"
    }
  ],
  "models": [
    {
      "apiKey": "",
      "completionOptions": {
        "temperature": 0
      },
      "contextLength": 131072000,
      "model": "gpt-4o",
      "provider": "openai",
      "systemMessage": "You are an AI language model that always uses LaTeX for mathematical expressions. Whenever you include equations or variables, ensure they are enclosed in $ signs. For example, f = wx + b should be written as $f = wx + b$ and \\mathbf{y} should be written as $\\mathbf{y}$. You give helpful and concise responses.",
      "title": "GPT-4o"
    },
    {
      "apiBase": "http://localhost:11434",
      "completionOptions": {
        "temperature": 0.2
      },
      "contextLength": 8196,
      "model": "llama3",
      "provider": "ollama",
      "systemMessage": "You give helpful and concise responses. When writing equations, use latex.",
      "title": "llama3-8b"
    }
  ],
  "tabAutocompleteModel": {
    "model": "starcoder2:3b",
    "provider": "ollama",
    "title": "Starcoder2 3b"
  },
}
  ```

This error seems to truncate the chat response (I'm not sure if it always does, I haven't noticed 126 truncated answeres), which seems to happen right before parsing a LaTeX expression. For example, this is what appears in the chat:

![Screenshot from 2024-07-16 01-17-56](https://github.com/user-attachments/assets/ea525e4d-15fe-4168-9f0f-1b0f54f09900)


If I copy the response from the copy button, I still get the full response, which in this case is:

```md
Transposing $X$ is necessary to correctly compute the gradient with respect to the weights $w$ using matrix multiplication. Let's break down why this is the case.

### Matrix Dimensions

1. **Shape of $X$**:
   - $X$ is an $m \times n$ matrix, where $m$ is the number of samples and $n$ is the number of features.

2. **Shape of $w$**:
   - $w$ is an $n \times 1$ vector (or $n$-dimensional array).

3. **Shape of $error$**:
   - $error$ is an $m \times 1$ vector, resulting from the operation $X @ w + b - y$.

### Gradient Calculation

The gradient with respect to $w$ is given by:

$$
\frac{\partial J}{\partial w_j} = \frac{1}{m} \sum_{i=1}^{m} \left( (X_i \cdot w + b - y_i) \cdot X_{ij} \right)
$$

In matrix form, this can be written as:

$$
\mathbf{dj\_dw} = \frac{1}{m} \mathbf{X}^T \cdot \mathbf{error}
$$

### Why Transpose?

- **Without Transpose**:
  - If you try to compute $\mathbf{X} \cdot \mathbf{error}$ directly, the dimensions won't align for matrix multiplication. Specifically, $\mathbf{X}$ is $m \times n$ and $\mathbf{error}$ is $m \times 1$, which is not compatible for multiplication.

- **With Transpose**:
  - By transposing $\mathbf{X}$, you get $\mathbf{X}^T$ which is $n \times m$. Now, $\mathbf{X}^T \cdot \mathbf{error}$ is a valid matrix multiplication, resulting in an $n \times 1$ vector, which matches the dimensions of $w$.

### Example

Consider a simple example with $m = 3$ samples and $n = 2$ features:

$$
\mathbf{X} = \begin{bmatrix}
x_{11} & x_{12} \\
x_{21} & x_{22} \\
x_{31} & x_{32}
\end{bmatrix}, \quad
\mathbf{w} = \begin{bmatrix}
w_1 \\
w_2
\end{bmatrix}, \quad
\mathbf{error} = \begin{bmatrix}
e_1 \\
e_2 \\
e_3
\end{bmatrix}
$$

To compute the gradient $\mathbf{dj\_dw}$:

$$
\mathbf{X}^T = \begin{bmatrix}
x_{11} & x_{21} & x_{31} \\
x_{12} & x_{22} & x_{32}
\end{bmatrix}
$$

Then:

$$
\mathbf{dj\_dw} = \frac{1}{m} \mathbf{X}^T \cdot \mathbf{error} = \frac{1}{m} \begin{bmatrix}
x_{11} & x_{21} & x_{31} \\
x_{12} & x_{22} & x_{32}
\end{bmatrix} \cdot \begin{bmatrix}
e_1 \\
e_2 \\
e_3
\end{bmatrix} = \frac{1}{m} \begin{bmatrix}
x_{11}e_1 + x_{21}e_2 + x_{31}e_3 \\
x_{12}e_1 + x_{22}e_2 + x_{32}e_3
\end{bmatrix}
$$

This results in an $n \times 1$ vector, which is the correct shape for the gradient with respect to $w$.

### Conclusion

Transposing $X$ ensures that the dimensions align correctly for matrix multiplication, allowing us to compute the gradient efficiently using vectorized operations. For more details on matrix operations and broadcasting, you can refer to the [NumPy documentation](https://numpy.org/doc/stable/user/quickstart.html).
```

**Comment by steventsvetkov** [comment]
I encounter this error every time I click inside an editable block of any jupyter notebook (it logs twice). It does not seem to have any other effects.

```
- OS: Pop!_OS 22.04 LTS x86_64
- Continue: 0.8.43
- IDE: vscode 1.91.0
- Model: gpt-4o
- config.json
```

```json
{
  "models": [
    {
      "apiKey": "",
      "completionOptions": {
        "temperature": 0
      },
      "contextLength": 131072000,
      "model": "gpt-4o",
      "provider": "openai",
      "systemMessage": "You are an AI language model that always uses LaTeX for mathematical expressions. Whenever you include equations or variables, ensure they are enclosed in $ signs. For example, f = wx + b should be written as $f = wx + b$ and \\mathbf{y} should be written as $\\mathbf{y}$. You give helpful and concise responses.",
      "title": "GPT-4o"
    }
  ],
}
  ```

**Comment by flekol** [comment]
@sestinj i have exactly the same problem. It even happens without an open file in a new window

Also it slows down opening new files by a lot from the explorer window. This is very noticeable if working over SSH. 

```
2024-07-18 22:24:37.752 [error] Error: Parsing failed
	at _Parser.parse (c:\Users\filip\.vscode\extensions\continue.continue-0.8.43-win32-x64\out\extension.js:94941:81)
	at _ImportDefinitionsService._getFileInfo (c:\Users\filip\.vscode\extensions\continue.continue-0.8.43-win32-x64\out\extension.js:95847:28)
	at async PrecalculatedLruCache.initKey (c:\Users\filip\.vscode\extensions\continue.continue-0.8.43-win32-x64\out\extension.js:93797:25)
```

**Comment by zenarcher007** [comment]
I am facing this same issue, although the effects of it may be more severe for me. The connection between these uncaught exceptions being constantly spammed and the occurrence of this problem can only be speculative, but seemingly only when the Continue extension is enabled, the extension host will freeze after a few minutes (and ~ 22 errors) with "Extension host unresponsive", and almost all functionality of VSCode will not complete, including saving files, running tasks, and file operations in the file explorer, requiring a reload

**Comment by Patrick-Erichsen** [comment]
@zenarcher007 is running `Macos Sonoma M1`

**Comment by Patrick-Erichsen** [comment]
@zenarcher007 - hopefully this is resolved in https://github.com/continuedev/continue/pull/1828

We will be shipping a new pre-release in the next day or two, so please circle back once you get that installed and let me know if it fixes things for you 👍

**Comment by zenarcher007** [comment]
@Patrick-Erichsen Great 👍. I did not notice the packages.json in core. I have been putting this version through its paces a bit, observing that when web-tree-sitter is turned back to 0.21, freezes and parse errors occur, whereas I cannot get them to occur after the version bump. While it's still possible it could be sporadic, it usually would freeze within the first 2 minutes of significant use, and I have been testing it for longer.

**Comment by Patrick-Erichsen** [comment]
Awesome, thank you for taking the time to test between the two versions. Sounds like it's at least fixing the issue on your local 👍

**Comment by zenarcher007** [comment]
@Patrick-Erichsen I may have made an oversight, and I apologize for this. Your pull request switches web-tree-sitter from version 0.21.0 to 0.22.0. However, I have noticed on my system that when switching this between the two versions, multi-line completion stops working with the latter (although single-line completion still works). I also tried version 0.22.6, but it doesn't seem to make a difference. I thought something had seemed a little odd afterwards, and speculating that Continue was helping out lesser than usual, I thought it was important to correct this.  
<br>  
On the newer version of web-tree-sitter, Continue produces the following error upon first opening a file, which seems, via extension.js, to be associated with web-tree-sitter. I thought to find where this is thrown from in the code, although there is little documentation on how to start the breakpoint-debugger for Continue on the [contributing](https://github.com/continuedev/continue/blob/main/CONTRIBUTING.md#vs-code) page.
```
x.onmessage @ localProcessExtensionHost.ts:378
log.ts:439   ERR [Extension Host] Aborted(LinkError: WebAssembly.instantiate(): Import #6 module="env" function="emscripten_memcpy_big": function import requires a callable)
console.ts:137 [Extension Host] Aborted(LinkError: WebAssembly.instantiate(): Import #6 module="env" function="emscripten_memcpy_big": function import requires a callable)
y @ console.ts:137
$logExtensionHostMessage @ mainThreadConsole.ts:39
S @ rpcProtocol.ts:458
Q @ rpcProtocol.ts:443
M @ rpcProtocol.ts:373
L @ rpcProtocol.ts:299
(anonymous) @ rpcProtocol.ts:161
B @ event.ts:1211
fire @ event.ts:1242
fire @ ipc.net.ts:650
```
Especially if others experience this issue, I might suggest switching this back for now

**Comment by Patrick-Erichsen** [comment]
Hey @zenarcher007 , good catch, we are indeed reverting back to 21 for now. Please keep us in the loop on your unresponsive issues though. We've made some other improvements to parsing in recent commits so hopeful that it will solve itself.
