### ISSUE TITLE
Unable to debug vscode extension

### ISSUE THREAD

**Issue by ilifanovwg** [continuedev/continue#1760]
### Before submitting your bug report

- [ ] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [ ] I've seen the [troubleshooting guide](https://docs.continue.dev/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS: Windows 11
- Continue: dev branch
- IDE: VS Code 1.91.1
- Model:
- config.json:
```

### Description

I'm trying to start debugging of the extension, checkout dev branch installed dependencies, but after launching of the extension I'm getting the error:
Activating extension 'Continue.continue' failed: Could not locate the bindings file. Tried:
 → d:\dev\continue\extensions\vscode\out\build\node_sqlite3.node
 → d:\dev\continue\extensions\vscode\out\build\Debug\node_sqlite3.node
 → d:\dev\continue\extensions\vscode\out\build\Release\node_sqlite3.node
 → d:\dev\continue\extensions\vscode\out\out\Debug\node_sqlite3.node
 → d:\dev\continue\extensions\vscode\out\Debug\node_sqlite3.node
 → d:\dev\continue\extensions\vscode\out\out\Release\node_sqlite3.node
 → d:\dev\continue\extensions\vscode\out\Release\node_sqlite3.node
 → d:\dev\continue\extensions\vscode\out\build\default\node_sqlite3.node
 → d:\dev\continue\extensions\vscode\out\compiled\20.9.0\win32\x64\node_sqlite3.node
 → d:\dev\continue\extensions\vscode\out\addon-build\release\install-root\node_sqlite3.node
 → d:\dev\continue\extensions\vscode\out\addon-build\debug\install-root\node_sqlite3.node
 → d:\dev\continue\extensions\vscode\out\addon-build\default\install-root\node_sqlite3.node
 → d:\dev\continue\extensions\vscode\out\lib\binding\node-v121-win32-x64\node_sqlite3.node.
 
![image](https://github.com/user-attachments/assets/fa5208da-8070-41bf-8072-86b2e8ab0d16)

### To reproduce

1. checkout dev branch
2. Open the VS Code command pallet (cmd/ctrl+shift+p) and select Tasks: Run Task and then select install-all-dependencies
3. Start debugging

**Comment by ilifanovwg** [comment]
and sometimes I'm getting another error 
Activating extension 'Continue.continue' failed: Cannot find module 'd:\dev\continue\extensions\vscode\out\extension.js'
Require stack:
- c:\Program Files\Microsoft VS Code\resources\app\out\vs\loader.js
- c:\Program Files\Microsoft VS Code\resources\app\out\bootstrap-amd.js
- c:\Program Files\Microsoft VS Code\resources\app\out\bootstrap-fork.js.

**Comment by Symbolk** [comment]
> and sometimes I'm getting another error Activating extension 'Continue.continue' failed: Cannot find module 'd:\dev\continue\extensions\vscode\out\extension.js' Require stack:
> 
> * c:\Program Files\Microsoft VS Code\resources\app\out\vs\loader.js
> * c:\Program Files\Microsoft VS Code\resources\app\out\bootstrap-amd.js
> * c:\Program Files\Microsoft VS Code\resources\app\out\bootstrap-fork.js.

Same here for the latest main branch code! This tells that the extension is not compiled successfully due to some reasons. Have you solved it?

**Comment by benlan96** [comment]
me too how to solve it

**Comment by nang-dev** [comment]
You can fix it by deleting the vscode/extension/out folder

**Comment by Symbolk** [comment]
I have successfully run it in VSCode, here are my commands, I am not sure whether there is a doc section including this, but hope it gives someone a hand:

How to run Continue VSCode
```
cd core
npm i

cd ..
cd binary
npm i
npm run build

cd ..
cd gui
npm i
npm run build

cd ..
cd extensions/vscode
npm i
npm run prepackage

ollama list
ollama run llama3.1:8b
ollama run gemma2:2b
ollama run starcoder2:3b
ollama pull nomic-embed-text

# Open extension.ts in VSCode
F5
```

**Comment by al3x-lm** [comment]
Same Issue:
after installing all dependencies I try to run Continue via vscode debugger but it fails.
vscode-extension:continue-ui:build task fails trying to remove:

- [info] Error removing unused binaries Error: EPERM: operation not permitted, unlink 'C:\Users\snappy\http\continue\extensions\vscode\bin\napi-v3\darwin\arm64\libonnxruntime.1.14.0.dylib'
- 
- Error: EPERM: operation not permitted, unlink 'C:\Users\snappy\http\continue\extensions\vscode\node_modules\@esbuild\win32-x64\esbuild.exe'

- OS: Windows 11
- IDE: VS Code 1.92

**Comment by al3x-lm** [comment]
@Symbolk tried your solution but did not worked for me.

**Comment by korealex** [comment]
> Same Issue: after installing all dependencies I try to run Continue via vscode debugger but it fails. vscode-extension:continue-ui:build task fails trying to remove:
> 
> * [info] Error removing unused binaries Error: EPERM: operation not permitted, unlink 'C:\Users\snappy\http\continue\extensions\vscode\bin\napi-v3\darwin\arm64\libonnxruntime.1.14.0.dylib'
> * Error: EPERM: operation not permitted, unlink 'C:\Users\snappy\http\continue\extensions\vscode\node_modules@esbuild\win32-x64\esbuild.exe'
> * OS: Windows 11
> * IDE: VS Code 1.92

Tested on different machines with same result.
![image](https://github.com/user-attachments/assets/4e74494f-3ad2-4a98-b233-244dde193f54)

This is on branch v0.8.50-vscode

```
 *  Executing task: node C:\Users\alros\http\continue/extensions/vscode/scripts/prepackage.js 

[info] Using target:  win32-x64
[info] Packaging extension for target  win32-x64
[info] npm install in extensions/vscode completed
[info] npm install in gui completed
[info] Copied gui build to JetBrains extension
Copied gui build to VSCode extension
[info] Copied onnxruntime-node
[info] Copied tree-sitter.wasm
[info] Copied llamaTokenizerWorkerPool.mjs
[info] Copied llamaTokenizer.mjs
[info] Copied tiktokenWorkerPool.mjs
npm installing esbuild binary
Copying esbuild@0.17.19 to @esbuild
node:fs:1878
  binding.unlink(path);
          ^

Error: EPERM: operation not permitted, unlink 'C:\Users\alros\http\continue\extensions\vscode\node_modules\@esbuild\win32-x64\esbuild.exe'
    at unlinkSync (node:fs:1878:11)
    at C:\Users\alros\http\continue\extensions\vscode\node_modules\rimraf\dist\commonjs\fix-eperm.js:52:20
    at method (C:\Users\alros\http\continue\extensions\vscode\node_modules\rimraf\dist\commonjs\retry-busy.js:50:24)
    at C:\Users\alros\http\continue\extensions\vscode\node_modules\rimraf\dist\commonjs\rimraf-windows.js:154:56
    at ignoreENOENTSync (C:\Users\alros\http\continue\extensions\vscode\node_modules\rimraf\dist\commonjs\ignore-enoent.js:12:16)
    at rimrafWindowsDirSync (C:\Users\alros\http\continue\extensions\vscode\node_modules\rimraf\dist\commonjs\rimraf-windows.js:154:49)
    at rimrafWindowsDirSync (C:\Users\alros\http\continue\extensions\vscode\node_modules\rimraf\dist\commonjs\rimraf-windows.js:161:22)
    at rimrafWindowsDirSync (C:\Users\alros\http\continue\extensions\vscode\node_modules\rimraf\dist\commonjs\rimraf-windows.js:161:22)
    at rimrafWindowsSync (C:\Users\alros\http\continue\extensions\vscode\node_modules\rimraf\dist\commonjs\rimraf-windows.js:82:16)
    at C:\Users\alros\http\continue\extensions\vscode\node_modules\rimraf\dist\commonjs\index.js:59:47 {
  errno: -4048,
  code: 'EPERM',
  syscall: 'unlink',
  path: 'C:\\Users\\alros\\http\\continue\\extensions\\vscode\\node_modules\\@esbuild\\win32-x64\\esbuild.exe'
}
```

Node.js v20.11.0

**Comment by eagle3y3** [comment]
> syscall: 'unlink'

You seem to have permission error. I see your syscall is "unlink." I had to run the command `npm config set script-shell cmd` for mine to work.

**Comment by who52023** [comment]
D:\develop\nodejs\node.exe .\out\index.js
Process exited with code 1
Uncaught Error Error: Could not locate the bindings file. Tried:
 → D:\develop_llm\vscode_proj\continue-main\binary\build\node_sqlite3.node
 → D:\develop_llm\vscode_proj\continue-main\binary\build\Debug\node_sqlite3.node
 → D:\develop_llm\vscode_proj\continue-main\binary\build\Release\node_sqlite3.node
 → D:\develop_llm\vscode_proj\continue-main\binary\out\Debug\node_sqlite3.node
 → D:\develop_llm\vscode_proj\continue-main\binary\Debug\node_sqlite3.node
 → D:\develop_llm\vscode_proj\continue-main\binary\out\Release\node_sqlite3.node
 → D:\develop_llm\vscode_proj\continue-main\binary\Release\node_sqlite3.node
 → D:\develop_llm\vscode_proj\continue-main\binary\build\default\node_sqlite3.node
 → D:\develop_llm\vscode_proj\continue-main\binary\compiled\20.11.0\win32\x64\node_sqlite3.node
 → D:\develop_llm\vscode_proj\continue-main\binary\addon-build\release\install-root\node_sqlite3.node
 → D:\develop_llm\vscode_proj\continue-main\binary\addon-build\debug\install-root\node_sqlite3.node
 → D:\develop_llm\vscode_proj\continue-main\binary\addon-build\default\install-root\node_sqlite3.node
 → D:\develop_llm\vscode_proj\continue-main\binary\lib\binding\node-v115-win32-x64\node_sqlite3.node
    at bindings (d:\develop_llm\vscode_proj\continue-main\core\node_modules\bindings\bindings.js:126:9)
    at ../core/node_modules/sqlite3/lib/sqlite3-binding.js (d:\develop_llm\vscode_proj\continue-main\core\node_modules\sqlite3\lib\sqlite3-binding.js:1:18)
    at __require (d:\develop_llm\vscode_proj\continue-main\binary\out\index.js:18:51)
    at ../core/node_modules/sqlite3/lib/sqlite3.js (d:\develop_llm\vscode_proj\continue-main\core\node_modules\sqlite3\lib\sqlite3.js:2:17)
    at __require (d:\develop_llm\vscode_proj\continue-main\binary\out\index.js:18:51)
    at <anonymous> (d:\develop_llm\vscode_proj\continue-main\core\autocomplete\cache.ts:3:21)
    at Module._compile (internal/modules/cjs/loader:1376:14)
    at Module._extensions..js (internal/modules/cjs/loader:1435:10)
    at Module.load (internal/modules/cjs/loader:1207:32)
    at Module._load (internal/modules/cjs/loader:1023:12)
    at executeUserEntryPoint (internal/modules/run_main:135:12)
    at <anonymous> (internal/main/run_main_module:28:49)
 debug Core Binary has a error hint

**Comment by SnowerII** [comment]
same question,tried but still not working.
im sure there can be problem in  npm install or build

**Comment by al3x-lm** [comment]
@sestinj any suggestions?
seems like the debugger script for windows fail when removing the esbuild files on the prepackage.js.
it complains on permissions to unlink the generated files on the prepackaging. 
When installing it fails too but it doesn't stops the process, on the debugger the unlink permission makes the process fail.

**Comment by heiung2001** [comment]
I'm using Windows 10 and encountered the same issues ("PERM unlink" and "Cannot find module 'd:\dev\continue\extensions\vscode\out\extension.js'"). I figured out that this problem occurs because VS Code doesn't have permission to run the **vscode-extension:continue-ui:build** task. I haven't found a proper way to fix these issues yet. However, if you still want to be in debug mode, here are my steps:
1. Close all vscode windows and run `node ${workspaceFolder}/extensions/vscode/scripts/prepackage.js` on terminal.
2. Open VScode and comment line 11 in ".vscode/tasks.json"
![image](https://github.com/user-attachments/assets/0ec5021c-fd74-4ef8-8912-9c6f6f916e0c)
3. Launch extension as in the docs mentioned.

**Comment by al3x-lm** [comment]
@heiung2001 Thanks! at least that helps, I moved to a Linux and there i can run the debugger perfectly. 
This will help at least test run on windows until there is a fix.

**Comment by DevangPagare002** [comment]
I think Windows users mostly experience this issue. I recommend installing **Ubuntu** via **WSL2**. Once set up, you can work with the repository in one of the following ways:

- Mount the repository folder from Windows into Ubuntu and launch it in VS Code.
- Clone the repository directly in Ubuntu.

After setting up the repository, follow the instructions in the `CONTRIBUTING.md` file to configure your environment and launch the extension.

If you run into errors while installing dependencies for the extension when mounting the Windows repository to Ubuntu, here's a quick fix:

- Change the End of Line Sequence for the workspace from CRLF to LF. This will allow you to run your `install_dependencies.sh` without issues.

**Comment by al3x-lm** [comment]
@DevangPagare002 Thanks for sharing the workflow. Sadly a work around is not an option since it will be ideal to just debug on windows. 

When running the debugger from Linux connected via remote-ssh on windows the prepackage script is for Linux so you get an sqlite architecture error. 

 I am working full on Linux for now and works great, same for mac, is just the prepackage script  + the esbuilder being sideloaded and installed with a different permissions that the rest of the node_modules. I am no windows expert so I just open an issue.

**Comment by sestinj** [comment]
For everyone experiencing the `Error: EPERM: operation not permitted, unlink 'C:\Users\alros\http\continue\extensions\vscode\node_modules\@esbuild\win32-x64\esbuild.exe'` error, I've just pushed a solution to the `dev` branch: https://github.com/continuedev/continue/commit/e0ddfeea8472db56aa96c18b33aa1664928f58dc

The problem here was that we are running `esbuild` in watch mode while trying to remove that folder. By having the esbuild-watch task depend on the prepackage task to finish, this conflict won't occur.

There's still a secondary issue though, which was the original
```
Activating extension 'Continue.continue' failed: Could not locate the bindings file. Tried:
→ d:\dev\continue\extensions\vscode\out\build\node_sqlite3.node
```

This seems to be more of a timing problem than anything else, as I've been able to confirm on my own windows machine that the node_sqlite3.node file is correctly downloaded to the out/build/Release folder. Probably in the worst case you will have to "Reload window" when you get this the first time.

If it's still causing major headaches, perhaps we can add some kind of timeout to make sure it is fully downloaded

**Comment by glm1024** [comment]
I got another issue in mac: 

Activating extension 'Continue.continue' failed: Request constructor: Expected init.body ("<ref *1> h [ReadableStream] { _state: 'readable', _reader: undefined, _storedError: undefined, _disturbed: false, _readableStreamController: h [ReadableStreamDefaultController] { _controlledReadableStream: [Circular *1], _queue: h { _cursor: 0, _size: 0, _front: [Object], _back: [Object] }, _queueTotalSize: 0, _started: false, _closeRequested: false, _pullAgain: false, _pulling: false, _strategySizeAlgorithm: [Function (anonymous)], _strategyHWM: 1, _pullAlgorithm: [Function (anonymous)], _cancelAlgorithm: [Function (anonymous)] } }") to be an instance of ReadableStream..
