### ISSUE TITLE
SQLITE_CORRUPT: database disk image is malformed

### ISSUE THREAD

**Issue by smiling-watermelon** [continuedev/continue#2016]
### Before submitting your bug report

- [X] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [X] I've seen the [troubleshooting guide](https://docs.continue.dev/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS: Fedora Linux 40 (Workstation Edition)
- Continue: v0.8.46
- IDE: VS Code 1.92.1
- Model: -
- config.json:
  
 {
  "models": [
    {
      "title": "GPT-4o",
      "provider": "openai",
      "model": "gpt-4o",
      "apiKey": "...",
      "systemMessage": "You are an expert software developer. You give helpful and concise responses."
    },
    {
      "title": "LLama 3",
      "provider": "ollama",
      "model": "llama3-8b",
      "systemMessage": "You are an expert software developer. You give helpful and concise responses. Whenever you write a code block you include the language after the opening ticks."
    }
  ],
  "customCommands": [
    {
      "name": "test",
      "prompt": "{{{ input }}}\n\nWrite a comprehensive set of unit tests for the selected code. It should setup, run tests that check for correctness including important edge cases, and teardown. Ensure that the tests are complete and sophisticated. Give the tests just as chat output, don't edit any file.",
      "description": "Write unit tests for highlighted code"
    }
  ],
  "allowAnonymousTelemetry": true,
  "docs": []
}
```

### Description

When the extension starts, I get this error. I'm not sure what/where this database image is, I couldn't find in the extension folder of Continue.

I'm not sure how I can cause it to be malformed, since last time I've used it, I have exited the editor as usual.

### To reproduce

Since Log Output doesn't support pasting images, I'll attach one here.
![image](https://github.com/user-attachments/assets/980a8798-6c88-4e7a-ba12-cd619431bba8)

### Log output

```Shell
[2024-08-15T05:20:55] [DEBUG] Logging initialized
[2024-08-15T05:20:55] [ERROR] Error adding item to minisearch: t is not iterable TypeError: t is not iterable
    at bc.addAll (https://file+.vscode-resource.vscode-cdn.net/home/woka/.vscode/extensions/continue.continue-0.8.46-linux-x64/gui/assets/index.js:684:8064)
    at https://file+.vscode-resource.vscode-cdn.net/home/woka/.vscode/extensions/continue.continue-0.8.46-linux-x64/gui/assets/index.js:684:23379
[2024-08-15T05:20:55] [ERROR] {}
```
```

**Comment by smiling-watermelon** [comment]
Note, found it after reading the source code, it's in:
`~/.continue/index`

**Comment by fry69** [comment]
Switch to the latest Pre-Release `0.9.197` in the extension view for Continue (top right).

Also stop VSCode, delete the ~/.continue/index folder (it will get rebuilt automatically) and start VSCode again.

If this problem appears again, please let us know.

**Comment by JakubCerven** [comment]
> Switch to the latest Pre-Release `0.9.197` in the extension view for Continue (top right).
> 
> Also stop VSCode, delete the entire `~/.continue/index` folder (it will get rebuilt automatically) and start VSCode again.
> 
> If this problem appears again, please post here.
> 
> (BTW: This is the first corrupt SQLite db file I see, this is very rare. Are you sure nothing else is interfering on your system? SQLite and their db files are extremely widely used and extremely stable. To corrupt a SQLite db file extraordinary things usually happen, none of which Continue is capable of.)

encountered same problem as described in the issue, upgrading to pre-release solved the problem

**Comment by fry69** [comment]
> encountered same problem as described in the issue, upgrading to pre-release solved the problem

You also saw a corrupt SQLite db file? This should absolutely never happen IMHO. Can you please post your system specs roughly, which OS version, which VSCode/Continue version (before you upgraded), etc?

**Comment by sealad886** [comment]
I'm pretty reliably able to corrupt the SQLite DB by adding or removing files _outside of VSC_ within a previously indexed path, then moving the Window back to somewhere that includes that folder. Took me a while to get there, but that's the behavior I'm able to re-create at this point. 
Of note, VSC can be open or closed, and it will still corrupt the db when trying to refresh.
