### ISSUE TITLE
Developer Console Log Error: "Error loading color theme"

### ISSUE THREAD

**Issue by Derjyn** [continuedev/continue#2033]
### Before submitting your bug report

- [X] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [X] I've seen the [troubleshooting guide](https://docs.continue.dev/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS: Windows 10
- Continue: 0.8.46 - 2024-08-11
- IDE: VSCode
- Model: N/A
- config.json:

{
  "tabAutocompleteModel": {
    "provider": "ollama",
    "title": "Tab Autocomplete Model",
    "model": "llama3.1:latest",
    "apiBase": "http://localhost:11434"
  },
  "embeddingsProvider": {
    "provider": "ollama",
    "title": "Embeddings Provider",
    "model": "nomic-embed-text:latest",
    "apiBase": "http://localhost:11434"
  },
  "models": [
    {
      "provider": "ollama",
      "title": "Llama 3.1",
      "model": "llama3.1:latest",
      "apiBase": "http://localhost:11434",
      "systemMessage": "You are an AI programming assistant. Before responding first extract high-level concepts and principles from given details, then use those concepts to guide your reasoning towards the correct solution. You will review your reasoning, to further understand the problem and devise a plan to solve the problem. Finally, you'll carry out the plan and solve the problem step by step.",
      "contextLength": 16384
    }
  ],
  "completionOptions": {
    "mirostat": 2,
    "numThreads": 0,
    "temperature": 0.2,
    "topK": 50,
    "frequencyPenalty": 0.5,
    "presencePenalty": 0,
    "maxTokens": 4096
  },
  "contextProviders": [
    {
      "name": "codebase",
      "params": {
        "nRetrieve": 60,
        "nFinal": 30,
        "useReranking": true
      }
    },
    {
      "name": "code",
      "params": {}
    },
    {
      "name": "tree",
      "params": {}
    },
    {
      "name": "docs",
      "params": {}
    },
    {
      "name": "diff",
      "params": {}
    },
    {
      "name": "open",
      "params": {}
    },
    {
      "name": "terminal",
      "params": {}
    },
    {
      "name": "problems",
      "params": {}
    },
    {
      "name": "folder",
      "params": {}
    },
    {
      "name": "os",
      "params": {}
    },
    {
      "name": "url",
      "params": {}
    }
  ],
  "slashCommands": [
    {
      "name": "edit",
      "description": "Edit selected code"
    },
    {
      "name": "comment",
      "description": "Write comments for the selected code"
    },
    {
      "name": "cmd",
      "description": "Generate a shell command"
    }
  ],
  "customCommands": [
    {
      "name": "explain",
      "prompt": "Explain the selected code.",
      "description": "Explain selected code"
    }
  ],
  "docs": [],
  "allowAnonymousTelemetry": false
}
```
```


### Description

As it says on the title. Seeing an error related to theming in the developer console.

### To reproduce

1. Fire up VSCode.
2. Toggle Developer Tools.
3. Read log.

### Log output

```Shell
[Extension Host] Error loading color theme:  SyntaxError: Expected ',' or '}' after property value in JSON at position 9025 (line 174 column 65)
	at JSON.parse (<anonymous>)
	at parseThemeString (c:\Users\derjy\.vscode\extensions\continue.continue-0.8.46-win32-x64\out\extension.js:435852:15)
	at getTheme (c:\Users\derjy\.vscode\extensions\continue.continue-0.8.46-win32-x64\out\extension.js:435879:18)
	at ContinueGUIWebviewViewProvider.getSidebarContent (c:\Users\derjy\.vscode\extensions\continue.continue-0.8.46-win32-x64\out\extension.js:436230:30)
	at ContinueGUIWebviewViewProvider.resolveWebviewView (c:\Users\derjy\.vscode\extensions\continue.continue-0.8.46-win32-x64\out\extension.js:436174:41)
	at c.$resolveWebviewView (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:155:55840)
	at E.S (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:150:5970)
	at E.Q (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:150:5736)
	at E.M (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:150:4723)
	at E.L (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:150:3814)
	at n.value (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:150:2282)
	at l.y (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:82:664)
	at l.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:82:881)
	at s.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:107:14502)
	at n.value (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:176:8481)
	at l.y (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:82:664)
	at l.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:82:881)
	at s.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:107:14502)
	at MessagePortMain.<anonymous> (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:176:6631)
	at MessagePortMain.emit (node:events:514:28)
	at MessagePortMain._internalPort.emit (node:electron/js2c/utility_init:2:2285)
```

**Comment by sestinj** [comment]
@Derjyn can you share what color theme you are using in VS Code?

Also from information here it looks like this is a warning, rather than a critical error. Let me know if that assumption is incorrect

**Comment by Derjyn** [comment]
The theme I'm using is [Eva Darker](https://marketplace.visualstudio.com/items?itemName=aleknev.Eva-Darker).

While it doesn't appear to be a critical error, as an end user... I like to keep a clean environment, and these warnings/errors start to add up. And there could certainly be performance issues in play.

I appreciate your eyes, and your continued work on... Continue! This issue hasn't stopped me from doing anything, but adds to scrolling and irritation in the back of my mind when navigating the console and such in VSC.
