### ISSUE TITLE
ctrl enter not using codebase

### ISSUE THREAD

**Issue by stjema** [continuedev/continue#2077]
### Before submitting your bug report

- [X] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [x] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [X] I've seen the [troubleshooting guide](https://docs.continue.dev/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS:win11
- Continue:0.8.46
- IDE:vsc
- Model:sonnet 3.5 non-beta
- config.json:
  
{
  "models": [
    {
      "title": "OpenRouter claude-3.5-sonnet",
      "provider": "openai",
      "model": "anthropic/claude-3.5-sonnet",
      "apiBase": "https://openrouter.ai/api/v1",
      "apiKey": "sk-or-v1-0ac5fffffffffffffffffffffffffffffffffffa2a",
      "requestOptions": {
        "extraBodyProperties": {
          "transforms": []
        }
      }
    },
    {
      "title": "OpenRouter DeepSeek-Coder-V2",
      "provider": "openai",
      "model": "deepseek/deepseek-coder",
      "apiBase": "https://openrouter.ai/api/v1",
      "apiKey": "sk-or-v1-0ffffffffffffffffffffffffffffffffffffffffffffffffff6a2a",
      "requestOptions": {
        "extraBodyProperties": {
          "transforms": []
        }
      }
    },
    {
      "title": "Codestral",
      "model": "codestral-latest",
      "apiKey": "YOURKEY",
      "completionOptions": {},
      "provider": "mistral"
    }
  ],
  "tabAutocompleteModel": {
    "title": "Tab Autocomplete",
    "provider": "free-trial",
    "model": "codestral-latest"
  },

  "contextProviders": [
    {
      "name": "code",
      "params": {}
    },
    {
      "name": "docs",
      "params": {}
    },
    {
      "name": "diff",
      "params": {}
    },
    {
      "name": "terminal",
      "params": {}
    },
    {
      "name": "problems",
      "params": {}
    },
    {
      "name": "folder",
      "params": {}
    },
    {
      "name": "codebase",
      "params": {}
    }
  ],
  "slashCommands": [
    {
      "name": "edit",
      "description": "Edit selected code"
    },
    {
      "name": "comment",
      "description": "Write comments for the selected code"
    },
    {
      "name": "share",
      "description": "Export the current chat session to markdown"
    },
    {
      "name": "cmd",
      "description": "Generate a shell command"
    },
    {
      "name": "commit",
      "description": "Generate a git commit message"
    }
  ],
  "embeddingsProvider": {
    "provider": "free-trial"
  },
  "reranker": {
    "name": "free-trial"
  }
}
```

### Description

clicking on "use codebase" work though.
its also a fresh install of vcs.

**Comment by Patrick-Erichsen** [comment]
Hi @stjema , any error output you can show here? https://docs.continue.dev/troubleshooting#vs-code

Also, could you share a screenshot of the results with "use codebase" vs cmd + enter?

**Comment by stjema** [comment]
if i click on use codebase:

`Failed to load resource: net::ERR_NETWORK_IO_SUSPENDED
console.ts:137 [Extension Host] Git not found:  Error: Git model not found
	at s.getAPI (c:\Users\stewie\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\git\dist\main.js:2:795499)
	at _VsCodeIdeUtils._getRepo (c:\Users\stewie\.vscode\extensions\continue.continue-0.8.46-win32-x64\out\extension.js:443362:41)
	at _VsCodeIdeUtils.getRepo (c:\Users\stewie\.vscode\extensions\continue.continue-0.8.46-win32-x64\out\extension.js:443383:31)
	at _VsCodeIdeUtils.getBranch (c:\Users\stewie\.vscode\extensions\continue.continue-0.8.46-win32-x64\out\extension.js:443407:33)
	at VsCodeIde.getBranch (c:\Users\stewie\.vscode\extensions\continue.continue-0.8.46-win32-x64\out\extension.js:443856:30)
	at c:\Users\stewie\.vscode\extensions\continue.continue-0.8.46-win32-x64\out\extension.js:361680:55
	at Array.map (<anonymous>)
	at retrieveContextItemsFromEmbeddings (c:\Users\stewie\.vscode\extensions\continue.continue-0.8.46-win32-x64\out\extension.js:361680:31)
y @ console.ts:137
$logExtensionHostMessage @ mainThreadConsole.ts:39
S @ rpcProtocol.ts:458
Q @ rpcProtocol.ts:443
M @ rpcProtocol.ts:373
L @ rpcProtocol.ts:299
(anonymous) @ rpcProtocol.ts:161
B @ event.ts:1230
fire @ event.ts:1261
fire @ ipc.net.ts:652
K.onmessage @ localProcessExtensionHost.ts:378
console.ts:137 [Extension Host] Error reading file EntryNotFound (FileSystemError): Error: ENOENT: no such file or directory, stat 'c:\Users\stewie\Documents\1111\index.html'
	at P.e (c:\Users\stewie\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:153:6206)
	at Object.stat (c:\Users\stewie\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:153:3977)
	at async _VsCodeIdeUtils.readFile (c:\Users\stewie\.vscode\extensions\continue.continue-0.8.46-win32-x64\out\extension.js:443197:29)
	at async VsCodeIde.readFile (c:\Users\stewie\.vscode\extensions\continue.continue-0.8.46-win32-x64\out\extension.js:443772:16)
	at async RerankerRetrievalPipeline.retrieveAndChunkRecentlyEditedFiles (c:\Users\stewie\.vscode\extensions\continue.continue-0.8.46-win32-x64\out\extension.js:361520:29)
	at async RerankerRetrievalPipeline._retrieveInitial (c:\Users\stewie\.vscode\extensions\continue.continue-0.8.46-win32-x64\out\extension.js:361604:43)
	at async RerankerRetrievalPipeline.run (c:\Users\stewie\.vscode\extensions\continue.continue-0.8.46-win32-x64\out\extension.js:361647:31)
	at async retrieveContextItemsFromEmbeddings (c:\Users\stewie\.vscode\extensions\continue.continue-0.8.46-win32-x64\out\extension.js:361704:19)
	at async c:\Users\stewie\.vscode\extensions\continue.continue-0.8.46-win32-x64\out\extension.js:429527:27
	at async c:\Users\stewie\.vscode\extensions\continue.continue-0.8.46-win32-x64\out\extension.js:469223:20
	at async i.value (c:\Users\stewie\.vscode\extensions\continue.continue-0.8.46-win32-x64\out\extension.js:435971:32)
y @ console.ts:137
$logExtensionHostMessage @ mainThreadConsole.ts:39
S @ rpcProtocol.ts:458
Q @ rpcProtocol.ts:443
M @ rpcProtocol.ts:373
L @ rpcProtocol.ts:299
(anonymous) @ rpcProtocol.ts:161
B @ event.ts:1230
fire @ event.ts:1261
fire @ ipc.net.ts:652
K.onmessage @ localProcessExtensionHost.ts:378
console.ts:137 [Extension Host] Error reading file EntryNotFound (FileSystemError): Error: ENOENT: no such file or directory, stat 'c:\Users\stewie\Documents\1111\styles.css'
	at P.e (c:\Users\stewie\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:153:6206)
	at Object.stat (c:\Users\stewie\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:153:3977)
	at async _VsCodeIdeUtils.readFile (c:\Users\stewie\.vscode\extensions\continue.continue-0.8.46-win32-x64\out\extension.js:443197:29)
	at async VsCodeIde.readFile (c:\Users\stewie\.vscode\extensions\continue.continue-0.8.46-win32-x64\out\extension.js:443772:16)
	at async RerankerRetrievalPipeline.retrieveAndChunkRecentlyEditedFiles (c:\Users\stewie\.vscode\extensions\continue.continue-0.8.46-win32-x64\out\extension.js:361520:29)
	at async RerankerRetrievalPipeline._retrieveInitial (c:\Users\stewie\.vscode\extensions\continue.continue-0.8.46-win32-x64\out\extension.js:361604:43)
	at async RerankerRetrievalPipeline.run (c:\Users\stewie\.vscode\extensions\continue.continue-0.8.46-win32-x64\out\extension.js:361647:31)
	at async retrieveContextItemsFromEmbeddings (c:\Users\stewie\.vscode\extensions\continue.continue-0.8.46-win32-x64\out\extension.js:361704:19)
	at async c:\Users\stewie\.vscode\extensions\continue.continue-0.8.46-win32-x64\out\extension.js:429527:27
	at async c:\Users\stewie\.vscode\extensions\continue.continue-0.8.46-win32-x64\out\extension.js:469223:20
	at async i.value (c:\Users\stewie\.vscode\extensions\continue.continue-0.8.46-win32-x64\out\extension.js:435971:32)
y @ console.ts:137
$logExtensionHostMessage @ mainThreadConsole.ts:39
S @ rpcProtocol.ts:458
Q @ rpcProtocol.ts:443
M @ rpcProtocol.ts:373
L @ rpcProtocol.ts:299
(anonymous) @ rpcProtocol.ts:161
B @ event.ts:1230
fire @ event.ts:1261
fire @ ipc.net.ts:652
K.onmessage @ localProcessExtensionHost.ts:378
console.ts:137 [Extension Host] Error reading file EntryNotFound (FileSystemError): Error: ENOENT: no such file or directory, stat 'c:\Users\stewie\Documents\1111\script.js'
	at P.e (c:\Users\stewie\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:153:6206)
	at Object.stat (c:\Users\stewie\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:153:3977)
	at async _VsCodeIdeUtils.readFile (c:\Users\stewie\.vscode\extensions\continue.continue-0.8.46-win32-x64\out\extension.js:443197:29)
	at async VsCodeIde.readFile (c:\Users\stewie\.vscode\extensions\continue.continue-0.8.46-win32-x64\out\extension.js:443772:16)
	at async RerankerRetrievalPipeline.retrieveAndChunkRecentlyEditedFiles (c:\Users\stewie\.vscode\extensions\continue.continue-0.8.46-win32-x64\out\extension.js:361520:29)
	at async RerankerRetrievalPipeline._retrieveInitial (c:\Users\stewie\.vscode\extensions\continue.continue-0.8.46-win32-x64\out\extension.js:361604:43)
	at async RerankerRetrievalPipeline.run (c:\Users\stewie\.vscode\extensions\continue.continue-0.8.46-win32-x64\out\extension.js:361647:31)
	at async retrieveContextItemsFromEmbeddings (c:\Users\stewie\.vscode\extensions\continue.continue-0.8.46-win32-x64\out\extension.js:361704:19)
	at async c:\Users\stewie\.vscode\extensions\continue.continue-0.8.46-win32-x64\out\extension.js:429527:27
	at async c:\Users\stewie\.vscode\extensions\continue.continue-0.8.46-win32-x64\out\extension.js:469223:20
	at async i.value (c:\Users\stewie\.vscode\extensions\continue.continue-0.8.46-win32-x64\out\extension.js:435971:32)
y @ console.ts:137
$logExtensionHostMessage @ mainThreadConsole.ts:39
S @ rpcProtocol.ts:458
Q @ rpcProtocol.ts:443
M @ rpcProtocol.ts:373
L @ rpcProtocol.ts:299
(anonymous) @ rpcProtocol.ts:161
B @ event.ts:1230
fire @ event.ts:1261
fire @ ipc.net.ts:652
K.onmessage @ localProcessExtensionHost.ts:378`

if i use shortcut, i dont see anything appearing in the console
![image](https://github.com/user-attachments/assets/6c1bc26a-5ae2-48f1-82b8-608066adebce)

**Comment by sestinj** [comment]
@stjema my first guess at what might be happening is that another keyboard shortcut, registered through VS Code or your operating system, is interfering with cmd+enter, as these would take precedence over our shortcuts in the webview. The best way to check this would be to press ctrl+shift+p, "Keyboard Shortcuts" and then search for shortcuts with that keybinding

**Comment by stjema** [comment]
but this also means that everybody else has the same issue? are most people here on mac?
i reinstaleld windows and vsc. thus everybody will have this issue on windows?

![image](https://github.com/user-attachments/assets/b10faef8-5e94-4fea-8de7-f549b283092e)
which do i need to change here?

**Comment by sestinj** [comment]
@stjema the keyboard shortcut to look for would be `ctrl+Enter` rather than `ctrl+Space`.

We do test Continue fairly frequently on Windows and I hadn't seen this before, so as far as I know it's not affecting all Windows users, hence my thinking that an overriding shortcut could be the culprit.

**Comment by stjema** [comment]
`hence my thinking that an overriding shortcut could be the culprit.
`
That is impossible. I reinstalled wimdows 11. I did not change any shortcuts manually.
