### ISSUE TITLE
IntelliJ: Create New Session not creating a session in history.

### ISSUE THREAD

**Issue by IngLP** [continuedev/continue#2085]
### Before submitting your bug report

- [X] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [X] I've seen the [troubleshooting guide](https://docs.continue.dev/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS: macOS 14.6.1
- Continue: 0.0.56
- IDE: IntelliJ
- Model: Sonnet 3.5
- config.json:
  
{
  "models": [
    {
      "model": "gpt-4o",
      "title": "GPT-4o",
      "apiKey": 
      "completionOptions": {},
      "provider": "openai"
    },
    {
      "model": "gpt-4o-mini",
      "title": "GPT-4o-mini",
      "apiKey": 
      "completionOptions": {},
      "provider": "openai"
    },
    {
      "title": "Codestral",
      "provider": "mistral",
      "model": "codestral-latest",
      "apiKey": 
    },
    {
      "title": "claude-3.5-sonnet",
      "provider": "anthropic",
      "model": "claude-3-5-sonnet-20240620",
      "apiKey": 
    },
    {
      "title": "Gemini Pro",
      "provider": "gemini",
      "model": "gemini-1.5-pro-latest",
      "apiKey":
    },
    {
      "title": "Gemini Pro Exp 0801",
      "provider": "gemini",
      "model": "gemini-1.5-pro-exp-0801",
      "apiKey": 
    },
    {
      "title": "Gemini Flash",
      "provider": "gemini",
      "model": "gemini-1.5-flash-latest",
      "apiKey": 
    }
  ],
  "slashCommands": [
    {
      "name": "edit",
      "description": "Edit selected code"
    },
    {
      "name": "comment",
      "description": "Write comments for the selected code"
    },
    {
      "name": "share",
      "description": "Export this session as markdown"
    },
    {
      "name": "cmd",
      "description": "Generate a shell command"
    },
    {
      "name": "onboard",
      "description": "Familiarize yourself with the codebase"
    }
  ],
  "customCommands": [
    {
      "name": "test",
      "prompt": "Write a comprehensive set of unit tests, using a PyTest class. It should setup, run tests that check for correctness including important edge cases, and teardown. Ensure that the tests are complete. Give the tests just as chat output, don't edit any file. Prefer literal values instead of computed ones. Do this for {{{ input }}}",
      "description": "Write unit tests for "
    },
    {
      "name": "check",
      "description": "Check for mistakes in my code",
      "prompt": "{{{ input }}}\n\nPlease read the highlighted code and check for any mistakes. You should look for the following, and be extremely vigilant:\n- Syntax errors\n- Logic errors\n- Security vulnerabilities\n- Performance issues\n- Anything else that looks wrong\n\nOnce you find an error, please explain it as clearly as possible, but without using extra words. For example, instead of saying 'I think there is a syntax error on line 5', you should say 'Syntax error on line 5'. Give your answer as one bullet point per mistake found."
    }
  ],
  "contextProviders": [
    {
      "name": "open",
      "params": {}
    },
    {
      "name": "code",
      "params": {}
    },
    {
      "name": "docs",
      "params": {}
    },
    {
      "name": "url"
    },
    {
      "name": "codebase",
      "params": {
        "nRetrieve": 70,
        "nFinal": 30,
        "useReranking": true
      }
    },
    {
      "name": "tree"
    }
  ],
  "embeddingsProvider": {
    "provider": "openai",
    "model": "voyage-code-2",
    "apiBase": "https://api.voyageai.com/v1/",
    "apiKey": 
  },
  "reranker": {
    "name": "free-trial"
  },
  "tabAutocompleteModel": {
    "title": "Codestral",
    "provider": "mistral",
    "model": "codestral-latest",
    "apiKey": 
  },
  "tabAutocompleteOptions": {
    "maxPromptTokens": 32000,
    "debounceDelay": 2000,
    "maxSuffixPercentage": 0.3
  },
  "allowAnonymousTelemetry": false
}
```

### Description

No new sessions are created when you click on New session. They are only created when you open IntelliJ

### To reproduce

1. Open Intellij
2. have a small conversation 
3. click on new session, have a 2nd conversation
4. click on new session, have a 3rd conversation
5. open history, you won't find the 2nd conversation, only the first
6. restart intelliJ. in history neither the 3rd session will be present.

### Log output

```Shell
No errors logged.
```

**Comment by cedmos** [comment]
Same issue here (right now no sessions saved at all). Wiped session directory. After two times starting IntelliJ it recreated a 'sessions' folder with a sessions.json containing an empty array. Tried to add 2-3 chats but none was persisting.

Mac OS 15.1.1
IDEA 2024.3
Continue Extension 0.0.83

Reverted back to my old session folder, sometimes it saves new sessions now (maybe related to title generation?)

**Comment by stone-w4tch3r** [comment]
Same here. Just want to inform team that issue is still present and needs to be addressed

**Comment by PVanV** [comment]
Same issue here, haven't had a session save since updating (both IntelliJ and continue) last week. No errors in logs as far as I can tell. Never noticed missing sessions before updating. Still need to try reverting updates.
Mac OS 15.1.1
IntelliJ IDEA 2024.1.x -> 2024.3.1.1
Continue 0.0.80 -> 0.0.83

**Comment by tim-massey** [comment]
I also don't have any sessions available. No idea what to try.
Ubuntu 24.04
Idea: 2024.3.1.1
Continue 0.0.84

**Comment by tahouse** [comment]
Same as other above but with some additional testing and poking around session json in working VS Code. @Patrick-Erichsen @RomneyDa 

**Environment:**
- macOS 15.2
- VS Code 1.96.4 with Continue 0.8.66
- IntelliJ IDEA 2024.3.2 (Ultimate Edition) with Continue 0.0.83

**Issue Description:**
1. Config and session sync works partially between VS Code and IDEA:
   - config.json settings transfer successfully
   - Existing session history from VS Code is visible in IDEA
   - Conversations started in VS Code can be continued in IDEA

2. Problems observed:
   - No new history is created when using IDEA
   - IDEA doesn't read latest state from json file when session is open in both editors
   - VS Code updates json with each message unless IDEA adds a message in IDE (message still never appears in json though)
   - Changes to existing session from VS Code don't appear in IDEA until restart, even with VS Code closed. New sessions from VS Code appear in IDEA history immediately
   - When IDEA is used in a session, VS Code later duplicates the session up to its last message

**Verification:**
- Directly checked session json file at ~/.continue/session/...json
- Tested with VS Code closed to rule out file lock issues

**Additional Notes:**
- Version mismatch between VS Code and IDEA plugins despite both being latest available
- Debugging information can be provided if instructions are given
- Unsure if related or not, but Folder and Codespace context providers also don't work in IDEA, file provider pointed at a folder seems to work fine though -- is this a filesystem permission issue?

**Comment by tahouse** [comment]
Adding relevant portion from JetBrains idea.log (from Help -> Show Log in Finder). These errors repeat 24 more times in my log, only change is the specific directory path being referenced (either the main project repo I'm working with or a subdirectory in the repo I was making changes in, possibly from using cmd+enter shortcut (@codebase doesn't appear as a context option))
```
2025-01-21 14:21:04,343 [  37422]   INFO - STDERR - java.io.FileNotFoundException: <<<redacted repo path>>> (Is a directory)
2025-01-21 14:21:04,343 [  37422]   INFO - STDERR - 	at java.base/java.io.FileInputStream.open0(Native Method)
2025-01-21 14:21:04,343 [  37422]   INFO - STDERR - 	at java.base/java.io.FileInputStream.open(FileInputStream.java:213)
2025-01-21 14:21:04,343 [  37422]   INFO - STDERR - 	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:152)
2025-01-21 14:21:04,343 [  37422]   INFO - STDERR - 	at com.github.continuedev.continueintellijextension.continue.IdeProtocolClient.readFile(IdeProtocolClient.kt:869)
2025-01-21 14:21:04,343 [  37422]   INFO - STDERR - 	at com.github.continuedev.continueintellijextension.continue.IdeProtocolClient.access$readFile(IdeProtocolClient.kt:126)
2025-01-21 14:21:04,343 [  37422]   INFO - STDERR - 	at com.github.continuedev.continueintellijextension.continue.IdeProtocolClient$handleMessage$1.invokeSuspend(IdeProtocolClient.kt:268)
2025-01-21 14:21:04,343 [  37422]   INFO - STDERR - 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
2025-01-21 14:21:04,343 [  37422]   INFO - STDERR - 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
2025-01-21 14:21:04,343 [  37422]   INFO - STDERR - 	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:115)
2025-01-21 14:21:04,343 [  37422]   INFO - STDERR - 	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:100)
2025-01-21 14:21:04,343 [  37422]   INFO - STDERR - 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
2025-01-21 14:21:04,343 [  37422]   INFO - STDERR - 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
2025-01-21 14:21:04,343 [  37422]   INFO - STDERR - 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
2025-01-21 14:21:04,343 [  37422]   INFO - STDERR - 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
```

**Comment by Patrick-Erichsen** [comment]
Hi folks, I believe this has been fixed on 0.0.86 which is currently available in [EAP](https://docs.continue.dev/troubleshooting#jetbrains-1). Apologies for the annoying bug!

**Comment by tahouse** [comment]
Thanks Patrick! Using instructions from https://docs.continue.dev/troubleshooting#jetbrains-1 and updating from Continue 0.0.83 -> EA Continue 0.0.86 session history is working for me. 

In addition, '@codespace' and '@folder' are both working now too.  Still have some strange session duplication when using the same session from VS Code and IDEA, but this is minor IMO and unlikely to occur for most use-cases.

**Comment by tim-massey** [comment]
I can confirm upgrading to latest fixed my issue, thanks for the work on it!!

**Comment by Patrick-Erichsen** [comment]
Thanks all for your patience here!

**Comment by 5tr1k3r** [comment]
![Image](https://github.com/user-attachments/assets/69045909-7aa0-4a4f-842d-8aa1830b7499)

After upgrading to 0.0.86, the original issue is gone, but all the sessions do not have proper titles

**Comment by spottenn** [comment]
> Hi folks, I believe this has been fixed on 0.0.86 which is currently available in [EAP](https://docs.continue.dev/troubleshooting#jetbrains-1). Apologies for the annoying bug!

Thanks for the fix! You guys are doing great! I was looking into the issue and possibly submitting a PR today to fix it, but you guys have beat me to it. 

Can confirm, 0.0.86 fixed this and `@codebase` and `@folder` issues on Webstorm on macOS.

**Comment by spottenn** [comment]
> After upgrading to 0.0.86, the original issue is gone, but all the sessions do not have proper titles

@5tr1k3r I wonder if that might be a separate issue, possibly related, but maybe not. Those look like incorrectly parsed or converted strings to me. Is everything else working properly about sessions?

**Comment by Patrick-Erichsen** [comment]
@5tr1k3r if you clear your session history (`rm -rf ~/.continue/sessions/`), does it persist on subsequent sessions?

**Comment by 5tr1k3r** [comment]
@Patrick-Erichsen The issue persists.

1. Updated to Continue 1.0.1
2. Closed IDE (PhpStorm 2024.3.2.1)
3. Removed the entire `sessions` directory
4. Opened IDE and started a new chat
5. A session was created with a name "[object Object][object Object]"

I am using Google's now-somewhat-outdated `gemini-exp-1206`.

I also opened one of the sessions and can see this, looks kinda weird:
```
      "promptLogs": [
        {
          "modelTitle": "Gemini Exp 1206",
          "prompt": "<redacted for brevity>",
          "completion": "[object Object][object Object][object Object][object Object]",
          "completionOptions": {
            "model": "gemini-exp-1206",
            "maxTokens": 4096
          }
        }
      ],
```

Sorry for taking this long to respond :(

**Comment by Patrick-Erichsen** [comment]
No worries, thanks for the follow up @5tr1k3r ! I've added a high priority label to this but uncertain how soon we'll be able to circle around to it.
