### ISSUE TITLE
continue.dev doesn't load in vscode.dev - tries to use node js module 

### ISSUE THREAD

**Issue by jlewi** [continuedev/continue#2131]
### Before submitting your bug report

- [X] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [X] I've seen the [troubleshooting guide](https://docs.continue.dev/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
vscode.dev
```

### Description

I went to vscode.dev
I installed the continue.dev extension from the extension marketplace.

The extension doesn't load. I see the following error in the extension host worker output.

```
2024-08-28 22:51:02.357 [error] Error: Cannot load module 'child_process'
	at m (https://main.vscode-cdn.net/stable/fee1edb8d6d72a0ddff41e5f71a671c23ed924b9/out/vs/workbench/api/worker/extensionHostWorker.js:112:483)
	at eval (https://continue.vscode-unpkg.net/Continue/continue/0.0.412/extension/out/extension.js#vscode-extension:42:86)
	at node_modules/node-machine-id/dist/index.js (https://continue.vscode-unpkg.net/Continue/continue/0.0.412/extension/out/extension.js#vscode-extension:43:6)
	at __require (https://continue.vscode-unpkg.net/Continue/continue/0.0.412/extension/out/extension.js#vscode-extension:14:50)
	at src/util/vscode.ts (https://continue.vscode-unpkg.net/Continue/continue/0.0.412/extension/out/extension.js#vscode-extension:906:38)
	at __init (https://continue.vscode-unpkg.net/Continue/continue/0.0.412/extension/out/extension.js#vscode-extension:11:56)
	at src/activation/environmentSetup.ts (https://continue.vscode-unpkg.net/Continue/continue/0.0.412/extension/out/extension.js#vscode-extension:56212:5)
	at __init (https://continue.vscode-unpkg.net/Continue/continue/0.0.412/extension/out/extension.js#vscode-extension:11:56)
	at src/extension.ts (https://continue.vscode-unpkg.net/Continue/continue/0.0.412/extension/out/extension.js#vscode-extension:68537:5)
	at __init (https://continue.vscode-unpkg.net/Continue/continue/0.0.412/extension/out/extension.js#vscode-extension:11:56)
	at eval (https://continue.vscode-unpkg.net/Continue/continue/0.0.412/extension/out/extension.js#vscode-extension:68542:1)
	at I.xb (https://main.vscode-cdn.net/stable/fee1edb8d6d72a0ddff41e5f71a671c23ed924b9/out/vs/workbench/api/worker/extensionHostWorker.js:112:627)
	at async Promise.all (index 0)
	at async s.n (https://main.vscode-cdn.net/stable/fee1edb8d6d72a0ddff41e5f71a671c23ed924b9/out/vs/workbench/api/worker/extensionHostWorker.js:96:6410)
	at async s.m (https://main.vscode-cdn.net/stable/fee1edb8d6d72a0ddff41e5f71a671c23ed924b9/out/vs/workbench/api/worker/extensionHostWorker.js:96:6373)
	at async s.l (https://main.vscode-cdn.net/stable/fee1edb8d6d72a0ddff41e5f71a671c23ed924b9/out/vs/workbench/api/worker/extensionHostWorker.js:96:5830)
```

I believe `child_process` is a node specific module that allows launching child processes.

### To reproduce

1. Go to vscode.dev
2. Click on extensions and load continue.dev
3. Click on the continue.dev icon; it just has a spinner
4. Click on output and look at the extension host output window

**Comment by sestinj** [comment]
@jlewi Continue is not and probably won't for a while be compatible with browser-only versions of VS Code like vscode.dev. It's not just because we use child_process, but because we require local databases like SQLite and LanceDB. Someday we may put in the extensive effort to package for both pure browser and local, but for now this is a major undertaking (not that we expect it to be this bad, but it took VS Code ~10 years I believe...)

That said, you should still be able to use Continue on something like code-server, which is actually backed by a real machine

**Comment by VitGottwald** [comment]
Would it make sense to start by using switching to VS Code APIs like `vscode.workspace.fs` and `vscode.Uri` instead of node specific APIs?

That would get us closer and limit the work down the road to deal with the databases only.

**Comment by jlewi** [comment]
@sestinj Thanks for clarifying that continue.dev doesn't work on in vscode.dev. I think there might be a bug somewhere then because extensions that don't support the browser should be marked as such and not show up in vscode.dev as installable.

If you look at GitHub Copilot for example in the extension market place you can see it won't let you install it.

I think it might be as simple as deleting the `browser` line your package.json
https://github.com/continuedev/continue/blob/832de225c2fbbc8c64866413585bd4453399c8d6/extensions/vscode/package.json#L59

[Relevant documentation](https://code.visualstudio.com/api/extension-guides/web-extensions#web-extension-anatomy)

> Extensions that have only a main entry point, but no browser are not web extensions. They are ignored by the web extension host and not available for download in the Extensions view.

> because we require local databases like SQLite and LanceDB. Someday we may put in the extensive effort to package for both pure browser and local

Have you thought about defining a Continue API that separates parts that can run in the browser from those that can't? This way if you want to run in the browser you don't need to run the full codeserver server you just need to run the Continue Backend?

I think this is advantageous because I think codeserver has some sharp edges if you run in a scale to zero mode. For example the UI won't be accessible until the server is up and you can lose unsaved changes when scaling down. vscode for web solves this problem since files/state can still be stored on your local machine.

# Use Case

I really like Continue because it brings Claude (and other models) into VSCode (demo [video](https://x.com/jeremylewi/status/1819211833355784363)). Compared to Claude/ChatGPT playgrounds VSCode for web + Continue have a couple of really nice advantages

* vscode for web is a richer playground - e.g. File Browser + access to local files
* Cheaper pay for what you use without being locked into subscriptions 

I work on [RunMe](https://runme.dev/). RunMe lets you edit markdown as VScode notebooks so that code blocks become executable. This creates a really great UX for interacting with AIs and tools ([video](https://x.com/jeremylewi/status/1827101679696932881)).

Continue is very complementary

* I regularly use Continue to chat with Claude to come up with commands
* I'd like to use Continue to chat withy my notes

**Comment by sestinj** [comment]
All good points made here! For now I've deleted the browser entry point as suggested: https://github.com/continuedev/continue/commit/855211d887f720ca09b2ba1ffdb2f74aa1599224

There will be many additional modifications needed to convert our entire core (which is assumed not to have access to VS Code APIs so that we can re-use it for the Jetbrains extension), so it's not likely on the short-term roadmap. When we get there though the biggest things will be replacing all usages of "fs", "child_process", "path", lancedb, sqlite, and a few others
