### ISSUE TITLE
Not support kwalletd

### ISSUE THREAD

**Issue by mrdev023** [continuedev/continue#2144]
### Before submitting your bug report

- [ ] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [x] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [x] I've seen the [troubleshooting guide](https://docs.continue.dev/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS: Linux, NixOS (branch: unstable)
- Continue: 0.0.64
- IDE: Jetbrains 2024.2.1
- Model: Any model
```

### Description

When i install and click to access to continue, Jetbrains log crash error. It seems to be a missing support from kwalletd. 

Missing method `readPasswordList` on org.kde.KWallet

> On d-spy application, i don't found any method call readPasswordList on org.freedesktop.secrets from session dbus.

### To reproduce

1. Install
2. Click on continue at right side
3. Crash

### Log output

```Shell
org.freedesktop.dbus.errors.UnknownMethod: No such method 'readPasswordList' in interface 'org.kde.KWallet' at object path '/modules/kwalletd5' (signature 'isss')
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486)
	at org.freedesktop.dbus.errors.Error.getException(Error.java:111)
	at org.freedesktop.dbus.errors.Error.throwException(Error.java:138)
	at org.freedesktop.dbus.RemoteInvocationHandler.executeRemoteMethod(RemoteInvocationHandler.java:146)
	at org.freedesktop.dbus.RemoteInvocationHandler.invoke(RemoteInvocationHandler.java:206)
	at com.intellij.credentialStore.$Proxy180.readPasswordList(Unknown Source)
	at com.intellij.credentialStore.KWalletCredentialStore.get(linuxKWalletLibrary.kt:89)
	at com.intellij.credentialStore.NativeCredentialStoreWrapper.get(NativeCredentialStoreWrapper.kt:46)
	at com.intellij.ide.passwordSafe.impl.BasePasswordSafe.get(PasswordSafeImpl.kt:96)
	at com.github.continuedev.continueintellijextension.auth.ContinueAuthService.retrieveSecret(ContinueAuthService.kt:142)
	at com.github.continuedev.continueintellijextension.auth.ContinueAuthService.getAccessToken(ContinueAuthService.kt:155)
	at com.github.continuedev.continueintellijextension.auth.ContinueAuthService.loadControlPlaneSessionInfo(ContinueAuthService.kt:188)
	at com.github.continuedev.continueintellijextension.activities.ContinuePluginStartupActivity$initializePlugin$1.invokeSuspend(ContinuePluginStartupActivity.kt:136)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:115)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:100)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
```

**Comment by sestinj** [comment]
This unfortunately might be a bug to report to IntelliJ—we are using their secrets management API and prefer not to take such touchy things into our own hands. The line is [here](https://github.com/continuedev/continue/blob/dev/extensions/intellij/src/main/kotlin/com/github/continuedev/continueintellijextension/auth/ContinueAuthService.kt#L143) where it happens, and appears to be standard usage of their API

**Comment by mrdev023** [comment]
https://invent.kde.org/frameworks/kwallet/-/issues/6

**Comment by mrdev023** [comment]
https://bugs.kde.org/show_bug.cgi?id=493356
