### ISSUE TITLE
LM Studio configuration - this.embeddingsProvider.embed is not a function

### ISSUE THREAD

**Issue by flleeppyy** [continuedev/continue#2149]
### Before submitting your bug report

- [X] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [X] I've seen the [troubleshooting guide](https://docs.continue.dev/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
**I am currently using an SSH tunnel to my laptop, running linux, with Continue**

- OS: Windows 10 v19045 (Remote is Kubuntu 22.04)
- Continue: 0.8.47
- IDE: VSCode 1.92.2 (Remote is the same)
- Model: LMStudio - `TheBloke/deepseek-coder-6.7B-instruct-GGUF` (Embedding model is `nomic-ai/nomic-embed-text-v1.5-GGUF/nomic-embed-text-v1.5.f16.gguf`)
- config.json:
  
{
  "models": [
    {
      "model": "AUTODETECT",
      "title": "LM Studio",
      "apiBase": "http://localhost:1234/v1/",
      "provider": "lmstudio"
    }
  ],
  "customCommands": [
    {
      "name": "test",
      "prompt": "{{{ input }}}\n\nWrite a comprehensive set of unit tests for the selected code. It should setup, run tests that check for correctness including important edge cases, and teardown. Ensure that the tests are complete and sophisticated. Give the tests just as chat output, don't edit any file.",
      "description": "Write unit tests for highlighted code"
    }
  ],
  "tabAutocompleteModel": {
    "model": "AUTODETECT",
    "title": "LM Studio",
    "apiBase": "http://localhost:1234/v1/",
    "provider": "lmstudio"
  },
  "contextProviders": [
    {
      "name": "code",
      "params": {}
    },
    {
      "name": "docs",
      "params": {}
    },
    {
      "name": "diff",
      "params": {}
    },
    {
      "name": "terminal",
      "params": {}
    },
    {
      "name": "problems",
      "params": {}
    },
    {
      "name": "folder",
      "params": {}
    },
    {
      "name": "codebase",
      "params": {}
    }
  ],
  "slashCommands": [
    {
      "name": "edit",
      "description": "Edit selected code"
    },
    {
      "name": "comment",
      "description": "Write comments for the selected code"
    },
    {
      "name": "share",
      "description": "Export the current chat session to markdown"
    },
    {
      "name": "cmd",
      "description": "Generate a shell command"
    },
    {
      "name": "commit",
      "description": "Generate a git commit message"
    }
  ],
  "embeddingsProvider": {
    "provider": "lmstudio",
    "model": "AUTODETECT"
  }
}
```

### Description

When I click the button in the bottom left to, I presume, do something with embeds and give the model context of my whole working directory, it fails a little bit later with the following:

https://github.com/user-attachments/assets/63b572b9-146e-4c48-9e69-a824d188fe63

```
(x6) [Extension Host] Error reading file EntryNotFound (FileSystemError): Error: ENOENT: no such file or directory, stat '/Users/Chen/.continue/config.json'
    at Function.e (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:153:6919)
    at Object.stat (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:153:3977)
    at _VsCodeIdeUtils.readFile (c:\Users\Chen\.vscode\extensions\continue.continue-0.8.47-win32-x64\out\extension.js:514154:29)
    at VsCodeIde.readFile (c:\Users\Chen\.vscode\extensions\continue.continue-0.8.47-win32-x64\out\extension.js:514729:16)
    at _CompletionProvider.getTabCompletion (c:\Users\Chen\.vscode\extensions\continue.continue-0.8.47-win32-x64\out\extension.js:102518:58)
    at _CompletionProvider.provideInlineCompletionItems (c:\Users\Chen\.vscode\extensions\continue.continue-0.8.47-win32-x64\out\extension.js:102454:27)
    at ContinueCompletionProvider.provideInlineCompletionItems (c:\Users\Chen\.vscode\extensions\continue.continue-0.8.47-win32-x64\out\extension.js:501590:27)
    at Y.provideInlineCompletions (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:154:120716)
    
(x2) [Extension Host] error when indexing:  Error: Failed to generate embeddings for 72 chunks with provider: undefined: TypeError: this.embeddingsProvider.embed is not a function
    at LanceDbIndex.getEmbeddings (c:\Users\Chen\.vscode\extensions\continue.continue-0.8.47-win32-x64\out\extension.js:430679:17)
    at LanceDbIndex.computeRows (c:\Users\Chen\.vscode\extensions\continue.continue-0.8.47-win32-x64\out\extension.js:430627:39)
    at LanceDbIndex.update (c:\Users\Chen\.vscode\extensions\continue.continue-0.8.47-win32-x64\out\extension.js:430783:24)
    at CodebaseIndexer.indexFiles (c:\Users\Chen\.vscode\extensions\continue.continue-0.8.47-win32-x64\out\extension.js:499918:39)
    at CodebaseIndexer.refresh (c:\Users\Chen\.vscode\extensions\continue.continue-0.8.47-win32-x64\out\extension.js:499788:30)
    at Core.refreshCodebaseIndex (c:\Users\Chen\.vscode\extensions\continue.continue-0.8.47-win32-x64\out\extension.js:500795:26)
    at c:\Users\Chen\.vscode\extensions\continue.continue-0.8.47-win32-x64\out\extension.js:500752:11
    at c:\Users\Chen\.vscode\extensions\continue.continue-0.8.47-win32-x64\out\extension.js:540180:20
    at i.value (c:\Users\Chen\.vscode\extensions\continue.continue-0.8.47-win32-x64\out\extension.js:506927:32)
```

### To reproduce

Setup with LM Studio, using a similar config, and press the little color button in the bottom left. The error will show in hover, and in the vscode devtools.

### Log output

```Shell
Other possibly relevant error:

[Extension Host] Error loading color theme:  TypeError: Cannot read properties of undefined (reading 'map')
	at convertTheme2 (c:\Users\Chen\.vscode\extensions\continue.continue-0.8.47-win32-x64\out\extension.js:505883:25)
	at getTheme (c:\Users\Chen\.vscode\extensions\continue.continue-0.8.47-win32-x64\out\extension.js:506842:51)
	at ContinueGUIWebviewViewProvider.getSidebarContent (c:\Users\Chen\.vscode\extensions\continue.continue-0.8.47-win32-x64\out\extension.js:507187:30)
	at ContinueGUIWebviewViewProvider.resolveWebviewView (c:\Users\Chen\.vscode\extensions\continue.continue-0.8.47-win32-x64\out\extension.js:507131:41)
	at c.$resolveWebviewView (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:156:57125)
	at E.S (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:151:5980)
	at E.Q (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:151:5746)
	at E.M (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:151:4739)
	at E.L (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:151:3830)
	at i.value (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:151:2297)
	at n.B (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:83:737)
	at n.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:83:954)
	at s.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:97:14453)
	at i.value (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:177:8655)
	at n.B (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:83:737)
	at n.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:83:954)
	at s.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:97:14453)
	at MessagePortMain.<anonymous> (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:177:6781)
	at MessagePortMain.emit (node:events:519:28)
	at MessagePortMain._internalPort.emit (node:electron/js2c/utility_init:2:2285)
```
```

**Comment by sestinj** [comment]
@flleeppyy We don't currently support AUTODETECT for the "model" property of embeddings providers. This is causing at least the first error, and may be related to others. Can you try using the model name there, and let me know if you're experiencing some of these other problems?

**Comment by enginterzi** [comment]
Hi @flleeppyy 
I'm also using LM Studio, and I noticed that embeddingsProvider does not support LM Studio. The embedding provider options were recently released also on LM Studio. I checked the code base, and I can validate this is not a bug.
