### ISSUE TITLE
Continue crashes after start in Jetbrains PyCharm

### ISSUE THREAD

**Issue by stone-w4tch3r** [continuedev/continue#2239]
### Before submitting your bug report

- [X] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [X] I've seen the [troubleshooting guide](https://docs.continue.dev/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS: fedora 40 KDE
- Continue: 
- IDE: Jetbrains PyCharm Community
- Model:
- config.json: 

{
  "models": [
    {
      "title": "Claude 3.5 Sonnet",
      "provider": "openai",
      "model": "claude-3-5-sonnet-20240620",
      "apiBase": "https://api.aimlapi.com/v1",
      "apiKey": "XXX"
    }
  ],
  "customCommands": [
    {
      "name": "test",
      "prompt": "{{{ input }}}\n\nWrite a comprehensive set of unit tests for the selected code. It should setup, run tests that check for correctness including important edge cases, and teardown. Ensure that the tests are complete and sophisticated. Give the tests just as chat output, don't edit any file.",
      "description": "Write unit tests for highlighted code"
    }
  ],
  "tabAutocompleteModel": {
    "title": "deepseek-coder-v2",
    "provider": "openai",
    "model": "deepseek-coder-v2",
    "apiBase": "https://openrouter.ai/api/v1",
    "apiKey": "XXX"
  },
  "embeddingsProvider": {
    "provider": "openai",
    "model": "voyage-code-2",
    "apiBase": "https://api.aimlapi.com/v1",
    "apiKey": "XXX"
  },
  "reranker": {
    "name": "free-trial"
  },
  "contextProviders": [
    {
      "name": "code",
      "params": {}
    },
    {
      "name": "docs",
      "params": {}
    },
    {
      "name": "diff",
      "params": {}
    },
    {
      "name": "terminal",
      "params": {}
    },
    {
      "name": "problems",
      "params": {}
    },
    {
      "name": "folder",
      "params": {}
    },
    {
      "name": "codebase",
      "params": {}
    }
  ],
  "slashCommands": [
    {
      "name": "edit",
      "description": "Edit selected code"
    },
    {
      "name": "comment",
      "description": "Write comments for the selected code"
    },
    {
      "name": "share",
      "description": "Export the current chat session to markdown"
    },
    {
      "name": "cmd",
      "description": "Generate a shell command"
    },
    {
      "name": "commit",
      "description": "Generate a git commit message"
    }
  ],
  "allowAnonymousTelemetry": true
}
```

### Description

Right after installation continue displays error message and no longer works

### To reproduce

1. Remove ~/.continue
2. Install fresh pycharm IDE
3. Install continue plugin
4. Open it's window
5. See message in bottom-right corner
6. Write your config.json
7. Try to send message/select model
8. Window blinks, nothing happens

### Log output

```Shell
Unfortunately, ~/.continue/logs not exists.
From main logs:

2024-09-12 00:44:05,265 [ 294208]   INFO - STDOUT - CoreMessenger exited, retrying in 2.0 seconds
2024-09-12 00:44:07,274 [ 296217]   INFO - STDOUT - Core process exited with output: 
2024-09-12 00:44:07,374 [ 296317]   INFO - STDERR - java.io.IOException: Stream closed
2024-09-12 00:44:07,374 [ 296317]   INFO - STDERR - 	at java.base/java.io.BufferedReader.ensureOpen(BufferedReader.java:123)
2024-09-12 00:44:07,374 [ 296317]   INFO - STDERR - 	at java.base/java.io.BufferedReader.readLine(BufferedReader.java:321)
2024-09-12 00:44:07,374 [ 296317]   INFO - STDERR - 	at java.base/java.io.BufferedReader.readLine(BufferedReader.java:396)
2024-09-12 00:44:07,374 [ 296317]   INFO - STDERR - 	at com.github.continuedev.continueintellijextension.continue.CoreMessenger._init_$lambda$4(CoreMessenger.kt:272)
2024-09-12 00:44:07,375 [ 296318]   INFO - STDERR - 	at java.base/java.lang.Thread.run(Thread.java:840)
...
...
2024-09-12 00:49:20,038 [ 608981]   INFO - STDOUT - Error writing to Continue core: java.io.IOException: Stream closed
```
```

**Comment by Nindouja** [comment]
I also happen to have this bug on latest unstable nixos. The plugin works ok in vscode, but in jetbrains it does nothing after adding a connection to local ollama and I have the same logs as above.

**Comment by RomneyDa** [comment]
@stone-w4tch3r @Nindouja I think this might be fixed on recent releases, could you verify if this issue should be left open?

**Comment by stone-w4tch3r** [comment]
@RomneyDa sorry I have no access to old pc now

**Comment by Nindouja** [comment]
I don't have this particular issue anymore. But I still cannot use the plugin because I'm on nixos and i've other issues. I'll open a dedicated issue for this; but now I'm not even sure I had the exact same problem as @RomneyDa in the first place.

**Comment by hades200082** [comment]
I'm seeing the Continue plugin crashing JetBrains Rider ... seems to be related to inline completions.

I can get it to work for a few minutes then Rider completely stops responding and memory usage shoots up. Only way out is to end task.

Windows 10
Rider 2024.3.6

When I disable the continue plugin the issue stops happening.

Using Ollama locally with qwen2.5-coder:1.5b.
