### ISSUE TITLE
Indexing error in oycharm

### ISSUE THREAD

**Issue by stone-w4tch3r** [continuedev/continue#2338]
### Before submitting your bug report

- [X] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [X] I've seen the [troubleshooting guide](https://docs.continue.dev/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS: fedora 40
- Continue: 0.0.64
- IDE: PyCharm 2024.2.1 (Professional Edition)
- Model:#PY-242.21829.153
- config.json:

{
  "models": [
    {
      "title": "Claude 3.5 Sonnet",
      "provider": "openai",
      "model": "anthropic/claude-3.5-sonnet",
      "apiBase": "https://openrouter.ai/api/v1",
      "apiKey": "xxx"
    }
  ],
  "customCommands": [
    {
      "name": "test",
      "prompt": "{{{ input }}}\n\nWrite a comprehensive set of unit tests for the selected code. It should setup, run tests that check for correctness including important edge cases, and teardown. Ensure that the tests are complete and sophisticated. Give the tests just as chat output, don't edit any file.",
      "description": "Write unit tests for highlighted code"
    }
  ],
  "tabAutocompleteModel": {
    "title": "Codestral",
    "provider": "mistral",
    "model": "codestral-latest",
    "apiKey": "xxx"
  },
  "embeddingsProvider": {
    "provider": "voyage",
    "model": "voyage-code-2",
    "apiKey": "xxx"
  },
  "reranker": {
      "name": "voyage",
      "params": {
        "model": "rerank-1",
        "apiKey": "xxx"
      }
  },
  "contextProviders": [
    {
      "name": "code",
      "params": {}
    },
    {
      "name": "docs",
      "params": {}
    },
    {
      "name": "diff",
      "params": {}
    },
    {
      "name": "terminal",
      "params": {}
    },
    {
      "name": "problems",
      "params": {}
    },
    {
      "name": "folder",
      "params": {}
    },
    {
      "name": "codebase",
      "params": {}
    }
  ],
  "slashCommands": [
    {
      "name": "edit",
      "description": "Edit selected code"
    },
    {
      "name": "comment",
      "description": "Write comments for the selected code"
    },
    {
      "name": "share",
      "description": "Export the current chat session to markdown"
    },
    {
      "name": "cmd",
      "description": "Generate a shell command"
    },
    {
      "name": "commit",
      "description": "Generate a git commit message"
    }
  ],
  "allowAnonymousTelemetry": true
}
```

### Description

Configured config.json according to documentation, but indexing fails right after start with different errors

### To reproduce

1. Setup config.json
2. Open PyCharm project
3. Open Continue chat
3. Indexing starts
4. Indexing fails with error

### Log output

```Shell
[info] Starting Continue core...
[2024-09-17T15:23:52] [info] Starting Continue core... 
[2024-09-17T15:23:52] Setup 
[2024-09-17T15:23:52] [PCR] Puppeteer version: [35m23.1.1[39m 
[2024-09-17T15:23:52] [PCR] Browser platform: [35mlinux[39m 
[2024-09-17T15:23:52] Core started 
[2024-09-17T15:23:53] Indexing: 0.0% complete, elapsed time: 0s, NaN file/sec 
[2024-09-17T15:23:55] [PCR] Chromium revision: [35m1356469[39m 
[2024-09-17T15:23:55] [PCR] [33mNot found local chromium[39m 
[2024-09-17T15:23:57] [PCR] Head request: https://storage.googleapis.com/chromium-browser-snapshots/Linux_x64/1356469/chrome-linux.zip - [32mtrue[39m (1870ms) 
[2024-09-17T15:23:57] [PCR] Downloading from: https://storage.googleapis.com ... 
[2024-09-17T15:23:57] Indexing: 25.0% complete, elapsed time: 4s, 4.00 file/sec 
[2024-09-17T15:23:57] Running migration: lancedb_sqlite_artifact_id_column 
[2024-09-17T15:23:57] Indexing: 25.0% complete, elapsed time: 5s, 3.20 file/sec 
[2024-09-17T15:24:01] error when indexing:  Error: Failed to generate embeddings for 279 chunks with provider: _OpenAIEmbeddingsProvider::voyage-code-2: Error: {"requestId":"25f9caf7-9911-4d9f-848d-e701dbb5f298","statusCode":400,"timestamp":"2024-09-17T15:24:01.458Z","path":"/v1/embeddings","message":"Invalid input","meta":{"_errors":[],"input":{"14":{"_errors":["String must contain at most 800 character(s)"]},"19":{"_errors":["String must contain at most 800 character(s)"]},"20":{"_errors":["String must contain at most 800 character(s)"]},"22":{"_errors":["String must contain at most 800 character(s)"]},"_errors":[]},"input_type":{"_errors":["Required"]}}}
[2024-09-17T15:24:11] (node:58721) ExperimentalWarning: The Fetch API is an experimental feature. This feature could change at any time
(Use `continue-binary --trace-warnings ...` to show where the warning was created) 
[2024-09-17T15:24:27] (node:58721) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead. 
[2024-09-17T15:24:35] [PCR] Chromium downloaded: 1356469 
[2024-09-17T15:24:37] [PCR] Chromium executablePath: [32m/home/user1/.continue/.utils/.chromium-browser-snapshots/chromium/linux-1356469/chrome-linux/chrome[39m 
[2024-09-17T15:24:37] [PCR] Chromium version: [35mChrome/131.0.6724.0[39m 
[2024-09-17T15:24:37] [PCR] Chromium launchable: [32mtrue[39m 
[2024-09-17T15:24:37] [PCR] Stats saved: /home/user1/.continue/.utils/.pcr-stats.json 
[2024-09-17T15:27:02] request to https://openrouter.ai/api/v1/chat/completions failed, reason: Client network socket disconnected before secure TLS connection was established

Code: ECONNRESET
Error number: ECONNRESET
Syscall: undefined
Type: system

FetchError: request to https://openrouter.ai/api/v1/chat/completions failed, reason: Client network socket disconnected before secure TLS connection was established
    at ClientRequest.<anonymous> (/snapshot/continue/binary/out/index.js:447646:14)
    at ClientRequest.emit (node:events:549:35)
    at TLSSocket.socketErrorListener (node:_http_client:465:9)
    at TLSSocket.emit (node:events:537:28)
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) 
[2024-09-17T15:27:02] Error: request to https://openrouter.ai/api/v1/chat/completions failed, reason: Client network socket disconnected before secure TLS connection was established 
[2024-09-17T15:27:02] Error running handler for "llm/streamChat":  Error: request to https://openrouter.ai/api/v1/chat/completions failed, reason: Client network socket disconnected before secure TLS connection was established
[2024-09-17T15:27:02] Error: request to https://openrouter.ai/api/v1/chat/completions failed, reason: Client network socket disconnected before secure TLS connection was established 
[2024-09-17T15:31:16] [object Object] 
[2024-09-17T15:31:16] [object Object] 
[2024-09-17T15:31:16] [object Object] 
[2024-09-17T15:31:17] [object Object] 
[2024-09-17T15:31:17] [object Object] 
[2024-09-17T15:31:17] [object Object] 
[2024-09-17T15:31:17] [object Object] 
[2024-09-17T15:31:17] [object Object] 
[2024-09-17T15:43:35] request to https://codestral.mistral.ai/v1/fim/completions failed, reason: Client network socket disconnected before secure TLS connection was established

Code: ECONNRESET
Error number: ECONNRESET
Syscall: undefined
Type: system

FetchError: request to https://codestral.mistral.ai/v1/fim/completions failed, reason: Client network socket disconnected before secure TLS connection was established
    at ClientRequest.<anonymous> (/snapshot/continue/binary/out/index.js:447646:14)
    at ClientRequest.emit (node:events:549:35)
    at TLSSocket.socketErrorListener (node:_http_client:465:9)
    at TLSSocket.emit (node:events:537:28)
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) 
[2024-09-17T15:43:35] Error generating autocompletion:  Error: request to https://codestral.mistral.ai/v1/fim/completions failed, reason: Client network socket disconnected before secure TLS connection was established
[2024-09-17T15:51:06] request to https://codestral.mistral.ai/v1/fim/completions failed, reason: Client network socket disconnected before secure TLS connection was established

Code: ECONNRESET
Error number: ECONNRESET
Syscall: undefined
Type: system

FetchError: request to https://codestral.mistral.ai/v1/fim/completions failed, reason: Client network socket disconnected before secure TLS connection was established
    at ClientRequest.<anonymous> (/snapshot/continue/binary/out/index.js:447646:14)
    at ClientRequest.emit (node:events:549:35)
    at TLSSocket.socketErrorListener (node:_http_client:465:9)
    at TLSSocket.emit (node:events:537:28)
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) 
[2024-09-17T15:51:06] Error generating autocompletion:  Error: request to https://codestral.mistral.ai/v1/fim/completions failed, reason: Client network socket disconnected before secure TLS connection was established
[2024-09-17T15:54:42] request to https://codestral.mistral.ai/v1/fim/completions failed, reason: Client network socket disconnected before secure TLS connection was established

Code: ECONNRESET
Error number: ECONNRESET
Syscall: undefined
Type: system

FetchError: request to https://codestral.mistral.ai/v1/fim/completions failed, reason: Client network socket disconnected before secure TLS connection was established
    at ClientRequest.<anonymous> (/snapshot/continue/binary/out/index.js:447646:14)
    at ClientRequest.emit (node:events:549:35)
    at TLSSocket.socketErrorListener (node:_http_client:465:9)
    at TLSSocket.emit (node:events:537:28)
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) 
[2024-09-17T15:54:42] Error generating autocompletion:  Error: request to https://codestral.mistral.ai/v1/fim/completions failed, reason: Client network socket disconnected before secure TLS connection was established
[2024-09-17T15:55:25] [object Object] 
[2024-09-17T15:55:25] [object Object] 
[2024-09-17T15:55:25] [object Object] 
[2024-09-17T15:55:25] [object Object] 
[2024-09-17T15:55:25] [object Object] 
[2024-09-17T15:55:25] [object Object] 
[2024-09-17T15:55:25] [object Object] 
[2024-09-17T15:55:25] [object Object] 
[2024-09-17T15:55:25] [object Object] 
[2024-09-17T15:56:42] request to https://codestral.mistral.ai/v1/fim/completions failed, reason: Client network socket disconnected before secure TLS connection was established

Code: ECONNRESET
Error number: ECONNRESET
Syscall: undefined
Type: system

FetchError: request to https://codestral.mistral.ai/v1/fim/completions failed, reason: Client network socket disconnected before secure TLS connection was established
    at ClientRequest.<anonymous> (/snapshot/continue/binary/out/index.js:447646:14)
    at ClientRequest.emit (node:events:549:35)
    at TLSSocket.socketErrorListener (node:_http_client:465:9)
    at TLSSocket.emit (node:events:537:28)
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) 
[2024-09-17T15:56:42] Error generating autocompletion:  Error: request to https://codestral.mistral.ai/v1/fim/completions failed, reason: Client network socket disconnected before secure TLS connection was established
[2024-09-17T15:57:44] request to https://codestral.mistral.ai/v1/fim/completions failed, reason: Client network socket disconnected before secure TLS connection was established

Code: ECONNRESET
Error number: ECONNRESET
Syscall: undefined
Type: system

FetchError: request to https://codestral.mistral.ai/v1/fim/completions failed, reason: Client network socket disconnected before secure TLS connection was established
    at ClientRequest.<anonymous> (/snapshot/continue/binary/out/index.js:447646:14)
    at ClientRequest.emit (node:events:549:35)
    at TLSSocket.socketErrorListener (node:_http_client:465:9)
    at TLSSocket.emit (node:events:537:28)
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) 
[2024-09-17T15:57:44] Error generating autocompletion:  Error: request to https://codestral.mistral.ai/v1/fim/completions failed, reason: Client network socket disconnected before secure TLS connection was established
[2024-09-17T16:01:23] request to https://codestral.mistral.ai/v1/fim/completions failed, reason: Client network socket disconnected before secure TLS connection was established

Code: ECONNRESET
Error number: ECONNRESET
Syscall: undefined
Type: system

FetchError: request to https://codestral.mistral.ai/v1/fim/completions failed, reason: Client network socket disconnected before secure TLS connection was established
    at ClientRequest.<anonymous> (/snapshot/continue/binary/out/index.js:447646:14)
    at ClientRequest.emit (node:events:549:35)
    at TLSSocket.socketErrorListener (node:_http_client:465:9)
    at TLSSocket.emit (node:events:537:28)
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) 
[2024-09-17T16:01:23] Error generating autocompletion:  Error: request to https://codestral.mistral.ai/v1/fim/completions failed, reason: Client network socket disconnected before secure TLS connection was established
[2024-09-17T16:08:01] request to https://codestral.mistral.ai/v1/fim/completions failed, reason: Client network socket disconnected before secure TLS connection was established

Code: ECONNRESET
Error number: ECONNRESET
Syscall: undefined
Type: system

FetchError: request to https://codestral.mistral.ai/v1/fim/completions failed, reason: Client network socket disconnected before secure TLS connection was established
    at ClientRequest.<anonymous> (/snapshot/continue/binary/out/index.js:447646:14)
    at ClientRequest.emit (node:events:549:35)
    at TLSSocket.socketErrorListener (node:_http_client:465:9)
    at TLSSocket.emit (node:events:537:28)
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) 
[2024-09-17T16:08:01] Error generating autocompletion:  Error: request to https://codestral.mistral.ai/v1/fim/completions failed, reason: Client network socket disconnected before secure TLS connection was established
[2024-09-17T16:08:10] [object Object] 
[2024-09-17T16:08:10] [object Object] 
[2024-09-17T16:11:41] [info] Exiting Continue core... 
[info] Starting Continue core...
[2024-09-20T18:50:10] [info] Starting Continue core... 
[2024-09-20T18:50:10] Setup 
[2024-09-20T18:50:10] Core started 
[2024-09-20T18:50:10] Indexing: 0.0% complete, elapsed time: 0s, NaN file/sec 
[2024-09-20T18:50:11] Chunk with more than 500 tokens constructed:  /home/user1/Projects/step-ca-webui/tests/test_logger.py 3267
[2024-09-20T18:50:11] Indexing: 25.0% complete, elapsed time: 1s, 3.00 file/sec 
[2024-09-20T18:50:11] Indexing: 25.0% complete, elapsed time: 1s, 3.00 file/sec 
[2024-09-20T18:50:11] Chunk with more than 500 tokens constructed:  /home/user1/Projects/step-ca-webui/tests/test_logger.py 3267
[2024-09-20T18:50:14] error when indexing:  Error: Failed to generate embeddings for 82 chunks with provider: _OpenAIEmbeddingsProvider::voyage-code-2: Error: {"requestId":"a8254141-12d2-45c5-9dc6-f2a07183648d","statusCode":400,"timestamp":"2024-09-20T18:50:13.993Z","path":"/v1/embeddings","message":"Invalid input","meta":{"_errors":[],"input":{"0":{"_errors":["String must contain at most 800 character(s)"]},"1":{"_errors":["String must contain at most 800 character(s)"]},"2":{"_errors":["String must contain at most 800 character(s)"]},"3":{"_errors":["String must contain at most 800 character(s)"]},"10":{"_errors":["String must contain at most 800 character(s)"]},"11":{"_errors":["String must contain at most 800 character(s)"]},"28":{"_errors":["String must contain at most 800 character(s)"]},"38":{"_errors":["String must contain at most 800 character(s)"]},"42":{"_errors":["String must contain at most 800 character(s)"]},"43":{"_errors":["String must contain at most 800 character(s)"]},"44":{"_errors":["String must contain at most 800 character(s)"]},"45":{"_errors":["String must contain at most 800 character(s)"]},"46":{"_errors":["String must contain at most 800 character(s)"]},"47":{"_errors":["String must contain at most 800 character(s)"]},"48":{"_errors":["String must contain at most 800 character(s)"]},"49":{"_errors":["String must contain at most 800 character(s)"]},"50":{"_errors":["String must contain at most 800 character(s)"]},"51":{"_errors":["String must contain at most 800 character(s)"]},"52":{"_errors":["String must contain at most 800 character(s)"]},"53":{"_errors":["String must contain at most 800 character(s)"]},"54":{"_errors":["String must contain at most 800 character(s)"]},"55":{"_errors":["String must contain at most 800 character(s)"]},"57":{"_errors":["String must contain at most 800 character(s)"]},"61":{"_errors":["String must contain at most 800 character(s)"]},"66":{"_errors":["String must contain at most 800 character(s)"]},"69":{"_errors":["String must contain at most 800 character(s)"]},"74":{"_errors":["String must contain at most 800 character(s)"]},"76":{"_errors":["String must contain at most 800 character(s)"]},"_errors":[]}}}
[2024-09-20T18:50:24] (node:66800) ExperimentalWarning: The Fetch API is an experimental feature. This feature could change at any time
(Use `continue-binary --trace-warnings ...` to show where the warning was created) 
[2024-09-20T19:14:55] Indexing: 0.0% complete, elapsed time: 0s, NaN file/sec 
[2024-09-20T19:14:55] Chunk with more than 500 tokens constructed:  /home/user1/Projects/step-ca-webui/tests/test_logger.py 3267
[2024-09-20T19:14:58] error when indexing:  Error: Failed to generate embeddings for 82 chunks with provider: _OpenAIEmbeddingsProvider::voyage-code-2: Error: {"requestId":"30dd4694-6123-450f-a726-3f31e06d1990","statusCode":400,"timestamp":"2024-09-20T19:14:57.860Z","path":"/v1/embeddings","message":"Invalid input","meta":{"_errors":[],"input":{"0":{"_errors":["String must contain at most 800 character(s)"]},"1":{"_errors":["String must contain at most 800 character(s)"]},"2":{"_errors":["String must contain at most 800 character(s)"]},"3":{"_errors":["String must contain at most 800 character(s)"]},"10":{"_errors":["String must contain at most 800 character(s)"]},"11":{"_errors":["String must contain at most 800 character(s)"]},"28":{"_errors":["String must contain at most 800 character(s)"]},"38":{"_errors":["String must contain at most 800 character(s)"]},"42":{"_errors":["String must contain at most 800 character(s)"]},"43":{"_errors":["String must contain at most 800 character(s)"]},"44":{"_errors":["String must contain at most 800 character(s)"]},"45":{"_errors":["String must contain at most 800 character(s)"]},"46":{"_errors":["String must contain at most 800 character(s)"]},"47":{"_errors":["String must contain at most 800 character(s)"]},"48":{"_errors":["String must contain at most 800 character(s)"]},"49":{"_errors":["String must contain at most 800 character(s)"]},"50":{"_errors":["String must contain at most 800 character(s)"]},"51":{"_errors":["String must contain at most 800 character(s)"]},"52":{"_errors":["String must contain at most 800 character(s)"]},"53":{"_errors":["String must contain at most 800 character(s)"]},"54":{"_errors":["String must contain at most 800 character(s)"]},"55":{"_errors":["String must contain at most 800 character(s)"]},"57":{"_errors":["String must contain at most 800 character(s)"]},"61":{"_errors":["String must contain at most 800 character(s)"]},"66":{"_errors":["String must contain at most 800 character(s)"]},"69":{"_errors":["String must contain at most 800 character(s)"]},"74":{"_errors":["String must contain at most 800 character(s)"]},"76":{"_errors":["String must contain at most 800 character(s)"]},"_errors":[]}}}
[2024-09-20T19:16:17] Indexing: 0.0% complete, elapsed time: 0s, NaN file/sec 
[2024-09-20T19:16:17] Chunk with more than 500 tokens constructed:  /home/user1/Projects/step-ca-webui/tests/test_logger.py 3267
[2024-09-20T19:16:20] error when indexing:  Error: Failed to generate embeddings for 82 chunks with provider: _OpenAIEmbeddingsProvider::voyage-code-2: Error: {"requestId":"72d8d496-6b45-4666-b522-1cb4fa818e0f","statusCode":400,"timestamp":"2024-09-20T19:16:19.942Z","path":"/v1/embeddings","message":"Invalid input","meta":{"_errors":[],"input":{"0":{"_errors":["String must contain at most 800 character(s)"]},"1":{"_errors":["String must contain at most 800 character(s)"]},"2":{"_errors":["String must contain at most 800 character(s)"]},"3":{"_errors":["String must contain at most 800 character(s)"]},"10":{"_errors":["String must contain at most 800 character(s)"]},"11":{"_errors":["String must contain at most 800 character(s)"]},"28":{"_errors":["String must contain at most 800 character(s)"]},"38":{"_errors":["String must contain at most 800 character(s)"]},"42":{"_errors":["String must contain at most 800 character(s)"]},"43":{"_errors":["String must contain at most 800 character(s)"]},"44":{"_errors":["String must contain at most 800 character(s)"]},"45":{"_errors":["String must contain at most 800 character(s)"]},"46":{"_errors":["String must contain at most 800 character(s)"]},"47":{"_errors":["String must contain at most 800 character(s)"]},"48":{"_errors":["String must contain at most 800 character(s)"]},"49":{"_errors":["String must contain at most 800 character(s)"]},"50":{"_errors":["String must contain at most 800 character(s)"]},"51":{"_errors":["String must contain at most 800 character(s)"]},"52":{"_errors":["String must contain at most 800 character(s)"]},"53":{"_errors":["String must contain at most 800 character(s)"]},"54":{"_errors":["String must contain at most 800 character(s)"]},"55":{"_errors":["String must contain at most 800 character(s)"]},"57":{"_errors":["String must contain at most 800 character(s)"]},"61":{"_errors":["String must contain at most 800 character(s)"]},"66":{"_errors":["String must contain at most 800 character(s)"]},"69":{"_errors":["String must contain at most 800 character(s)"]},"74":{"_errors":["String must contain at most 800 character(s)"]},"76":{"_errors":["String must contain at most 800 character(s)"]},"_errors":[]}}}
[2024-09-20T19:16:32] [info] Exiting Continue core... 
[info] Starting Continue core...
[2024-09-20T19:16:53] [info] Starting Continue core... 
[2024-09-20T19:16:53] Setup 
[2024-09-20T19:16:53] Core started 
[2024-09-20T19:16:53] Indexing: 0.0% complete, elapsed time: 0s, NaN file/sec 
[2024-09-20T19:16:53] LanceDBIndex, skipping /home/user1/Projects/step-ca-webui/README.md: Error: did not chunk properly 
[2024-09-20T19:16:53] LanceDBIndex, skipping /home/user1/Projects/step-ca-webui/requirements.txt: Error: did not chunk properly 
[2024-09-20T19:16:53] LanceDBIndex, skipping /home/user1/Projects/step-ca-webui/docs/architecture-overview.puml: Error: did not chunk properly 
[2024-09-20T19:16:53] LanceDBIndex, skipping /home/user1/Projects/step-ca-webui/docs/class-diagram.puml: Error: did not chunk properly 
[2024-09-20T19:16:53] LanceDBIndex, skipping /home/user1/Projects/step-ca-webui/docs/core-api.yaml: Error: did not chunk properly 
[2024-09-20T19:16:53] LanceDBIndex, skipping /home/user1/Projects/step-ca-webui/docs/ui-mockups.md: Error: did not chunk properly 
[2024-09-20T19:16:54] error when indexing:  Error: Failed to generate embeddings for 84 chunks with provider: undefined: TypeError: this.embeddingsProvider.embed is not a function
[2024-09-20T19:17:03] Indexing: 0.0% complete, elapsed time: 0s, NaN file/sec 
[2024-09-20T19:17:03] LanceDBIndex, skipping /home/user1/Projects/step-ca-webui/README.md: Error: did not chunk properly 
[2024-09-20T19:17:03] LanceDBIndex, skipping /home/user1/Projects/step-ca-webui/requirements.txt: Error: did not chunk properly 
[2024-09-20T19:17:03] LanceDBIndex, skipping /home/user1/Projects/step-ca-webui/docs/architecture-overview.puml: Error: did not chunk properly 
[2024-09-20T19:17:03] LanceDBIndex, skipping /home/user1/Projects/step-ca-webui/docs/class-diagram.puml: Error: did not chunk properly 
[2024-09-20T19:17:03] LanceDBIndex, skipping /home/user1/Projects/step-ca-webui/docs/core-api.yaml: Error: did not chunk properly 
[2024-09-20T19:17:03] LanceDBIndex, skipping /home/user1/Projects/step-ca-webui/docs/ui-mockups.md: Error: did not chunk properly 
[2024-09-20T19:17:03] error when indexing:  Error: Failed to generate embeddings for 84 chunks with provider: undefined: TypeError: this.embeddingsProvider.embed is not a function
[2024-09-20T19:17:04] (node:75453) ExperimentalWarning: The Fetch API is an experimental feature. This feature could change at any time
(Use `continue-binary --trace-warnings ...` to show where the warning was created)
```

**Comment by stone-w4tch3r** [comment]
Connected with #2320?

**Comment by Patrick-Erichsen** [comment]
Hi @stone-w4tch3r , these connection errors seem like a different issue but going to group it with the other indexing issues. Thanks for the detailed logs!

**Comment by Altroo** [comment]
Same issue it's with voyage provider in embedding :  

`"embeddingsProvider": {
    "provider": "voyage",
    "model": "voyage-code-2",
    "apiKey": "XXX"
  },`
  
  when change the provider to for example free-trial, it works.

**Comment by Altroo** [comment]
@stone-w4tch3r fixed on the latest release, thanks to everyone involved.
