### ISSUE TITLE
HTTP 429 Too Many Requests

### ISSUE THREAD

**Issue by AlexJ-StL** [continuedev/continue#2343]
### Before submitting your bug report

- [X] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [X] I've seen the [troubleshooting guide](https://docs.continue.dev/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS:Windows 11
- Continue:0.8.52
- IDE:VS Code 1.92.1
- Model:llama-3.1-8b-instant
- config.json:
  
  "tabAutocompleteModel": {
    "title": "llama-3.1-8b-instant",
    "model": "llama3.1-8b",
    "contextLength": 131072,
    "apiKey": "********",
    "completionOptions": {},
    "provider": "groq"
```

### Description

This occurred right after I opened a txt file to edit a couple of things. I wasn't using Continue or attempting any tab completions. As a matter of fact, I didn't even have the side tab with Continue open.

Looking at the 'Continue: LLM...' it appears that Continue sent* (see below) the contents of the TXT file I was reading over and over again until Groq's request limit prevented it from sending anymore. I received 5 of the HTTP 429 error messages (see screenshot below) all at once, so my guess is that it was sending the requests back to back without stopping. 

* Continue sent to Groq the following on repeat:
* "==========================================================================
==========================================================================
Settings:
contextLength: 131072
model: llama3.1-8b
maxTokens: 2048
temperature: 0.01
stop: <fim_prefix>,<fim_suffix>,<fim_middle>,<file_sep>,<|endoftext|>,</fim_middle>,</code>,

,

,/src/,#- coding: utf-8,```,
function,
class,
module,
export,
import
raw: true
log: undefined

############################################
<fim_prefix>
"The content of my txt..."
<fim_suffix><fim_middle>

...then it would repeat from the beginning..."

![Screenshot 2024-09-21 195727](https://github.com/user-attachments/assets/f1b13c70-c78d-478e-afcc-4ab7b4ba0df3)

### Log output

```Shell
console.ts:137 [Extension Host] Error generating autocompletion:  Error: HTTP 429 Too Many Requests from https://api.groq.com/openai/v1/chat/completions

{"error":{"message":"Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01ht7j91w5fjx8yabp2xh9hq37` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.969s. Visit https://console.groq.com/docs/rate-limits for more information.","type":"requests","code":"rate_limit_exceeded"}}

    at customFetch (c:\Users\AlexJ\.vscode\extensions\continue.continue-0.9.211-win32-x64\out\extension.js:104571:19)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at withExponentialBackoff (c:\Users\AlexJ\.vscode\extensions\continue.continue-0.9.211-win32-x64\out\extension.js:104258:26)
    at _Groq._streamChat (c:\Users\AlexJ\.vscode\extensions\continue.continue-0.9.211-win32-x64\out\extension.js:483821:26)
    at _Groq._streamComplete (c:\Users\AlexJ\.vscode\extensions\continue.continue-0.9.211-win32-x64\out\extension.js:483778:26)
    at _Groq.streamComplete (c:\Users\AlexJ\.vscode\extensions\continue.continue-0.9.211-win32-x64\out\extension.js:104668:26)
    at ListenableGenerator._start (c:\Users\AlexJ\.vscode\extensions\continue.continue-0.9.211-win32-x64\out\extension.js:96495:28)
C @ console.ts:137
notificationsAlerts.ts:42 HTTP 429 Too Many Requests from https://api.groq.com/openai/v1/chat/completions  {"error":{"message":"Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01ht7j91w5fjx8yabp2xh9hq37` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.969s. Visit https://console.groq.com/docs/rate-limits for more information.","type":"requests","code":"rate_limit_exceeded"}}
c @ notificationsAlerts.ts:42
console.ts:137 [Extension Host] Error generating autocompletion:  Error: HTTP 429 Too Many Requests from https://api.groq.com/openai/v1/chat/completions

{"error":{"message":"Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01ht7j91w5fjx8yabp2xh9hq37` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.287s. Visit https://console.groq.com/docs/rate-limits for more information.","type":"requests","code":"rate_limit_exceeded"}}

    at customFetch (c:\Users\AlexJ\.vscode\extensions\continue.continue-0.9.211-win32-x64\out\extension.js:104571:19)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at withExponentialBackoff (c:\Users\AlexJ\.vscode\extensions\continue.continue-0.9.211-win32-x64\out\extension.js:104258:26)
    at _Groq._streamChat (c:\Users\AlexJ\.vscode\extensions\continue.continue-0.9.211-win32-x64\out\extension.js:483821:26)
    at _Groq._streamComplete (c:\Users\AlexJ\.vscode\extensions\continue.continue-0.9.211-win32-x64\out\extension.js:483778:26)
    at _Groq.streamComplete (c:\Users\AlexJ\.vscode\extensions\continue.continue-0.9.211-win32-x64\out\extension.js:104668:26)
    at ListenableGenerator._start (c:\Users\AlexJ\.vscode\extensions\continue.continue-0.9.211-win32-x64\out\extension.js:96495:28)
C @ console.ts:137
notificationsAlerts.ts:42 HTTP 429 Too Many Requests from https://api.groq.com/openai/v1/chat/completions  {"error":{"message":"Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01ht7j91w5fjx8yabp2xh9hq37` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.287s. Visit https://console.groq.com/docs/rate-limits for more information.","type":"requests","code":"rate_limit_exceeded"}}
c @ notificationsAlerts.ts:42
console.ts:137 [Extension Host] Error generating autocompletion:  Error: HTTP 429 Too Many Requests from https://api.groq.com/openai/v1/chat/completions

{"error":{"message":"Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01ht7j91w5fjx8yabp2xh9hq37` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 399ms. Visit https://console.groq.com/docs/rate-limits for more information.","type":"requests","code":"rate_limit_exceeded"}}

    at customFetch (c:\Users\AlexJ\.vscode\extensions\continue.continue-0.9.211-win32-x64\out\extension.js:104571:19)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at withExponentialBackoff (c:\Users\AlexJ\.vscode\extensions\continue.continue-0.9.211-win32-x64\out\extension.js:104258:26)
    at _Groq._streamChat (c:\Users\AlexJ\.vscode\extensions\continue.continue-0.9.211-win32-x64\out\extension.js:483821:26)
    at _Groq._streamComplete (c:\Users\AlexJ\.vscode\extensions\continue.continue-0.9.211-win32-x64\out\extension.js:483778:26)
    at _Groq.streamComplete (c:\Users\AlexJ\.vscode\extensions\continue.continue-0.9.211-win32-x64\out\extension.js:104668:26)
    at ListenableGenerator._start (c:\Users\AlexJ\.vscode\extensions\continue.continue-0.9.211-win32-x64\out\extension.js:96495:28)
C @ console.ts:137
notificationsAlerts.ts:42 HTTP 429 Too Many Requests from https://api.groq.com/openai/v1/chat/completions  {"error":{"message":"Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01ht7j91w5fjx8yabp2xh9hq37` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 399ms. Visit https://console.groq.com/docs/rate-limits for more information.","type":"requests","code":"rate_limit_exceeded"}}
c @ notificationsAlerts.ts:42
console.ts:137 [Extension Host] Error generating autocompletion:  Error: HTTP 429 Too Many Requests from https://api.groq.com/openai/v1/chat/completions

{"error":{"message":"Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01ht7j91w5fjx8yabp2xh9hq37` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.042s. Visit https://console.groq.com/docs/rate-limits for more information.","type":"requests","code":"rate_limit_exceeded"}}

    at customFetch (c:\Users\AlexJ\.vscode\extensions\continue.continue-0.9.211-win32-x64\out\extension.js:104571:19)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at withExponentialBackoff (c:\Users\AlexJ\.vscode\extensions\continue.continue-0.9.211-win32-x64\out\extension.js:104258:26)
    at _Groq._streamChat (c:\Users\AlexJ\.vscode\extensions\continue.continue-0.9.211-win32-x64\out\extension.js:483821:26)
    at _Groq._streamComplete (c:\Users\AlexJ\.vscode\extensions\continue.continue-0.9.211-win32-x64\out\extension.js:483778:26)
    at _Groq.streamComplete (c:\Users\AlexJ\.vscode\extensions\continue.continue-0.9.211-win32-x64\out\extension.js:104668:26)
    at ListenableGenerator._start (c:\Users\AlexJ\.vscode\extensions\continue.continue-0.9.211-win32-x64\out\extension.js:96495:28)
C @ console.ts:137
notificationsAlerts.ts:42 HTTP 429 Too Many Requests from https://api.groq.com/openai/v1/chat/completions  {"error":{"message":"Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01ht7j91w5fjx8yabp2xh9hq37` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.042s. Visit https://console.groq.com/docs/rate-limits for more information.","type":"requests","code":"rate_limit_exceeded"}}
c @ notificationsAlerts.ts:42
console.ts:137 [Extension Host] Error generating autocompletion:  Error: HTTP 429 Too Many Requests from https://api.groq.com/openai/v1/chat/completions

{"error":{"message":"Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01ht7j91w5fjx8yabp2xh9hq37` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.006s. Visit https://console.groq.com/docs/rate-limits for more information.","type":"requests","code":"rate_limit_exceeded"}}

    at customFetch (c:\Users\AlexJ\.vscode\extensions\continue.continue-0.9.211-win32-x64\out\extension.js:104571:19)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at withExponentialBackoff (c:\Users\AlexJ\.vscode\extensions\continue.continue-0.9.211-win32-x64\out\extension.js:104258:26)
    at _Groq._streamChat (c:\Users\AlexJ\.vscode\extensions\continue.continue-0.9.211-win32-x64\out\extension.js:483821:26)
    at _Groq._streamComplete (c:\Users\AlexJ\.vscode\extensions\continue.continue-0.9.211-win32-x64\out\extension.js:483778:26)
    at _Groq.streamComplete (c:\Users\AlexJ\.vscode\extensions\continue.continue-0.9.211-win32-x64\out\extension.js:104668:26)
    at ListenableGenerator._start (c:\Users\AlexJ\.vscode\extensions\continue.continue-0.9.211-win32-x64\out\extension.js:96495:28)
C @ console.ts:137
notificationsAlerts.ts:42 HTTP 429 Too Many Requests from https://api.groq.com/openai/v1/chat/completions  {"error":{"message":"Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01ht7j91w5fjx8yabp2xh9hq37` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 1.006s. Visit https://console.groq.com/docs/rate-limits for more information.","type":"requests","code":"rate_limit_exceeded"}}
c @ notificationsAlerts.ts:42
console.ts:137 [Extension Host] Error generating autocompletion:  Error: HTTP 429 Too Many Requests from https://api.groq.com/openai/v1/chat/completions

{"error":{"message":"Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01ht7j91w5fjx8yabp2xh9hq37` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 526ms. Visit https://console.groq.com/docs/rate-limits for more information.","type":"requests","code":"rate_limit_exceeded"}}

    at customFetch (c:\Users\AlexJ\.vscode\extensions\continue.continue-0.9.211-win32-x64\out\extension.js:104571:19)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at withExponentialBackoff (c:\Users\AlexJ\.vscode\extensions\continue.continue-0.9.211-win32-x64\out\extension.js:104258:26)
    at _Groq._streamChat (c:\Users\AlexJ\.vscode\extensions\continue.continue-0.9.211-win32-x64\out\extension.js:483821:26)
    at _Groq._streamComplete (c:\Users\AlexJ\.vscode\extensions\continue.continue-0.9.211-win32-x64\out\extension.js:483778:26)
    at _Groq.streamComplete (c:\Users\AlexJ\.vscode\extensions\continue.continue-0.9.211-win32-x64\out\extension.js:104668:26)
    at ListenableGenerator._start (c:\Users\AlexJ\.vscode\extensions\continue.continue-0.9.211-win32-x64\out\extension.js:96495:28)
C @ console.ts:137
notificationsAlerts.ts:42 HTTP 429 Too Many Requests from https://api.groq.com/openai/v1/chat/completions  {"error":{"message":"Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01ht7j91w5fjx8yabp2xh9hq37` on requests per minute (RPM): Limit 30, Used 30, Requested 1. Please try again in 526ms. Visit https://console.groq.com/docs/rate-limits for more information.","type":"requests","code":"rate_limit_exceeded"}}
```

**Comment by HusainBhattiwala** [comment]
facing same issue is this been resolved ?

**Comment by AlexJ-StL** [comment]
> facing same issue is this been resolved ?

Nope. This is the first response that I have gotten. As for me I just shut off tab completion so I could continue working.

**Comment by AlexJ-StL** [comment]
bump

**Comment by AlexJ-StL** [comment]
> facing same issue is this been resolved ?

The closest thing to an answer that I have at the moment is located in this thread: https://github.com/continuedev/continue/issues/2457#issuecomment-2402693231

**Comment by ctwardy** [comment]
Amplifying.  I don't have this issue yet, but reading #2457 and #2343, I think commenters mistakenly think this (#2343) is a problem with the rate-limit, while the reporter makes a good case it's Continue stuck in a loop:

> it appears that Continue sent* ... the contents of the TXT file ... **over and over again** until Groq's request limit prevented it from sending anymore. I **received 5 of the HTTP 429 error messages ... all at once**, so my guess is that it was **sending the requests back to back without stopping**.

There is a suggestion on the other thread that upgrading solves #2457. Maybe this too?

**Comment by AlexJ-StL** [comment]
> Amplifying. I don't have this issue yet, but reading #2457 and #2343, I think commenters mistakenly attribute this (#2343) to a problem with the rate-limit, while the reporter makes a good case it's Continue stuck in a loop:
> 
> > it appears that Continue sent* ... the contents of the TXT file ... **over and over again** until Groq's request limit prevented it from sending anymore. I **received 5 of the HTTP 429 error messages ... all at once**, so my guess is that it was **sending the requests back to back without stopping**.
> 
> There is a suggestion on the other thread that upgrading solves #2457. Maybe this too?

Thank you for commenting! I'll look into the potential remedy.

To be honest, I've been working on some other things and haven't earnestly attempted to find a solution.

**Comment by wesleyboar** [comment]
I received this error upon sending a message in chat. I reproduced it three times. The message and context was small. Disabling autocomplete ([credit](https://github.com/continuedev/continue/issues/2343#issuecomment-2378034460)) allowed my next attempt to succeed.

**Comment by AlexJ-StL** [comment]
> I received this error upon sending a message in chat, without receiving a response. I reproduced it three times. The message and context was small. Disabling autocomplete ([as mentioned](https://github.com/continuedev/continue/issues/2343#issuecomment-2378034460)) allowed my next attempt to succeed.
> 
> _**Update**: Some requests later in the same chat (autocomplete still disabled), the error occurred again consistently. Restarting VS code did not help. Starting a new chat seemed to have resolved the error, but I instead just got the error **after** a response (instead of before)._
> 
> Is this error making me lose credits faster?
> I've been watching my credit usage in Anthropic since before the errors and after. It jumped up by $1 of usage after only a few messages (with errors). Previous interaction (of a similar scope) was taking only small fractions of cents at a time.
> 
> _**Update**: This may be because I had one chat that became very long, and I read (somewhere) that with each message in a long chat, Claude re-reads the entire chat._

I'm sorry to hear that you are having the same issue as I am. Perhaps you should open another issue thread because I think that at this point this one is going to remain open. We all may have better luck if there are multiple threads active. Just mention this one in that thread and it will link our threads together.

To answer your last question specifically... Yes, this will increase your usage. If you are using a paid service I would suggest, like you have been, keeping a close watch because it will likely send things multiple times. If the context is long....well... then it will be a lot.

Since this has been unresolved I have become very proficient with Aider and Cline (formerly ClaudeDev). That has kind of become my "AI Tool Stack" of sorts. For refactoring, feature addition, and other edit focused tasks I use Aider from CLI and to get an idea out of my head, planned out, and at least a MVP I have been using Cline. I will be lost if they ever pay wall those tools....

Hope this helps.
Cheers.

**Comment by QuanTran91** [comment]
Are there anyone taking a look on it

**Comment by RomneyDa** [comment]
@AlexJ-StL as shown in the error message, you are seeing exponential backoff retries since it hit 429. It will try 5 times with backoff.
See `core/util/withExponentialBackoff.ts`

>This occurred right after I opened a txt file to edit a couple of things. I wasn't using Continue or attempting any tab completions. As a matter of fact, I didn't even have the side tab with Continue open.

Continue's Tab autocomplete works independent of the chat sidebar. You can turn it on and off in the status bar. Tab completions trigger automatically debounced with user input, not with a manual trigger.

As far as I can tell this is all expected behavior in the case the provider (groq) rate limit has been hit. Anyone see reasons it wouldn't be?

**Comment by matthill33** [comment]
@RomneyDa is exponential backoff enabled for vertexai endpoints? I have not seen the "withExponentialBackoff" logs when hitting 429s when interacting with Vertex AI.

**Comment by matthill33** [comment]
Posted discussion - https://github.com/continuedev/continue/discussions/10155

**Comment by RomneyDa** [comment]
@matthill33 yes Vertex should be using withExponentialBackoff. The VertexAI LLM class has its own fetch but users super.fetch which uses it. Could you share logs?

@AlexJ-StL 
>To answer your last question specifically... Yes, this will increase your usage. If you are using a paid service I would suggest, like you have been, keeping a close watch because it will likely send things multiple times. If the context is long....well... then it will be a lot.

As far as I understand most providers would not charge usage for inputs of a request which they end up rate limiting. If anyone finds specific cases of this happening please post here but also open an issue with the provider, as that would be bad practice on their part (counting tokens is basically free, inference is expensive)

**Comment by RomneyDa** [comment]
@matthill33 I'm wondering if the issue is that the vertex errors aren't being properly recognized as 429's on our side. This would explain why we get an insane volume of gemini 429 errors (assuming similar to vertex error). Maybe gemini doesn't throw status 429

**Comment by RomneyDa** [comment]
@matthill33 PR to detect 429 in error message, I think this will probably fix most 429s. I will try to verify that the status ISN't 429 when the error code says 429
https://github.com/continuedev/continue/pull/10674/changes

**Comment by RomneyDa** [comment]
Improved here/ will say 
Fixed by https://github.com/continuedev/continue/pull/11773
