### ISSUE TITLE
Error: EPERM: operation not permitted, scandir

### ISSUE THREAD

**Issue by hung135** [continuedev/continue#2415]
### Before submitting your bug report

- [X] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [X] I've seen the [troubleshooting guide](https://docs.continue.dev/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS:
- Continue:
- IDE:
- Model:
- config.json:
```

### Description

Error: EPERM: operation not permitted, scandir
'C:\Windows\Temp'

I'm operating in a government environment and this path is locked down.
Would there be a way to configure it to point this to another directory?

**Comment by sestinj** [comment]
@hung135 thanks for bringing this up. I'm looking into where exactly we write to tmp in the first place: is there any chance you can share [the logs](https://docs.continue.dev/troubleshooting#check-the-logs)? My guess is there's a stack trace that will make the problem quite clear

**Comment by macote** [comment]
I had the same issue. Here's the log:
```
   INFO Started local extension host with pid 22316.
   ERR Extension 'ms-vscode.cpptools' appears in product.json but enables LESS API proposals than the extension wants.
package.json (LOSES): terminalDataWriteEvent, lmTools
product.json (WINS): terminalDataWriteEvent
  WARN [twxs.cmake]: Cannot register 'cmake.cmakePath'. This property is already registered.
 An iframe which has both allow-scripts and allow-same-origin for its sandbox attribute can escape its sandboxing.
mountTo @ workbench.desktop.main.js:3368
 Overwriting grammar scope name to file mapping for scope source.dart.
Old grammar file: file:///c%3A/Users/mac/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/extensions/dart/syntaxes/dart.tmLanguage.json.
New grammar file: file:///c%3A/Users/mac/.vscode/extensions/dart-code.dart-code-3.102.0/syntaxes/dart.json
register @ workbench.desktop.main.js:1312
 Overwriting grammar scope name to file mapping for scope source.dart.
Old grammar file: file:///c%3A/Users/mac/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/extensions/dart/syntaxes/dart.tmLanguage.json.
New grammar file: file:///c%3A/Users/mac/.vscode/extensions/dart-code.dart-code-3.102.0/syntaxes/dart.json
register @ textMateTokenization…er.workerMain.js:29
  INFO Settings Sync: Updating due to initialize
  INFO Settings Sync: Updating authentication providers. Authentication Providers from store: Array(2)
  INFO Settings Sync: Authentication providers updated Array(0)
  INFO Settings Sync: Updating authentication providers. Authentication Providers from store: Array(2)
  INFO Settings Sync: Authentication providers updated Array(1)
  INFO Settings Sync: Updating authentication providers. Authentication Providers from store: Array(2)
  INFO Settings Sync: Authentication providers updated Array(1)
log.ts:419  INFO Settings Sync: Updating authentication providers. Authentication Providers from store: Array(2)
log.ts:419  INFO Settings Sync: Authentication providers updated Array(2)
log.ts:419  INFO Settings Sync: Updating authentication providers. Authentication Providers from store: Array(2)
log.ts:419  INFO Settings Sync: Authentication providers updated Array(2)
log.ts:419  INFO Settings Sync: Updating authentication providers. Authentication Providers from store: Array(2)
log.ts:419  INFO Settings Sync: Authentication providers updated Array(2)
log.ts:419  INFO Settings Sync: Updating due to declared authentication providers changed
log.ts:419  INFO Settings Sync: Updating authentication providers. Authentication Providers from store: Array(2)
log.ts:419  INFO Settings Sync: Authentication providers updated Array(2)
log.ts:419  INFO Settings Sync: Updating due to declared authentication providers changed
log.ts:419  INFO Settings Sync: Updating authentication providers. Authentication Providers from store: Array(2)
log.ts:419  INFO Settings Sync: Authentication providers updated Array(2)
log.ts:419  INFO Settings Sync: Updating due to declared authentication providers changed
log.ts:419  INFO Settings Sync: Updating authentication providers. Authentication Providers from store: Array(2)
log.ts:419  INFO Settings Sync: Authentication providers updated Array(2)
log.ts:419  INFO [perf] Render performance baseline is 84ms
log.ts:439   ERR [Extension Host] (node:22316) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `Code --trace-deprecation ...` to show where the warning was created)
console.ts:137 [Extension Host] (node:22316) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `Code --trace-deprecation ...` to show where the warning was created)
uGi @ console.ts:137
abstractTaskService.ts:2087 Timed out getting tasks from  typescript
(anonymous) @ abstractTaskService.ts:2087
abstractTaskService.ts:2087 Timed out getting tasks from  typescript
(anonymous) @ abstractTaskService.ts:2087
log.ts:419  INFO Settings Sync: Updating authentication providers. Authentication Providers from store: Array(2)
log.ts:419  INFO Settings Sync: Authentication providers updated Array(2)
console.ts:137 [Extension Host] [node.js fs] readdir with filetypes failed with error:  Error: EPERM: operation not permitted, scandir 'c:\Users\mac\AppData\Local\Microsoft\Windows\INetCache\Low\Content.IE5'
	at async Object.readdir (node:internal/original-fs/promises:950:18)
	at async g2 (file:///c:/Users/mac/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:30:88638)
	at async Object.Bh (file:///c:/Users/mac/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:30:88567)
	at async ch.readdir (file:///c:/Users/mac/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:166:14588)
	at async Object.readDirectory (file:///c:/Users/mac/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:114:7116)
	at async DFSWalker.listDirForWalking (c:\Users\mac\.vscode\extensions\continue.continue-0.8.61-win32-x64\out\extension.js:136181:25)
	at async DFSWalker.walk (c:\Users\mac\.vscode\extensions\continue.continue-0.8.61-win32-x64\out\extension.js:136140:35)
	at async walkDirAsync (c:\Users\mac\.vscode\extensions\continue.continue-0.8.61-win32-x64\out\extension.js:136115:3)
	at async walkDir (c:\Users\mac\.vscode\extensions\continue.continue-0.8.61-win32-x64\out\extension.js:136108:20)
	at async Promise.all (index 0)
	at async FileContextProvider.loadSubmenuItems (c:\Users\mac\.vscode\extensions\continue.continue-0.8.61-win32-x64\out\extension.js:182271:25)
	at async c:\Users\mac\.vscode\extensions\continue.continue-0.8.61-win32-x64\out\extension.js:598617:25
	at async c:\Users\mac\.vscode\extensions\continue.continue-0.8.61-win32-x64\out\extension.js:640577:20
	at async mh.value (c:\Users\mac\.vscode\extensions\continue.continue-0.8.61-win32-x64\out\extension.js:605657:32)
uGi @ console.ts:137
console.ts:137 [Extension Host] [node.js fs] readdir with filetypes failed with error:  Error: EPERM: operation not permitted, scandir 'c:\Users\mac\AppData\Local\Microsoft\Windows\INetCache\Low\Content.IE5'
	at async Object.readdir (node:internal/original-fs/promises:950:18)
	at async g2 (file:///c:/Users/mac/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:30:88638)
	at async Object.Bh (file:///c:/Users/mac/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:30:88567)
	at async ch.readdir (file:///c:/Users/mac/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:166:14588)
	at async Object.readDirectory (file:///c:/Users/mac/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:114:7116)
	at async DFSWalker.listDirForWalking (c:\Users\mac\.vscode\extensions\continue.continue-0.8.61-win32-x64\out\extension.js:136181:25)
	at async DFSWalker.walk (c:\Users\mac\.vscode\extensions\continue.continue-0.8.61-win32-x64\out\extension.js:136140:35)
	at async walkDirAsync (c:\Users\mac\.vscode\extensions\continue.continue-0.8.61-win32-x64\out\extension.js:136115:3)
	at async walkDir (c:\Users\mac\.vscode\extensions\continue.continue-0.8.61-win32-x64\out\extension.js:136108:20)
	at async _VsCodeIde.listFolders (c:\Users\mac\.vscode\extensions\continue.continue-0.8.61-win32-x64\out\extension.js:638945:24)
	at async FolderContextProvider.loadSubmenuItems (c:\Users\mac\.vscode\extensions\continue.continue-0.8.61-win32-x64\out\extension.js:522214:25)
	at async c:\Users\mac\.vscode\extensions\continue.continue-0.8.61-win32-x64\out\extension.js:598617:25
	at async c:\Users\mac\.vscode\extensions\continue.continue-0.8.61-win32-x64\out\extension.js:640577:20
	at async mh.value (c:\Users\mac\.vscode\extensions\continue.continue-0.8.61-win32-x64\out\extension.js:605657:32)
uGi @ console.ts:137
log.ts:439   ERR [Extension Host] Error handling webview message: {
  "msg": {
    "messageId": "fa29e104-2cfb-4cff-9afb-c5c70b494c76",
    "messageType": "context/loadSubmenuItems",
    "data": {
      "title": "file"
    }
  }
}

NoPermissions (FileSystemError): Error: EPERM: operation not permitted, scandir 'c:\Users\mac\AppData\Local\Microsoft\Windows\INetCache\Low\Content.IE5'
console.ts:137 [Extension Host] Error handling webview message: {
  "msg": {
    "messageId": "fa29e104-2cfb-4cff-9afb-c5c70b494c76",
    "messageType": "context/loadSubmenuItems",
    "data": {
      "title": "file"
    }
  }
}

NoPermissions (FileSystemError): Error: EPERM: operation not permitted, scandir 'c:\Users\mac\AppData\Local\Microsoft\Windows\INetCache\Low\Content.IE5'
uGi @ console.ts:137
notificationsAlerts.ts:42 Error: EPERM: operation not permitted, scandir 'c:\Users\mac\AppData\Local\Microsoft\Windows\INetCache\Low\Content.IE5'
c @ notificationsAlerts.ts:42
log.ts:439   ERR [Extension Host] Error handling webview message: {
  "msg": {
    "messageId": "ed908393-d446-4df2-87c0-27d9861a8da8",
    "messageType": "context/loadSubmenuItems",
    "data": {
      "title": "folder"
    }
  }
}

NoPermissions (FileSystemError): Error: EPERM: operation not permitted, scandir 'c:\Users\mac\AppData\Local\Microsoft\Windows\INetCache\Low\Content.IE5'
console.ts:137 [Extension Host] Error handling webview message: {
  "msg": {
    "messageId": "ed908393-d446-4df2-87c0-27d9861a8da8",
    "messageType": "context/loadSubmenuItems",
    "data": {
      "title": "folder"
    }
  }
}

NoPermissions (FileSystemError): Error: EPERM: operation not permitted, scandir 'c:\Users\mac\AppData\Local\Microsoft\Windows\INetCache\Low\Content.IE5'
uGi @ console.ts:137
notificationsAlerts.ts:42 Error: EPERM: operation not permitted, scandir 'c:\Users\mac\AppData\Local\Microsoft\Windows\INetCache\Low\Content.IE5'
c @ notificationsAlerts.ts:42
console.ts:137 [Extension Host] [node.js fs] readdir with filetypes failed with error:  Error: EPERM: operation not permitted, scandir 'c:\Users\mac\AppData\Local\Microsoft\Windows\INetCache\Low\Content.IE5'
	at async Object.readdir (node:internal/original-fs/promises:950:18)
	at async g2 (file:///c:/Users/mac/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:30:88638)
	at async Object.Bh (file:///c:/Users/mac/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:30:88567)
	at async ch.readdir (file:///c:/Users/mac/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:166:14588)
	at async Object.readDirectory (file:///c:/Users/mac/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:114:7116)
	at async DFSWalker.listDirForWalking (c:\Users\mac\.vscode\extensions\continue.continue-0.8.61-win32-x64\out\extension.js:136181:25)
	at async DFSWalker.walk (c:\Users\mac\.vscode\extensions\continue.continue-0.8.61-win32-x64\out\extension.js:136140:35)
	at async walkDirAsync (c:\Users\mac\.vscode\extensions\continue.continue-0.8.61-win32-x64\out\extension.js:136115:3)
	at async walkDir (c:\Users\mac\.vscode\extensions\continue.continue-0.8.61-win32-x64\out\extension.js:136108:20)
	at async Promise.all (index 0)
	at async FileSearch.initializeFileSearchState (c:\Users\mac\.vscode\extensions\continue.continue-0.8.61-win32-x64\out\extension.js:632625:25)
uGi @ console.ts:137
index.js:1226 Error loading items for file: Object
(anonymous) @ index.js:1226
index.js:1226 Error loading items for folder: Object
(anonymous) @ index.js:1226
console.ts:137 [Extension Host] [node.js fs] readdir with filetypes failed with error:  Error: EPERM: operation not permitted, scandir 'c:\Users\mac\AppData\Local\Microsoft\Windows\INetCache\Low\Content.IE5'
	at async Object.readdir (node:internal/original-fs/promises:950:18)
	at async g2 (file:///c:/Users/mac/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:30:88638)
	at async Object.Bh (file:///c:/Users/mac/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:30:88567)
	at async ch.readdir (file:///c:/Users/mac/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:166:14588)
	at async Object.readDirectory (file:///c:/Users/mac/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:114:7116)
	at async DFSWalker.listDirForWalking (c:\Users\mac\.vscode\extensions\continue.continue-0.8.61-win32-x64\out\extension.js:136181:25)
	at async DFSWalker.walk (c:\Users\mac\.vscode\extensions\continue.continue-0.8.61-win32-x64\out\extension.js:136140:35)
	at async walkDirAsync (c:\Users\mac\.vscode\extensions\continue.continue-0.8.61-win32-x64\out\extension.js:136115:3)
	at async walkDir (c:\Users\mac\.vscode\extensions\continue.continue-0.8.61-win32-x64\out\extension.js:136108:20)
	at async Promise.all (index 0)
	at async getAllSuggestedDocs (c:\Users\mac\.vscode\extensions\continue.continue-0.8.61-win32-x64\out\extension.js:597740:19)
	at async c:\Users\mac\.vscode\extensions\continue.continue-0.8.61-win32-x64\out\extension.js:598995:33
	at async c:\Users\mac\.vscode\extensions\continue.continue-0.8.61-win32-x64\out\extension.js:640577:20
	at async mh.value (c:\Users\mac\.vscode\extensions\continue.continue-0.8.61-win32-x64\out\extension.js:605657:32)
uGi @ console.ts:137
log.ts:439   ERR [Extension Host] Error handling webview message: {
  "msg": {
    "messageId": "86a8fa95-b79c-43e1-b8c5-a48d48981c1c",
    "messageType": "docs/getSuggestedDocs"
  }
}

NoPermissions (FileSystemError): Error: EPERM: operation not permitted, scandir 'c:\Users\mac\AppData\Local\Microsoft\Windows\INetCache\Low\Content.IE5'
console.ts:137 [Extension Host] Error handling webview message: {
  "msg": {
    "messageId": "86a8fa95-b79c-43e1-b8c5-a48d48981c1c",
    "messageType": "docs/getSuggestedDocs"
  }
}

NoPermissions (FileSystemError): Error: EPERM: operation not permitted, scandir 'c:\Users\mac\AppData\Local\Microsoft\Windows\INetCache\Low\Content.IE5'
uGi @ console.ts:137
notificationsAlerts.ts:42 Error: EPERM: operation not permitted, scandir 'c:\Users\mac\AppData\Local\Microsoft\Windows\INetCache\Low\Content.IE5'
c @ notificationsAlerts.ts:42
console.ts:137 [Extension Host] rejected promise not handled within 1 second: NoPermissions (FileSystemError): Error: EPERM: operation not permitted, scandir 'c:\Users\mac\AppData\Local\Microsoft\Windows\INetCache\Low\Content.IE5'
uGi @ console.ts:137
console.ts:137 [Extension Host] stack trace: NoPermissions (FileSystemError): Error: EPERM: operation not permitted, scandir 'c:\Users\mac\AppData\Local\Microsoft\Windows\INetCache\Low\Content.IE5'
	at Ji.e (file:///c:/Users/mac/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:114:9238)
	at Object.readDirectory (file:///c:/Users/mac/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:114:7197)
	at async DFSWalker.listDirForWalking (c:\Users\mac\.vscode\extensions\continue.continue-0.8.61-win32-x64\out\extension.js:136181:25)
	at async DFSWalker.walk (c:\Users\mac\.vscode\extensions\continue.continue-0.8.61-win32-x64\out\extension.js:136140:35)
	at async walkDirAsync (c:\Users\mac\.vscode\extensions\continue.continue-0.8.61-win32-x64\out\extension.js:136115:3)
	at async walkDir (c:\Users\mac\.vscode\extensions\continue.continue-0.8.61-win32-x64\out\extension.js:136108:20)
	at async Promise.all (index 0)
	at async FileSearch.initializeFileSearchState (c:\Users\mac\.vscode\extensions\continue.continue-0.8.61-win32-x64\out\extension.js:632625:25)
uGi @ console.ts:137
mainThreadExtensionService.ts:78 [Continue.continue]Error: EPERM: operation not permitted, scandir 'c:\Users\mac\AppData\Local\Microsoft\Windows\INetCache\Low\Content.IE5'
$onExtensionRuntimeError @ mainThreadExtensionService.ts:78
mainThreadExtensionService.ts:79 NoPermissions (FileSystemError): Error: EPERM: operation not permitted, scandir 'c:\Users\mac\AppData\Local\Microsoft\Windows\INetCache\Low\Content.IE5'
	at Ji.e (file:///c:/Users/mac/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:114:9238)
	at Object.readDirectory (file:///c:/Users/mac/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:114:7197)
	at async DFSWalker.listDirForWalking (c:\Users\mac\.vscode\extensions\continue.continue-0.8.61-win32-x64\out\extension.js:136181:25)
	at async DFSWalker.walk (c:\Users\mac\.vscode\extensions\continue.continue-0.8.61-win32-x64\out\extension.js:136140:35)
	at async walkDirAsync (c:\Users\mac\.vscode\extensions\continue.continue-0.8.61-win32-x64\out\extension.js:136115:3)
	at async walkDir (c:\Users\mac\.vscode\extensions\continue.continue-0.8.61-win32-x64\out\extension.js:136108:20)
	at async Promise.all (index 0)
	at async FileSearch.initializeFileSearchState (c:\Users\mac\.vscode\extensions\continue.continue-0.8.61-win32-x64\out\extension.js:632625:25)
$onExtensionRuntimeError @ mainThreadExtensionService.ts:79
console.ts:137 [Extension Host] [node.js fs] readdir with filetypes failed with error:  Error: EPERM: operation not permitted, scandir 'c:\Users\mac\AppData\Local\Microsoft\Windows\INetCache\Low\Content.IE5'
	at async Object.readdir (node:internal/original-fs/promises:950:18)
	at async g2 (file:///c:/Users/mac/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:30:88638)
	at async Object.Bh (file:///c:/Users/mac/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:30:88567)
	at async ch.readdir (file:///c:/Users/mac/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:166:14588)
	at async Object.readDirectory (file:///c:/Users/mac/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:114:7116)
	at async DFSWalker.listDirForWalking (c:\Users\mac\.vscode\extensions\continue.continue-0.8.61-win32-x64\out\extension.js:136181:25)
	at async DFSWalker.walk (c:\Users\mac\.vscode\extensions\continue.continue-0.8.61-win32-x64\out\extension.js:136140:35)
	at async walkDirAsync (c:\Users\mac\.vscode\extensions\continue.continue-0.8.61-win32-x64\out\extension.js:136115:3)
	at async CodebaseIndexer.refreshDirs (c:\Users\mac\.vscode\extensions\continue.continue-0.8.61-win32-x64\out\extension.js:597453:28)
	at async Core.refreshCodebaseIndex (c:\Users\mac\.vscode\extensions\continue.continue-0.8.61-win32-x64\out\extension.js:599077:26)
uGi @ console.ts:137
console.ts:137 [Extension Host] rejected promise not handled within 1 second: NoPermissions (FileSystemError): Error: EPERM: operation not permitted, scandir 'c:\Users\mac\AppData\Local\Microsoft\Windows\INetCache\Low\Content.IE5'
uGi @ console.ts:137
console.ts:137 [Extension Host] stack trace: NoPermissions (FileSystemError): Error: EPERM: operation not permitted, scandir 'c:\Users\mac\AppData\Local\Microsoft\Windows\INetCache\Low\Content.IE5'
	at Ji.e (file:///c:/Users/mac/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:114:9238)
	at Object.readDirectory (file:///c:/Users/mac/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:114:7197)
	at async DFSWalker.listDirForWalking (c:\Users\mac\.vscode\extensions\continue.continue-0.8.61-win32-x64\out\extension.js:136181:25)
	at async DFSWalker.walk (c:\Users\mac\.vscode\extensions\continue.continue-0.8.61-win32-x64\out\extension.js:136140:35)
	at async walkDirAsync (c:\Users\mac\.vscode\extensions\continue.continue-0.8.61-win32-x64\out\extension.js:136115:3)
	at async CodebaseIndexer.refreshDirs (c:\Users\mac\.vscode\extensions\continue.continue-0.8.61-win32-x64\out\extension.js:597453:28)
	at async Core.refreshCodebaseIndex (c:\Users\mac\.vscode\extensions\continue.continue-0.8.61-win32-x64\out\extension.js:599077:26)
uGi @ console.ts:137
mainThreadExtensionService.ts:78 [Continue.continue]Error: EPERM: operation not permitted, scandir 'c:\Users\mac\AppData\Local\Microsoft\Windows\INetCache\Low\Content.IE5'
$onExtensionRuntimeError @ mainThreadExtensionService.ts:78
mainThreadExtensionService.ts:79 NoPermissions (FileSystemError): Error: EPERM: operation not permitted, scandir 'c:\Users\mac\AppData\Local\Microsoft\Windows\INetCache\Low\Content.IE5'
	at Ji.e (file:///c:/Users/mac/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:114:9238)
	at Object.readDirectory (file:///c:/Users/mac/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:114:7197)
	at async DFSWalker.listDirForWalking (c:\Users\mac\.vscode\extensions\continue.continue-0.8.61-win32-x64\out\extension.js:136181:25)
	at async DFSWalker.walk (c:\Users\mac\.vscode\extensions\continue.continue-0.8.61-win32-x64\out\extension.js:136140:35)
	at async walkDirAsync (c:\Users\mac\.vscode\extensions\continue.continue-0.8.61-win32-x64\out\extension.js:136115:3)
	at async CodebaseIndexer.refreshDirs (c:\Users\mac\.vscode\extensions\continue.continue-0.8.61-win32-x64\out\extension.js:597453:28)
	at async Core.refreshCodebaseIndex (c:\Users\mac\.vscode\extensions\continue.continue-0.8.61-win32-x64\out\extension.js:599077:26)
$onExtensionRuntimeError @ mainThreadExtensionService.ts:79
```

**Comment by sestinj** [comment]
thanks @macote, and what is the workspace directory path that you have open in your IDE when this happens?

**Comment by macote** [comment]
`C:\Dev\GitHub\macote\hshchk`
