### ISSUE TITLE
Jetbrains - RuntimeExceptionWithAttachments: Read access is allowed from inside read-action only

### ISSUE THREAD

**Issue by bitmario** [continuedev/continue#2455]
### Before submitting your bug report

- [X] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [X] I've seen the [troubleshooting guide](https://docs.continue.dev/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS: MacOS 15.0
- Continue: 0.0.71
- IDE: IntelliJ IDEA 2024.2.3
```

### Description

Autocomplete does not work and an IDE error popup is displayed - see stack trace below.

Looks like a new issue in v0.0.71. 0.0.70 does not exhibit this behavior.

### To reproduce

Simply type to trigger autocomplete

### Log output

```Shell
com.intellij.openapi.diagnostic.RuntimeExceptionWithAttachments: Read access is allowed from inside read-action only (see Application.runReadAction()); see https://jb.gg/ij-platform-threading for details
Current thread: Thread[#233,DefaultDispatcher-worker-2,5,main] 1653774253 (EventQueue.isDispatchThread()=false)
SystemEventQueueThread: Thread[#56,AWT-EventQueue-0,6,main] 1075774421
	at com.intellij.util.concurrency.ThreadingAssertions.createThreadAccessException(ThreadingAssertions.java:177)
	at com.intellij.util.concurrency.ThreadingAssertions.softAssertReadAccess(ThreadingAssertions.java:129)
	at com.intellij.openapi.application.impl.ApplicationImpl.assertReadAccessAllowed(ApplicationImpl.java:915)
	at com.intellij.openapi.editor.impl.CaretImpl.getOffset(CaretImpl.java:661)
	at com.intellij.openapi.editor.CaretModel.getOffset(CaretModel.java:129)
	at com.github.continuedev.continueintellijextension.autocomplete.AutocompleteService.shouldRenderCompletion(AutocompleteService.kt:115)
	at com.github.continuedev.continueintellijextension.autocomplete.AutocompleteService.access$shouldRenderCompletion(AutocompleteService.kt:39)
	at com.github.continuedev.continueintellijextension.autocomplete.AutocompleteService$triggerCompletion$1.invoke(AutocompleteService.kt:97)
	at com.github.continuedev.continueintellijextension.autocomplete.AutocompleteService$triggerCompletion$1.invoke(AutocompleteService.kt:90)
	at com.github.continuedev.continueintellijextension.continue.CoreMessenger.handleMessage(CoreMessenger.kt:104)
	at com.github.continuedev.continueintellijextension.continue.CoreMessenger.access$handleMessage(CoreMessenger.kt:18)
	at com.github.continuedev.continueintellijextension.continue.CoreMessenger$4.invokeSuspend(CoreMessenger.kt:239)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:115)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:100)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
```

**Comment by Patrick-Erichsen** [comment]
Hi @bitmario , could you try upgrading to 0.0.75 and see if the issue is resolved? That seems to have fixed things for a few users in this thread: https://github.com/continuedev/continue/issues/2457
