### ISSUE TITLE
[CON-282] Indexing causing lag for larger codebases

### ISSUE THREAD

**Issue by sestinj** [continuedev/continue#2525]
### Before submitting your bug report

- [X] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [X] I've seen the [troubleshooting guide](https://docs.continue.dev/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS:*
- Continue version:0.8.53, 0.9.215
- IDE version:VS Code
```

### Description

Recently a number of users have reported some lag due to indexing. In rare cases, it goes as far as causing the extension host to crash. This problem appears to go away when setting `"disableIndexing": true` in config.json.

<sub>[CON-282](https://linear.app/continue/issue/CON-282/indexing-causing-lag-for-larger-codebases)</sub>

**Comment by ian-hailey** [comment]
How can we get some debug logs for this issue? All I see in the VSC dev tools is Extension host (LocalProcess pid: 24752) is unresponsive.

**Comment by sestinj** [comment]
@ian-hailey @oldgithubman I think I've solved this in 0.8.54. It was happening only with the "transformers.js" embeddings provider (which is the default if you've not set up any "embeddingsProvider" in config.json.

We just needed to throttle it a bit to avoid it using too much CPU. For me this consistently stopped the extension host from going unresponsive, but curious to know if it also solves the problem for you

Indexing taking too long sounds like a separate problem, though once you've indexed your codebase once everything should be incremental from there, and you can still use basically all features, including @ codebase

**Comment by ian-hailey** [comment]
> @ian-hailey @oldgithubman I think I've solved this in 0.8.54. It was happening only with the "transformers.js" embeddings provider (which is the default if you've not set up any "embeddingsProvider" in config.json.
> 
> We just needed to throttle it a bit to avoid it using too much CPU. For me this consistently stopped the extension host from going unresponsive, but curious to know if it also solves the problem for you
> 
> Indexing taking too long sounds like a separate problem, though once you've indexed your codebase once everything should be incremental from there, and you can still use basically all features, including @ codebase

I have local Ollama as embeddingsProvider so I guess this transformers.js fix doesn't apply to me?

  "embeddingsProvider": {
    "title": "Nomic Embed Text",
    "provider": "ollama",
    "model": "nomic-embed-text"
  },

**Comment by Fmstrat** [comment]
Finally figured out that this is what is causing my CPU to spike one `code` thread to 100% when `continue` was enabled. I'm on `0.8.59` and this is still an issue for me. The repo that triggers it is only about 500 files, but does have a lot of history in the `.git` folder if that plays a role at all.

**Comment by Fmstrat** [comment]
@oldgithubman In the end, how were you debugging this? Since this only happens on one of my repos, I'd like to try to understand why, or find a way to stop indexing just that repo.

**Comment by Fmstrat** [comment]
@ian-hailey I notice in the codebase for indexing there is a `yield` which allows for a pause/cancel. Where is the progress of the indexing actually displayed in VSCode? Thanks.

**Comment by Patrick-Erichsen** [comment]
@Fmstrat progress is displayed in the "More" page (circle w/ three dots in bottom right).

The contents of your `.gitignore` should be ignored by default, but you may have luck attempting to explicitly ignore some files/folders via [`.continueignore`](https://docs.continue.dev/customize/deep-dives/codebase#ignore-files-during-indexing).

**Comment by Fmstrat** [comment]
@Patrick-Erichsen Thanks.

So I'm not sure if this is helpful, but I managed to narrow it down to a single directory of shell scripts in my repo. So I WAS wondering if this was actually about the size of the repo or not. I moved files back over in batches to see if there was a particular file or files that caused the issue, unfortunately, no luck. It indexed them fine one by one, but when pulling the whole repo back in, failed again.

The `pause` doesn't do anything under `More`, as the process is probably locked up. (Says it's indexing 107 files).

I did see some console logs like this, though they may be unrelated:

```
console.ts:137 [Extension Host] Error parsing /repos/setup/software/optional/az.sh: TypeError: Cannot read properties of undefined (reading 'apply')
    at e3.<computed> (/home/fmstrat/.vscode/extensions/continue.continue-0.8.59-linux-x64/out/extension.js:85780:63)
    at wasm://wasm/0055765a:wasm-function[15]:0x29b5
    at wasm://wasm/000b54aa:wasm-function[234]:0x25635
    at _Parser.parse (/home/fmstrat/.vscode/extensions/continue.continue-0.8.59-linux-x64/out/extension.js:86453:29)
    at CodeSnippetsCodebaseIndex.getSnippetsInFile (/home/fmstrat/.vscode/extensions/continue.continue-0.8.59-linux-x64/out/extension.js:130073:28)
    at async CodeSnippetsCodebaseIndex.update (/home/fmstrat/.vscode/extensions/continue.continue-0.8.59-linux-x64/out/extension.js:130093:24)
    at async CodebaseIndexer.indexFiles (/home/fmstrat/.vscode/extensions/continue.continue-0.8.59-linux-x64/out/extension.js:540089:39)
    at async CodebaseIndexer.refreshDirs (/home/fmstrat/.vscode/extensions/continue.continue-0.8.59-linux-x64/out/extension.js:539961:30)
    at async Core.refreshCodebaseIndex (/home/fmstrat/.vscode/extensions/continue.continue-0.8.59-linux-x64/out/extension.js:540979:26)
```

**Comment by Patrick-Erichsen** [comment]
Interesting - if you just remove the shell scripts, is the repo able to index properly? Any particular shell script that seems like it could be the culprit?

**Comment by Fmstrat** [comment]
@Patrick-Erichsen Unfortunately, no. Fortunately, I was able to narrow down that it's not a particular file that is the problem.
- Removed scripts, indexing worked
- Added them in one at a time, restarting VSCode in between, indexing worked

This whole repo is scripts, so I originally started going folder by folder.

@oldgithubman Sorry, I mean were you doing anything to debug other than looking at the Developer Tools?

**Comment by Fmstrat** [comment]
I'm hopeful I can get to a PR for this. I've narrowed it down to the tree iterator and so far have tried to use a `Promise.race` to skip if things lock up, but no luck on root cause.
