### ISSUE TITLE
Doc Indexing: embeddingsProvider.embed is not a function

### ISSUE THREAD

**Issue by codekoriko** [continuedev/continue#2527]
### Before submitting your bug report

- [x] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [x] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [x] I've seen the [troubleshooting guide](https://docs.continue.dev/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS: WSL Debian
- Continue version: v0.9.215 (pre-release)
- IDE version: Vscode 1.94.2 
- Model: 
- config.json:

{
  "embeddingsProvider": [
    {
      "provider": "openai",
      "model": "text-embedding-3-large",
      "apiKey": "[API_KEY]"
    }
  ]
}
```
```


### Description

when adding a doc 
```
{
  "docs": [
    {
      "title": "Pandas",
      "startUrl": "https://pandas.pydata.org/docs",
      "rootUrl": "https://pandas.pydata.org/docs",
      "faviconUrl": "https://pandas.pydata.org/docs/_static/favicon.ico"
    }
  ]
}
```
In Developer Tools console I get `Error chunking article:  TypeError: embeddingsProvider.embed is not a function`


Is it the `openai` `embeddingsProvider` that is not compatible? Will it work with `Voyage AI` or `Ollama`?

### To reproduce

_No response_

### Log output

```Shell
[Extension Host] Crawl completed
console.ts:137 [Extension Host] Creating embeddings for 329 articles
329
console.ts:137 [Extension Host] Error chunking article:  TypeError: embeddingsProvider.embed is not a function
	at _DocsService.indexAndAdd (c:\Users\xxxxxx\.vscode\extensions\continue.continue-0.9.215-win32-x64\out\extension.js:448881:64)
	at indexAndAdd.next (<anonymous>)
	at _DocsService.syncConfigAndSqlite (c:\Users\xxxxxx\.vscode\extensions\continue.continue-0.9.215-win32-x64\out\extension.js:449009:36)
	at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
	at async c:\Users\xxxxxx\.vscode\extensions\continue.continue-0.9.215-win32-x64\out\extension.js:448981:13
log.ts:439   ERR [Extension Host] No embeddings were created for site: https://pandas.pydata.org/docs
 Num chunks: 4009
console.ts:137 [Extension Host] No embeddings were created for site: https://pandas.pydata.org/docs
 Num chunks: 4009
```

**Comment by codekoriko** [comment]
apparently it also fails when indexing local files

```
[Extension Host] error when indexing:  Error: Failed to generate embeddings for 18 chunks with provider: undefined: TypeError: this.embeddingsProvider.embed is not a function
    at LanceDbIndex.getEmbeddings (c:\Users\salticidae\.vscode\extensions\continue.continue-0.9.215-win32-x64\out\extension.js:450142:17)
    at LanceDbIndex.computeRows (c:\Users\salticidae\.vscode\extensions\continue.continue-0.9.215-win32-x64\out\extension.js:450090:39)
    at LanceDbIndex.update (c:\Users\salticidae\.vscode\extensions\continue.continue-0.9.215-win32-x64\out\extension.js:450246:24)
    at CodebaseIndexer.indexFiles (c:\Users\salticidae\.vscode\extensions\continue.continue-0.9.215-win32-x64\out\extension.js:518245:39)
    at CodebaseIndexer.refresh (c:\Users\salticidae\.vscode\extensions\continue.continue-0.9.215-win32-x64\out\extension.js:518117:30)
    at Core.refreshCodebaseIndex (c:\Users\salticidae\.vscode\extensions\continue.continue-0.9.215-win32-x64\out\extension.js:518973:26)
```

and some files don't chunk properly
```
[Extension Host] LanceDBIndex, skipping \home\xxxxxxxxx\dev\js\xxxxxxxxx\README.md: Error: did not chunk properly
```

**Comment by codekoriko** [comment]
apparently it also fails when indexing local files

```
[Extension Host] error when indexing:  Error: Failed to generate embeddings for 18 chunks with provider: undefined: TypeError: this.embeddingsProvider.embed is not a function
    at LanceDbIndex.getEmbeddings (c:\Users\xxxxxx\.vscode\extensions\continue.continue-0.9.215-win32-x64\out\extension.js:450142:17)
    at LanceDbIndex.computeRows (c:\Users\xxxxxx\.vscode\extensions\continue.continue-0.9.215-win32-x64\out\extension.js:450090:39)
    at LanceDbIndex.update (c:\Users\xxxxxx\.vscode\extensions\continue.continue-0.9.215-win32-x64\out\extension.js:450246:24)
    at CodebaseIndexer.indexFiles (c:\Users\xxxxxx\.vscode\extensions\continue.continue-0.9.215-win32-x64\out\extension.js:518245:39)
    at CodebaseIndexer.refresh (c:\Users\xxxxxx\.vscode\extensions\continue.continue-0.9.215-win32-x64\out\extension.js:518117:30)
    at Core.refreshCodebaseIndex (c:\Users\xxxxx\.vscode\extensions\continue.continue-0.9.215-win32-x64\out\extension.js:518973:26)
```

and some files don't chunk properly
```
[Extension Host] LanceDBIndex, skipping \home\xxxxxxxxx\dev\js\xxxxxxxxx\README.md: Error: did not chunk properly
```

**Comment by checorone** [comment]
Hi

I tracked this issue down to this line 
https://github.com/continuedev/continue/blob/main/core/config/load.ts#L409

Map returns undefined on any provider, guess that it expects provider name, but somehow the whole structure is passed
If I hardcode provider name here (like 'openai') it starts working fine. Not sure how to fix it properly, I have no experience with TS at all) 

So maybe someone with knowledge could take a look on this?

**Comment by codekoriko** [comment]
after a Clean uninstall:

- Windows - Delete %APPDATA%\Code and %USERPROFILE%\.vscode.

- macOS - Delete $HOME/Library/Application Support/Code and ~/.vscode.

- Linux - Delete $HOME/.config/Code and ~/.vscode.

and re-install (make sure you delete your synced settings before reinstalling and recreating your profiles etc... (I know that's quite some work)

But it finally works for me 🥳 so I'm closing it

**Comment by mp-hive** [comment]
Simply deleting `%APPDATA%\Code` and restarting VSCode did it for me. No re-install necessary
