### ISSUE TITLE
Favicon not found

### ISSUE THREAD

**Issue by Melodeiro** [continuedev/continue#2562]
### Before submitting your bug report

- [X] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [X] I've seen the [troubleshooting guide](https://docs.continue.dev/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS: Windows
- Continue version: 0.75.0
- IDE version: JB IDEA Ultimate 2024.2.3
- Model: any
- config.json: 
  
{
  ...,
  "docs": [
    {
      "startUrl": "https://opensource.expediagroup.com/graphql-kotlin/docs/",
      "rootUrl": "https://opensource.expediagroup.com/graphql-kotlin/docs/",
      "title": "GraphQL Server Kotlin",
      "maxDepth": 3,
      "favicon": "https://opensource.expediagroup.com/graphql-kotlin/img/favicon.ico"
    },
    {
      "startUrl": "https://www.apollographql.com/docs/kotlin/",
      "rootUrl": "https://www.apollographql.com/docs/kotlin/",
      "title": "Apollo Kotlin",
      "maxDepth": 3,
      "faviconUrl": "https://www.apollographql.com/favicon/favicon-16x16.png"
    }
  ]
}
```

### Description

Cannot make a request with docs context. Getting the error below:

![image](https://github.com/user-attachments/assets/91aa52ed-ef11-4063-aa7c-d927e1a9a689)

Maybe faviconUrl were renamed to favicon or wise-versa? I see in config.json schema there is just "favicon":

![image](https://github.com/user-attachments/assets/e829ed12-b902-43fa-8795-b230e400d51a)

But none of the favicon or faviconUrl worked. So i guess there is an issue with default docs from continue plugin. They are specified with faviconUrl name. Also looks like that favicon is not optional which is the opposite to what the continue documentation says.

### To reproduce

I just tried to make a request with `@docs` provider. Doesn't matter if you add your docs or just keep only default ones

### Log output

```Shell
[2024-10-18T07:34:25] Error: Could not parse CSS stylesheet
    at exports2.createStylesheet (C:\snapshot\continue\binary\out\index.js:215325:25)
    at HTMLStyleElementImpl._updateAStyleBlock (C:\snapshot\continue\binary\out\index.js:216229:9)
    at HTMLStyleElementImpl._poppedOffStackOfOpenElements (C:\snapshot\continue\binary\out\index.js:216212:14)
    at JSDOMParse5Adapter.onItemPop (C:\snapshot\continue\binary\out\index.js:191547:48)
    at Parser5.onItemPop (C:\snapshot\continue\binary\out\index.js:188295:91)
    at OpenElementStack2.pop (C:\snapshot\continue\binary\out\index.js:187272:22)
    at endTagInText2 (C:\snapshot\continue\binary\out\index.js:190327:23)
    at Parser5._endTagOutsideForeignContent (C:\snapshot\continue\binary\out\index.js:189042:13)
    at Parser5.onEndTag (C:\snapshot\continue\binary\out\index.js:189008:16)
    at Tokenizer3.emitCurrentTagToken (C:\snapshot\continue\binary\out\index.js:184767:24) html{scroll-padding-top:170px}html.dark .shiki,html.dark .shiki code{background-color:var(--shiki-dark-bg)!important}html.dark .shiki,html.dark .shiki span{color:var(--shiki-dark)!important;font-style:var(--shiki-dark-font-style)!important;font-weight:var(--shiki-dark-font-weight)!important;-webkit-text-decoration:var(--shiki-dark-text-decoration)!important;text-decoration:var(--shiki-dark-text-decoration)!important}[id^=graph-]{line-height:normal!important;g rect,polygon.labelBox{stroke-width:2}.cluster rect{fill:none!important;stroke-width:2!important}.edgeLabel rect{background:none!important;fill:none!important}g rect,polygon.labelBox{stroke-width:2!important}.label text,span{color:inherit!important;fill:currentColor!important}.edgePath .path,.flowchart-link,.messageLine0,.messageLine1{stroke:currentColor!important}.marker,#arrowhead path{stroke:currentColor!important;fill:currentColor!important}.cluster-label{line-height:1.6em!important}.arrowheadPath{fill:currentColor!important}.noteText,text.actor{tspan{fill:currentColor!important}}.label foreignObject,.cluster-label foreignObject{overflow:visible!important}}th{border:solid 1px #B4C0BE;padding:4px}td{padding:12px;border:solid 1px #B4C0BE}tbody tr:nth-child(odd){background-color:#f2f4f4}.dark tbody tr:nth-child(odd){background-color:#182c35}.dark th,.dark td{border:solid 1px #365E72}

[2024-10-18T07:34:25] Error: Could not parse CSS stylesheet
    at exports2.createStylesheet (C:\snapshot\continue\binary\out\index.js:215325:25)
    at HTMLStyleElementImpl._updateAStyleBlock (C:\snapshot\continue\binary\out\index.js:216229:9)
    at HTMLStyleElementImpl._poppedOffStackOfOpenElements (C:\snapshot\continue\binary\out\index.js:216212:14)
    at JSDOMParse5Adapter.onItemPop (C:\snapshot\continue\binary\out\index.js:191547:48)
    at Parser5.onItemPop (C:\snapshot\continue\binary\out\index.js:188295:91)
    at OpenElementStack2.pop (C:\snapshot\continue\binary\out\index.js:187272:22)
    at endTagInText2 (C:\snapshot\continue\binary\out\index.js:190327:23)
    at Parser5._endTagOutsideForeignContent (C:\snapshot\continue\binary\out\index.js:189042:13)
    at Parser5.onEndTag (C:\snapshot\continue\binary\out\index.js:189008:16)
    at Tokenizer3.emitCurrentTagToken (C:\snapshot\continue\binary\out\index.js:184767:24) html{scroll-padding-top:170px}html.dark .shiki,html.dark .shiki code{background-color:var(--shiki-dark-bg)!important}html.dark .shiki,html.dark .shiki span{color:var(--shiki-dark)!important;font-style:var(--shiki-dark-font-style)!important;font-weight:var(--shiki-dark-font-weight)!important;-webkit-text-decoration:var(--shiki-dark-text-decoration)!important;text-decoration:var(--shiki-dark-text-decoration)!important}[id^=graph-]{line-height:normal!important;g rect,polygon.labelBox{stroke-width:2}.cluster rect{fill:none!important;stroke-width:2!important}.edgeLabel rect{background:none!important;fill:none!important}g rect,polygon.labelBox{stroke-width:2!important}.label text,span{color:inherit!important;fill:currentColor!important}.edgePath .path,.flowchart-link,.messageLine0,.messageLine1{stroke:currentColor!important}.marker,#arrowhead path{stroke:currentColor!important;fill:currentColor!important}.cluster-label{line-height:1.6em!important}.arrowheadPath{fill:currentColor!important}.noteText,text.actor{tspan{fill:currentColor!important}}.label foreignObject,.cluster-label foreignObject{overflow:visible!important}}th{border:solid 1px #B4C0BE;padding:4px}td{padding:12px;border:solid 1px #B4C0BE}tbody tr:nth-child(odd){background-color:#f2f4f4}.dark tbody tr:nth-child(odd){background-color:#182c35}.dark th,.dark td{border:solid 1px #365E72}

[2024-10-18T07:34:26] Error [ERR_UNSUPPORTED_ESM_URL_SCHEME]: Only URLs with a scheme in: file, data are supported by the default ESM loader. On Windows, absolute paths must be valid file:// URLs. Received protocol 'c:' 
[2024-10-18T07:34:26] Could not load config.ts as absolute path, retrying as file url ... 
[2024-10-18T07:34:26] Error [ERR_UNSUPPORTED_ESM_URL_SCHEME]: Only URLs with a scheme in: file, data are supported by the default ESM loader. On Windows, absolute paths must be valid file:// URLs. Received protocol 'c:' 
[2024-10-18T07:34:26] Could not load config.ts as absolute path, retrying as file url ... 
[2024-10-18T07:34:26] Indexing new doc: https://www.apollographql.com/docs/kotlin 
[2024-10-18T07:34:26] Already in queue 
[2024-10-18T07:34:27] [info] Exiting Continue core... 
[info] Starting Continue core...
[2024-10-18T07:34:39] [info] Starting Continue core... 
[2024-10-18T07:34:39] Setup 
[2024-10-18T07:34:39] Core started 
[2024-10-18T07:34:39] Error [ERR_UNSUPPORTED_ESM_URL_SCHEME]: Only URLs with a scheme in: file, data are supported by the default ESM loader. On Windows, absolute paths must be valid file:// URLs. Received protocol 'c:' 
[2024-10-18T07:34:39] Could not load config.ts as absolute path, retrying as file url ... 
[2024-10-18T07:34:48] Generated repo map for  at C:\Users\Melodeiro\.continue\.utils\repo_map.txt
```

**Comment by Melodeiro** [comment]
Just tried it in latest pre-release vs code version and getting the same error. Im using the default context experimental feature, maybe that is the reason:

  "experimental": {
    "defaultContext": [
      {
        "name": "docs"
      }
    ]
  }
