### ISSUE TITLE
PluginException "ActionUpdateThread.OLD_EDT" thrown in IntelliJ with 0.0.78

### ISSUE THREAD

**Issue by florian-hansen-mw** [continuedev/continue#2728]
### Before submitting your bug report

- [X] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [X] I've seen the [troubleshooting guide](https://docs.continue.dev/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS: MacOS 15.1
- Continue version: 0.0.78
- IDE version: IntelliJ 
IntelliJ IDEA 2024.2.4 (Ultimate Edition)
Build #IU-242.23726.103, built on October 23, 2024

Runtime version: 21.0.4+13-b509.26 aarch64 (JCEF 122.1.9)
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Toolkit: sun.lwawt.macosx.LWCToolkit
macOS 15.1
Kotlin plugin: K2 mode (Beta)
GC: G1 Young Generation, G1 Concurrent GC, G1 Old Generation
Memory: 4096M
Cores: 12
Metal Rendering is ON
Registry:
  ide.balloon.shadow.size=0
  ide.browser.jcef.jsQueryPoolSize=200
  ide.browser.jcef.contextMenu.devTools.enabled=true
  ide.experimental.ui=true
  i18n.locale=
Non-Bundled Plugins:
  com.github.continuedev.continueintellijextension (0.0.78)
  org.intellij.plugins.hcl (242.23339.11)
  PythonCore (242.23726.103)
  org.jetbrains.plugins.go-template (242.20224.155)
  Pythonid (242.23726.103)
  PlantUML integration (7.11.2-IJ2023.2)
  mobi.hsz.idea.gitignore (4.5.4)
Kotlin: 242.23726.103-IJ

- Model: all
- config.json:
  
{
  "models": [
    {
      "apiKey": "",
      "engine": "gpt-4o",
      "apiBase": "",
      "apiType": "azure",
      "model": "gpt-4o",
      "title": "GPT-4o",
      "systemMessage": "You are an expert software developer. You give helpful and concise responses. Omit greetings.",
      "provider": "azure",
      "apiVersion": "2024-08-01-preview"
    }
  ],
  "tabAutocompleteModel": {
    "title": "codeqwen",
    "provider": "ollama",
    "model": "codeqwen:latest"
  },
  "embeddingsProvider": {
    "title": "text-embedding-3-large",
    "provider": "openai",
    "model": "text-embedding-3-large",
    "apiBase": "",
    "engine": "text-embedding-3-large",
    "apiVersion": "2023-05-15",
    "apiType": "azure",
    "apiKey": ""
  },
  "customCommands": [
    {
      "name": "test",
      "prompt": "{{{ input }}}\n\nWrite a comprehensive set of unit tests for the selected code. It should setup, run tests that check for correctness including important edge cases, and teardown. Ensure that the tests are complete and sophisticated. Give the tests just as chat output, don't edit any file.",
      "description": "Write unit tests for highlighted code"
    }
  ],
  "contextProviders": [
    {
      "name": "diff",
      "params": {}
    },
    {
      "name": "folder",
      "params": {}
    },
    {
      "name": "codebase",
      "params": {}
    }
  ],
  "slashCommands": [
    {
      "name": "edit",
      "description": "Edit selected code"
    },
    {
      "name": "comment",
      "description": "Write comments for the selected code"
    },
    {
      "name": "share",
      "description": "Export the current chat session to markdown"
    },
    {
      "name": "commit",
      "description": "Generate a git commit message"
    }
  ],
  "allowAnonymousTelemetry": false
}
```

### Description

When starting IntelliJ, I see an exception:

com.intellij.diagnostic.PluginException: `ActionUpdateThread.OLD_EDT` is deprecated and going to be removed soon. 'com.github.continuedev.continueintellijextension.autocomplete.CancelAutocompleteAction' must override `getActionUpdateThread()` and chose EDT or BGT. See ActionUpdateThread javadoc. [Plugin: com.github.continuedev.continueintellijextension]
	at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:23)
	at com.intellij.diagnostic.PluginException.createByClass(PluginException.java:90)
	at com.intellij.diagnostic.PluginException.reportDeprecatedUsage(PluginException.java:125)
	at com.intellij.openapi.actionSystem.ActionUpdateThreadAware.getActionUpdateThread(ActionUpdateThreadAware.java:21)
	at com.intellij.openapi.actionSystem.AnAction.getActionUpdateThread(AnAction.java:201)

No helpful completions are shown, it only suggests "{" inline.

### To reproduce

1. Install Plugin
2. Start IDE

### Log output

```Shell
[2024-10-29T15:38:43] [info] Starting Continue core... 
[2024-10-29T15:38:43] Setup 
[2024-10-29T15:38:43] Core started 
[2024-10-29T15:38:43] Error loading remote config:  Error: ENOENT: no such file or directory, open '/Users/me/.continue/.configs/localhost/config.json'
[2024-10-29T15:38:43] Error loading remotely set config.js:  Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/Users/me/.continue/.configs/localhost/config.js' imported from /snapshot/continue/binary/out/index.js
[2024-10-29T15:38:43] (node:45671) ExperimentalWarning: The Fetch API is an experimental feature. This feature could change at any time
(Use `continue-binary --trace-warnings ...` to show where the warning was created) 
[2024-10-29T15:38:43] Failed to retrieve from remote cache TypeError: fetch failed
[2024-10-29T15:38:44] Chunk to delete wasn't found in the table:  /Users/me/Documents/Projekte/.../build.gradle.kts
[2024-10-29T15:38:44] Failed to retrieve from remote cache TypeError: fetch failed
```

**Comment by chubshaun** [comment]
Confirmed I see this a lot when refactoring file names / editing project window.

```
com.intellij.diagnostic.PluginException: `ActionUpdateThread.OLD_EDT` is deprecated and going to be removed soon. 'com.github.continuedev.continueintellijextension.autocomplete.CancelAutocompleteAction' must override `getActionUpdateThread()` and chose EDT or BGT. See ActionUpdateThread javadoc. [Plugin: com.github.continuedev.continueintellijextension]
	at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:23)
	at com.intellij.diagnostic.PluginException.createByClass(PluginException.java:90)
	at com.intellij.diagnostic.PluginException.reportDeprecatedUsage(PluginException.java:125)
	at com.intellij.openapi.actionSystem.ActionUpdateThreadAware.getActionUpdateThread(ActionUpdateThreadAware.java:21)
	at com.intellij.openapi.actionSystem.AnAction.getActionUpdateThread(AnAction.java:201)
```

**Comment by sprite5** [comment]
on 0.0.88 still not works it's my log
`com.intellij.diagnostic.PluginException: `ActionUpdateThread.OLD_EDT` is deprecated and going to be removed soon. 'com.github.continuedev.continueintellijextension.autocomplete.CancelAutocompleteAction' must override `getActionUpdateThread()` and chose EDT or BGT. See ActionUpdateThread javadoc. [Plugin: com.github.continuedev.continueintellijextension]
	at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:23)
	at com.intellij.diagnostic.PluginException.createByClass(PluginException.java:90)
	at com.intellij.diagnostic.PluginException.reportDeprecatedUsage(PluginException.java:125)
	at com.intellij.openapi.actionSystem.ActionUpdateThreadAware.getActionUpdateThread(ActionUpdateThreadAware.java:21)
	at com.intellij.openapi.actionSystem.AnAction.getActionUpdateThread(AnAction.java:199)
2025-02-12 10:52:25,961 [  53568] SEVERE - #com.github.continuedev.continueintellijextension.autocomplete.CancelAutocompleteAction - IntelliJ IDEA 2024.1.6  Build #IC-241.19072.14
2025-02-12 10:52:25,961 [  53568] SEVERE - #com.github.continuedev.continueintellijextension.autocomplete.CancelAutocompleteAction - JDK: 17.0.11; VM: OpenJDK 64-Bit Server VM; Vendor: JetBrains s.r.o.
2025-02-12 10:52:25,961 [  53568] SEVERE - #com.github.continuedev.continueintellijextension.autocomplete.CancelAutocompleteAction - OS: Mac OS X
2025-02-12 10:52:25,961 [  53568] SEVERE - #com.github.continuedev.continueintellijextension.autocomplete.CancelAutocompleteAction - Plugin to blame: Continue version: 0.0.88
2025-02-12 10:52:25,962 [  53569] SEVERE - #com.github.continuedev.continueintellijextension.autocomplete.CancelAutocompleteAction - Last Action: EditorBackSpace`
