### ISSUE TITLE
@ not triggering context Provider in chat - Windows

### ISSUE THREAD

**Issue by RomneyDa** [continuedev/continue#2808]
### Before submitting your bug report

- [X] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [X] I've seen the [troubleshooting guide](https://docs.continue.dev/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS: Windows
- Continue version: 0.0.80
- IDE version: ?
- Model: NA
- config: NA
```

### Description

https://discord.com/channels/1108621136150929458/1302434456686170138
typing @ does not always trigger context provider menu, especially on new window
seems to be linked to the new Cmd + I edit feature

### To reproduce

![image](https://github.com/user-attachments/assets/5cf13b84-e752-489e-9691-9828595170b2)

**Comment by PRANJALRANA11** [comment]
https://github.com/user-attachments/assets/6860c3fe-eb27-4503-8b6a-39e36d170380

It's working on windows for my system 11 @RomneyDa @sestinj

**Comment by FallDownTheSystem** [comment]
It starts to work after navigating, doesn't have to be the edit page (ctrl + i), going to history and back also makes it work.

**Comment by LymanBE** [comment]
I just want to confirm that navigatin to the history and back works as a workaround.

A maybe related issue: The Jetbrains plugin also won't show the context window but only for the last message. If you edit a previous prompt, it will. Tricky UI issues, it seems.

**Comment by Sillocan** [comment]
This isn't working on macos for me as well. I've even tried reloading the window. The history trick _did_ work though

**Comment by alanwilter** [comment]
Yet, same issue with Mac, and the history did the trick as well.

**Comment by RomneyDa** [comment]
Seems to be happening to many people. I haven't been able to duplicate. Anyone seeing errors in the console at the same time?

**Comment by PretzelVector** [comment]
Hello,

I am reliably reproducing this on linux by reloading the window. (VSCode v1.95.1 + Continue v0.9.230)

**Setup**
1. Create a new VSCode profile
2. Install Continue
3. Reload Window: Use command palette (Ctrl+Shift+P) to issue reload window
4. Upgrade to pre-release
5. Reload Window

**Reproduction**
1. ctrl+L to open Continue
2. Type `@`, **context menu will not appear**
3. Switch to History and back to chat
4. Type `@`, **context menu does appear**
5. Reload Window 
6. Continue window will still be open, ctrl+L to focus Continue chat
7. Type `@`, **context menu will not appear**

There are no logs in Continue during that cycle. The "Extension Host" log contains an error with continue in the backtrace during VSCode startup (during reload), but seems unrelated.
```
2024-11-14 17:07:07.589 [error] RangeError: path should be a `path.relative()`d string, but got "../../../exthost"
    at throwError (/home/pv/.vscode/extensions/continue.continue-0.9.226-linux-x64/out/extension.js:71768:13)
    at checkPath (/home/pv/.vscode/extensions/continue.continue-0.9.226-linux-x64/out/extension.js:71782:16)
    at Ignore2._test (/home/pv/.vscode/extensions/continue.continue-0.9.226-linux-x64/out/extension.js:71870:9)
    at Ignore2.ignores (/home/pv/.vscode/extensions/continue.continue-0.9.226-linux-x64/out/extension.js:71897:21)
    at /home/pv/.vscode/extensions/continue.continue-0.9.226-linux-x64/out/extension.js:548630:31
```

Please let me know if there are other logs I can provide.

Thank you all for your contributions,
~PV

**Comment by joewinke** [comment]
+1 mac os. It was working fine and then @ context stopped working. I installed 3 prior versions back as I thought it might be an auto update, but that didn't work. Came here and found the history fix and that works.

However it still is limited - when I start a new session and press / normally I get everything in my .prompts but now I get a neutered version offering /share /cmd /test
![Screenshot 2024-11-17 at 12 11 09 AM](https://github.com/user-attachments/assets/7d52814a-f889-4462-ad1c-aecd4b541765)

**Comment by jsade** [comment]
+1 for @ not triggering context provider, macOS, pre-release version of Continue. I get rid of the issue for a while by running "Codebase Force Re-index." 

The developer log is filled with 
```
mainThreadExtensionService.ts:78 [Continue.continue]path should be a `path.relative()`d string, but got "../../../.continue/config.json"
$onExtensionRuntimeError	@	mainThreadExtensionService.ts:78
```

The extension's Features page > Runtime Status shows:

```
Uncaught Errors (3)
 path should be a path.relative()d string, but got "../../../../../extension-output-Continue.continue-#1-Continue"
 path should be a path.relative()d string, but got "../../../../../main"
 path should be a path.relative()d string, but got "../../../.continue/config.json"
```

**Comment by tranquochuy645** [comment]
+1 in Ubuntu

**Comment by RomneyDa** [comment]
Is anyone still experiencing this on most recent prerelease?
@PretzelVector have followed your steps, can't reproduce on my machine

**Comment by Joilence** [comment]
> Is anyone still experiencing this on most recent prerelease?

I still have this.  macOS 15.1.1 / VSCode 1.95.3 / Continue v0.8.58

**Comment by joewinke** [comment]
Yes just updated and relaunched. Still don't have my slash / shortcuts (prompts) and had to go to history to reactivate @ wasn't working upon relaunch.

**Comment by stefan-detter-m** [comment]
+1 in Windows 11 / VSCode 1.94.2 / Continue v0.8.58

**Comment by kaylynb** [comment]
Bluefin/Fedora 41 /  VSCode 1.59.3 / Continue v0.9.233 (pre-release) & v0.8.59. 0.8.55 is the last version that works for me.

**Comment by kaylynb** [comment]
I think this is related to telemetry somehow? I ran vscode in an isolated environment and it worked until I added my usual settings.json. As soon as I remove `"telemetry.telemetryLevel": "off"` the "@" menu works again.

I bisected the code and it appears to be introduced in https://github.com/continuedev/continue/commit/3d5d43e246086dea2a6a9844db2079ebff74f483. I replaced `TipTapEditor.tsx` from the previous commit and it worked even with telemetry turned off.

**Comment by RomneyDa** [comment]
@joewinke you may need to add `version: 1` to your prompt files since prompt files v2 is out
https://docs.continue.dev/customize/deep-dives/prompt-files

**Comment by RomneyDa** [comment]
@kaylynb awesome, thanks for looking into this. I'll take a closer look at that commit

**Comment by alanwilter** [comment]
@kaylynb I tried what you mentioned. To start with, I never had `telemetry` entry in my `setting.json`. I couldn't reproduce your solution.

I'm using Mac Sequoia with Vscode 1.95.3 and for both Continue `v0.8.59` and `v0.9.235`.

I still need to do the re-index trick to get the prompts and then I can use `@` to access even my prompts.

BTW, what's the difference between prompts v1 x v2?

I have this prompt:

```yml

<system>
You are an expert programmer
</system>

{{{ input }}}

You will follow the guidelines to understand what unit testing is, and how to generate useful unit tests:
{{{ url "https://aws.amazon.com/what-is/unit-testing/" }}}

Write unit tests for the above selected code, following each of these instructions:
- Use pytest
- Properly set up and tear down if needed
- Include important edge cases
- The tests should be complete and sophisticated
- Give the tests just as chat output, don't edit any file
- Don't explain how to set up pytest
- Add typings according to python 3.9 convention, so no need to use `from typing import` etc.
- Add one line docstring explaining what the test does
```

What do I need to change to make it complies with prompts version 2?

**Comment by joewinke** [comment]
> @joewinke you may need to add `version: 1` to your prompt files since prompt files v2 is out https://docs.continue.dev/customize/deep-dives/prompt-files

OK so the whole architecture has changed? Before i had prompts in .prompts/ now they need to be in .continue/prompts ... and before I did /[promptName] now the flow is @prompts > [promptName]? What is slash / denoting now? Thanks @RomneyDa

**Comment by lendle** [comment]
This is happening for me as well on mac/vscode whenever I start vscode. I just updated to the newest pre-release, `0.9.235`, but this has been happening consistently for at least a couple months on a couple of machines with various levels of custom configs. 

Going to history and back to chat gets it to work. So does going to `...` and clicking re-index.

I don't see anything in the dev console or continue output.

**Comment by kaylynb** [comment]
[Screencast From 2024-11-26 08-16-56.webm](https://github.com/user-attachments/assets/dcc4a75c-9f93-4b62-89ad-02124748b2c0)

Just tried in a clean VM and am able to repro. Also repros on MacOS.

**Comment by Patrick-Erichsen** [comment]
@qinlinwang you were correct, the issue was the Mentions not being configured properly when the editor first loads.

**Comment by kaylynb** [comment]
@qinlinwang yeah I just looked over it and it looks like there is a race condition with the `availableContextProviders` prop. With telemetry enabled it has a different initial state. The `useEditor` call doesn't have it in the dependency array, so the first render it's disabled as the effect isn't called again until the component is mounted again (for example, by going to history view and back).

Looks like it's already been fixed in the last hour though. I do wonder if the dependency array should be filled out properly instead of just removing the conditional render check, but I know that it can cause issues in some codebases to declare dependencies and I'm not familiar with this one.

**Comment by RomneyDa** [comment]
@kaylynb the `useEditor` hook can't react to changes in state variables, it only injects the config once on mount, so the `useUpdatingRef` paradigm is used for stuff like `availableContextProviders` -> availableContextProvidersRef` so that values accessed will always be up to date

**Comment by RomneyDa** [comment]
Thank you all for the help on this bug!
