### ISSUE TITLE
Deprecated `ActionUpdateThread.OLD_EDT` usage in `continueintellijextension`

### ISSUE THREAD

**Issue by px100** [continuedev/continue#2819]
### Before submitting your bug report

- [X] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [X] I've seen the [troubleshooting guide](https://docs.continue.dev/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS: macOS
- Continue version: v0.0.80
- IDE version: Build #IU-242.23726.103, built on October 23, 2024
- Model: Sonnet 3.5
- config.json:
```

### Description

Encountering a deprecation warning related to the `ActionUpdateThread.OLD_EDT` in the Continue.dev extension for JetBrains IntelliJ IDEA. The `CancelAutocompleteAction` class needs to override `getActionUpdateThread()` and specify either `EDT` or `BGT` to ensure compatibility with upcoming updates.

### To reproduce

1. Install and enable the Continue.dev IntelliJ extension.
2. Attempt to trigger the autocomplete functionality.
3. Observe the deprecation warning in the logs.

### Log output

```Shell
com.intellij.diagnostic.PluginException: ActionUpdateThread.OLD_EDT is deprecated and going to be removed soon. 'com.github.continuedev.continueintellijextension.autocomplete.CancelAutocompleteAction' must override getActionUpdateThread() and chose EDT or BGT. See ActionUpdateThread javadoc. [Plugin: com.github.continuedev.continueintellijextension]
	at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:23)
	at com.intellij.diagnostic.PluginException.createByClass(PluginException.java:90)
	at com.intellij.diagnostic.PluginException.reportDeprecatedUsage(PluginException.java:125)
	at com.intellij.openapi.actionSystem.ActionUpdateThreadAware.getActionUpdateThread(ActionUpdateThreadAware.java:21)
	at com.intellij.openapi.actionSystem.AnAction.getActionUpdateThread(AnAction.java:201)
```

**Comment by chubshaun** [comment]
Just to add to this, for me this message is thrown in a bold red error message as soon as I open some repos (I don't even have Continue setup for autocomplete functionality) in Webstorm.

**Comment by sestinj** [comment]
Very good to know, thanks for the report. We'll be attempting to clean a lot of small errors like this in December and will take care to fix this

**Comment by ben-clegg** [comment]
I've upgraded today, and can confirm to new readers that this still impacts 0.0.83

**Comment by dandv** [comment]
Just saw this when opening a directory with no files.
