### ISSUE TITLE
VSC + WSL + PTYHON (VENV) JUPYTER + CONTINUE: Cant execute cells after running a few times after open a project "NO notebook document for 'file:///home/user/code/notebook.ipynb'

### ISSUE THREAD

**Issue by msjfuria** [continuedev/continue#3000]
### Before submitting your bug report

- [X] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [X] I've seen the [troubleshooting guide](https://docs.continue.dev/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS: Win11
- Continue version: v0.8.57
- IDE version: VSC 1.95.3
- Model: Claude Sonnet 3.5
- config.json:
  
{
  "models": [
    {
      "title": "Llama 3.1 8B",
      "provider": "ollama",
      "model": "llama3.1:8b"
    },
    {
      "model": "claude-3-5-sonnet-20240620",
      "provider": "anthropic",
      "apiKey": "",
      "title": "Claude 3.5 Sonnet"
    }
  ],
  "tabAutocompleteModel": {
    "title": "Codestral",
    "provider": "mistral",
    "model": "codestral-latest",
    "apiKey": ""
  },
  "customCommands": [
    {
      "name": "test",
      "prompt": "{{{ input }}}\n\nWrite a comprehensive set of unit tests for the selected code. It should setup, run tests that check for correctness including important edge cases, and teardown. Ensure that the tests are complete and sophisticated. Give the tests just as chat output, don't edit any file.",
      "description": "Write unit tests for highlighted code"
    }
  ],
  "contextProviders": [
    {
      "name": "code",
      "params": {}
    },
    {
      "name": "docs",
      "params": {}
    },
    {
      "name": "diff",
      "params": {}
    },
    {
      "name": "terminal",
      "params": {}
    },
    {
      "name": "problems",
      "params": {}
    },
    {
      "name": "folder",
      "params": {}
    },
    {
      "name": "codebase",
      "params": {}
    }
  ],
  "slashCommands": [
    {
      "name": "edit",
      "description": "Edit selected code"
    },
    {
      "name": "comment",
      "description": "Write comments for the selected code"
    },
    {
      "name": "share",
      "description": "Export the current chat session to markdown"
    },
    {
      "name": "cmd",
      "description": "Generate a shell command"
    },
    {
      "name": "commit",
      "description": "Generate a git commit message"
    }
  ],
  "experimental": {
    "modelRoles": {
      "repoMapFileSelection": "Claude 3 Haiku"
    }
  },
  "embeddingsProvider": {
    "provider": "ollama",
    "model": "nomic-embed-text"
  }
}
```

### Description

After starting to code, executing, and asking for suggestions a few times, I encountered this bug: "NO notebook document for 'file:///home'."

The cell is stuck in execution, and I can't restart or interrupt it.

Without continue-dev I never had this bug. 

Please help! This extension is awesome, I dont want to change to another one.

### To reproduce

Use the same environment: VS Code + WSL + Python (venv) + Jupyter + Continue.
Start coding and running a Jupyter notebook for 5–10 minutes.

### Log output

```Shell
ERR NO notebook document for 'file:///home/miltg14/code/scripts/oai_vectorstore_sales_sync.ipynb': Error: NO notebook document for 'file:///home/miltg14/code/scripts/oai_vectorstore_sales_sync.ipynb'
	at ah.getNotebookDocument (file:///home/miltg14/.vscode-server/bin/f1a4fb101478ce6ec82fe9627c43efbf9e98c813/out/vs/workbench/api/node/extensionHostProcess.js:155:5865)
	at Mb.$cellExecutionChanged (file:///home/miltg14/.vscode-server/bin/f1a4fb101478ce6ec82fe9627c43efbf9e98c813/out/vs/workbench/api/node/extensionHostProcess.js:155:25614)
	at py.S (file:///home/miltg14/.vscode-server/bin/f1a4fb101478ce6ec82fe9627c43efbf9e98c813/out/vs/workbench/api/node/extensionHostProcess.js:31:155639)
	at py.Q (file:///home/miltg14/.vscode-server/bin/f1a4fb101478ce6ec82fe9627c43efbf9e98c813/out/vs/workbench/api/node/extensionHostProcess.js:31:155419)
	at py.M (file:///home/miltg14/.vscode-server/bin/f1a4fb101478ce6ec82fe9627c43efbf9e98c813/out/vs/workbench/api/node/extensionHostProcess.js:31:154508)
	at py.L (file:///home/miltg14/.vscode-server/bin/f1a4fb101478ce6ec82fe9627c43efbf9e98c813/out/vs/workbench/api/node/extensionHostProcess.js:31:153613)
	at mh.value (file:///home/miltg14/.vscode-server/bin/f1a4fb101478ce6ec82fe9627c43efbf9e98c813/out/vs/workbench/api/node/extensionHostProcess.js:31:152410)
	at P.B (file:///home/miltg14/.vscode-server/bin/f1a4fb101478ce6ec82fe9627c43efbf9e98c813/out/vs/workbench/api/node/extensionHostProcess.js:29:746)
	at P.fire (file:///home/miltg14/.vscode-server/bin/f1a4fb101478ce6ec82fe9627c43efbf9e98c813/out/vs/workbench/api/node/extensionHostProcess.js:29:964)
	at Vn.fire (file:///home/miltg14/.vscode-server/bin/f1a4fb101478ce6ec82fe9627c43efbf9e98c813/out/vs/workbench/api/node/extensionHostProcess.js:31:9457)
	at mh.value (file:///home/miltg14/.vscode-server/bin/f1a4fb101478ce6ec82fe9627c43efbf9e98c813/out/vs/workbench/api/node/extensionHostProcess.js:174:13300)
	at P.B (file:///home/miltg14/.vscode-server/bin/f1a4fb101478ce6ec82fe9627c43efbf9e98c813/out/vs/workbench/api/node/extensionHostProcess.js:29:746)
	at P.fire (file:///home/miltg14/.vscode-server/bin/f1a4fb101478ce6ec82fe9627c43efbf9e98c813/out/vs/workbench/api/node/extensionHostProcess.js:29:964)
	at Vn.fire (file:///home/miltg14/.vscode-server/bin/f1a4fb101478ce6ec82fe9627c43efbf9e98c813/out/vs/workbench/api/node/extensionHostProcess.js:31:9457)
	at Fm.A (file:///home/miltg14/.vscode-server/bin/f1a4fb101478ce6ec82fe9627c43efbf9e98c813/out/vs/workbench/api/node/extensionHostProcess.js:31:12573)
	at mh.value (file:///home/miltg14/.vscode-server/bin/f1a4fb101478ce6ec82fe9627c43efbf9e98c813/out/vs/workbench/api/node/extensionHostProcess.js:31:10993)
	at P.B (file:///home/miltg14/.vscode-server/bin/f1a4fb101478ce6ec82fe9627c43efbf9e98c813/out/vs/workbench/api/node/extensionHostProcess.js:29:746)
	at P.fire (file:///home/miltg14/.vscode-server/bin/f1a4fb101478ce6ec82fe9627c43efbf9e98c813/out/vs/workbench/api/node/extensionHostProcess.js:29:964)
	at j5.acceptChunk (file:///home/miltg14/.vscode-server/bin/f1a4fb101478ce6ec82fe9627c43efbf9e98c813/out/vs/workbench/api/node/extensionHostProcess.js:31:7940)
	at mh.value (file:///home/miltg14/.vscode-server/bin/f1a4fb101478ce6ec82fe9627c43efbf9e98c813/out/vs/workbench/api/node/extensionHostProcess.js:31:7226)
	at P.B (file:///home/miltg14/.vscode-server/bin/f1a4fb101478ce6ec82fe9627c43efbf9e98c813/out/vs/workbench/api/node/extensionHostProcess.js:29:746)
	at P.fire (file:///home/miltg14/.vscode-server/bin/f1a4fb101478ce6ec82fe9627c43efbf9e98c813/out/vs/workbench/api/node/extensionHostProcess.js:29:964)
	at V2.z (file:///home/miltg14/.vscode-server/bin/f1a4fb101478ce6ec82fe9627c43efbf9e98c813/out/vs/workbench/api/node/extensionHostProcess.js:31:21944)
	at V2.acceptFrame (file:///home/miltg14/.vscode-server/bin/f1a4fb101478ce6ec82fe9627c43efbf9e98c813/out/vs/workbench/api/node/extensionHostProcess.js:31:21750)
	at W2.n (file:///home/miltg14/.vscode-server/bin/f1a4fb101478ce6ec82fe9627c43efbf9e98c813/out/vs/workbench/api/node/extensionHostProcess.js:31:20278)
	at file:///home/miltg14/.vscode-server/bin/f1a4fb101478ce6ec82fe9627c43efbf9e98c813/out/vs/workbench/api/node/extensionHostProcess.js:31:17510
	at Socket.t (file:///home/miltg14/.vscode-server/bin/f1a4fb101478ce6ec82fe9627c43efbf9e98c813/out/vs/workbench/api/node/extensionHostProcess.js:31:15451)
	at Socket.emit (node:events:519:28)
	at addChunk (node:internal/streams/readable:559:12)
	at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
	at Readable.push (node:internal/streams/readable:390:5)
	at TCP.onStreamRead (node:internal/stream_base_commons:191:23)
```

**Comment by derluke** [comment]
Another hint?

In the `Extension Host` output, I see errors such as 

```
2024-11-26 10:36:51.010 [error] RangeError: path should be a `path.relative()`d string, but got "..\..\..\..\Users\User\AppData\Local\Programs\Microsoft VS Code\extension-output-ms-toolsai.jupyter-#1-Jupyter"
	at throwError (c:\Users\User\.vscode\extensions\continue.continue-0.8.59-win32-x64\out\extension.js:71830:13)
	at checkPath (c:\Users\User\.vscode\extensions\continue.continue-0.8.59-win32-x64\out\extension.js:71844:16)
	at Ignore2._test (c:\Users\User\.vscode\extensions\continue.continue-0.8.59-win32-x64\out\extension.js:71932:9)
	at Ignore2.ignores (c:\Users\User\.vscode\extensions\continue.continue-0.8.59-win32-x64\out\extension.js:71959:21)
	at c:\Users\User\.vscode\extensions\continue.continue-0.8.59-win32-x64\out\extension.js:540954:31
```

could it be the space in the path? Or the fact it tries to go across file systems (from wsl into windows)

**Comment by derluke** [comment]
https://github.com/continuedev/continue/issues/1463#issuecomment-2500294344

**Comment by Capsar** [comment]
Do you happen to have the Ruff extension enabled too?
