### ISSUE TITLE
Windows Path Error: ENOTDIR: not a directory, scandir ~\.continue\config.json'

### ISSUE THREAD

**Issue by sschneider-ihre-pvs** [continuedev/continue#3007]
### Before submitting your bug report

- [X] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [X] I've seen the [troubleshooting guide](https://docs.continue.dev/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS: Win10
- Continue version: v0.8.57
- IDE version: vscode 1.95.3
- Model: 
- config.json:
  
{
  "models": [
    {
      "model": "llama3.1:8b",
      "provider": "ollama",
      "title": "Llama3.1:8b"
    }
  ],
  "tabAutocompleteModel": {
    "title": "Starcoder",
    "provider": "ollama",
    "model": "starcoder2:3b"
  },
  "tabAutocompleteOptions": {
    "debounceDelay": 200,
    "maxPromptTokens": 500,
    "useOtherFiles": false
  },
  "embeddingsProvider": {
    "provider": "ollama",
    "model": "nomic-embed-text"
  },
  "customCommands": [
    {
      "name": "test",
      "prompt": "{{{ input }}}\n\nWrite a comprehensive set of unit tests for the selected code. It should setup, run tests that check for correctness including important edge cases, and teardown. Ensure that the tests are complete and sophisticated. Give the tests just as chat output, don't edit any file.",
      "description": "Write unit tests for highlighted code"
    }
  ],
  "contextProviders": [
    {
      "name": "code",
      "params": {}
    },
    {
      "name": "docs",
      "params": {}
    },
    {
      "name": "diff",
      "params": {}
    },
    {
      "name": "terminal",
      "params": {}
    },
    {
      "name": "problems",
      "params": {}
    },
    {
      "name": "folder",
      "params": {}
    },
    {
      "name": "codebase",
      "params": {}
    }
  ],
  "slashCommands": [
    {
      "name": "share",
      "description": "Export the current chat session to markdown"
    },
    {
      "name": "cmd",
      "description": "Generate a shell command"
    },
    {
      "name": "commit",
      "description": "Generate a git commit message"
    }
  ]
}
```

### Description

Error resolving config.json reported in vscode devtools

### To reproduce

start vscode and type with autocomplete active

### Log output

```Shell
console.ts:137 [Extension Host] rejected promise not handled within 1 second: EntryNotADirectory (FileSystemError): Error: ENOTDIR: not a directory, scandir '$HOME\.continue\config.json'
uGi	@	console.ts:137
$logExtensionHostMessage	@	mainThreadConsole.ts:39
S	@	rpcProtocol.ts:458
Q	@	rpcProtocol.ts:443
M	@	rpcProtocol.ts:373
L	@	rpcProtocol.ts:299
(anonymous)	@	rpcProtocol.ts:161
B	@	event.ts:1243
fire	@	event.ts:1274
fire	@	ipc.net.ts:652
l.onmessage	@	localProcessExtensionHost.ts:378
console.ts:137 [Extension Host] stack trace: EntryNotADirectory (FileSystemError): Error: ENOTDIR: not a directory, scandir '$HOME\.continue\config.json'
	at Ji.e (file:///$HOME/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:114:9116)
	at Object.readDirectory (file:///$HOME/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:114:7197)
	at async DFSWalker.listDirForWalking ($HOME\.vscode\extensions\continue.continue-0.8.57-win32-x64\out\extension.js:130189:25)
	at async DFSWalker.walk ($HOME\.vscode\extensions\continue.continue-0.8.57-win32-x64\out\extension.js:130148:35)
	at async walkDirAsync ($HOME\.vscode\extensions\continue.continue-0.8.57-win32-x64\out\extension.js:130123:3)
	at async CodebaseIndexer.refresh ($HOME\.vscode\extensions\continue.continue-0.8.57-win32-x64\out\extension.js:540310:28)
	at async Core.refreshCodebaseIndex ($HOME\.vscode\extensions\continue.continue-0.8.57-win32-x64\out\extension.js:541322:26)
	at async $HOME\.vscode\extensions\continue.continue-0.8.57-win32-x64\out\extension.js:541274:11
uGi	@	console.ts:137
$logExtensionHostMessage	@	mainThreadConsole.ts:39
S	@	rpcProtocol.ts:458
Q	@	rpcProtocol.ts:443
M	@	rpcProtocol.ts:373
L	@	rpcProtocol.ts:299
(anonymous)	@	rpcProtocol.ts:161
B	@	event.ts:1243
fire	@	event.ts:1274
fire	@	ipc.net.ts:652
l.onmessage	@	localProcessExtensionHost.ts:378
mainThreadExtensionService.ts:78 [Continue.continue]Error: ENOTDIR: not a directory, scandir '$HOME\.continue\config.json'
$onExtensionRuntimeError	@	mainThreadExtensionService.ts:78
S	@	rpcProtocol.ts:458
Q	@	rpcProtocol.ts:443
M	@	rpcProtocol.ts:373
L	@	rpcProtocol.ts:299
(anonymous)	@	rpcProtocol.ts:161
B	@	event.ts:1243
fire	@	event.ts:1274
fire	@	ipc.net.ts:652
l.onmessage	@	localProcessExtensionHost.ts:378
mainThreadExtensionService.ts:79 EntryNotADirectory (FileSystemError): Error: ENOTDIR: not a directory, scandir '$HOME\.continue\config.json'
	at Ji.e (file:///$HOME/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:114:9116)
	at Object.readDirectory (file:///$HOME/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:114:7197)
	at async DFSWalker.listDirForWalking ($HOME\.vscode\extensions\continue.continue-0.8.57-win32-x64\out\extension.js:130189:25)
	at async DFSWalker.walk ($HOME\.vscode\extensions\continue.continue-0.8.57-win32-x64\out\extension.js:130148:35)
	at async walkDirAsync ($HOME\.vscode\extensions\continue.continue-0.8.57-win32-x64\out\extension.js:130123:3)
	at async CodebaseIndexer.refresh ($HOME\.vscode\extensions\continue.continue-0.8.57-win32-x64\out\extension.js:540310:28)
	at async Core.refreshCodebaseIndex ($HOME\.vscode\extensions\continue.continue-0.8.57-win32-x64\out\extension.js:541322:26)
	at async $HOME\.vscode\extensions\continue.continue-0.8.57-win32-x64\out\extension.js:541274:11
$onExtensionRuntimeError	@	mainThreadExtensionService.ts:79
S	@	rpcProtocol.ts:458
Q	@	rpcProtocol.ts:443
M	@	rpcProtocol.ts:373
L	@	rpcProtocol.ts:299
(anonymous)	@	rpcProtocol.ts:161
B	@	event.ts:1243
fire	@	event.ts:1274
fire	@	ipc.net.ts:652
l.onmessage	@	localProcessExtensionHost.ts:378


mainThreadExtensionService.ts:78 [Continue.continue]path should be a `path.relative()`d string, but got "..\..\.continue\config.json"
$onExtensionRuntimeError	@	mainThreadExtensionService.ts:78
S	@	rpcProtocol.ts:458
Q	@	rpcProtocol.ts:443
M	@	rpcProtocol.ts:373
L	@	rpcProtocol.ts:299
(anonymous)	@	rpcProtocol.ts:161
B	@	event.ts:1243
fire	@	event.ts:1274
fire	@	ipc.net.ts:652
l.onmessage	@	localProcessExtensionHost.ts:378
mainThreadExtensionService.ts:79 RangeError: path should be a `path.relative()`d string, but got "..\..\.continue\config.json"
	at throwError ($HOME\…tension.js:71775:13)
	at checkPath ($HOME\…tension.js:71789:16)
	at Ignore2._test ($HOME\…xtension.js:71877:9)
	at Ignore2.ignores ($HOME\…tension.js:71904:21)
	at $HOME\…ension.js:541300:31
```
```

**Comment by mikeparisstuff** [comment]
I'm also seeing this error. In my case it was first:

```
EntryNotADirectory (FileSystemError): Error: ENOTDIR: not a directory, scandir '<homedir>/.continue/config.json'
```

Then I ran `xattr -c ~/.continue/config.json` after some GPT'ing because 🤷‍♂️. Then I got:

```
Error: ENOTDIR: not a directory, scandir '<homedir>/Library/Application Support/Code/User/settings.json
```

Then I googled. Now, I'm here. Let me know if you need more details.

**Comment by mikeparisstuff** [comment]
I was able to fix the issue by rolling back the version by a ~month. Version `v0.8.54` is working.

**Comment by Patrick-Erichsen** [comment]
Good to know, should be straightforward to bisect from that version.

**Comment by RomneyDa** [comment]
@sschneider-ihre-pvs still seeing this?

**Comment by sschneider-ihre-pvs** [comment]
error is gone. but I do not get autocomplete suggestions :D
