### ISSUE TITLE
Extension is not activating(Visual Studio Code) 

### ISSUE THREAD

**Issue by MaheshBhushan** [continuedev/continue#3009]
### Before submitting your bug report

- [X] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [X] I've seen the [troubleshooting guide](https://docs.continue.dev/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS: Windows 11
- Continue version:v0.8.57
- IDE version: VSCode 1.95.3
```

### Description

now you will get an notification "Error activating the Continue extension"
I have tried all the methods to check if my other extensions are conflicting with the activation of this extension, but i am still getting the same error. Below is the error that is showing up.

![image](https://github.com/user-attachments/assets/d44c0579-8de0-44f5-ae10-f072963e9cfe)

### To reproduce

-> Go to Visual Studio Code.
-> Open Extensions Section.
-> Install the extension "Continue-Codeastral, Claude, and more".
-> Try opening the extension.

### Log output

```Shell
2024-11-20 21:54:01.212 [info] Extension host with pid 7500 started
2024-11-20 21:54:01.330 [info] ExtensionService#_doActivateExtension vscode.git-base, startup: true, activationEvent: '*', root cause: vscode.git
2024-11-20 21:54:01.343 [info] ExtensionService#_doActivateExtension vscode.emmet, startup: false, activationEvent: 'onLanguage'
2024-11-20 21:54:01.437 [info] ExtensionService#_doActivateExtension vscode.git, startup: true, activationEvent: '*'
2024-11-20 21:54:01.655 [info] ExtensionService#_doActivateExtension vscode.github, startup: true, activationEvent: '*'
2024-11-20 21:54:01.895 [info] Eager extensions activated
2024-11-20 21:54:01.918 [info] ExtensionService#_doActivateExtension vscode.debug-auto-launch, startup: false, activationEvent: 'onStartupFinished'
2024-11-20 21:54:01.928 [info] ExtensionService#_doActivateExtension vscode.merge-conflict, startup: false, activationEvent: 'onStartupFinished'
2024-11-20 21:54:01.965 [info] ExtensionService#_doActivateExtension ecmel.vscode-html-css, startup: false, activationEvent: 'onStartupFinished'
2024-11-20 21:54:32.013 [info] ExtensionService#_doActivateExtension Continue.continue, startup: false, activationEvent: 'onStartupFinished'
2024-11-20 21:54:44.493 [error] Error: command 'continue.viewLogs' not found
    at mWe.n (vscode-file://vscode-app/c:/Users/dell/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1295:1341)
    at mWe.executeCommand (vscode-file://vscode-app/c:/Users/dell/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1295:1273)
2024-11-20 21:55:37.146 [info] Extension host terminating: renderer closed the MessagePort
2024-11-20 21:55:37.155 [info] Extension host with pid 7500 exiting with code 0
2024-11-20 21:55:37.799 [info] Extension host with pid 7524 started
2024-11-20 21:55:37.809 [info] ExtensionService#_doActivateExtension vscode.emmet, startup: false, activationEvent: 'onLanguage'
2024-11-20 21:55:37.829 [info] ExtensionService#_doActivateExtension vscode.git-base, startup: false, activationEvent: '*', root cause: vscode.git
2024-11-20 21:55:37.848 [info] ExtensionService#_doActivateExtension vscode.git, startup: false, activationEvent: '*'
2024-11-20 21:55:37.908 [info] ExtensionService#_doActivateExtension vscode.github, startup: false, activationEvent: '*'
2024-11-20 21:55:38.012 [info] Eager extensions activated
2024-11-20 21:55:38.020 [info] ExtensionService#_doActivateExtension vscode.debug-auto-launch, startup: false, activationEvent: 'onStartupFinished'
2024-11-20 21:55:38.024 [info] ExtensionService#_doActivateExtension vscode.merge-conflict, startup: false, activationEvent: 'onStartupFinished'
2024-11-20 21:55:40.391 [info] ExtensionService#_doActivateExtension Continue.continue, startup: false, activationEvent: 'onStartupFinished'
2024-11-20 21:56:26.023 [info] ExtensionService#_doActivateExtension vscode.github-authentication, startup: false, activationEvent: 'onAuthenticationRequest:github'
```

**Comment by RomneyDa** [comment]
note, I had this error as well and fixed on this branch by adding the viewlogs command back to package.json
https://github.com/continuedev/continue/pull/2978/files#diff-288f1ebddf6afc6081e2ca910029e86e55c9cd7871b425c2a97a82a2cd77ac9e

**Comment by MaheshBhushan** [comment]
> note, I had this error as well and fixed on this branch by adding the viewlogs command back to package.json https://github.com/continuedev/continue/pull/2978/files#diff-288f1ebddf6afc6081e2ca910029e86e55c9cd7871b425c2a97a82a2cd77ac9e



Thank you for sharing the fix and pointing me to the branch! I tried adding the viewlogs command back to package.json as suggested and also done the other changes committed, but unfortunately, I'm still encountering the same error. Do you have any additional suggestions or insights on what else might be causing this? I’d greatly appreciate your help!

**Comment by Patrick-Erichsen** [comment]
Have you tried removing the project and recloning? A bit of a blunt approach but that would be a good way to guarantee you're starting from scratch;

**Comment by MatsPro** [comment]
I had the same issue yesterday. In my case it was a simple solution. Due to work restrictions I always have to manually download the .vsix install file to update. Since I usually work on Windows I downloaded the windows version. However, this time I had to install on a Red Hat Enterprise Linux machine.

At first I tried to install the Windows vsix on the linux machine which triggered the same error like yours. This morning I discovered my error and downloaded the linux version. Works flawless without the error now, so you might take a look at your vsix versions.

**Comment by labsnoir** [comment]
I got the same error message. In my case the OS is Windows 11 running on ARM (Snapdragon X). Wonder if this could be a cause for the error...

**Comment by kiolygenius** [comment]
I've got same error. 
My environment: 
OS:  Arch Linux x86_64,
VSCode Package:  visual-studio-code-bin

Neither installing from ms market nor installing from vsix amd64 version do work.
Version 0.9-pre failed either.

**Comment by SpontaneousDuck** [comment]
Current error I am getting on Windows 11 running on ARM (Snapdragon X):

`[Extension Host] Error activating extension:  Error: \\?\c:\Users\k.witham\.vscode\extensions\continue.continue-0.8.66-win32-arm64\out\build\Release\node_sqlite3.node is not a valid Win32 application.`

**Comment by MarcoWel** [comment]
Same here (x86_64 under Windows with newest VS Code 1.96.3)

**Comment by Patrick-Erichsen** [comment]
@MarcoWel are there any logs you can also share? https://docs.continue.dev/troubleshooting#check-the-logs

**Comment by kiolygenius** [comment]
> @MarcoWel are there any logs you can also share? https://docs.continue.dev/troubleshooting#check-the-logs 是否有任何日志可以共享？https://docs.continue.dev/troubleshooting#check-the-logs
> 
> I think there are likely two separate issues for folks running into this more recently:我认为最近遇到这种情况的人可能有两个不同的问题：
> 
>     * @kiolygenius:  [fix: disable indexing for unsupported CPUs #3551](https://github.com/continuedev/continue/pull/3551)
> 
>     * @SpontaneousDuck : ["node_sqlite3.node is not a valid Win32 application" on Windows on ARM64 #839](https://github.com/continuedev/continue/issues/839)

Not likely. My CPU is Intel i7-12700 that supports FMA and AVX2.

**Comment by Patrick-Erichsen** [comment]
cc @RomneyDa here - there appears to be some URI issues here:

- `ERR Unable to resolve nonexistent file 'vscode-userdata:/c:/Users/mw/AppData/Roaming/Code/User/globalStorage/continue.continue': Error: Unable to resolve nonexistent file 'vscode-userdata:/c:/Users/mw/AppData/Roaming/Code/User/globalStorage/continue.continue'`
- `[Extension Host] Error activating extension:  Error: \\?\c:\Users\k.witham\.vscode\extensions\continue.continue-0.8.66-win32-arm64\out\build\Release\node_sqlite3.node is not a valid Win32 application.`

I believe we have fixes for these merged/in-progress but worth mentioning here.

**Comment by MarcoWel** [comment]
Got it working again - seems the Continue extension needs executable rights in the path `C:\Users\<username>\.vscode\extensions\continue.continue-0.9.251-win32-x64\out\build\Release\`, otherwise loading the extension fails.

This was blocked on our machines by GPO. For other extensions this is not necessary (it was probably not necessary for older revisions of the Continue extensions either, as we changed nothing on the configuration before it stopped working).

**Comment by digiperfect-tech** [comment]
Facing this issue on ubuntu/linux. Seems it appeared with a recent update?

**Comment by Patrick-Erichsen** [comment]
@digiperfect-tech any additional logs you can share? 

@MarcoWel I don't believe we modified any permissions on the binary. That is odd that you had to manually do so. Haven't seen other reports of that so far at least.

**Comment by shanselman** [comment]
Hitting this also on Windows 11 ARM64, worked fine a month ago

**Comment by shanselman** [comment]
@Patrick-Erichsen that script above fixes the issue on Windows 11 ARM64...definitely a long standing issue here

**Comment by Patrick-Erichsen** [comment]
@shanselman looks like LanceDB has support for windows arm64 now! https://github.com/lancedb/lancedb/issues/1841

Planning to pull that in soon here.

**Comment by extrange** [comment]
Still happening on NixOS:

```
 - system: `"x86_64-linux"`
 - host os: `Linux 6.13.0, NixOS, 25.05 (Warbler), 25.05.20250201.3a22805`
 - multi-user?: `no`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.24.12`
 - nixpkgs: `/nix/store/hjb1rqv2mfs5ny47amj2gsc8xk05x5g6-source`
```

```
Version: 1.96.4
Commit: cd4ee3b1c348a13bafd8f9ad8060705f6d4b9cba
Date: 2025-01-16T00:16:19.038Z
Electron: 32.2.6
ElectronBuildId: 10629634
Chromium: 128.0.6613.186
Node.js: 20.18.1
V8: 12.8.374.38-electron.0
OS: Linux x64 6.13.0
```

**Comment by Patrick-Erichsen** [comment]
@extrange your issue might be related to unsupported CPU features on Linux x64, see here: https://github.com/continuedev/continue/pull/3883

**Comment by extrange** [comment]
@Patrick-Erichsen Actually, I've found and fixed the issue by switching from `pkgs.vscode` to `pkgs.vscode.fhsWithPackages` as shown [here](https://github.com/extrange/nixos-config/commit/d6bf48d46a97201ebf7e69b6707f352e43080963). On debugging the extension the error was about `libstdc++` or similar missing, which is a known issue on Nix for extensions with bundled libraries

**Comment by acquahackman** [comment]
> OS environments:
> 
> 1. Ubuntu
> 2. MacOS
>    Continue file: **continue-0.9.268.vsix**
> 
> Error message: **Error activating the Continue extension**
> 
> I also have similar issue. first executed the script `scripts/install-dependencies.sh`. then obtained the `.vsix` file. installed the extension via vsix file. on both systems I got the same error

Ok here is what I was doing wrong. Building the **.vsix** on the wrong platform. i rebuild it and set the **--target darwin-arm64** for macOS.

**Comment by burgesswon** [comment]
Hi sir
Seems like the problem's still not be solved.
Any update?

**Comment by burgesswon** [comment]
Oh after I cleaned the vscode cache the problem was fixed.
Just deleted C:\Users\<Username>\AppData\Roaming\Code on Windows

**Comment by acquahackman** [comment]
@burgesswon , could you describe your platform environment and target computer for your .vsix file?

**Comment by Nezteb** [comment]
On latest VS Code Insiders + Pre-Release of the Continue extension, I have this same issue.

Continue extension: 1.1.3
VS Code: 1.98.0-insider
OS: macOS 15.3

I've tried reinstalling a couple times.

**Comment by bbartels** [comment]
> Got it working again - seems the Continue extension needs executable rights in the path `C:\Users\<username>\.vscode\extensions\continue.continue-0.9.251-win32-x64\out\build\Release\`, otherwise loading the extension fails.
> 
> This was blocked on our machines by GPO. For other extensions this is not necessary (it was probably not necessary for older revisions of the Continue extensions either, as we changed nothing on the configuration before it stopped working).

@Patrick-Erichsen 

We are running into the same issue, we have some strict permissioning on our workstations and it is unfortunately blocking continue.dev from being activated.

**Comment by Patrick-Erichsen** [comment]
@bbartels does disabling indexing work for you?

<img width="349" alt="Image" src="https://github.com/user-attachments/assets/b09dd357-4b59-4fac-ba20-7ea924bfa0ac" />

**Comment by bbartels** [comment]
I am unfortunately unable to get to that point even, as at that point the `openConfigPage` command is not set up yet.

![Image](https://github.com/user-attachments/assets/0d208822-0c9a-4670-bee5-e9c6c00cf108)

**Comment by Patrick-Erichsen** [comment]
@bbartels got it, that makes sense. I'm not certain if that would have worked anyways to be honest.

> EDIT: After trying various versions, looks like this additional perm requirements arise starting in 0.8.2

I am relatively certain we were shipping `sqlite_node.node` prior to 0.8.2 - perhaps the solution here is just updating the permissions on the binary?

**Comment by bbartels** [comment]
> [@bbartels](https://github.com/bbartels) got it, that makes sense. I'm not certain if that would have worked anyways to be honest.
> 
> > EDIT: After trying various versions, looks like this additional perm requirements arise starting in 0.8.2
> 
> I am relatively certain we were shipping `sqlite_node.node` prior to 0.8.2 - perhaps the solution here is just updating the permissions on the binary?

Unfortunately, due to the companies stance on security it may not be possible to make changes to the binary permissions.

**Comment by henryfung3a27** [comment]
I found something. Continue does not load when VSCode is using certain themes (`workbench.colorTheme`) in the User `settings.json` (by the command `workbench.action.openSettingsJson`).

These would load:
```
"workbench.colorTheme": "Default Dark+"
"workbench.colorTheme": "Andromeda"
"workbench.colorTheme": "Andromeda Bordered"
"workbench.colorTheme": "Andromeda Italic"
"workbench.colorTheme": "Monokai"
"workbench.colorTheme": "Monokai Dark Soda"
"workbench.colorTheme": "Monokai Dimmed"
"workbench.colorTheme": "One Dark Monokai"
```

This would not load:
```
"workbench.colorTheme": "Andromeda Colorizer"
```

I have tried several themes and only one of them makes Continue fail to load, which is the one I am using. Not sure why. 

Continue v1.0.3 (2025-03-11)
VSCode v1.98.2 (2025-03-12)
Windows 11 x64
Andromeda theme v1.8.2

**Comment by Patrick-Erichsen** [comment]
Interesting - I'll add this to my mental checklist of random extension categories that could interfere with Continue 😅 

I would definitely recommend using the [extension bisect](https://code.visualstudio.com/blogs/2021/02/16/extension-bisect) feature in VS Code in the future if you ever want to narrow things like this down

**Comment by donaldrowens** [comment]
> [@henryfung3a27](https://github.com/henryfung3a27) Wow. I kid you not, I am using the exact same color theme: https://marketplace.visualstudio.com/items?itemName=EliverLara.andromeda
> 
> I've uninstalled the color theme and now the extension works as expected.
> 
> This same color theme was apparently also breaking my GitLab integration, which has been broken for a while...
> 
> I am baffled at how a color scheme could cause this. 🤔

I've been having this issue for a bit and finally decided to look into it. I am also running the same color theme. Very interesting.

**Comment by stomir** [comment]
I am having this issue, on Windows, using VSCodium, not using any theme addons (using default dark modern).

**Comment by jumpmanjay** [comment]
Also having this issue using code-server (that is using code 1.95.1) on a CentOS7 server connecting from a windows browser.

**Comment by jumpmanjay** [comment]
> Also having this issue using code-server (that is using code 1.95.1) on a CentOS7 server connecting from a windows browser.

It works on a CentOS8 server, however.

**Comment by dvacnt** [comment]
I also have the error command 'continue.viewLogs not found.
As the bug was opened 7 months earlier and isn't always solved, is this plug in is a joke?
I go back to cursor, at least it works !

**Comment by SteelPh0enix** [comment]
I also have the same issue - it's also caused by Andromeda Colorized theme!
Any ETA on fix?

**Comment by Patrick-Erichsen** [comment]
@uinstinct - this might be a good one to pick up!

**Comment by uinstinct** [comment]
Hey @SteelPh0enix, can you tell me which version of continue you are on and which os platform & cpu architecture you are using?

**Comment by SteelPh0enix** [comment]
> Hey [@SteelPh0enix](https://github.com/SteelPh0enix), can you tell me which version of continue you are on and which os platform & cpu architecture you are using?

Sure @uinstinct - here's my VSCode info:
```
Version: 1.101.2
Commit: 2901c5ac6db8a986a5666c3af51ff804d05af0d4
Date: 2025-06-24T20:27:15.391Z
Electron: 35.5.1
ElectronBuildId: 11727614
Chromium: 134.0.6998.205
Node.js: 22.15.1
V8: 13.4.114.21-electron.0
OS: Linux x64 6.15.5-arch1-1
```

I'm running latest Arch Linux (via EndeavourOS distribution), my CPU is Ryzen 9 5900X. My Continue.dev version is 1.0.15

Additionally, i've just checked if the issue still persist - it does, BUT it's a problem only if i start VSCode with Andromeda Colorized theme enabled. If i configure VSCode to use different theme, start it, let all plugins load, and THEN change the theme everything seems to works correctly.

**Comment by SteelPh0enix** [comment]
@uinstinct the issue seems to be happening again, this time on Continue version 1.1.67 (i'm running on pre-release currently)

```
Version: 1.102.2
Commit: c306e94f98122556ca081f527b466015e1bc37b0
Date: 2025-07-22T12:15:48.520Z
Electron: 35.6.0
ElectronBuildId: 11847422
Chromium: 134.0.6998.205
Node.js: 22.15.1
V8: 13.4.114.21-electron.0
OS: Linux x64 6.15.8-arch1-1
```

**Comment by passivedragon** [comment]
Issue persists on linux (NixOS) with version 1.1.80, default dark color theme
has been this way for many months, it definitely isn't a windows specific bug

**Comment by amozeo** [comment]
hey there, I stumbled upon this bug when trying to install this extension from the marketplace
I use NixOS. I just tried to install extension from `"${vscode-extensions.continue.continue}/share/vscode/extensions/Continue.continue` path using "Developer: Install extension from location" code action, and it worked. (replacing the attrpath inside `${}` with nix store path)

This feels like a dirty way, ideally you should wrap the vscode/vscodium package so it adds the extension automatically with `vscode-with-extensions`, however it doesn't fit in how I use vscode (impurely).

I hope that helps other users that use NixOS!

<details><summary>nix-info</summary>
<p>

 - system: `"x86_64-linux"`
 - host os: `Linux 6.16.1, NixOS, 25.05 (Warbler), 25.05.git.9cb344e96d5b`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.28.4`
 - nixpkgs: `/nix/store/2nd42hrfpcy3wc175jl0rhgw78gna8wx-nixpkgs-self`

</p>
</details>

**Comment by yumesha** [comment]
@amozeo I can't find the continue in nix store path.

when I try to use `Developer: Install extension from location` it just open a folder location not related to continue.

if it possible can you share me your configure?

**Comment by amozeo** [comment]
> when I try to use `Developer: Install extension from location` it just open a folder location not related to continue.

you select a continue extension folder there

for example, `nix-build "<nixpkgs>" -A vscode-extensions.continue.continue` outputs nix store path after build, you use that directory appended with `/share/vscode/extensions/Continue.continue`

**Comment by yumesha** [comment]
> > when I try to use `Developer: Install extension from location` it just open a folder location not related to continue.
> 
> you select a continue extension folder there
> 
> for example, `nix-build "<nixpkgs>" -A vscode-extensions.continue.continue` outputs nix store path after build, you use that directory appended with `/share/vscode/extensions/Continue.continue`

I have copy the file list of the `nix-build "<nixpkgs>" -A vscode-extensions.continue.continue` to `/share/vscode/extensions/Continue.continue`

I get new error

command 'continue.focusContinueInput' not found
