### ISSUE TITLE
Is it possible to customize the link for OpenAPI?

### ISSUE THREAD

**Issue by aston314** [continuedev/continue#302]
Thanks.

**Comment by lstep** [comment]
https://github.com/continuedev/ggml-server-example

**Comment by TyDunn** [comment]
@aston314 can you tell me more about what you mean by "Is it possible to customize the link for OpenAPI"?

You can use different OpenAI models, different models from other providers, self-host your own, or use ggml like @lstep mentioned. More information here: https://continue.dev/docs/customization#change-the-default-llm

You can also configure the settings for the OpenAI models and use our SDK to use different models when and where you want. If you share more on what you to do, we can give specific instructions on how to accomplish it

**Comment by aston314** [comment]
Custom https://api.openai.com/ url.

**Comment by sestinj** [comment]
I see! We previously only allowed usage of the Azure OpenAI service, but I've just made a commit and updated the extension to allow changing the base_url only, assuming this is what you mean. See changes here: https://github.com/continuedev/continue/commit/cb0c815ad799050ecc0abdf3d15981e9832b9829

The docs are updated at https://continue.dev/docs/customization#azure-openai-service

Basically, you'll want to go to the config file, and can leave `default_model` as "gpt4", but then want to add:
```
openai_server_info=OpenAIServerInfo(
    base_url="<YOUR_BASE_URL>"
)
```

to the config object

**Comment by aston314** [comment]
Wait for publishing the new version.

**Comment by sestinj** [comment]
A new version is published (v0.0.222) with these changes. Let me know if you have any more questions about this, I'm actually quite interested in the use case (we might be able to replace many of our other LLM classes with the OpenAI Python SDK by only changing the base_url). I'm closing this issue but can re-open if needed

**Comment by aston314** [comment]
Traceback (most recent call last):

  File "/Users/aston/.continue/server/env/lib/python3.11/site-packages/continuedev/core/sdk.py", line 163, in create
    config = sdk._load_config_dot_py()
             ^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/Users/aston/.continue/server/env/lib/python3.11/site-packages/continuedev/core/sdk.py", line 277, in _load_config_dot_py
    spec.loader.exec_module(config)

  File "<frozen importlib._bootstrap_external>", line 940, in exec_module

  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed

  File "/Users/aston/.continue/config.py", line 40, in <module>
    openai_server_info=OpenAIServerInfo(
                       ^^^^^^^^^^^^^^^^

NameError: name 'OpenAIServerInfo' is not defined

**Comment by aston314** [comment]
Can u fix this?

**Comment by sestinj** [comment]
Yup, you'll have to import the `OpenAIServerInfo` class at the top of your config file: 

```python
from continuedev.core.config import OpenAIServerInfo
```

**Comment by aston314** [comment]
Traceback (most recent call last):

  File "/Users/aston/.continue/server/env/lib/python3.11/site-packages/aiohttp/connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/base_events.py", line 1112, in create_connection
    transport, protocol = await self._create_connection_transport(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/base_events.py", line 1145, in _create_connection_transport
    await waiter

  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/futures.py", line 287, in __await__
    yield self  # This tells Task to wait for completion.
    ^^^^^^^^^^

  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/tasks.py", line 339, in __wakeup
    future.result()

  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/futures.py", line 203, in result
    raise self._exception.with_traceback(self._exception_tb)

  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/sslproto.py", line 575, in _on_handshake_complete
    raise handshake_exc

  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/sslproto.py", line 557, in _do_handshake
    self._sslobj.do_handshake()

  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/ssl.py", line 979, in do_handshake
    self._sslobj.do_handshake()

ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1002)


The above exception was the direct cause of the following exception:


Traceback (most recent call last):

  File "/Users/aston/.continue/server/env/lib/python3.11/site-packages/openai/api_requestor.py", line 668, in arequest_raw
    result = await session.request(**request_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/Users/aston/.continue/server/env/lib/python3.11/site-packages/aiohttp/client.py", line 536, in _request
    conn = await self._connector.connect(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/Users/aston/.continue/server/env/lib/python3.11/site-packages/aiohttp/connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/Users/aston/.continue/server/env/lib/python3.11/site-packages/aiohttp/connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/Users/aston/.continue/server/env/lib/python3.11/site-packages/aiohttp/connector.py", line 1209, in _create_direct_connection
    raise last_exc

  File "/Users/aston/.continue/server/env/lib/python3.11/site-packages/aiohttp/connector.py", line 1178, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/Users/aston/.continue/server/env/lib/python3.11/site-packages/aiohttp/connector.py", line 982, in _wrap_create_connection
    raise ClientConnectorCertificateError(req.connection_key, exc) from exc

aiohttp.client_exceptions.ClientConnectorCertificateError: Cannot connect to host api.openai.com:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1002)')]


The above exception was the direct cause of the following exception:


Traceback (most recent call last):

  File "/Users/aston/.continue/server/env/lib/python3.11/site-packages/continuedev/core/autopilot.py", line 245, in _run_singular_step
    observation = await step(self.continue_sdk)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/Users/aston/.continue/server/env/lib/python3.11/site-packages/continuedev/core/main.py", line 320, in __call__
    return await self.run(sdk)
           ^^^^^^^^^^^^^^^^^^^

  File "/Users/aston/.continue/server/env/lib/python3.11/site-packages/continuedev/plugins/steps/chat.py", line 34, in run
    async for chunk in generator:

  File "/Users/aston/.continue/server/env/lib/python3.11/site-packages/continuedev/libs/llm/openai.py", line 89, in stream_chat
    async for chunk in await openai.ChatCompletion.acreate(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/Users/aston/.continue/server/env/lib/python3.11/site-packages/openai/api_resources/chat_completion.py", line 45, in acreate
    return await super().acreate(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/Users/aston/.continue/server/env/lib/python3.11/site-packages/openai/api_resources/abstract/engine_api_resource.py", line 217, in acreate
    response, _, api_key = await requestor.arequest(
                           ^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/Users/aston/.continue/server/env/lib/python3.11/site-packages/openai/api_requestor.py", line 372, in arequest
    result = await self.arequest_raw(
             ^^^^^^^^^^^^^^^^^^^^^^^^

  File "/Users/aston/.continue/server/env/lib/python3.11/site-packages/openai/api_requestor.py", line 685, in arequest_raw
    raise error.APIConnectionError("Error communicating with OpenAI") from e

openai.error.APIConnectionError: Error communicating with OpenAI

**Comment by aston314** [comment]
openai_server_info=OpenAIServerInfo(
    base_url="https://ai.fakeopen.com"
    ),

default_model="gpt-3.5-turbo",

apikey:pk-this-is-a-real-free-pool-token-for-everyone

Please test it.

**Comment by aston314** [comment]
not work,just connect to :
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host api.openai.com:443 ssl:default [None]

I have set the base_url.
