### ISSUE TITLE
Doesn't seem to generate any responses

### ISSUE THREAD

**Issue by sammcj** [continuedev/continue#303]
1. Install the extension 
2. Highlight code
3. Ask "what does this do"
4. Wait some time
5. Either nothing happens, or sometimes you may get an error (see below)

I occasionally see:

```
('IDE Protocol _receive_json timed out after 20 seconds', 'visibleFiles')
```

- Latest stable VSCode (1.80.1)
- Latest stable macOS (13.5)
- Latest Continue version ([unreleased] Published 5/28/2023, 06:17:59)

Traceback:

```
Traceback (most recent call last):

  File "/Users/samm/.pyenv/versions/3.11.3/lib/python3.11/asyncio/tasks.py", line 490, in wait_for
    return fut.result()
           ^^^^^^^^^^^^

  File "/Users/samm/.pyenv/versions/3.11.3/lib/python3.11/asyncio/futures.py", line 198, in result
    raise exc

  File "/Users/samm/.pyenv/versions/3.11.3/lib/python3.11/asyncio/tasks.py", line 269, in __step
    result = coro.throw(exc)
             ^^^^^^^^^^^^^^^

  File "/Users/samm/.continue/server/env/lib/python3.11/site-packages/continuedev/libs/util/queue.py", line 17, in get
    return await self.queues[message_type].get()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/Users/samm/.pyenv/versions/3.11.3/lib/python3.11/asyncio/queues.py", line 158, in get
    await getter

  File "/Users/samm/.pyenv/versions/3.11.3/lib/python3.11/asyncio/futures.py", line 287, in __await__
    yield self  # This tells Task to wait for completion.
    ^^^^^^^^^^

  File "/Users/samm/.pyenv/versions/3.11.3/lib/python3.11/asyncio/tasks.py", line 339, in __wakeup
    future.result()

  File "/Users/samm/.pyenv/versions/3.11.3/lib/python3.11/asyncio/futures.py", line 198, in result
    raise exc

asyncio.exceptions.CancelledError


The above exception was the direct cause of the following exception:


Traceback (most recent call last):

  File "/Users/samm/.continue/server/env/lib/python3.11/site-packages/continuedev/server/ide.py", line 166, in _receive_json
    return await asyncio.wait_for(self.sub_queue.get(message_type), timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/Users/samm/.pyenv/versions/3.11.3/lib/python3.11/asyncio/tasks.py", line 492, in wait_for
    raise exceptions.TimeoutError() from exc

TimeoutError


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "/Users/samm/.continue/server/env/lib/python3.11/site-packages/continuedev/core/autopilot.py", line 244, in _run_singular_step
    observation = await step(self.continue_sdk)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/Users/samm/.continue/server/env/lib/python3.11/site-packages/continuedev/core/main.py", line 320, in __call__
    return await self.run(sdk)
           ^^^^^^^^^^^^^^^^^^^

  File "/Users/samm/.continue/server/env/lib/python3.11/site-packages/continuedev/core/main.py", line 341, in run
    observation = await sdk.run_step(step)
                  ^^^^^^^^^^^^^^^^^^^^^^^^

  File "/Users/samm/.continue/server/env/lib/python3.11/site-packages/continuedev/core/sdk.py", line 203, in run_step
    return await self.__autopilot._run_singular_step(step)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/Users/samm/.continue/server/env/lib/python3.11/site-packages/continuedev/core/autopilot.py", line 306, in _run_singular_step
    await self.update_subscribers()

  File "/Users/samm/.continue/server/env/lib/python3.11/site-packages/continuedev/core/autopilot.py", line 129, in update_subscribers
    full_state = await self.get_full_state()
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/Users/samm/.continue/server/env/lib/python3.11/site-packages/continuedev/core/autopilot.py", line 101, in get_full_state
    selected_context_items=await self.context_manager.get_selected_items()
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/Users/samm/.continue/server/env/lib/python3.11/site-packages/continuedev/core/context.py", line 122, in get_selected_items
    return sum([await provider.get_selected_items() for provider in self.context_providers.values()], [])
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/Users/samm/.continue/server/env/lib/python3.11/site-packages/continuedev/core/context.py", line 122, in <listcomp>
    return sum([await provider.get_selected_items() for provider in self.context_providers.values()], [])
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/Users/samm/.continue/server/env/lib/python3.11/site-packages/continuedev/plugins/context_providers/highlighted_code.py", line 55, in get_selected_items
    if len(items) == 0 and (fallback_item := await self._get_fallback_context_item()):
                                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/Users/samm/.continue/server/env/lib/python3.11/site-packages/continuedev/plugins/context_providers/highlighted_code.py", line 37, in _get_fallback_context_item
    visible_files = await self.ide.getVisibleFiles()
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/Users/samm/.continue/server/env/lib/python3.11/site-packages/continuedev/server/ide.py", line 334, in getVisibleFiles
    resp = await self._send_and_receive_json({}, VisibleFilesResponse, "visibleFiles")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/Users/samm/.continue/server/env/lib/python3.11/site-packages/continuedev/server/ide.py", line 173, in _send_and_receive_json
    resp = await self._receive_json(message_type)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/Users/samm/.continue/server/env/lib/python3.11/site-packages/continuedev/server/ide.py", line 168, in _receive_json
    raise Exception(

Exception: ('IDE Protocol _receive_json timed out after 20 seconds', 'visibleFiles')
```

**Comment by sestinj** [comment]
Hi @sammcj . I have reason to believe this issue is solved, as we have fixed a problem with `_get_fallback_context_item`, and have no longer been able to reproduce the bug. Let me know when you have the chance to give it another try and, importantly, you can now view all of the server logs in `~/.continue/continue.log`, so if a problem arises again, this information will help us much more quickly address it. Thanks!

**Comment by sestinj** [comment]
@sammcj this has since been fixed as far as I was able to reproduce it, but I'd like to also be sure that things are working well for you. Let me know, and then I'll close the issue or fix whatever else comes up. Thanks!

**Comment by sammcj** [comment]
Yes that seems to have fixed it!

thanks for the quick response.
