### ISSUE TITLE
Chat Takes Too Long when Gathering Context

### ISSUE THREAD

**Issue by danialcheung** [continuedev/continue#3036]
### Before submitting your bug report

- [X] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [X] I've seen the [troubleshooting guide](https://docs.continue.dev/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS: Windows 10
- Continue version: v0.8.57
- IDE version: VSCode 1.95.3
- Model: Qwen 2.5 Coder Instruct
- config.json:
  
{
  "models": [
    {
      "title": "OpenAI-compatible server / API",
      "provider": "openai",
      "model": "qwen2.5-coder-instruct",
      "apiKey": "sk-xxxxxxxxx",
      "apiBase": "http://xxxxxxx:xxxx/v1",
      "contextLength": 8192
    }
  ],
 "embeddingsProvider": {
     "provider": "transformers.js"
  },
  "customCommands": [
    {
      "name": "test",
      "prompt": "{{{ input }}}\n\nWrite a comprehensive set of unit tests for the selected code. It should setup, run tests that check for correctness including important edge cases, and teardown. Ensure that the tests are complete and sophisticated. Give the tests just as chat output, don't edit any file.",
      "description": "Write unit tests for highlighted code"
    }
  ],
  "contextProviders": [
    {
      "name": "code",
      "params": {}
    },
    {
      "name": "docs",
      "params": {}
    },
    {
      "name": "diff",
      "params": {}
    },
    {
      "name": "terminal",
      "params": {}
    },
    {
      "name": "problems",
      "params": {}
    },
    {
      "name": "folder",
      "params": {}
    },
    {
      "name": "codebase",
      "params": {
        "nRetrieve": 20,
        "nFinal": 10,
        "useReranking": true
      }
    }
  ],
  "slashCommands": [
    {
      "name": "edit",
      "description": "Edit selected code"
    },
    {
      "name": "comment",
      "description": "Write comments for the selected code"
    },
    {
      "name": "share",
      "description": "Export the current chat session to markdown"
    },
    {
      "name": "cmd",
      "description": "Generate a shell command"
    },
    {
      "name": "commit",
      "description": "Generate a git commit message"
    }
  ],
"requestOptions": {},"analytics": {},"userToken": "","docs": [],"ui": {},"allowAnonymousTelemetry": true,"tabAutocompleteOptions": {}}
```

### Description

When the database needs to be queried, it can take up to 10 minutes for a response. If it doesn't, the response is instant. I'm using vLLM hosted via Xinference. 

### To reproduce

1. Host your LLM on xinference running on vLLM engine
2. Edit config.json file, API key optional depending on how xinference was setup
3. Open a project and let it be indexed
4. Run a query where you mention the codebase or a file

### Log output

```Shell
webviewElement.ts:486 An iframe which has both allow-scripts and allow-same-origin for its sandbox attribute can escape its sandboxing.
mountTo @ webviewElement.ts:486
TMScopeRegistry.ts:46 Overwriting grammar scope name to file mapping for scope source.java.
Old grammar file: file:///c%3A/Users/xxxxxxxx/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/extensions/java/syntaxes/java.tmLanguage.json.
New grammar file: file:///c%3A/Users/xxxxxxxx/.vscode/extensions/redhat.java-1.36.0-win32-x64/language-support/java/java.tmLanguage.json
register @ TMScopeRegistry.ts:46
TMScopeRegistry.ts:46 Overwriting grammar scope name to file mapping for scope source.groovy.
Old grammar file: file:///c%3A/Users/xxxxxxxx/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/extensions/groovy/syntaxes/groovy.tmLanguage.json.
New grammar file: file:///c%3A/Users/xxxxxxxx/.vscode/extensions/vscjava.vscode-gradle-3.16.4/syntaxes/groovy.tmLanguage.json
register @ TMScopeRegistry.ts:46
TMScopeRegistry.ts:46 Overwriting grammar scope name to file mapping for scope source.java.
Old grammar file: file:///c%3A/Users/xxxxxxxx/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/extensions/java/syntaxes/java.tmLanguage.json.
New grammar file: file:///c%3A/Users/xxxxxxxx/.vscode/extensions/redhat.java-1.36.0-win32-x64/language-support/java/java.tmLanguage.json
register @ TMScopeRegistry.ts:46
TMScopeRegistry.ts:46 Overwriting grammar scope name to file mapping for scope source.groovy.
Old grammar file: file:///c%3A/Users/xxxxxxxx/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/extensions/groovy/syntaxes/groovy.tmLanguage.json.
New grammar file: file:///c%3A/Users/xxxxxxxx/.vscode/extensions/vscjava.vscode-gradle-3.16.4/syntaxes/groovy.tmLanguage.json
register @ TMScopeRegistry.ts:46
log.ts:419  INFO Settings Sync: Updating due to initialize
log.ts:419  INFO Settings Sync: Updating authentication providers. Authentication Providers from store: Array(2)0: {id: 'github', scopes: Array(1)}1: {id: 'microsoft', scopes: Array(4)}length: 2[[Prototype]]: Array(0)
log.ts:419  INFO Settings Sync: Authentication providers updated Array(0)
log.ts:419  INFO Settings Sync: Updating authentication providers. Authentication Providers from store: Array(2)
log.ts:419  INFO Settings Sync: Authentication providers updated Array(1)
log.ts:419  INFO Settings Sync: Updating authentication providers. Authentication Providers from store: Array(2)
log.ts:419  INFO Settings Sync: Authentication providers updated Array(1)
log.ts:419  INFO Settings Sync: Updating authentication providers. Authentication Providers from store: Array(2)
log.ts:419  INFO Settings Sync: Authentication providers updated Array(2)
log.ts:419  INFO Settings Sync: Updating authentication providers. Authentication Providers from store: Array(2)
log.ts:419  INFO Settings Sync: Authentication providers updated Array(2)
log.ts:419  INFO Settings Sync: Updating due to declared authentication providers changed
log.ts:419  INFO Settings Sync: Updating authentication providers. Authentication Providers from store: Array(2)
log.ts:419  INFO Settings Sync: Authentication providers updated Array(2)
log.ts:419  INFO Settings Sync: Updating due to declared authentication providers changed
log.ts:419  INFO Settings Sync: Updating authentication providers. Authentication Providers from store: Array(2)
log.ts:419  INFO Settings Sync: Authentication providers updated Array(2)
log.ts:419  INFO [perf] Render performance baseline is 60ms
```
```

**Comment by tomasz-stefaniak** [comment]
To make sure we are on the same page, this problem doesn't occur if you use a different model provider? For example, if you deploy a model locally via Ollama?

**Comment by danialcheung** [comment]
@tomasz-stefaniak This problem seems to occur even with an external provider for the embedding models too, I also tried using xinference to host an external model, but it also took about the same time to process

**Comment by sestinj** [comment]
@danialcheung It seems like the inference server is just taking a lot of time to handle large context if this only happens when using @ codebase.

If you try a curl request with a very large input, does it also take a long time?

**Comment by richardbowman** [comment]
I'm seeing this same issue. It just hangs for upwards of a couple minutes whenever i submit a chat with the @codebase. I can see my CPU is doing a lot of work. I'm not unclear why its using my CPU so heavily? I can confirm my embeddings provider through LM Studio is being used to create the RAG's index. Querying a vector DB usually isn't so intensive??

**Comment by chk-mk** [comment]
I'm getting similar results, using vscode, ollama with llama3.1:8b for chat and nomic-embed-text for embeddings.

I did some investigation, and the context-gathering time is proportional to the size of the index.sqlite DB (roughly 1 second per 10 MB), which itself is proportional to the size of _all_ codebases indexed (not just the folder you have open right now). The DB can easily grow to multiple GB, hence minutes-long lookups.

The only way to make it fast was to delete the whole index folder and re-index a small codebase only.

It reminds me of DBs with a missing index where it falls back to a sequential scan.

**Comment by benkirkley** [comment]
I'm also having this issue and for me the issue is present in v0.0.70 and above. The issue does not occur in 0.0.69.

In my example, I have two simple files open in Jetbrains. When I add any kind of context (@openfiles, @codebase, @file, etc) the initial processing time leaps up. I ran the same prompt under 0.0.69 and 0.0.75, these are the results:

Model: Llama 3.1
Context: @openfiles (2 simple files)
Time before reply v0.0.69: 2 seconds
Time before reply v0.0.75: 18 seconds

**Comment by danialcheung** [comment]
> @danialcheung It seems like the inference server is just taking a lot of time to handle large context if this only happens when using @ codebase.
> 
> If you try a curl request with a very large input, does it also take a long time?

I don't believe this is the case, I even tried filling up the context with roughly 14k tokens and it was still able to answer in a timely manner, less than a minute.

**Comment by anrgct** [comment]
I also encountered this situation where the embedding model was not requested, and it kept showing "Gathering Context." I suspect that setting `config.json` `experimental.modelRoles.applyCodeBlock` triggered a complex process when requesting the repomap.
```js
// core/context/retrieval/repoMapRequest.ts
function isSupportedModel(
  config: ContinueConfig,
  modelTitle?: string,
): boolean {
  if (config.experimental?.modelRoles?.applyCodeBlock) {
    return true;
  }

  if (!modelTitle) {
    return false;
  }
```

**Comment by anrgct** [comment]
It seems that this is also related to the codebase index not being updated correctly. My embedding API was not enabled, which caused the refresh to fail. After I enabled the API, clicking "click to re-index" did not refresh, but when I switched branches, re-indexed, and then switched back, it was able to index, and there was no delay in the @codebase request either.

**Comment by bodzebod** [comment]
I have the same problem. Gathering context takes more than 15 minutes, and I have no idea why. I deleted my index folder, and reindexed it, but it doesn't change anything. It used to work fine some weeks ago, I couldn't say when it broke. I'm on VSCODE with prerelease version 0.9.246.

**Comment by benkirkley** [comment]
> I'm also having this issue and for me the issue is present in v0.0.70 and above. The issue does not occur in 0.0.69.
> 
> In my example, I have two simple files open in Jetbrains. When I perform a chat and add any kind of context (Open Files, Codebase, Files, etc) the initial processing time leaps up. I ran the same prompt under 0.0.69 and 0.0.75. Before each test I ran prompts without context added to make sure the model is loaded into RAM and working properly. These are the results:
> 
> Model: Llama 3.1 8B
> Provider: Ollama (local)
> OS: MacOS Context: Open Files (2 simple files)
> Time before reply v0.0.69: 2 seconds
> Time before reply v0.0.70: 18 seconds
> Time before reply v0.0.75: 18 seconds

I've tested v0.0.83 in IntelliJ IDEA and the issue now appears to be resolved for me. 
Time before reply v0.0.83: 2 seconds

**Comment by bodzebod** [comment]
I'm now running vscode extension 0.9.258, using voyage.ai for embeddings and reranker, and the issue came back. when using @codebase provider, the prompt is stuck forever again.
In extension host log exthost.log, I found the following:


2025-01-31 14:06:16.617 [error] Error (FileSystemError): Unable to resolve filesystem provider with relative file path 'kafka:XXX-cmJpdjkyLmRldjQuYmF0Y2guMS5mcy5jYXdzLmxvY2FsOjM5MDky/vscode-kafka-XXX-cmJpdjkyLmRldjQuYmF0Y2guMS5mcy5jYXdzLmxvY2FsOjM5MDky-nr-remote?topic=nr-remote'
	at Qi.e (file:///c:/TEMP/Tools/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:115:9853)
	at Object.readFile (file:///c:/TEMP/Tools/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:115:7581)
	at async _RecentlyEditedTracker.insertRange (c:\Users\XXX\.vscode\extensions\continue.continue-0.9.258-win32-x64\out\extension.js:606383:27)

What's weird is that this error seems to refer to both continue.dev and "tools for apache kafka" extensions. 
The relative file path mentioned in the error is about a kafka consumer I opened via the extension "tools for apache kafka". But the error is raised by continue.dev.
