### ISSUE TITLE
set up code error 

### ISSUE THREAD

**Issue by Rainmen-xia** [continuedev/continue#3047]
### Before submitting your bug report

- [ ] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [ ] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [X] I've seen the [troubleshooting guide](https://docs.continue.dev/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS:macos 
- Continue version: latest
- IDE version:
- Model:
- config.json:
```

### Description

I can't install all dependencies successful.

### To reproduce

when i start "run tasks ", then "install all dependencies", I got an error:
<img width="962" alt="image" src="https://github.com/user-attachments/assets/61b7f888-73e9-4582-9907-625e1127fc13">

### Log output

```Shell
You can mark the path "apache-arrow" as external to exclude it from the bundle, which will remove this error. You can also surround this "require" call with a try/catch block to handle this failure at run-time instead of bundle-time.

✘ [ERROR] Could not resolve "apache-arrow"

    ../../core/node_modules/vectordb/dist/remote/index.js:19:31:
      19 │ const apache_arrow_1 = require("apache-arrow");
         ╵                                ~~~~~~~~~~~~~~

  You can mark the path "apache-arrow" as external to exclude it from the bundle, which will remove this error. You can also surround this "require" call with a try/catch block to handle this failure at run-time instead of bundle-time.

✘ [ERROR] Could not resolve "apache-arrow"

    ../../core/node_modules/vectordb/dist/sanitize.js:24:31:
      24 │ const apache_arrow_1 = require("apache-arrow");
         ╵                                ~~~~~~~~~~~~~~

  You can mark the path "apache-arrow" as external to exclude it from the bundle, which will remove this error. You can also surround this "require" call with a try/catch block to handle this failure at run-time instead of bundle-time.

✘ [ERROR] Could not resolve "apache-arrow"

    ../../core/node_modules/vectordb/dist/remote/client.js:18:31:
      18 │ const apache_arrow_1 = require("apache-arrow");
         ╵                                ~~~~~~~~~~~~~~

  You can mark the path "apache-arrow" as external to exclude it from the bundle, which will remove this error. You can also surround this "require" call with a try/catch block to handle this failure at run-time instead of bundle-time.

/Users/..../continue/extensions/vscode/node_modules/esbuild/lib/main.js:1636
  let error = new Error(`${text}${summary}`);
              ^

Error: Build failed with 6 errors:
../../core/node_modules/vectordb/dist/arrow.js:17:31: ERROR: Could not resolve "apache-arrow"
../../core/node_modules/vectordb/dist/index.js:17:31: ERROR: Could not resolve "apache-arrow"
../../core/node_modules/vectordb/dist/query.js:17:31: ERROR: Could not resolve "apache-arrow"
../../core/node_modules/vectordb/dist/remote/client.js:18:31: ERROR: Could not resolve "apache-arrow"
../../core/node_modules/vectordb/dist/remote/index.js:19:31: ERROR: Could not resolve "apache-arrow"
...
    at failureErrorWithLog (/Users/....//continue/extensions/vscode/node_modules/esbuild/lib/main.js:1636:15)
    at /Users/....//continue/extensions/vscode/node_modules/esbuild/lib/main.js:1048:25
    at /Users/..../continue/extensions/vscode/node_modules/esbuild/lib/main.js:993:52
    at buildResponseToResult (/Users/....//continue/extensions/vscode/node_modules/esbuild/lib/main.js:1046:7)
    at /Users/....//continue/extensions/vscode/node_modules/esbuild/lib/main.js:1075:16
    at responseCallbacks.<computed> (/Users/....//continue/extensions/vscode/node_modules/esbuild/lib/main.js:697:9)
    at handleIncomingPacket (/Users/....//continue/extensions/vscode/node_modules/esbuild/lib/main.js:752:9)
    at Socket.readFromStdout (/Users/....//continue/extensions/vscode/node_modules/esbuild/lib/main.js:673:7)
    at Socket.emit (node:events:519:28)
    at addChunk (node:internal/streams/readable:559:12) {
  errors: [
    {
      detail: undefined,
      id: '',
      location: {
        column: 31,
        file: '../../core/node_modules/vectordb/dist/arrow.js',
        length: 14,
        line: 17,
        lineText: 'const apache_arrow_1 = require("apache-arrow");',
        namespace: '',
        suggestion: ''
      },
      notes: [
        {
          location: null,
          text: 'You can mark the path "apache-arrow" as external to exclude it from the bundle, which will remove this error. You can also surround this "require" call with a try/catch block to handle this failure at run-time instead of bundle-time.'
        }
      ],
      pluginName: '',
      text: 'Could not resolve "apache-arrow"'
    },
    {
      detail: undefined,
 id: '',
      location: {
        column: 31,
        file: '../../core/node_modules/vectordb/dist/index.js',
        length: 14,
        line: 17,
        lineText: 'const apache_arrow_1 = require("apache-arrow");',
        namespace: '',
        suggestion: ''
      },
      notes: [
        {
          location: null,
          text: 'You can mark the path "apache-arrow" as external to exclude it from the bundle, which will remove this error. You can also surround this "require" call with a try/catch block to handle this failure at run-time instead of bundle-time.'
        }
      ],
      pluginName: '',
      text: 'Could not resolve "apache-arrow"'
    },
    {
      detail: undefined,
      id: '',
      location: {
        column: 31,
        file: '../../core/node_modules/vectordb/dist/query.js',
        length: 14,
        line: 17,
        lineText: 'const apache_arrow_1 = require("apache-arrow");',
        namespace: '',
        suggestion: ''
      },
      notes: [
        {
          location: null,
          text: 'You can mark the path "apache-arrow" as external to exclude it from the bundle, which will remove this error. You can also surround this "require" call with a try/catch block to handle this failure at run-time instead of bundle-time.'
        }
      ],
      pluginName: '',
      text: 'Could not resolve "apache-arrow"'
    },
    {
      detail: undefined,
      id: '',
      location: {
        column: 31,
        file: '../../core/node_modules/vectordb/dist/remote/client.js',
        length: 14,
        line: 18,
        lineText: 'const apache_arrow_1 = require("apache-arrow");',
        namespace: '',
        suggestion: ''
      },
      notes: [
        {
          location: null,
          text: 'You can mark the path "apache-arrow" as external to exclude it from the bundle, which will remove this error. You can also surround this "require" call with a try/catch block to handle this failure at run-time instead of bundle-time.'
        }
      ],
      pluginName: '',
      text: 'Could not resolve "apache-arrow"'
    },
    {
      detail: undefined,
      id: '',
      location: {
        column: 31,
        file: '../../core/node_modules/vectordb/dist/remote/index.js',
        length: 14,
        line: 19,
        lineText: 'const apache_arrow_1 = require("apache-arrow");',
        namespace: '',
        suggestion: ''
      },
      notes: [
        {
          location: null,
          text: 'You can mark the path "apache-arrow" as external to exclude it from the bundle, which will remove this error. You can also surround this "require" call with a try/catch block to handle this failure at run-time instead of bundle-time.'
        }
      ],
      pluginName: '',
      text: 'Could not resolve "apache-arrow"'
    },
    {
      detail: undefined,
      id: '',
      location: {
        column: 31,
        file: '../../core/node_modules/vectordb/dist/sanitize.js',
        length: 14,
        line: 24,
        lineText: 'const apache_arrow_1 = require("apache-arrow");',
        namespace: '',
        suggestion: ''
      },
      notes: [
        {
          location: null,
          text: 'You can mark the path "apache-arrow" as external to exclude it from the bundle, which will remove this error. You can also surround this "require" call with a try/catch block to handle this failure at run-time instead of bundle-time.'
        }
      ],
      pluginName: '',
      text: 'Could not resolve "apache-arrow"'
    }
  ],
  warnings: []
}

Node.js v20.16.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! continue@0.9.233 esbuild-base: `node scripts/esbuild.js "--minify"`
npm ERR! Exit status 1
npm ERR!
```

**Comment by Rainmen-xia** [comment]
I fix it by add the  	"apache-arrow" in esbuild config。
		external: [
			"esbuild",
			"./xhr-sync-worker.js",
			"llamaTokenizerWorkerPool.mjs",
			"tiktokenWorkerPool.mjs",
			"vscode",
			"./index.node",
			"apache-arrow"
		],

**Comment by Rainmen-xia** [comment]
got another error:
use http2.0 error,I fix it by force the curl use 1.1:
binary/build.js
`
execCmdSync(`curl --http1.1 -L -o ${targetDir}/build.tar.gz ${downloadUrl}`);
`

**Comment by sestinj** [comment]
@Rainmen-xia is this all happening on the main branch after running the "install-all-dependencies" task?

**Comment by Rainmen-xia** [comment]
yes

**Comment by Rainmen-xia** [comment]
then you need to install apache-arrow your self ,in vscode fold.

**Comment by aaron-magic** [comment]
this issue still happen in latest continue version, any alternative solution instead of Rainmen's fix ?
