### ISSUE TITLE
Add Azure Embeddings Provider

### ISSUE THREAD

**Issue by RomneyDa** [continuedev/continue#3072]
### Validations

- [X] I believe this is a way to improve. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue+label%3Aenhancement) that requests the same enhancement

### Problem

@konrad1221 on discord
https://discord.com/channels/1108621136150929458/1305209412641751122

Add support for azure embeddings model deployments

**Comment by ctwardy** [comment]
Copy/Pasting key items from that thread. It seems a mix of config settings and _Azure_ OpenAI having a different embed config than OpenAI.:

## @konrad1221
It seems like there is some issue with the mapping of the fields in the config.json for the embeddingProvider

```
I was using embedding provider by Azure OpenAI. So far it was working for me, now I see 
[Extension Host] error when indexing:  Error: Failed to generate embeddings for 41 chunks with provider: OpenAIEmbeddingsProvider::text-embedding-3-large: Error: {"error":{"code":"DeploymentNotFound", "message":"The API deployment for this resource does not exist. If you created the deployment within the last 5 minutes, please wait a moment and try again."}}
```

why I think there is a problem with mapping, the error suggests `OpenAIEmbeddingsProvider::text-embedding-3-large` while I have it configured
```json
"embeddingsProvider": {
    "provider": "openai",
    "model": "text-embedding-3-large",
    "apiBase": "https://<REDACTED>.openai.azure.com/",
    "deployment": "embedding-large",
    "apiVersion": "2023-05-15",
    "apiType": "azure",
    "apiKey": "<REDACTED>"
  },
```
and I am sure the deployment exisits, I am, using it with other projects 

I moved to local `.continuerc.json` and now it seems to be working. The error is gone. 

When I removed the file, then it should fallback to `~/.continue/config.json` but it seems like it has issues with paths
```powershell
mainThreadExtensionService.ts:78 [Continue.continue]path should be a 
`path.relative()`d string, but got "../../.continue/config.json"
```
and
```powershell
RangeError: path should be a `path.relative()`d string, but got "../../.continue/config.json"
```

It is macOS Sonoma 14.7.1. The mentioned section is already above

## @RomneyDa 
The error message comes from [here](https://github.com/continuedev/continue/blob/dev/core/indexing/LanceDbIndex.ts#L171-L172)

And that id is set [here](https://github.com/continuedev/continue/blob/dev/core/indexing/embeddings/BaseEmbeddingsProvider.ts#L40-L44)

Looks like it's showing the id `OpenAIEmbeddingsProvider::text-embedding-3-large` in the error not the model, so that seems fine.

I think you're right, it's simply not finding the config file and the root cause is the path error.

In that case, I'm doing a PR to fix a bunch of path issues this week, see this issue (and a bunch of related). My hunch is will be fixed by that! #2780 

## Config & env vars
(Discussion about env vars in config files referencing #1729.)

## @LostInAzureOpenAIEmbeddings
Hi @konrad1221 and @Dallin Romney (@Continue) I'm having the same issue on a windows machine. I was using the version 0.8.58 and I was just getting this error 
```powershell
[Extension Host] error when indexing:  
Error: Failed to generate embeddings for 186 chunks with provider: OpenAIEmbeddingsProvider::text-embedding-3-large: 
Error: { 
   "error":{
        "code":"DeploymentNotFound",
        "message":"The API deployment for this resource does not exist. If you created the deployment within the last 5 minutes, please wait a moment and try again."
    }
}
    at LanceDbIndex.getEmbeddings (c:\Users\x\.vscode\extensions\continue.continue-0.8.58-win32-x64\out\extension.js:175457:17)
                  :
    at async Core.refreshCodebaseIndex (c:\Users\xx\.vscode\extensions\continue.continue-0.8.58-win32-x64\out\extension.js:540973:26)
```
 after swapping to the preview, version 0.9.233, i'm getting this :
```powershell
console.ts:137 [Extension Host] stack trace: 
RangeError: path should be a `path.relative()`d string, but got "..\..\..\.continue\config.json"
        :
mainThreadExtensionService.ts:78 [Continue.continue] path should be a `path.relative()`d string, but got "..\..\..\.continue\config.json"
$onExtensionRuntimeError @ mainThreadExtensionService.ts:78
```
## @RomneyDa 
For azure set provider to `azure`

**oh yes looks like azure isn't supported for embeddings yet 😢**  

(Check typo in `deployment` -- @Lost... reports that worked.)

but is the endpoint openai compatible?

I guess it won't work simply because openai embeddings provider won't use the azure credentials properly at the moment

**Comment by mantosh-mariner** [comment]
Hi, I’m Mantosh , and I’m interested in contributing to this project. I came across number of issue  and would like to work on it. Could you please assign it to me? 

Thank you for your time and for maintaining this project. Looking forward to your reply!

**Comment by sestinj** [comment]
Of course, just assigned it to you @mantosh-mariner!

**Comment by engleccma** [comment]
Hey I'm facing the same issue, it would be great to solve it. @mantosh-mariner are you working on it ? Do you need help ?

**Comment by JanHenze** [comment]
Hey we are having the same problem with the pre-release 0.9.259. All chat models work fine, but the embedding model is not reachable. We suspect that the break is introduced after version 0.9.242 and the release of the OpenAI adapters. It works fine with version 0.9.241.

Are there any updates on this issue? We would love to move on to a newer version.
