### ISSUE TITLE
{"type":"invalid_request_error" message":"messages.O: Input does not match the expected shape." }

### ISSUE THREAD

**Issue by samuela** [continuedev/continue#3095]
### Before submitting your bug report

- [X] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [X] I've seen the [troubleshooting guide](https://docs.continue.dev/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS: macOS
- Continue version: v0.8.59
- IDE version: Version: 1.95.3 (Universal)
- Model: Claude 3.5 Sonnet
- config.json: n/a
```

### Description

I'm seeing an error:
```
 Error in Continue free trial server: 400
{"type":"error" error":
{"type":"invalid_request_error" message":"messages.O: Input does not match the expected shape." }}
```
when trying to use Continue. I don't have a foolproof path to reproduce yet. It appears to occur sporadically when invoking Continue.

### To reproduce

<img width="579" alt="Screenshot 2024-11-26 at 5 05 51 PM" src="https://github.com/user-attachments/assets/b99d0445-7108-47c7-b1bc-e35aa13736a6">

### Log output

```Shell
[Extension Host] Error: HTTP 500 Internal Server Error from https://proxy-server-blue-l6vsfbzhba-uw.a.run.app/stream_chat

Error in Continue free trial server: 400 {"type":"error","error":{"type":"invalid_request_error","message":"messages.0: Input does not match the expected shape."}}
    at customFetch (/Users/samuelainsworth/.vscode/extensions/continue.continue-0.8.59-darwin-arm64/out/extension.js:84457:19)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at withExponentialBackoff (/Users/samuelainsworth/.vscode/extensions/continue.continue-0.8.59-darwin-arm64/out/extension.js:80543:26)
    at FreeTrial._streamChat (/Users/samuelainsworth/.vscode/extensions/continue.continue-0.8.59-darwin-arm64/out/extension.js:529241:26)
    at FreeTrial.streamChat (/Users/samuelainsworth/.vscode/extensions/continue.continue-0.8.59-darwin-arm64/out/extension.js:84642:30)
    at FreeTrial.chat (/Users/samuelainsworth/.vscode/extensions/continue.continue-0.8.59-darwin-arm64/out/extension.js:84613:26)
    at Function.describe (/Users/samuelainsworth/.vscode/extensions/continue.continue-0.8.59-darwin-arm64/out/extension.js:540232:31)
    at /Users/samuelainsworth/.vscode/extensions/continue.continue-0.8.59-darwin-arm64/out/extension.js:540765:18
    at /Users/samuelainsworth/.vscode/extensions/continue.continue-0.8.59-darwin-arm64/out/extension.js:582342:20
    at mh.value (/Users/samuelainsworth/.vscode/extensions/continue.continue-0.8.59-darwin-arm64/out/extension.js:547452:32)
log.ts:439   ERR [Extension Host] Error handling webview message: {
  "msg": {
    "messageId": "2509ccb1-fe59-4545-b292-3af1445b276a",
    "messageType": "chatDescriber/describe",
    "data": "This is a Bubble Sort algorithm. It's one of the simplest sorting algorithms that works by repeatedly stepping through the list, comparing adjacent elements and swapping them if they are in the wrong order. \n\nThe key characteristics of this implementation are:\n1. Two nested loops\n2. Adjacent element comparison\n3. Swapping of elements when the left one is greater than the right one\n\nWhile simple to understand, Bubble Sort has a time complexity of O(n²), making it inefficient for large datasets. It's mainly used for educational purposes or for very small lists where its simplicity might be advantageous.\n\nFor better performance in real applications, you'd typically use more efficient algorithms like Quick Sort (Python's built-in `sort()` uses Timsort, a hybrid sorting algorithm)."
  }
}

Error: HTTP 500 Internal Server Error from https://proxy-server-blue-l6vsfbzhba-uw.a.run.app/stream_chat

Error in Continue free trial server: 400 {"type":"error","error":{"type":"invalid_request_error","message":"messages.0: Input does not match the expected shape."}}
console.ts:137 [Extension Host] Error handling webview message: {
  "msg": {
    "messageId": "2509ccb1-fe59-4545-b292-3af1445b276a",
    "messageType": "chatDescriber/describe",
    "data": "This is a Bubble Sort algorithm. It's one of the simplest sorting algorithms that works by repeatedly stepping through the list, comparing adjacent elements and swapping them if they are in the wrong order. \n\nThe key characteristics of this implementation are:\n1. Two nested loops\n2. Adjacent element comparison\n3. Swapping of elements when the left one is greater than the right one\n\nWhile simple to understand, Bubble Sort has a time complexity of O(n²), making it inefficient for large datasets. It's mainly used for educational purposes or for very small lists where its simplicity might be advantageous.\n\nFor better performance in real applications, you'd typically use more efficient algorithms like Quick Sort (Python's built-in `sort()` uses Timsort, a hybrid sorting algorithm)."
  }
}

Error: HTTP 500 Internal Server Error from https://proxy-server-blue-l6vsfbzhba-uw.a.run.app/stream_chat

Error in Continue free trial server: 400 {"type":"error","error":{"type":"invalid_request_error","message":"messages.0: Input does not match the expected shape."}}
uGi @ console.ts:137
console.ts:137 [Extension Host] No corresponding diffInfo found for newFilepath
```

**Comment by QuangNguyen-Code4You-Extern** [comment]
+1

**Comment by inusedname** [comment]
+1

**Comment by mr-feek** [comment]
I'm also running into this -- first time trying out continue within the jetbrains IDE. 

I just asked a simple question to the trial claude integration:

"what framework is my app using" and hit command+enter to include my project as context.

```
[2024-12-11T19:12:52] Error: HTTP 500 Internal Server Error from https://proxy-server-blue-l6vsfbzhba-uw.a.run.app/stream_chat

Error in Continue free trial server: 400 {"type":"error","error":{"type":"invalid_request_error","message":"messages.1: Input does not match the expected shape."}}
```

**Comment by RomneyDa** [comment]
This issue appears to be stale
