### ISSUE TITLE
"when I try to send a message, the text is reset" from Discord

### ISSUE THREAD

**Issue by TyDunn** [continuedev/continue#310]
[Discord thread](https://discord.com/channels/1108621136150929458/1120078552788893768/1134101217610584135)

Help me figure it out, it doesn't work for me, when I try to send a message, the text is reset 

I also catch errors "A Python virtual enviroment cannot be activated because running scripts is disabled for this user. In order to use Continue, please enable signed scripts to run with this command in PowerShell: Set-ExecutionPolicy -ExecutionPolicy RemoteSigned -Scope CurrentUser, reload VS Code, and then try again."

and
 
Continue requires Python3. Please install from https://www.python.org/downloads, reload VS Code, and try again.

I tried to fix it as written in the error but the errors don't go away

![ScreenRecorderProject172](https://github.com/continuedev/continue/assets/13314504/69e9f377-10bf-481d-ac46-cbf553e0632d)

**Comment by irekgroup** [comment]
there are no active connections on port 65432, the command produces no output

Loading Continue server...

attempts to connect to the server do not give a positive response

**Comment by sestinj** [comment]
@irekgroup Since this comment 8 hours ago, I believe I have resolved this issue.

However, even if not, I've added the ability to view the server logs, which would expose the issue. You can see these by using the "Continue: View Logs" command in the VS Code command palette (cmd+shift+p).

If still not working, it would also be helpful to know operating system. Hoping to get you past this barrier asap—thanks!

**Comment by irekgroup** [comment]
a log fragment from the application, Visual Studio Code

```
2023-07-29 16:05:13.606 [error] [xabikos.JavaScriptSnippets]: Unknown language in `contributes.JavaScriptSnippets.language`. Provided value: vue
2023-07-29 16:05:16.110 [info] [perf] Render performance baseline is 83ms
2023-07-29 16:05:19.136 [info] UNRESPONSIVE extension host: starting to profile NOW
2023-07-29 16:05:20.445 [info] UNRESPONSIVE extension host: received responsive event and cancelling profiling session
2023-07-29 16:05:33.381 [error] cannot open file:///c%3A/Users/allab/.continue/continue.log. Detail: Unable to read file 'c:\Users\allab\.continue\continue.log' (Error: Unable to resolve nonexistent file 'c:\Users\allab\.continue\continue.log'): Error: cannot open file:///c%3A/Users/allab/.continue/continue.log. Detail: Unable to read file 'c:\Users\allab\.continue\continue.log' (Error: Unable to resolve nonexistent file 'c:\Users\allab\.continue\continue.log')
    at e.$g0.$tryOpenDocument (vscode-file://vscode-app/c:/Users/allab/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2306:36550)
```

**Comment by sestinj** [comment]
@irekgroup thanks for all of this extra information. A quick update: I'm working [here](https://github.com/continuedev/continue/issues/320) on a solution to bundle the python code as an executable, which I expect to solve this issue. Will let you know as soon as this is done

**Comment by sestinj** [comment]
@irekgroup I believe you've already been @'ed in another issue, but let me know about the status of this. A version that packages an executable is now released (should fix this), and I'd like to either close this issue if resolved.

**Comment by irekgroup** [comment]
This error https://github.com/continuedev/continue/issues/310#issue-1824787943 now clearly not.

It's different now. It looks like there is a problem with the OpenAI API. The model 'gpt-4' does not exist or you do not have access to it. Please check the OpenAI documentation to learn more. 

This is a default error that I got when I first started continue

```
Traceback (most recent call last):

  File "continuedev\src\continuedev\core\sdk.py", line 46, in create
    config = sdk._load_config_dot_py()

  File "continuedev\src\continuedev\core\sdk.py", line 169, in _load_config_dot_py
    path = getConfigFilePath()

  File "continuedev\src\continuedev\libs\util\paths.py", line 39, in getConfigFilePath
    with open(path, 'r') as f:

FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\allab\\.continue\\config.py'
```

I got this error when trying to send a question to gpt
```
Traceback (most recent call last):

  File "continuedev\src\continuedev\core\autopilot.py", line 248, in _run_singular_step
    observation = await step(self.continue_sdk)

  File "continuedev\src\continuedev\core\main.py", line 319, in __call__
    return await self.run(sdk)

  File "continuedev\src\continuedev\plugins\steps\chat.py", line 35, in run
    async for chunk in generator:

  File "continuedev\src\continuedev\libs\llm\maybe_proxy_openai.py", line 49, in stream_chat
    async for item in resp:

  File "continuedev\src\continuedev\libs\llm\openai.py", line 116, in stream_chat
    async for chunk in await openai.ChatCompletion.acreate(

  File "openai\api_resources\chat_completion.py", line 45, in acreate

  File "openai\api_resources\abstract\engine_api_resource.py", line 217, in acreate

  File "openai\api_requestor.py", line 310, in arequest

  File "openai\api_requestor.py", line 646, in _interpret_async_response

  File "openai\api_requestor.py", line 683, in _interpret_response_line

openai.error.InvalidRequestError: The model `gpt-4` does not exist or you do not have access to it. Learn more: https://help.openai.com/en/articles/7102672-how-can-i-access-gpt-4.
```

**Comment by sestinj** [comment]
@irekgroup The first error is known, and a solution was just released.

As for the latter, it might be possible that your OpenAI key doesn't have access to GPT-4. If you use "gpt-3.5-turbo" might this error disappear?

(you can edit this in config.py by changing the "default=..." line in "Models" to use model="gpt-3.5-turbo" instead of "gpt-4".)

**Comment by irekgroup** [comment]
Now everything fell into place, but before that I had to do:

```
1. Run netstat -ano | find "65432"
2. After you've got the PID, type the following command but replace "<PID>" with the actual PID value: taskkill /F /PID <PID>. 3. For example, if the PID is 1234, you would type: taskkill /F /PID 1234
Then restart VS Code
```

After that, I deleted .continue, and reinstalled Continue in CAPE, and only then I got a .config file that I was able to edit, hooray!

Can I ask a question,
Is there a VSC hotkey to call this function?
![image](https://github.com/continuedev/continue/assets/70753735/61f4a10a-67b8-45be-b942-dd5ebe1dc20d)

**Comment by sestinj** [comment]
That's great! We'll have to work on making sure all this debugging isn't necessary, but glad you got it working.

You can use command+period when your cursor is over text with a red/yellow underline to bring up quick fixes ([VS Code docs](https://code.visualstudio.com/docs/editor/refactoring#:~:text=clicking%20on%20the%20code%20action%20lightbulb%20or%20using%20the%20quick%20fix%20command%20%E2%8C%98.%20will%20display%20quick%20fixes%20and%20refactorings.)).

Other shortcuts for Continue are:
- command+m to toggle the text entry box
- command+shift+m to toggle text entry with /edit prefixed so that it will edit code instead of just answering
- If you drag the Continue icon from the left side of the screen to the right, you can keep the window pinned at the right as in this screenshot below. Then you can use option/alt+command+m to toggle that window
<img width="1512" alt="Screen Shot 2023-08-04 at 10 12 14 AM" src="https://github.com/continuedev/continue/assets/33237525/99647b56-dd15-49df-ba94-4022274b0a4d">
