### ISSUE TITLE
Add a request rate limit for embeddings model

### ISSUE THREAD

**Issue by lakshits11** [continuedev/continue#3106]
### Before submitting your bug report

- [X] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [X] I've seen the [troubleshooting guide](https://docs.continue.dev/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS: Windows 11
- Continue version: 0.8.57
- IDE version: VS Codium
- Model: Mistral Embed API
```

### Description

So my embeddings settings look something like this:

config.ts
```ts
mistral_embeddings: {
    model: "mistral-embed",
    apiKey: apiKeys.MISTRAL,
    maxChunkSize: 2048,
    maxBatchSize: 16,
    requestOptions: {
      timeout: 1001
    },
    provider: "mistral",
    apiBase: "https://api.mistral.ai/v1"
  },
```
  
  When using this configuration to generate embeddings, I get this console msg:
  ```log
  [Extension Host] error when indexing:  Error: Failed to generate embeddings for 129 chunks with provider: MistralEmbeddingsProvider::mistral-embed::2048: Error: {"message":"Requests rate limit exceeded"}
	at LanceDbIndex.getEmbeddings (c:\Users\Lakshit\.vscode-oss\extensions\continue.continue-0.8.57-win32-x64\out\extension.js:175314:17)
	at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
	at async LanceDbIndex.computeRows (c:\Users\Lakshit\.vscode-oss\extensions\continue.continue-0.8.57-win32-x64\out\extension.js:175262:28)
	at async LanceDbIndex.update (c:\Users\Lakshit\.vscode-oss\extensions\continue.continue-0.8.57-win32-x64\out\extension.js:175418:24)
	at async CodebaseIndexer.indexFiles (c:\Users\Lakshit\.vscode-oss\extensions\continue.continue-0.8.57-win32-x64\out\extension.js:540456:39)
	at async CodebaseIndexer.refresh (c:\Users\Lakshit\.vscode-oss\extensions\continue.continue-0.8.57-win32-x64\out\extension.js:540328:30)
	at async Core.refreshCodebaseIndex (c:\Users\Lakshit\.vscode-oss\extensions\continue.continue-0.8.57-win32-x64\out\extension.js:541322:26)
```

Same issue I am facing in voyage too:
```
[Extension Host] error when indexing:  Error: Failed to generate embeddings for 271 chunks with provider: VoyageEmbeddingsProvider::voyage-code-2: Error: {"detail":"You have not yet added your payment method in the billing page and will have reduced rate limits of 3 RPM and 10K TPM.  Please add your payment method in the billing page (https://dash.voyageai.com/billing/payment-methods) to unlock our standard rate limits (https://docs.voyageai.com/docs/rate-limits).  Even with payment methods entered, the free tokens (200M tokens for Voyage series 3) will still apply. See our pricing docs (https://docs.voyageai.com/docs/pricing) for the free tokens for your model."}
	at LanceDbIndex.getEmbeddings (c:\Users\Lakshit\.vscode-oss\extensions\continue.continue-0.8.57-win32-x64\out\extension.js:175314:17)
	at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
	at async LanceDbIndex.computeRows (c:\Users\Lakshit\.vscode-oss\extensions\continue.continue-0.8.57-win32-x64\out\extension.js:175262:28)
	at async LanceDbIndex.update (c:\Users\Lakshit\.vscode-oss\extensions\continue.continue-0.8.57-win32-x64\out\extension.js:175418:24)
	at async CodebaseIndexer.indexFiles (c:\Users\Lakshit\.vscode-oss\extensions\continue.continue-0.8.57-win32-x64\out\extension.js:540456:39)
	at async CodebaseIndexer.refresh (c:\Users\Lakshit\.vscode-oss\extensions\continue.continue-0.8.57-win32-x64\out\extension.js:540328:30)
	at async Core.refreshCodebaseIndex (c:\Users\Lakshit\.vscode-oss\extensions\continue.continue-0.8.57-win32-x64\out\extension.js:541322:26)
```
	
So i request you to resolve this. Thanks!

Also btw, is there a way to index the contents ? I just read the difference between indexing and embedding and would love if my model know where a particular function is used etc and that seems to be done by indexing maybe??

**Comment by sestinj** [comment]
I think that the solution will have to be increasing rate limits in this case

**Comment by lakshits11** [comment]
No the mistral embed has 1 request per second limit and its context length is 32k tokens so I guess this will work pretty well if i send requests within limits

**Comment by RomneyDa** [comment]
Potentially fixed by this:
https://github.com/continuedev/continue/pull/4581

Some embed invokations weren't using the custom fetch that has exponential backoff built in.
