### ISSUE TITLE
Continue showing blank grey box

### ISSUE THREAD

**Issue by dausruddin** [continuedev/continue#3167]
### Before submitting your bug report

- [X] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [X] I've seen the [troubleshooting guide](https://docs.continue.dev/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS:ArchLinux (KDE)
- Continue version:
- IDE version:
- Model: qwen2.5-coder
- config.json:
  
{
  "models": [
    {
      "model": "AUTODETECT",
      "title": "Ollama Arch",
      "apiBase": "http://192.168.0.146:11434",
      "provider": "ollama"
    },
    {
      "model": "AUTODETECT",
      "title": "Autodetect",
      "provider": "ollama"
    }
  ],
  "tabAutocompleteModel": {
    "title": "Codestral",
    "provider": "mistral",
    "model": "codestral-latest",
    "apiKey": ""
  },
  "customCommands": [
    {
      "name": "test",
      "prompt": "{{{ input }}}\n\nWrite a comprehensive set of unit tests for the selected code. It should setup, run tests that check for correctness including important edge cases, and teardown. Ensure that the tests are complete and sophisticated. Give the tests just as chat output, don't edit any file.",
      "description": "Write unit tests for highlighted code"
    }
  ],
  "contextProviders": [
    {
      "name": "code",
      "params": {}
    },
    {
      "name": "docs",
      "params": {}
    },
    {
      "name": "diff",
      "params": {}
    },
    {
      "name": "terminal",
      "params": {}
    },
    {
      "name": "problems",
      "params": {}
    },
    {
      "name": "folder",
      "params": {}
    },
    {
      "name": "codebase",
      "params": {}
    }
  ],
  "slashCommands": [
    {
      "name": "share",
      "description": "Export the current chat session to markdown"
    },
    {
      "name": "cmd",
      "description": "Generate a shell command"
    },
    {
      "name": "commit",
      "description": "Generate a git commit message"
    }
  ],
  "docs": [
    {
      "startUrl": "https://docs.python-telegram-bot.org/en/v21.7/",
      "title": "Python Telegram Bot v21.7",
      "faviconUrl": ""
    },
    {
      "startUrl": "https://ffmpeg.org/ffmpeg.html",
      "title": "ffmpeg",
      "faviconUrl": ""
    },
    {
      "startUrl": "https://docs.joinpeertube.org/api/rest-getting-started",
      "title": "Peertube",
      "faviconUrl": ""
    },
    {
      "startUrl": "https://docs.joinpeertube.org/api-rest-reference.html",
      "title": "Peertube API",
      "faviconUrl": ""
    }
  ],
  "experimental": {
    "useChromiumForDocsCrawling": true
  }
}
```

### Description

I had this issue twice in a few days, and I am not sure how to replicate. 
Basically after I switched to Firefox, then came back to VSCode, Continue became a big gray box. 
The only way to fix this was to restart VSCode.

![image](https://github.com/user-attachments/assets/e7c9d1b4-a3d6-432f-a96d-c12169f2c093)

### To reproduce

This is what I did when this happen, not necessarily the steps needed to reproduce as it happened randomly.
I cannot replicate this anymore.

1. Start using Continue.
2. Switch to Firefox
3. #. Switch back to VSCode.

### Log output

```Shell
console.ts:137 [Extension Host] stack trace: RangeError: path should be a `path.relative()`d string, but got "../../../extension-output-Continue.continue-#2-Continue - LLM Prompt/Completion"
	at throwError (/home/john/.vscode/extensions/continue.continue-0.8.60-linux-x64/out/extension.js:71825:13)
	at checkPath (/home/john/.vscode/extensions/continue.continue-0.8.60-linux-x64/out/extension.js:71839:16)
	at Ignore2._test (/home/john/.vscode/extensions/continue.continue-0.8.60-linux-x64/out/extension.js:71927:9)
	at Ignore2.ignores (/home/john/.vscode/extensions/continue.continue-0.8.60-linux-x64/out/extension.js:71954:21)
	at /home/john/.vscode/extensions/continue.continue-0.8.60-linux-x64/out/extension.js:541456:31
uGi @ console.ts:137
mainThreadExtensionService.ts:78 [Continue.continue]path should be a `path.relative()`d string, but got "../../../extension-output-Continue.continue-#2-Continue - LLM Prompt/Completion"
$onExtensionRuntimeError @ mainThreadExtensionService.ts:78
mainThreadExtensionService.ts:79 RangeError: path should be a `path.relative()`d string, but got "../../../extension-output-Continue.continue-#2-Continue - LLM Prompt/Completion"
	at throwError (vscode-file://vscode-app/home/john/.vscode/extensions/continue.continue-0.8.60-linux-x64/out/extension.js:71825:13)
	at checkPath (vscode-file://vscode-app/home/john/.vscode/extensions/continue.continue-0.8.60-linux-x64/out/extension.js:71839:16)
	at Ignore2._test (vscode-file://vscode-app/home/john/.vscode/extensions/continue.continue-0.8.60-linux-x64/out/extension.js:71927:9)
	at Ignore2.ignores (vscode-file://vscode-app/home/john/.vscode/extensions/continue.continue-0.8.60-linux-x64/out/extension.js:71954:21)
	at vscode-file://vscode-app/home/john/.vscode/extensions/continue.continue-0.8.60-linux-x64/out/extension.js:541456:31
$onExtensionRuntimeError @ mainThreadExtensionService.ts:79
console.ts:137 [Extension Host] rejected promise not handled within 1 second: RangeError: path should be a `path.relative()`d string, but got "../../../extension-output-Continue.continue-#2-Continue - LLM Prompt/Completion"
uGi @ console.ts:137
console.ts:137 [Extension Host] stack trace: RangeError: path should be a `path.relative()`d string, but got "../../../extension-output-Continue.continue-#2-Continue - LLM Prompt/Completion"
	at throwError (/home/john/.vscode/extensions/continue.continue-0.8.60-linux-x64/out/extension.js:71825:13)
	at checkPath (/home/john/.vscode/extensions/continue.continue-0.8.60-linux-x64/out/extension.js:71839:16)
	at Ignore2._test (/home/john/.vscode/extensions/continue.continue-0.8.60-linux-x64/out/extension.js:71927:9)
	at Ignore2.ignores (/home/john/.vscode/extensions/continue.continue-0.8.60-linux-x64/out/extension.js:71954:21)
	at /home/john/.vscode/extensions/continue.continue-0.8.60-linux-x64/out/extension.js:541456:31
uGi @ console.ts:137
mainThreadExtensionService.ts:78 [Continue.continue]path should be a `path.relative()`d string, but got "../../../extension-output-Continue.continue-#2-Continue - LLM Prompt/Completion"
$onExtensionRuntimeError @ mainThreadExtensionService.ts:78
mainThreadExtensionService.ts:79 RangeError: path should be a `path.relative()`d string, but got "../../../extension-output-Continue.continue-#2-Continue - LLM Prompt/Completion"
	at throwError (vscode-file://vscode-app/home/john/.vscode/extensions/continue.continue-0.8.60-linux-x64/out/extension.js:71825:13)
	at checkPath (vscode-file://vscode-app/home/john/.vscode/extensions/continue.continue-0.8.60-linux-x64/out/extension.js:71839:16)
	at Ignore2._test (vscode-file://vscode-app/home/john/.vscode/extensions/continue.continue-0.8.60-linux-x64/out/extension.js:71927:9)
	at Ignore2.ignores (vscode-file://vscode-app/home/john/.vscode/extensions/continue.continue-0.8.60-linux-x64/out/extension.js:71954:21)
	at vscode-file://vscode-app/home/john/.vscode/extensions/continue.continue-0.8.60-linux-x64/out/extension.js:541456:31
$onExtensionRuntimeError @ mainThreadExtensionService.ts:79
console.ts:137 [Extension Host] rejected promise not handled within 1 second: RangeError: path should be a `path.relative()`d string, but got "../../../extension-output-Continue.continue-#2-Continue - LLM Prompt/Completion"
uGi @ console.ts:137
console.ts:137 [Extension Host] stack trace: RangeError: path should be a `path.relative()`d string, but got "../../../extension-output-Continue.continue-#2-Continue - LLM Prompt/Completion"
	at throwError (/home/john/.vscode/extensions/continue.continue-0.8.60-linux-x64/out/extension.js:71825:13)
	at checkPath (/home/john/.vscode/extensions/continue.continue-0.8.60-linux-x64/out/extension.js:71839:16)
	at Ignore2._test (/home/john/.vscode/extensions/continue.continue-0.8.60-linux-x64/out/extension.js:71927:9)
	at Ignore2.ignores (/home/john/.vscode/extensions/continue.continue-0.8.60-linux-x64/out/extension.js:71954:21)
	at /home/john/.vscode/extensions/continue.continue-0.8.60-linux-x64/out/extension.js:541456:31
uGi @ console.ts:137
mainThreadExtensionService.ts:78 [Continue.continue]path should be a `path.relative()`d string, but got "../../../extension-output-Continue.continue-#2-Continue - LLM Prompt/Completion"
$onExtensionRuntimeError @ mainThreadExtensionService.ts:78
mainThreadExtensionService.ts:79 RangeError: path should be a `path.relative()`d string, but got "../../../extension-output-Continue.continue-#2-Continue - LLM Prompt/Completion"
	at throwError (vscode-file://vscode-app/home/john/.vscode/extensions/continue.continue-0.8.60-linux-x64/out/extension.js:71825:13)
	at checkPath (vscode-file://vscode-app/home/john/.vscode/extensions/continue.continue-0.8.60-linux-x64/out/extension.js:71839:16)
	at Ignore2._test (vscode-file://vscode-app/home/john/.vscode/extensions/continue.continue-0.8.60-linux-x64/out/extension.js:71927:9)
	at Ignore2.ignores (vscode-file://vscode-app/home/john/.vscode/extensions/continue.continue-0.8.60-linux-x64/out/extension.js:71954:21)
	at vscode-file://vscode-app/home/john/.vscode/extensions/continue.continue-0.8.60-linux-x64/out/extension.js:541456:31
$onExtensionRuntimeError @ mainThreadExtensionService.ts:79
console.ts:137 [Extension Host] No corresponding diffInfo found for newFilepath
console.ts:137 [Extension Host] No corresponding diffInfo found for newFilepath
console.ts:137 [Extension Host] No corresponding diffInfo found for newFilepath
console.ts:137 [Extension Host] rejected promise not handled within 1 second: RangeError: path should be a `path.relative()`d string, but got "../../../.continue/config.json"
uGi @ console.ts:137
$logExtensionHostMessage @ mainThreadConsole.ts:39
S @ rpcProtocol.ts:458
Q @ rpcProtocol.ts:443
M @ rpcProtocol.ts:373
L @ rpcProtocol.ts:299
(anonymous) @ rpcProtocol.ts:161
B @ event.ts:1243
fire @ event.ts:1274
fire @ ipc.net.ts:652
l.onmessage @ localProcessExtensionHost.ts:378
console.ts:137 [Extension Host] stack trace: RangeError: path should be a `path.relative()`d string, but got "../../../.continue/config.json"
	at throwError (/home/john/.vscode/extensions/continue.continue-0.8.60-linux-x64/out/extension.js:71825:13)
	at checkPath (/home/john/.vscode/extensions/continue.continue-0.8.60-linux-x64/out/extension.js:71839:16)
	at Ignore2._test (/home/john/.vscode/extensions/continue.continue-0.8.60-linux-x64/out/extension.js:71927:9)
	at Ignore2.ignores (/home/john/.vscode/extensions/continue.continue-0.8.60-linux-x64/out/extension.js:71954:21)
	at /home/john/.vscode/extensions/continue.continue-0.8.60-linux-x64/out/extension.js:541456:31
uGi @ console.ts:137
$logExtensionHostMessage @ mainThreadConsole.ts:39
S @ rpcProtocol.ts:458
Q @ rpcProtocol.ts:443
M @ rpcProtocol.ts:373
L @ rpcProtocol.ts:299
(anonymous) @ rpcProtocol.ts:161
B @ event.ts:1243
fire @ event.ts:1274
fire @ ipc.net.ts:652
l.onmessage @ localProcessExtensionHost.ts:378
mainThreadExtensionService.ts:78 [Continue.continue]path should be a `path.relative()`d string, but got "../../../.continue/config.json"
$onExtensionRuntimeError @ mainThreadExtensionService.ts:78
S @ rpcProtocol.ts:458
Q @ rpcProtocol.ts:443
M @ rpcProtocol.ts:373
L @ rpcProtocol.ts:299
(anonymous) @ rpcProtocol.ts:161
B @ event.ts:1243
fire @ event.ts:1274
fire @ ipc.net.ts:652
l.onmessage @ localProcessExtensionHost.ts:378
mainThreadExtensionService.ts:79 RangeError: path should be a `path.relative()`d string, but got "../../../.continue/config.json"
	at throwError (vscode-file://vscode-app/home/john/.vscode/extensions/continue.continue-0.8.60-linux-x64/out/extension.js:71825:13)
	at checkPath (vscode-file://vscode-app/home/john/.vscode/extensions/continue.continue-0.8.60-linux-x64/out/extension.js:71839:16)
	at Ignore2._test (vscode-file://vscode-app/home/john/.vscode/extensions/continue.continue-0.8.60-linux-x64/out/extension.js:71927:9)
	at Ignore2.ignores (vscode-file://vscode-app/home/john/.vscode/extensions/continue.continue-0.8.60-linux-x64/out/extension.js:71954:21)
	at vscode-file://vscode-app/home/john/.vscode/extensions/continue.continue-0.8.60-linux-x64/out/extension.js:541456:31
$onExtensionRuntimeError @ mainThreadExtensionService.ts:79
S @ rpcProtocol.ts:458
Q @ rpcProtocol.ts:443
M @ rpcProtocol.ts:373
L @ rpcProtocol.ts:299
(anonymous) @ rpcProtocol.ts:161
B @ event.ts:1243
fire @ event.ts:1274
fire @ ipc.net.ts:652
l.onmessage @ localProcessExtensionHost.ts:378
```

**Comment by Ricardo-Miguel-Caldeira** [comment]
Same here but don't even need to change window.

**Comment by RomneyDa** [comment]
@Ricardo-Miguel-Caldeira @dausruddin still seeing this on most recent prerelease? May have been caused by indexing crashing on startup or similar

**Comment by RomneyDa** [comment]
Closing for now but let me know if needs to be reopened!

**Comment by kralor-guldan** [comment]
I think this issue is related to vscode, not continuedev. I am seeing the issue in other extensions as well.

**Comment by RomneyDa** [comment]
This seems to have been resolved
