### ISSUE TITLE
Edit (cmd+I) is not working on files open in VSCode remote-ssh workspace

### ISSUE THREAD

**Issue by avneeshs1** [continuedev/continue#3193]
### Before submitting your bug report

- [X] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [X] I've seen the [troubleshooting guide](https://docs.continue.dev/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS: VSCode client is running on macOS. VSCode server and all the code files are located on a linux machine. 
- Continue version: 0.9.239
- IDE version: VSCode version 1.96.0-insider
- Model: claude-3-5-sonnet-latest
- tabAutocompleteModel: qwen2.5-code 1.5B running via ollama on the macOS machine.
- config.json:
  
{
  "models": [
    {
      "model": "AUTODETECT",
      "title": "Autodetect",
      "apiKey": "",
      "provider": "openai"
    },
    {
      "model": "claude-3-5-sonnet-latest",
      "title": "Claude 3.5 Sonnet",
      "apiKey": "",
      "provider": "anthropic"
    }
  ],

  "tabAutocompleteModel": {
      "title": "Qwen2.5-Coder 1.5B",
      "provider": "ollama",
      "model": "qwen2.5-coder:1.5b"
  },
  "customCommands": [
    {
      "name": "test",
      "prompt": "{{{ input }}}\n\nWrite a comprehensive set of unit tests for the selected code. It should setup, run tests that check for correctness including important edge cases, and teardown. Ensure that the tests are complete and sophisticated. Give the tests just as chat output, don't edit any file.",
      "description": "Write unit tests for highlighted code"
    }
  ],
  "docs": [
    {
      "title": "ClearAlpha Docs",
      "startUrl": "https://docs-beta.clearalpha.tech",
      "rootUrl": "https://docs-beta.clearalpha.tech",
      "faviconUrl": "https://docs-beta.clearalpha.tech/icons/ca-img.png",
    }
  ],
  "contextProviders": [
    {
      "name": "code",
      "params": {}
    },
    {
      "name": "docs",
      "params": {}
    },
    {
      "name": "diff",
      "params": {}
    },
    {
      "name": "terminal",
      "params": {}
    },
    {
      "name": "problems",
      "params": {}
    },
    {
      "name": "folder",
      "params": {}
    },
    {
      "name": "codebase",
      "params": {}
    }
  ],
  "slashCommands": [
    {
      "name": "share",
      "description": "Export the current chat session to markdown"
    },
    {
      "name": "cmd",
      "description": "Generate a shell command"
    },
    {
      "name": "commit",
      "description": "Generate a git commit message"
    }
  ]
}
```

### Description

Continue is able to fetch the suggested edits from the LLM models just fine. However, when it tries to apply the edits to the file, it throws a bunch of errors.

### To reproduce

1. Open a VS Code project using remote ssh.
2. Edit a file, select a piece of code and hit cmd+i
3. Type in the change and let the extension suggest edits
4. Try to accept the edits in the extension window. The edits don't apply and the console logs show error.

![image](https://github.com/user-attachments/assets/76d0d83c-8ef4-47a6-ab4e-8f3e4a345fe0)

### Log output

```Shell
Console Logs
============
console.ts:137 [Extension Host] rejected promise not handled within 1 second: CodeExpectedError: cannot open file:///home/avneesh.saxena/dev/macro/com/cat/vendors/ubs/qis.py. Detail: Unable to read file '/home/avneesh.saxena/dev/macro/com/cat/vendors/ubs/qis.py' (Error: Unable to resolve nonexistent file '/home/avneesh.saxena/dev/macro/com/cat/vendors/ubs/qis.py') (at console.<anonymous> (file:///Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:159:26388))
CQi @ console.ts:137
$logExtensionHostMessage @ mainThreadConsole.ts:39
S @ rpcProtocol.ts:458
Q @ rpcProtocol.ts:443
M @ rpcProtocol.ts:373
L @ rpcProtocol.ts:299
(anonymous) @ rpcProtocol.ts:161
B @ event.ts:1243
fire @ event.ts:1274
fire @ ipc.net.ts:652
l.onmessage @ localProcessExtensionHost.ts:378
console.ts:137 [Extension Host] stack trace: CodeExpectedError: cannot open file:///home/avneesh.saxena/dev/macro/com/cat/vendors/ubs/qis.py. Detail: Unable to read file '/home/avneesh.saxena/dev/macro/com/cat/vendors/ubs/qis.py' (Error: Unable to resolve nonexistent file '/home/avneesh.saxena/dev/macro/com/cat/vendors/ubs/qis.py')
    at hVe.$tryOpenDocument (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:747:8481) (at console.<anonymous> (file:///Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:159:26388))
CQi @ console.ts:137
$logExtensionHostMessage @ mainThreadConsole.ts:39
S @ rpcProtocol.ts:458
Q @ rpcProtocol.ts:443
M @ rpcProtocol.ts:373
L @ rpcProtocol.ts:299
(anonymous) @ rpcProtocol.ts:161
B @ event.ts:1243
fire @ event.ts:1274
fire @ ipc.net.ts:652
l.onmessage @ localProcessExtensionHost.ts:378
log.ts:445   ERR cannot open file:///home/avneesh.saxena/dev/macro/com/cat/vendors/ubs/qis.py. Detail: Unable to read file '/home/avneesh.saxena/dev/macro/com/cat/vendors/ubs/qis.py' (Error: Unable to resolve nonexistent file '/home/avneesh.saxena/dev/macro/com/cat/vendors/ubs/qis.py'): CodeExpectedError: cannot open file:///home/avneesh.saxena/dev/macro/com/cat/vendors/ubs/qis.py. Detail: Unable to read file '/home/avneesh.saxena/dev/macro/com/cat/vendors/ubs/qis.py' (Error: Unable to resolve nonexistent file '/home/avneesh.saxena/dev/macro/com/cat/vendors/ubs/qis.py')
    at hVe.$tryOpenDocument (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:747:8481)


LLM Logs
========
This is the code to rewrite:

    tdata = data[ticker]


The user's request is: "can you all type hints to this variable"

Here is the rewritten code:==========================================================================
==========================================================================
Completion:
Here's the code with added type hints:

```python
    tdata: typing.Tuple[pd.Series, pd.DataFrame] = data[ticker]
```

This type
```

**Comment by JLCareglio** [comment]
I have the same error while working with WSL

**Comment by Patrick-Erichsen** [comment]
This appears to be another instance of https://github.com/continuedev/continue/issues/2780

We're actively looking into SSH/WSL issues and hoping to get it resolved ASAP. In the meantime unfortunately I would recommend using Chat and either the "Copy" or "Apply" buttons.

**Comment by RomneyDa** [comment]
@avneeshs1 are you still seeing this issue?
Should have been fixed by https://github.com/continuedev/continue/pull/3247

**Comment by avneeshs1** [comment]
@RomneyDa, it seems to be working now. Tyvm! I had disable the extension so I haven't tested everything fully. If anything breaks, I will report back but good to close the bug for now. Thanks.

**Comment by RomneyDa** [comment]
Great! Thanks for digging into this.
