### ISSUE TITLE
"An error occurred: fetch is not a function" while running a custom LLM

### ISSUE THREAD

**Issue by juliettAlphaNovember** [continuedev/continue#3202]
### Before submitting your bug report

- [X] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [X] I've seen the [troubleshooting guide](https://docs.continue.dev/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS: Windows 10
- Continue version: v0.8.60
- IDE version: VSCode 1.95.3 (latest)
```

### Description

I have implemented a custom LLM that I use to connect to a custom company GPT endpoint (API is not compliant with standard OpenAI API).
I was inspired by the:
https://github.com/continuedev/continue/issues/2250#issuecomment-2348004867

Everything used to work as intended but recently I experienced the following error:
`An error occurred: fetch is not a function`

It seems to me that this might be related to the:
https://github.com/continuedev/continue/pull/2935

In the:
core/config/types.ts
the CustomLLM does not specify the `signal: AbortSignal` so perhaps it might be causing my issue?
```
export interface CustomLLMWithOptionals {
    options: LLMOptions;
    streamCompletion?: (
      prompt: string,
      options: CompletionOptions,
      fetch: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>,
    ) => AsyncGenerator<string>;
    streamChat?: (
      messages: ChatMessage[],
      options: CompletionOptions,
      fetch: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>,
    ) => AsyncGenerator<string>;
    listModels?: (
      fetch: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>,
    ) => Promise<string[]>;
  }

  /**
   * The LLM interface requires you to specify either `streamCompletion` or `streamChat` (or both).
   */
  export type CustomLLM = RequireAtLeastOne<
    CustomLLMWithOptionals,
    "streamCompletion" | "streamChat"
  >;
```

config.ts
```
export function modifyConfig(config: Config): Config {
  config.models.push({
    options: {
      title: "Custom LLM",
      model: "Custom LLM",
      requestOptions: {
        caBundlePath: "<PATH>"
      }
    },
    streamCompletion: async function* (
      prompt: string,
      options: CompletionOptions,
      fetch
    ) {
      try {
        const apiKey = "<API_KEY>";
        if (!apiKey) {
          throw new Error("API key is not set.");
        }
  
        const response = await fetch("<CUSTOM_COMPANY_ENDPOINT>", {
          method: "POST",
          headers: {
            "Content-Type": "application/json",
            "Authorization": `basic ${apiKey}`,
          },
          body: JSON.stringify({
            model: "gpt-4o",
            messages: [
              { role: "user", content: prompt },
            ],
            stream: false,
          }),
        });
  
        if (!response.ok) {
          const errorText = await response.text();
          throw new Error(`HTTP Error ${response.status}: ${response.statusText}\n${errorText}`);
        }
  
        const data = await response.json();
  
        if (data.choices && data.choices.length > 0) {
          const content = data.choices[0].message?.content;
          if (content) {
            yield content;
          } else {
            throw new Error("The response does not contain content.");
          }
        } else {
          throw new Error("The response does not contain choices.");
        }
  
      } catch (error) {
        console.error("An error occurred in streamCompletion:", error);
        yield `An error occurred: ${error instanceof Error ? error.message : String(error)}`;
      }
    },
  });
  return config;
}
```

### To reproduce

1. Create a CustomLLM model and try to  use the chat window.

### Log output

```Shell
ERR [Extension Host] An error occurred in streamCompletion: TypeError: fetch is not a function
	at CustomLLMClass.streamCompletion [as customStreamCompletion] (<user_path>\.continue\out\config.js:42:32)
	at streamCompletion.next (<anonymous>)
	at CustomLLMClass._streamComplete <user_path>\.vscode\extensions\continue.continue-0.8.60-win32-x64\out\extension.js:538324:28)
	at _streamComplete.next (<anonymous>)
	at CustomLLMClass.streamChat (<user_path>\.vscode\extensions\continue.continue-0.8.60-win32-x64\out\extension.js:84625:30)
	at async llmStreamChat (<user_path>\.vscode\extensions\continue.continue-0.8.60-win32-x64\out\extension.js:541134:23)
	at async mh.value (<user_path>\.vscode\extensions\continue.continue-0.8.60-win32-x64\out\extension.js:548054:29)
```

**Comment by Patrick-Erichsen** [comment]
cc @sestinj as he was more involved in the PR you referenced (https://github.com/continuedev/continue/pull/2935). It does seem plausible /likelythat the issue is with the `AbortSignal` as you described.

**Comment by livingtonds** [comment]
Hi!Something new about issue?I have same problem with my custom LLM:
`An error occurred: fetch is not a function`
![image](https://github.com/user-attachments/assets/75089270-f344-4451-bf01-4415c908f711)

**Comment by AbdurNawaz** [comment]
Change the below line:
```js
 await fetch("<CUSTOM_COMPANY_ENDPOINT>"
```
To:
```js
 await this.fetch("<CUSTOM_COMPANY_ENDPOINT>"
```

It should start working
