### ISSUE TITLE
Continue causes VS Code extension host to fail resolving files

### ISSUE THREAD

**Issue by Fadelis98** [continuedev/continue#3255]
### Before submitting your bug report

- [X] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [X] I've seen the [troubleshooting guide](https://docs.continue.dev/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS: Windows(ssh to linux server)
- Continue version: v0.9.241(pre-release)/v0.8.60(stable)
- IDE version: vscode 1.95.3
- Model: ollama
- config.json:
  
{
  "models": [
    {
      "title": "qwen2.5-chat",
      "model": "qwen2.5-coder:32b",
      "provider": "ollama",
      "apiBase": "http://10.xxx.x.xx:xxxxx"
    }
  ],
  "tabAutocompleteModel": {
    "title": "qwen2.5-fim",
    "model": "qwen2.5-coder:14b-base",
    "provider": "ollama",
    "apiBase": "http://10.xxx.x.xx:xxxxx"
  },
  "tabAutocompleteOptions": {
    "debounceDelay": 500,
    "maxPromptTokens": 1500,
    "multilineCompletions": "never"
  },
  "embeddingsProvider": {
    "provider": "ollama",
    "model": "mxbai-embed-large",
    "apiBase": "http://10.xxx.x.xx:xxxxx"
  },
  "customCommands": [
    {
      "name": "test",
      "prompt": "{{{ input }}}\n\nWrite a comprehensive set of unit tests for the selected code. It should setup, run tests that check for correctness including important edge cases, and teardown. Ensure that the tests are complete and sophisticated. Give the tests just as chat output, don't edit any file.",
      "description": "Write unit tests for highlighted code"
    }
  ],
  "contextProviders": [
    {
      "name": "code",
      "params": {}
    },
    {
      "name": "docs",
      "params": {}
    },
    {
      "name": "diff",
      "params": {}
    },
    {
      "name": "terminal",
      "params": {}
    },
    {
      "name": "problems",
      "params": {}
    },
    {
      "name": "folder",
      "params": {}
    },
    {
      "name": "codebase",
      "params": {}
    }
  ],
  "slashCommands": [
    {
      "name": "share",
      "description": "Export the current chat session to markdown"
    },
    {
      "name": "cmd",
      "description": "Generate a shell command"
    },
    {
      "name": "commit",
      "description": "Generate a git commit message"
    }
  ]
}
```

### Description

Emable `continue` and open any file in vscode, there's an error in the output of extension host(see below). It says that the extension tries to open a non-exist file. The path reported is an reletive path begins with  `/username` instead of the correct absolute path `/home/username/...`, and it use `\` instead of `/`, so I guess its a bug related to the reletive path resolve defference between Windows and UNIX-style file system.

This bug is similar to #1107 , #1194 . However in my case, this bug affects other extensions' functionality like jupyter notebook and pylance. The notebook will not be able to excute after it has been launched for a short time, so I have to disable continue.

### To reproduce

1. Install continue
2. ssh to a remote machine
3. open any file

### Log output

When clicking a file in workspace
```Shell
2024-12-09 13:55:19.893 [error] Error: Unable to read file '\username\path\to\file.py' (Error: Unable to resolve nonexistent file '\username\path\to\file.py')
    at Pnt.F (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:3088:69674)
    at Pnt.D (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:3088:69499)
    at async Gnt.M (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:3089:9119)
    at async Gnt.readStream (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:3089:8894)
    at async Pde.Db (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1275:11960)
    at async Pde.resolve (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1275:10435)
    at async Unt.W (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:3089:5752)
    at async tWe.r (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1275:20910) vscode.executeDefinitionProvider undefined
```

when clicking the OUTPUT pannel:
```
2024-12-09 13:59:36.590 [error] RangeError: path should be a `path.relative()`d string, but got "..\..\..\..\Program Files\Microsoft VS Code\exthost"
	at throwError (c:\Users\username\.vscode\extensions\continue.continue-0.8.60-win32-x64\out\extension.js:71825:13)
	at checkPath (c:\Users\username\.vscode\extensions\continue.continue-0.8.60-win32-x64\out\extension.js:71839:16)
	at Ignore2._test (c:\Users\username\.vscode\extensions\continue.continue-0.8.60-win32-x64\out\extension.js:71927:9)
	at Ignore2.ignores (c:\Users\username\.vscode\extensions\continue.continue-0.8.60-win32-x64\out\extension.js:71954:21)
	at c:\Users\username\.vscode\extensions\continue.continue-0.8.60-win32-x64\out\extension.js:541450:31
```

**Comment by Fadelis98** [comment]
after some further investigation,this is exactly the same bug mentioned in #3000, and there is a meta issue #2780. I suggest that this bug is not caused by wsl, and happens on all remote linux servers.

**Comment by BasWeg** [comment]
I've the same issue. Running localy at LinuxMint

**Comment by rafaelgildin** [comment]
Me too, is there any solution for this bug, please?

**Comment by Fadelis98** [comment]
> Me too, is there any solution for this bug, please?

As mentioned in #2780 , this bug has been fixed by #3247 3 weeks ago, so switch to the pre-release version works for me.
