### ISSUE TITLE
Highlight code is not working

### ISSUE THREAD

**Issue by aston314** [continuedev/continue#332]
When I have multiple files open, not all of them respond to the .continue operation after selecting the code.

**Comment by sestinj** [comment]
Could you give any more details about what you are trying to do? What would it mean to successfully respond to the continue operation?

**Comment by sestinj** [comment]
@aston314 I've fixed a number of related issues just now. Does your problem still occur in the latest version? (v0.0.302 and beyond?)

**Comment by rylos** [comment]
for me /edit command with selected code never works and it gives this error `/edit explain this code
'code'
View Traceback
Traceback (most recent call last):

  File "continuedev\src\continuedev\core\autopilot.py", line 264, in _run_singular_step
    observation = await step(self.continue_sdk)

  File "continuedev\src\continuedev\core\main.py", line 326, in __call__
    return await self.run(sdk)

  File "continuedev\src\continuedev\plugins\steps\main.py", line 231, in run
    range_in_files = sdk.get_code_context(only_editing=True)

  File "continuedev\src\continuedev\core\sdk.py", line 181, in get_code_context
    highlighted_ranges = self.__autopilot.context_manager.context_providers[

KeyError: 'code'`

**Comment by cheuk-cheng** [comment]
In my case, if I highlight the entire Python 3 script (which is about 250 lines) and ask Continue with a prompt like "Find bugs in the Python code" by using a locally running Ollama llama2:13b model in macOS, it will say that the code is too long.  Highighting only a few lines works fine though.

**Comment by Nokic233** [comment]
I have same. ``No highlighted file appears after selecting the code``

![企业微信截图_169208373775](https://github.com/continuedev/continue/assets/74362493/fc41fc9d-b862-4449-82d5-a645ef42a2a3)


platform: win11 22H2 22621.1105
continue: v0.0.307
vscode: v1.80.1

```
// log
[2023-08-15 14:59:58,736] [DEBUG] Testing logs
[2023-08-15 15:00:03,822] [DEBUG] Accepted websocket connection from Address(host='127.0.0.1', port=60081)
[2023-08-15 15:00:03,823] [DEBUG] Sending IDE message: workspaceDirectory
[2023-08-15 15:00:03,823] [DEBUG] Sending IDE message: uniqueId
[2023-08-15 15:00:03,825] [DEBUG] Received message while initializing workspaceDirectory
[2023-08-15 15:00:03,825] [DEBUG] Received message while initializing uniqueId
[2023-08-15 15:00:04,166] [DEBUG] Received IDE message: getSessionId
[2023-08-15 15:00:04,166] [DEBUG] New session: None
[2023-08-15 15:00:04,287] [DEBUG] Starting context manager
[2023-08-15 15:00:04,331] [DEBUG] Sending session id: 75e52047-1339-41c5-a733-f930b8660f25
[2023-08-15 15:00:04,332] [DEBUG] Sending IDE message: getSessionId
[2023-08-15 15:00:04,389] [DEBUG] Received websocket connection at url: ws://localhost:65432/gui/ws?session_id=75e52047-1339-41c5-a733-f930b8660f25
[2023-08-15 15:00:04,389] [DEBUG] Session started
[2023-08-15 15:00:04,389] [DEBUG] Registered websocket for session 75e52047-1339-41c5-a733-f930b8660f25
[2023-08-15 15:00:08,193] [DEBUG] Received IDE message: highlightedCodePush
[2023-08-15 15:00:08,915] [DEBUG] Received IDE message: highlightedCodePush
[2023-08-15 15:00:09,525] [DEBUG] Received IDE message: highlightedCodePush
[2023-08-15 15:00:09,727] [DEBUG] MeilisearchApiError. Server error '503 Service Unavailable' for url 'http://localhost:7700/health'
For more information check: https://httpstatuses.com/503  
[2023-08-15 15:00:10,627] [DEBUG] MeilisearchApiError. Server error '503 Service Unavailable' for url 'http://localhost:7700/health'
For more information check: https://httpstatuses.com/503  
[2023-08-15 15:00:11,528] [DEBUG] MeilisearchApiError. Server error '503 Service Unavailable' for url 'http://localhost:7700/health'
For more information check: https://httpstatuses.com/503  
[2023-08-15 15:00:12,415] [DEBUG] MeilisearchApiError. Server error '503 Service Unavailable' for url 'http://localhost:7700/health'
For more information check: https://httpstatuses.com/503  
[2023-08-15 15:00:13,303] [DEBUG] MeilisearchApiError. Server error '503 Service Unavailable' for url 'http://localhost:7700/health'
For more information check: https://httpstatuses.com/503  
[2023-08-15 15:00:14,094] [DEBUG] Received IDE message: highlightedCodePush
[2023-08-15 15:00:14,175] [DEBUG] MeilisearchApiError. Server error '503 Service Unavailable' for url 'http://localhost:7700/health'
For more information check: https://httpstatuses.com/503  
[2023-08-15 15:00:19,290] [DEBUG] MeilisearchApiError. Server error '503 Service Unavailable' for url 'http://localhost:7700/health'
For more information check: https://httpstatuses.com/503  
[2023-08-15 15:00:20,184] [DEBUG] MeilisearchApiError. Server error '503 Service Unavailable' for url 'http://localhost:7700/health'
For more information check: https://httpstatuses.com/503  
[2023-08-15 15:00:21,066] [DEBUG] MeilisearchApiError. Server error '503 Service Unavailable' for url 'http://localhost:7700/health'
For more information check: https://httpstatuses.com/503  
[2023-08-15 15:00:21,924] [DEBUG] MeilisearchApiError. Server error '503 Service Unavailable' for url 'http://localhost:7700/health'
For more information check: https://httpstatuses.com/503  
[2023-08-15 15:00:22,805] [DEBUG] MeilisearchApiError. Server error '503 Service Unavailable' for url 'http://localhost:7700/health'
For more information check: https://httpstatuses.com/503  
[2023-08-15 15:00:23,689] [DEBUG] MeilisearchApiError. Server error '503 Service Unavailable' for url 'http://localhost:7700/health'
For more information check: https://httpstatuses.com/503  
[2023-08-15 15:00:24,299] [WARNING] MeiliSearch did not start within 5 seconds
[2023-08-15 15:00:24,299] [WARNING] MeiliSearch not running, avoiding any dependent context providers
[2023-08-15 15:00:48,592] [DEBUG] Received IDE message: highlightedCodePush
[2023-08-15 15:00:49,594] [DEBUG] Received IDE message: highlightedCodePush
[2023-08-15 15:00:58,751] [DEBUG] Received IDE message: highlightedCodePush
[2023-08-15 15:00:59,489] [DEBUG] Received IDE message: highlightedCodePush
[2023-08-15 15:01:03,071] [DEBUG] Received IDE message: highlightedCodePush
[2023-08-15 15:01:03,452] [DEBUG] Received IDE message: highlightedCodePush
[2023-08-15 15:01:09,951] [DEBUG] Received IDE message: highlightedCodePush
[2023-08-15 15:01:23,735] [DEBUG] Received IDE message: highlightedCodePush
[2023-08-15 15:01:36,694] [DEBUG] Received IDE message: highlightedCodePush
[2023-08-15 15:01:42,963] [DEBUG] Received IDE message: highlightedCodePush
[2023-08-15 15:01:51,107] [DEBUG] Received IDE message: highlightedCodePush
[2023-08-15 15:01:51,535] [DEBUG] Received IDE message: highlightedCodePush
[2023-08-15 15:02:13,367] [DEBUG] Received GUI message {"messageType":"delete_at_index","data":{"index":1}}
[2023-08-15 15:02:13,368] [DEBUG] Received GUI message {"messageType":"delete_at_index","data":{"index":1}}
```

**Comment by Kingo71** [comment]
Same here, Windows environment

**Comment by quoclucnguyen** [comment]
Same issue, windows env

**Comment by sestinj** [comment]
@rylos @aston314 @Stan-Stani @Chaaronn @Kingo71 @Nokic233 @cheuk-cheng I found the bug, this is solved in version v0.0.309. You should be able to highlight code without issue and have the range displayed just above the input box. Let me know if there's still something off!

**Comment by Kingo71** [comment]
It works for me now after updating to v0.0.309 and restarting Windows (probably the server was still running in the background).
Thank you @sestinj for fixing it so quickly.

**Comment by sestinj** [comment]
Going to close this issue because the error was quite obvious, so I'm confident it was solved. If something else comes up, it probably should be categorized in a new issue.
