### ISSUE TITLE
Version 0.8.63 causes "404 Resource not found," while 0.8.61 works fine

### ISSUE THREAD

**Issue by alexspringgit** [continuedev/continue#3388]
### Before submitting your bug report

- [X] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [x] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [X] I've seen the [troubleshooting guide](https://docs.continue.dev/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS: Windows 11 23H2
- Continue version: 0.8.63
- IDE version: VSCode 1.96.0
- Model: gpt-4o on Azure
- config.json:

{
  "models": [
    {
      "title": "GPT-4o Azure",
      "model": "gpt-4o",
      "provider": "openai",
      "apiBase": "https://[REDACTED].openai.azure.com",
      "deployment": "[REDACTED]",
      "apiVersion": "2024-10-21",
      "apiType": "azure",
      "apiKey": "[REDACTED]"
    }
  ]
}
```

### Description

When using version 0.8.63, I encounter a "404 Resource not found" error. However, when I revert to version 0.8.61, the issue is resolved. I read #2541 and followed the advice in this [comment](https://github.com/continuedev/continue/issues/2541#issuecomment-2420228373) to delete `~/.continue/index`, but it did not resolve the issue.

### To reproduce

1. Install version 0.8.63 and attempt a chat session to experience the error.
2. Install version 0.8.61 and attempt a chat session to confirm the issue is resolved.

### Log output

```Shell
[Extension Host] Error: 404 Resource not found 
at APIError.generate (c:\Users\[REDACTED]\.vscode\extensions\continue.continue-0.8.63-win32-x64\out\extension.js:91792:18) 
at OpenAI.makeStatusError (c:\Users\[REDACTED]\.vscode\extensions\continue.continue-0.8.63-win32-x64\out\extension.js:92694:25) 
at OpenAI.makeRequest (c:\Users\[REDACTED]\.vscode\extensions\continue.continue-0.8.63-win32-x64\out\extension.js:92738:29) 
at process.processTicksAndRejections (node:internal/process/task_queues:95:5) 
at async OpenAIApi.chatCompletionStream (c:\Users\[REDACTED]\.vscode\extensions\continue.continue-0.8.63-win32-x64\out\extension.js:96782:26) 
at async OpenAI2.streamChat (c:\Users\[REDACTED]\.vscode\extensions\continue.continue-0.8.63-win32-x64\out\extension.js:108614:32) 
at async llmStreamChat (c:\Users\[REDACTED]\.vscode\extensions\continue.continue-0.8.63-win32-x64\out\extension.js:602632:23) 
at async kh.value (c:\Users\[REDACTED]\.vscode\extensions\continue.continue-0.8.63-win32-x64\out\extension.js:609610:29)
```

**Comment by alexspringgit** [comment]
Additional Information: In the pre-release versions, the error occurs in 0.9.242, but is not present in 0.9.241.

**Comment by ctwardy** [comment]
Seeing this here too, and saw it in pre-release also. Also **Azure OpenAI**.

### Error Message

``` 
console.ts:137 [Extension Host] Error handling webview message: {
  "msg": {
    "messageId": ".....",
    "messageType": "llm/streamChat",
    "data": {
      "messages": [
        {
          "role": "user",
          "content": [
            {
              "type": "text",
              "text": "\n\nts src/app/features/serial-preview/serial-preview-actions/serial-preview-actions.component.ts (628-628)\n    this.toastService.toastInfo( 'Duplicating document...' );\n\nHi -- what does this mean to you?  (This is a test)"
            }
          ]
        },
        {
          "role": "assistant",
          "content": ""
        }
      ],
      "title": "Azure Private Cloud GPT-3.5 Turbo",
      "completionOptions": {}
    }
  }
}
```

### Sample model config
GP4 and 4-o are similar:
``` 
{
      "title": "Azure Private GPT-3.5 Turbo",
      "provider": "openai",
      "apiType": "azure",
      "model": "gpt-3.5t",
      "deployment": "gpt35t",
      "apiBase": "https://azureapi.[REDACTED]/",
      "apiVersion": "2024-06-01",
      "apiKey": "${AZURE_OPENAI_API_KEY}",
      "systemMessage": "You are an expert software developer. You give helpful and concise responses.",
      "contextLength": 8192,
      "completionOptions": {
        "maxTokens": 4096 // Use 3.5 for longer responses.
      }
    }
```

**Comment by danoco78** [comment]
I’m having the same issue, except that I’m on version 0.9.246.
this is my setup:
- OS: Mac os 15.2 (24C101)
- Continue version: 0.9.246
- IDE version: VSCode Version: 1.96.2 (Universal)
- Model: gpt-4o on Azure

**Comment by Patrick-Erichsen** [comment]
Hi folks, thanks for the notice here. Tracking updates to this issue, and other related issues with Azure after the 0.8.63 release, in this thread: https://github.com/continuedev/continue/issues/3477

**Comment by sestinj** [comment]
See here: https://github.com/continuedev/continue/issues/3477#issuecomment-2557668758

This should be solved in a new release

**Comment by DenisMkS** [comment]
it's working now, thanks!
