### ISSUE TITLE
Error in local deployment model.

### ISSUE THREAD

**Issue by gaomeng6470** [continuedev/continue#3394]
### Before submitting your bug report

- [ ] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [ ] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [ ] I've seen the [troubleshooting guide](https://docs.continue.dev/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS:
- Continue version:
- IDE version:
- Model:
- config.json:
  
 "tabAutocompleteModel": {
    "title": "deepseek-coder-v2",
    "provider": "ollama",
    "model": "deepseek-coder-v2:16b-lite-instruct-q8_0",
    "apiBase": "http://114.55.254.105:11434"
  },
  "tabAutocompleteOptions": {
    "debounceDelay": 500,
    "maxPromptTokens": 4000,
    "disableInFiles": [
      "*.md"
    ],
    "multilineCompletions": "always"
  },
```

### Description

Unable to connect，logs is

Code: undefined
Error number: undefined
Syscall: undefined
Type: undefined

Error: HTTP 404 Not Found from http://114.55.254.105:11434/api/generate

This may mean that you forgot to add '/v1' to the end of your 'apiBase' in config.json.
    at customFetch (C:\snapshot\continue\binary\out\index.js:531387:17)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async withExponentialBackoff (C:\snapshot\continue\binary\out\index.js:531128:22)
    at async Ollama._streamComplete (C:\snapshot\continue\binary\out\index.js:536634:22)
    at async Ollama.streamComplete (C:\snapshot\continue\binary\out\index.js:531520:24)
    at async ListenableGenerator._start (C:\snapshot\continue\binary\out\index.js:534349:24) 
[2024-12-16T07:00:36] Error generating autocompletion:  Error: HTTP 404 Not Found from http://114.55.254.105:11434/api/generate

This may mean that you forgot to add '/v1' to the end of your 'apiBase' in config.json.
[2024-12-16T07:00:38] Codebase indexing already in progress, skipping indexing of files

**Comment by sestinj** [comment]
@gaomeng6470 would you be able to share what version of Ollama you are using?

**Comment by gaomeng6470** [comment]
ollama version is 0.2.1

**Comment by gaomeng6470** [comment]
> @gaomeng6470您能分享一下您正在使用的 Ollama 版本吗？

ollama 版本是 0.2.1

**Comment by ericrange** [comment]
same here. curl works though
```
curl http://x.x.x.x:11434/api/generate -d '{
    "model": "codestral",
    "prompt": "Why is the sky blue?"
  }'
```

**Comment by sestinj** [comment]
@ericrange @gaomeng6470 can you try this with the latest Ollama version and let me know if the same problem happens? The latest should be 0.5.4. I don't know that we'll be able to forever support versions of Ollama that much older

**Comment by nsteinmetz** [comment]
I also have this issue since a few releases - I also changed from deepseeker to qwen, so I don't know if it's a model issue or ollama configuration or continue issue.

```
ollama --version
ollama version is 0.5.4
```


Should it be understood as:
```
"apiBase": "http://x.x.x.x:1234/v1/api/generate"
```

or 

"apiBase/v1": "http://x.x.x.x:1234/api/generate"

**Comment by prospero78** [comment]
> My bad, in my case, it was a wrong reference to the model between the one I pulled and the one I configured - I would have prefered as an output that model was not found better than this message.

Yes, Im confirm this bad behevior. Im set true model LLM in ${workSpaceFolder}/.vscode/conf.json and plugin begin true work.

**Comment by RomneyDa** [comment]
I believe this has been fixed but please reopen if needed.
