### ISSUE TITLE
Can't use proxy host with self-signed certificates

### ISSUE THREAD

**Issue by klauern** [continuedev/continue#341]
**Describe the bug**
I am trying to use this with my proxy instance of OpenAI, but when I try to connect to it, i get an error:

**Console logs**

```
Traceback (most recent call last):

  File "aiohttp/connector.py", line 980, in _wrap_create_connection
  File "asyncio/base_events.py", line 1103, in create_connection
  File "asyncio/base_events.py", line 1133, in _create_connection_transport
  File "asyncio/futures.py", line 285, in __await__
  File "asyncio/tasks.py", line 304, in __wakeup
  File "asyncio/futures.py", line 201, in result
  File "asyncio/sslproto.py", line 534, in data_received
  File "asyncio/sslproto.py", line 188, in feed_ssldata
  File "ssl.py", line 975, in do_handshake
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1007)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "openai/api_requestor.py", line 588, in arequest_raw
  File "aiohttp/client.py", line 536, in _request
  File "aiohttp/connector.py", line 540, in connect
  File "aiohttp/connector.py", line 901, in _create_connection
  File "aiohttp/connector.py", line 1209, in _create_direct_connection
  File "aiohttp/connector.py", line 1178, in _create_direct_connection
  File "aiohttp/connector.py", line 982, in _wrap_create_connection

aiohttp.client_exceptions.ClientConnectorCertificateError: Cannot connect to host ai-gateway.myplace.com:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1007)')]

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "continuedev/src/continuedev/core/autopilot.py", line 248, in _run_singular_step
    observation = await step(self.continue_sdk)
  File "continuedev/src/continuedev/core/main.py", line 319, in __call__
    return await self.run(sdk)
  File "continuedev/src/continuedev/plugins/steps/chat.py", line 35, in run
    async for chunk in generator:
  File "continuedev/src/continuedev/libs/llm/openai.py", line 116, in stream_chat
    async for chunk in await openai.ChatCompletion.acreate(
  File "openai/api_resources/chat_completion.py", line 45, in acreate
  File "openai/api_resources/abstract/engine_api_resource.py", line 217, in acreate
  File "openai/api_requestor.py", line 300, in arequest
  File "openai/api_requestor.py", line 605, in arequest_raw
openai.error.APIConnectionError: Error communicating with OpenAI
```

**Additional context**

**Comment by sestinj** [comment]
It looks like this site has an http connection, and I'm unable to load the webpage in my browser (http://ai-gateway.myplace.com). I can add an option to disable SSL, which would probably fix this. Is there anything else that would be useful to know about this site so I could give it a test on my own?

**Comment by klauern** [comment]
I replace the URL as it was an internal site that resolves within a VPN.  It's effectively a proxy of the OpenAI API endpoint, but using it's own keys.  Behavior should be the same, as I have been able to use this endpoint effectively by overriding the `OPENAI_API_KEY` and `OPENAI_API_BASE` url's to point to this instead of the default ones.

**Comment by klauern** [comment]
The SSL key is internal, so it would be trusted normally, but isn't for this case probably because we're using the default Python CA stores which won't have these.

**Comment by sestinj** [comment]
Ok, this makes sense. There are two ways of going about this, the first being an option to disable SSL. From a quick search (see [here](https://community.openai.com/t/how-can-i-disable-ssl-verification-when-using-openai-api-in-python/110837/4)), it looks like the `verify_ssl_certs` property for the OpenAI Python client is broken, so while I've made an update to try using it, I've also updated the `GGML` class as something else to try.

The GGML class was intended to connect to a local llamacpp server, but I believe this has the same API as OpenAI, so switching the base URL there could work. Try like this: 

```python
from continuedev.libs.llm.ggml import GGML

config = ContinueConfig(
    ...
    models=Models(
        default=GGML(server_url="http://ai-gateway.myplace.com", verify_ssl=False)  # <-- Can use same verify_ssl property with the OpenAI class, I'm just not certain whether it will work
    )
)
```

And the second method would be to add certificates manually. If you have access to these on your machine, I've also added a `ca_bundle_path` property to the OpenAI class. This would seem the best solution.

Changes are on their way through CI right now, I'll update you when the newest version is released (should be ~15 minutes)

**Comment by sestinj** [comment]
Sorry @klauern, just realized I didn't send an update, but the new version is released. Let me know if ca_bundle_paths works, this is definitely the preferred approach

**Comment by sestinj** [comment]
@klauern I'm really sorry I missed this last message. If you're still trying to get this to work, I think the best thing would be to attempt the raw API call from a Python REPL to see if we can narrow down the scope of the problem. I've seen certain situations where it's actually a problem for any python request in general, and I have a few ideas of how to solve if that is the case

For example, you could attempt `requests.post("http://ai-gateway.myplace.com//v1/completions", verify=False, json={"prompt": "This is a test"})`

**Comment by klauern** [comment]
I was able to get a chance to test this again and it works!  There were some changes to the UI and whatnot, so I just blew away the entire config in `~/.continue/` and re-built it.  I also think the docs might need to be updated to point to the new package paths for the custom OpenAI endpoint, too, but that's a separate issue.  That said, I see things working and am excited to try it out again.  Thank you

**Comment by sestinj** [comment]
@klauern awesome!

Do you mean the `continuedev.libs.llm` paths?

**Comment by klauern** [comment]
Yes, the docs weren't pointing to the same places, so I had to look at the source to find the right path.
