### ISSUE TITLE
Invalid request sent to OpenAI. Please try again.

### ISSUE THREAD

**Issue by irekgroup** [continuedev/continue#342]
The problem is that I get the Invalid request sent to OpenAI error. Please try again, while receiving a return message from Continue

**Screenshots**

![ScreenRecorderProject1](https://github.com/continuedev/continue/assets/70753735/ae786092-f96b-49a4-972b-7d757c9dd84d)

**Environment**
- Operating System: [e.g. Win10]
- Python Version: [e.g. 3.11.4]
- Continue Version: [e.g. v0.0.225]

**Console logs**
```
Traceback (most recent call last):

  File "continuedev\src\continuedev\core\autopilot.py", line 248, in _run_singular_step
    observation = await step(self.continue_sdk)

  File "continuedev\src\continuedev\core\main.py", line 319, in __call__
    return await self.run(sdk)

  File "continuedev\src\continuedev\plugins\steps\chat.py", line 45, in run
    self.name = remove_quotes_and_escapes(await sdk.models.medium.complete(

  File "continuedev\src\continuedev\libs\llm\maybe_proxy_openai.py", line 39, in complete
    return await self.llm.complete(prompt, with_history=with_history, **kwargs)

  File "continuedev\src\continuedev\libs\llm\openai.py", line 140, in complete
    resp = (await openai.ChatCompletion.acreate(

  File "openai\api_resources\chat_completion.py", line 45, in acreate

  File "openai\api_resources\abstract\engine_api_resource.py", line 217, in acreate

  File "openai\api_requestor.py", line 310, in arequest

  File "openai\api_requestor.py", line 646, in _interpret_async_response

  File "openai\api_requestor.py", line 683, in _interpret_response_line

openai.error.InvalidRequestError: The model `gpt-4` does not exist or you do not have access to it. Learn more: https://help.openai.com/en/articles/7102672-how-can-i-access-gpt-4.


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "continuedev\src\continuedev\core\autopilot.py", line 248, in _run_singular_step
    observation = await step(self.continue_sdk)

  File "continuedev\src\continuedev\core\main.py", line 319, in __call__
    return await self.run(sdk)

  File "continuedev\src\continuedev\plugins\steps\chat.py", line 45, in run
    self.name = remove_quotes_and_escapes(await sdk.models.medium.complete(

  File "continuedev\src\continuedev\libs\llm\maybe_proxy_openai.py", line 39, in complete
    return await self.llm.complete(prompt, with_history=with_history, **kwargs)

  File "continuedev\src\continuedev\libs\llm\openai.py", line 140, in complete
    resp = (await openai.ChatCompletion.acreate(

  File "openai\api_resources\chat_completion.py", line 45, in acreate

  File "openai\api_resources\abstract\engine_api_resource.py", line 217, in acreate

  File "openai\api_requestor.py", line 310, in arequest

  File "openai\api_requestor.py", line 646, in _interpret_async_response

  File "openai\api_requestor.py", line 683, in _interpret_response_line

openai.error.InvalidRequestError: The model `gpt-4` does not exist or you do not have access to it. Learn more: https://help.openai.com/en/articles/7102672-how-can-i-access-gpt-4.


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "continuedev\src\continuedev\core\autopilot.py", line 248, in _run_singular_step
    observation = await step(self.continue_sdk)

  File "continuedev\src\continuedev\core\main.py", line 319, in __call__
    return await self.run(sdk)

  File "continuedev\src\continuedev\plugins\steps\chat.py", line 45, in run
    self.name = remove_quotes_and_escapes(await sdk.models.medium.complete(

  File "continuedev\src\continuedev\libs\llm\maybe_proxy_openai.py", line 39, in complete
    return await self.llm.complete(prompt, with_history=with_history, **kwargs)

  File "continuedev\src\continuedev\libs\llm\openai.py", line 140, in complete
    resp = (await openai.ChatCompletion.acreate(

  File "openai\api_resources\chat_completion.py", line 45, in acreate

  File "openai\api_resources\abstract\engine_api_resource.py", line 217, in acreate

  File "openai\api_requestor.py", line 310, in arequest

  File "openai\api_requestor.py", line 646, in _interpret_async_response

  File "openai\api_requestor.py", line 683, in _interpret_response_line

openai.error.InvalidRequestError: The model `gpt-4` does not exist or you do not have access to it. Learn more: https://help.openai.com/en/articles/7102672-how-can-i-access-gpt-4.
```

**Comment by sestinj** [comment]
@irekgroup Are you using your own API key here? I'm interested in whether this works through our proxy server. You might try going to VS Code settings, setting the OPENAI_API_KEY to "", and reloading the window.

**Comment by irekgroup** [comment]
Yes, it solved my problem!

**Comment by sestinj** [comment]
Ok, great! It seems like the API key you were using must not have had access to gpt-4. You will have limited usage through our proxy server, so after this something else you might try is to use gpt-3.5-turbo as the default model until you have a key with access. You can change the config file like to look like this:

```python
...
config=ContinueConfig(
    ...
    models=Models(
        default=MaybeProxyOpenAI(model="gpt-3.5-turbo"),
    )
)
```

Closing this issue as it seems resolved.

**Comment by zhh210** [comment]
I was able to set the default model with my azure gpt-3.5-turbo. But started getting the same error after recent update. Where is the `OPENAI_API_KEY` in vs-code settings? I can only see settings of continue.* but no `OPENAI_API_KEY`.

```
Traceback (most recent call last):

  File "server/continuedev/core/autopilot.py", line 217, in _run_singular_step

  File "server/continuedev/plugins/steps/chat.py", line 56, in run

  File "server/continuedev/libs/llm/base.py", line 382, in stream_chat

  File "server/continuedev/libs/llm/openai.py", line 164, in _stream_chat

  File "openai/api_resources/chat_completion.py", line 45, in acreate

  File "openai/api_resources/abstract/engine_api_resource.py", line 217, in acreate

  File "openai/api_requestor.py", line 310, in arequest

  File "openai/api_requestor.py", line 646, in _interpret_async_response

  File "openai/api_requestor.py", line 683, in _interpret_response_line

openai.error.InvalidRequestError: Resource not found
```
