### ISSUE TITLE
Failure to connect to locally running Ollama instance on WSL

### ISSUE THREAD

**Issue by Patrick-Erichsen** [continuedev/continue#3435]
### Before submitting your bug report

- [ ] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [ ] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [ ] I've seen the [troubleshooting guide](https://docs.continue.dev/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
OS: Windows 11 with WSL2
Continue version: tried multiple, including v0.8.50, v0.8.60, v0.8.63 and v0.9.245
IDE version: VS Code v1.96.0
Ollama version: tried v0.3.12 and v0.5.1
```

### Description

I've had this setup for few months and it has worked great. Not sure what has changed but Continue isn't working anymore with Ollama (Ollama hosted locally under WSL2). Ollama is still accessible from the host Windows machine. I don't currently have access to other providers to check if those would work.

Getting this error if I try to chat:
```
Failed to connect to local Ollama instance, please ensure Ollama is both installed and running. You can download Ollama from https://ollama.ai.
```

Some trace:
```
[Extension Host] Error: Failed to connect to local Ollama instance, please ensure Ollama is both installed and running. You can download Ollama from https://ollama.ai.
    at customFetch2 (c:\Users\morland\.vscode\extensions\continue.continue-0.8.63-win32-x64\out\extension.js:108369:23)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async withExponentialBackoff (c:\Users\morland\.vscode\extensions\continue.continue-0.8.63-win32-x64\out\extension.js:104224:26)
    at async Ollama2._streamChat (c:\Users\morland\.vscode\extensions\continue.continue-0.8.63-win32-x64\out\extension.js:116838:26)
    at async Ollama2.streamChat (c:\Users\morland\.vscode\extensions\continue.continue-0.8.63-win32-x64\out\extension.js:108621:32)
    at async llmStreamChat (c:\Users\morland\.vscode\extensions\continue.continue-0.8.63-win32-x64\out\extension.js:602632:23)
    at async kh.value (c:\Users\morland\.vscode\extensions\continue.continue-0.8.63-win32-x64\out\extension.js:609610:29)
```

At least Continue v0.8.0 (I did not try everything in between) is still able to talk to Ollama and I'm getting some response, although quite messy one.

**Comment by CRASH-Tech** [comment]
I maked some debug. And I thint it's because new continue versions are ignored "apiBase" params. And trys to connect over "127.0.0.1" instead of "localhost", which forwards by windows to wsl.
So, my workarround it's a switch wsl to mirror nework mode.
C:\Users\username\.wslconfig:
```
[wsl2]
networkingMode=mirrored
[experimental]
hostAddressLoopback=true
```
Also you can increase default wsl memmory for some models:
```
[wsl2]
**memory=26GB**
networkingMode=mirrored
[experimental]
hostAddressLoopback=true
```

**Comment by OlehPendrakovskyi** [comment]
The same problem here.

**Comment by ziggekatten** [comment]
Yep, me as well

**Comment by noodlr-ai-temp** [comment]
Same issue, but above workaround not working.
