### ISSUE TITLE
requestOptions.proxy Not Working

### ISSUE THREAD

**Issue by ByJacob** [continuedev/continue#3442]
### Before submitting your bug report

- [X] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [X] I've seen the [troubleshooting guide](https://docs.continue.dev/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS: linux
- Continue version: v0.9.246 (pre-release)
- IDE version:

Version: 1.95.0-insider
Commit: 62a233cc87dc8d52a817739bc0d917089d4d103b
Date: 2024-10-17T05:09:34.012Z
Electron: 32.1.2
ElectronBuildId: 10323173
Chromium: 128.0.6613.162
Node.js: 20.17.0
V8: 12.8.374.33-electron.0
OS: Linux x64 6.6.63-1-MANJARO
```
- Model: Azure
- config.json:
  
...
"models": [
    {
      "model": "gpt-4-32k",
      "contextLength": 128000,
      "title": "Gpt-4-32k",
      "systemMessage": "REDACTED",
      "apiKey": "REDACTED",
      "engine": "gpt-4-32k",
      "apiBase": "REDACTED",
      "apiVersion": "2024-02-15-preview",
      "apiType": "azure",
      "provider": "azure",
      "requestOptions": {
        "proxy": "REDACTED"
      }
    },
...
  ```
```

### Description

It has been observed that the requestOptions.proxy parameter in the format http://user:pass@host:port does not work as expected. This prevents users from successfully routing requests through the specified proxy.

### To reproduce

Configure the requestOptions.proxy parameter using the format http://user:pass@host:port.
Send a request to the API.
Observe that the request does not route through the specified proxy.

Workaround: Use Proxy Support with override and set the proxy in Visual Studio Code (VSC).

**Comment by tomasz-stefaniak** [comment]
This might be related to a broader set of Azure issues reported here: https://github.com/continuedev/continue/issues/3477

**Comment by BLumia** [comment]
Can reproduce on vscode. My configuration looks like:

```yaml
  - name: GPT-4o
    provider: openai
    model: gpt-4o-mini
    apiKey: sk-proj-REDACTED
    requestOptions:
      proxy: socks5h://127.0.0.1:11451
```

Neither `socks5h`, `socks5` nor `http` works. When testing, the VSCode setting option `Http: Proxy Support` has been changed to `fallback` as well.

**Comment by korniux** [comment]
- MacOS vscode 1.103.2
- continue 1.0.24

Got error in VSCode DevTools when used `requestOptions.proxy: http://...`:

```
TypeError: Cannot read properties of undefined (reading 'call')
	at HttpsProxyAgent3.getName (/Users/<user>/.vscode/extensions/continue.continue-1.0.24-darwin-arm64/out/extension.js:138038:50)
	at HttpsProxyAgent3.addRequest (node:_http_agent:248:21)
	at /Applications/Visual Studio Code.app/Contents/Resources/app/node_modules/agent-base/dist/index.js:137:31
```

Also looks like only `http|https` proxies is handled.
