### ISSUE TITLE
Continue Server Starting: "Error: spawn EBUSY"

### ISSUE THREAD

**Issue by ferrantejake** [continuedev/continue#345]
**Describe the bug**
When loading the Continue extension (v0.0.258) , the extensions hangs on "Continue Server Starting"

**To Reproduce**
1. Install Continue v0.0.258
2. Open 'Output'
3. Change output to 'Extension Host'

Alternatively, see devtools console logs.

**Expected behavior**
Continue Server starts when loading VSCode

**Screenshots**
![image](https://github.com/continuedev/continue/assets/9873344/b93f868e-f808-4cdf-9750-f3a032d27766)

**Environment**
VSCode/Box details:
Version: 1.80.1 (user setup)
Commit: 74f6148eb9ea00507ec113ec51c489d6ffb4b771
Date: 2023-07-12T17:22:07.651Z
Electron: 22.3.14
ElectronBuildId: 21893604
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Windows_NT x64 10.0.22621

**Console logs**

*Extension Host Output*
```
2023-08-04 17:04:05.804 [error] Error: spawn EBUSY
    at ChildProcess.spawn (node:internal/child_process:441:11)
    at spawn (node:child_process:752:9)
    at vb (c:\Users\jakef\.vscode\extensions\continue.continue-0.0.258\out\extension.js:93:28142)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
2023-08-04 17:05:56.200 [info] Extension host terminating: renderer closed the MessagePort
2023-08-04 17:05:56.217 [error] Canceled: Canceled
    at Object.I [as $3] (c:\Users\jakef\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:7:1032)
    at c:\Users\jakef\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:111:8033
    at Array.forEach (<anonymous>)
    at t.dispose (c:\Users\jakef\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:111:7998)
    at i.terminate (c:\Users\jakef\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:113:8567)
    at u.terminate (c:\Users\jakef\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:117:1532)
    at E (c:\Users\jakef\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:127:32236)
    at MessagePortMain.<anonymous> (c:\Users\jakef\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:127:28665)
    at MessagePortMain.emit (node:events:513:28)
    at MessagePortMain.emit (node:domain:489:12)
    at Object.MessagePortMain._internalPort.emit (node:electron/js2c/utility_init:2:367) setContext undefined
2023-08-04 17:05:56.220 [error] Canceled: Canceled
    at new h (c:\Users\jakef\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:99:42413)
    at t.O (c:\Users\jakef\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:111:11236)
    at Proxy.U.<computed>.q.charCodeAt.U.<computed> (c:\Users\jakef\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:111:8675)
    at e.$vL.g (c:\Users\jakef\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:99:63549)
    at e.$vL.executeCommand (c:\Users\jakef\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:99:62973)
    at P.registerCommand.description (c:\Users\jakef\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:99:62280)
    at e.$vL.h (c:\Users\jakef\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:99:64085)
    at e.$vL.g (c:\Users\jakef\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:99:63073)
    at e.$vL.executeCommand (c:\Users\jakef\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:99:62973)
    at Object.executeCommand (c:\Users\jakef\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:117:20971)
    at i.D [as value] (c:\Users\jakef\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\git\dist\main.js:2:1260424)
    at p.w (c:\Users\jakef\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:60:1902)
    at p.x (c:\Users\jakef\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:60:1972)
    at p.fire (c:\Users\jakef\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:60:2188)
    at Object.m [as dispose] (c:\Users\jakef\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\git\dist\main.js:2:1275972)
    at c:\Users\jakef\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\git\dist\main.js:2:1280539
    at Array.forEach (<anonymous>)
    at g.dispose (c:\Users\jakef\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\git\dist\main.js:2:1280525)
    at o.<anonymous> (c:\Users\jakef\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:95:4162)
    at o.dispose (c:\Users\jakef\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:95:4297)
    at o.<anonymous> (c:\Users\jakef\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\git\dist\main.js:2:1262437)
    at o.dispose (c:\Users\jakef\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:95:4297)
    at S (c:\Users\jakef\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:10:11731)
    at i.Z (c:\Users\jakef\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:113:10370)
    at c:\Users\jakef\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:113:8332
    at Array.map (<anonymous>)
    at i.S (c:\Users\jakef\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:113:8319)
    at i.terminate (c:\Users\jakef\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:113:8591)
    at u.terminate (c:\Users\jakef\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:117:1532)
    at E (c:\Users\jakef\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:127:32236)
    at MessagePortMain.<anonymous> (c:\Users\jakef\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:127:28665)
    at MessagePortMain.emit (node:events:513:28)
    at MessagePortMain.emit (node:domain:489:12)
    at Object.MessagePortMain._internalPort.emit (node:electron/js2c/utility_init:2:367) setContext undefined
2023-08-04 17:05:56.224 [error] Canceled: Canceled
    at new h (c:\Users\jakef\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:99:42413)
    at t.O (c:\Users\jakef\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:111:11236)
    at Proxy.U.<computed>.q.charCodeAt.U.<computed> (c:\Users\jakef\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:111:8675)
    at e.$vL.g (c:\Users\jakef\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:99:63549)
    at e.$vL.executeCommand (c:\Users\jakef\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:99:62973)
    at P.registerCommand.description (c:\Users\jakef\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:99:62280)
    at e.$vL.h (c:\Users\jakef\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:99:64085)
    at e.$vL.g (c:\Users\jakef\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:99:63073)
    at e.$vL.executeCommand (c:\Users\jakef\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:99:62973)
    at Object.executeCommand (c:\Users\jakef\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:117:20971)
    at t.$ie.set b [as b] (c:\Users\jakef\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\github\dist\extension.js:2:675669)
    at c:\Users\jakef\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\github\dist\extension.js:2:676313
    at i.value (c:\Users\jakef\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\git\dist\main.js:2:1347255)
    at p.w (c:\Users\jakef\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:60:1902)
    at p.x (c:\Users\jakef\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:60:1972)
    at p.fire (c:\Users\jakef\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:60:2188)
    at Object.m [as dispose] (c:\Users\jakef\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\git\dist\main.js:2:1275972)
    at c:\Users\jakef\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\git\dist\main.js:2:1280539
    at Array.forEach (<anonymous>)
    at g.dispose (c:\Users\jakef\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\git\dist\main.js:2:1280525)
    at o.<anonymous> (c:\Users\jakef\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:95:4162)
    at o.dispose (c:\Users\jakef\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:95:4297)
    at o.<anonymous> (c:\Users\jakef\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\git\dist\main.js:2:1262437)
    at o.dispose (c:\Users\jakef\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:95:4297)
    at S (c:\Users\jakef\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:10:11731)
    at i.Z (c:\Users\jakef\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:113:10370)
    at c:\Users\jakef\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:113:8332
    at Array.map (<anonymous>)
    at i.S (c:\Users\jakef\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:113:8319)
    at i.terminate (c:\Users\jakef\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:113:8591)
    at u.terminate (c:\Users\jakef\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:117:1532)
    at E (c:\Users\jakef\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:127:32236)
    at MessagePortMain.<anonymous> (c:\Users\jakef\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:127:28665)
    at MessagePortMain.emit (node:events:513:28)
    at MessagePortMain.emit (node:domain:489:12)
    at Object.MessagePortMain._internalPort.emit (node:electron/js2c/utility_init:2:367) setContext undefined
2023-08-04 17:05:56.225 [error] Canceled: Canceled
    at new h (c:\Users\jakef\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:99:42413)
    at t.O (c:\Users\jakef\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:111:11236)
    at Proxy.U.<computed>.q.charCodeAt.U.<computed> (c:\Users\jakef\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:111:8675)
    at e.$vL.g (c:\Users\jakef\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:99:63549)
    at e.$vL.executeCommand (c:\Users\jakef\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:99:62973)
    at Object.executeCommand (c:\Users\jakef\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:117:20971)
    at Pne.clearInlineCompletionStates (c:\Users\jakef\.vscode\extensions\amazonwebservices.aws-toolkit-vscode-1.83.0\dist\src\main.js:4268:3693)
    at dqe (c:\Users\jakef\.vscode\extensions\amazonwebservices.aws-toolkit-vscode-1.83.0\dist\src\main.js:4816:5065)
    at s1e (c:\Users\jakef\.vscode\extensions\amazonwebservices.aws-toolkit-vscode-1.83.0\dist\src\main.js:5025:416)
    at Module.dPe (c:\Users\jakef\.vscode\extensions\amazonwebservices.aws-toolkit-vscode-1.83.0\dist\src\main.js:5028:67)
    at i.Z (c:\Users\jakef\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:113:10175)
    at c:\Users\jakef\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:113:8332
    at Array.map (<anonymous>)
    at i.S (c:\Users\jakef\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:113:8319)
    at i.terminate (c:\Users\jakef\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:113:8591)
    at u.terminate (c:\Users\jakef\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:117:1532)
    at E (c:\Users\jakef\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:127:32236)
    at MessagePortMain.<anonymous> (c:\Users\jakef\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:127:28665)
    at MessagePortMain.emit (node:events:513:28)
    at MessagePortMain.emit (node:domain:489:12)
    at Object.MessagePortMain._internalPort.emit (node:electron/js2c/utility_init:2:367)
2023-08-04 17:05:56.288 [info] Extension host with pid 28776 exiting with code 0
```

**Comment by sestinj** [comment]
It looks like we're not correctly waiting for download prior to running the server. If you reload the window with "cmd+shift+p" and then "Reload Window", this may resolve the issue. You might also check whether the "run" file exists at `c:\Users\jakef\.vscode\extensions\continue.continue-0.0.258\server\exe\run`. Both of these things would be helpful to know, but I'll giving this a deeper look immediately. Thanks for the logs!

**Comment by sestinj** [comment]
@ferrantejake This was in fact the issue. I was able to reproduce it on my own Windows machine and have pushed a fix that solved the issue. Let me know how it goes, excited to get Continue working for you!

**Comment by ferrantejake** [comment]
Just updated to v0.0.263. I was able to successfully make a request and get a response, so this looks fixed! Thanks @sestinj👍
