### ISSUE TITLE
Issue with installing esbuild in prepackage script

### ISSUE THREAD

**Issue by ajshedivy** [continuedev/continue#3461]
### Before submitting your bug report

- [X] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [X] I've seen the [troubleshooting guide](https://docs.continue.dev/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS:MacOS
- Continue version: main branch
- IDE version: 
- Model:
- config.json:
```

### Description

In the prepackage script, the following occurs when installing the modules in temp dir:
```
Contents of: esbuild@0.17.19 []
[info] Copied esbuild, @esbuild, @lancedb, @vscode/ripgrep, workerpool
File out/node_modules/@esbuild/darwin-arm64/bin/esbuild does not exist
Parent folder out/node_modules/@esbuild/darwin-arm64/bin does not exist
Grandparent folder out/node_modules/@esbuild/darwin-arm64 does not exist
Contents of grandgrandparent folder: []
/Users/USER/sandbox/oss/ai/continue_dev/continue/scripts/util/index.js:92
    throw new Error(
          ^

Error: The following files were missing:
- out/node_modules/@esbuild/darwin-arm64/bin/esbuild

The following files were empty:
- 
    at validateFilesPresent (/Users/USER/sandbox/oss/ai/continue_dev/continue/scripts/util/index.js:92:11)
    at /Users/USER/sandbox/oss/ai/continue_dev/continue/extensions/vscode/scripts/prepackage.js:475:3
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

I noticed this after pulling latest changes from main. Seems to be an intermittent issue. To fix this error I manually cleaned the temp dir:
```bash
rm -fr /tmp/continue-node_modules-esbuild0.17.19
```

## Suggested fix:
in the [async function installNodeModuleInTempDirAndCopyToCurrent](https://github.com/ajshedivy/continue/blob/85f27b9e01c05b79e162eeb2605d96fb8fd19354/extensions/vscode/scripts/prepackage.js#L280) in the prepackage script, explicitly remove the temp directory that the package is installed in, or create a `continue` subfolder in `tmp`.

looks like the tmp folder cleanup step is commented out: https://github.com/ajshedivy/continue/blob/85f27b9e01c05b79e162eeb2605d96fb8fd19354/extensions/vscode/scripts/prepackage.js#L335, not sure if this was intentional.

**Comment by sestinj** [comment]
Some strange timing-related issues here that led to commenting that out, though I'm not certain what the exact core problem is

**Comment by Patrick-Erichsen** [comment]
Just had this same issue, thanks for sharing your solution @ajshedivy !
