### ISSUE TITLE
requested model (18.4 GiB) is too large for this system (6.8 GiB)

### ISSUE THREAD

**Issue by gaomeng6470** [continuedev/continue#3464]
### Before submitting your bug report

- [ ] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [ ] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [ ] I've seen the [troubleshooting guide](https://docs.continue.dev/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS:
- Continue version:
- IDE version:
- Model:
- config.json:
  

{"error":"requested model (18.4 GiB) is too large for this system (6.8 GiB)"}
    at customFetch (C:\snapshot\continue\binary\out\index.js:531387:17)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async withExponentialBackoff (C:\snapshot\continue\binary\out\index.js:531128:22)
    at async Ollama._streamComplete (C:\snapshot\continue\binary\out\index.js:536634:22)
    at async Ollama.streamComplete (C:\snapshot\continue\binary\out\index.js:531520:24)
    at async ListenableGenerator._start (C:\snapshot\continue\binary\out\index.js:534349:24) 
[2024-12-20T02:51:46] Error generating autocompletion:  Error: HTTP 500 Internal Server Error from http://xxxxxxxxxxx/api/generate
```

### Description

![image](https://github.com/user-attachments/assets/4ace2701-37c1-4b14-9441-952b1ded44f9)

**Comment by tomasz-stefaniak** [comment]
@gaomeng6470 could you share the steps needed to reproduce this?

Based on the error message, it seems like Ollama requires a model that is larger than the remaining hard drive capacity.

**Comment by RomneyDa** [comment]
Closing since space limitation doesn't appear to be Continue-specific.
@gaomeng6470 thank you for the report, feel free to open another issue if anything comes up!
