### ISSUE TITLE
gpt-4-32k is not working

### ISSUE THREAD

**Issue by TyDunn** [continuedev/continue#376]
**Describe the bug**

Traceback (most recent call last):

  File "continuedev/src/continuedev/core/autopilot.py", line 264, in _run_singular_step
    observation = await step(self.continue_sdk)

  File "continuedev/src/continuedev/core/main.py", line 326, in __call__
    return await self.run(sdk)

  File "continuedev/src/continuedev/plugins/steps/chat.py", line 67, in run
    async for chunk in generator:

  File "continuedev/src/continuedev/libs/llm/maybe_proxy_openai.py", line 49, in stream_chat
    async for item in resp:

  File "continuedev/src/continuedev/libs/llm/openai.py", line 122, in stream_chat
    args["model"], messages, self.context_length, args["max_tokens"], None, functions=args.get("functions", None), system_message=self.system_message)

  File "continuedev/src/continuedev/libs/llm/openai.py", line 70, in context_length
    return MAX_TOKENS_FOR_MODEL[self.model]

KeyError: 'gpt-4-32k'

**To Reproduce**

Use `gpt-4-32k` as your model

**Expected behavior**

It should work

**Environment**

- Operating System: MacOS

**Comment by sestinj** [comment]
This was solved by simply adding the option to a dictionary. Avoiding future instances of this problem by safely accessing the dictionary.
