### ISSUE TITLE
Continue breaks with togethercomputer/llama-2-70b-chat

### ISSUE THREAD

**Issue by TyDunn** [continuedev/continue#379]
**Describe the bug**

It is not possible to use Together API with llama-2-70b-chat model

**To Reproduce**
1. Change config to
``python
    models=Models(
        default=TogetherLLM(
            api_key="api-key",
            model="togethercomputer/llama-2-70b-chat"
        )
    ),
``
2. Send an instruction
3. Press Continue
4. See the error

**Error**

```
Traceback (most recent call last):

  File "/var/folders/zd/zfms33rs6gj781r191yw4_jw0000gn/T/_MEIO3tfVC/continuedev/src/continuedev/libs/llm/together.py", line 101, in stream_chat
    "content": json.loads(chunk[6:])["choices"][0]["text"]

  File "json/__init__.py", line 346, in loads

  File "json/decoder.py", line 337, in decode

  File "json/decoder.py", line 355, in raw_decode

json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "continuedev/src/continuedev/core/autopilot.py", line 264, in _run_singular_step
    observation = await step(self.continue_sdk)

  File "continuedev/src/continuedev/core/main.py", line 326, in __call__
    return await self.run(sdk)

  File "continuedev/src/continuedev/plugins/steps/chat.py", line 67, in run
    async for chunk in generator:

  File "/var/folders/zd/zfms33rs6gj781r191yw4_jw0000gn/T/_MEIO3tfVC/continuedev/src/continuedev/libs/llm/together.py", line 104, in stream_chat
    raise Exception(str(line[0]))

Exception: b'{"status":"finished","prompt":["\\n<bot>: - Highlight code section and ask a question or give instructions\\n- Use `cmd+m` (Mac) / `ctrl+m` (Windows) to open Continue\\n- Use `/help` to ask questions about how to use Continue\\n- [Customize Continue](https://continue.dev/docs/customization) (e.g. use your own API key) by typing \'/config\'.\\n<human>: hello\\n<bot>:"],"model":"togethercomputer/llama-2-70b-chat","model_owner":"","tags":{},"num_returns":1,"args":{"prompt":"\\n<bot>: - Highlight code section and ask a question or give instructions\\n- Use `cmd+m` (Mac) / `ctrl+m` (Windows) to open Continue\\n- Use `/help` to ask questions about how to use Continue\\n- [Customize Continue](https://continue.dev/docs/customization) (e.g. use your own API key) by typing \'/config\'.\\n<human>: hello\\n<bot>:","max_tokens":1024,"temperature":0.5,"top_p":1,"frequency_penalty":0,"presence_penalty":0,"model":"togethercomputer/llama-2-70b-chat","stream_tokens":true},"subjobs":[],"output":{"error":"unmarshal output \\"\\": unexpected end of JSON input","result_type":"error"}}'
```

**Expected behavior**

It should not error

**Screenshots**

<img width="1161" alt="Screenshot 2023-08-16 at 9 16 25 AM" src="https://github.com/continuedev/continue/assets/13314504/8a598220-c3ab-4967-8bc9-8f776d4c91aa">

**Comment by sestinj** [comment]
Solved, had to deal with different JSON formats coming in from different models (sometimes prefixed by "data: ")
