### ISSUE TITLE
Stuck on load continue server because glibc 2.38 is not found

### ISSUE THREAD

**Issue by TyDunn** [continuedev/continue#392]
This is from a user:
- Tried to use Continue again but got stuck on "Load Continue Server"
- In the console, it complains about not finding glibc 2.38, but I actually have installed it
- Is there any documentation on the software dependencies besides VS Code itself?
- Operating System: Arch Linux (Manjaro distribution)

**Comment by zeroAska** [comment]
Additional details:
1. OS: Arch Linux, no longer manjaro distribution.
2. VS code version:  
``` 
$ code --version
1.81.1
6c3e3dba23e8fadc360aed75ce363ba185c49794
x64
```
3.  Glibc version: 2.38-3
```
$ pacman -Q glibc
glibc 2.38-3
```


Error: got stuck on "Load Continue Server"
Console output: 
```
5
workbench.desktop.main.js:sourcemap:627   ERR [uncaught exception in main]: /usr/lib/libm.so.6: version `GLIBC_2.38' not found (required by /usr/lib/code/node_modules.asar.unpacked/@vscode/sqlite3/build/Release/vscode-sqlite3.node): Error: /usr/lib/libm.so.6: version `GLIBC_2.38' not found (required by /usr/lib/code/node_modules.asar.unpacked/@vscode/sqlite3/build/Release/vscode-sqlite3.node)
    at process.func [as dlopen] (node:electron/js2c/asar_bundle:2:1822)
    at Module._extensions..node (node:internal/modules/cjs/loader:1226:18)
    at Object.func [as .node] (node:electron/js2c/asar_bundle:2:2049)
    at Module.load (node:internal/modules/cjs/loader:1011:32)
    at Module._load (node:internal/modules/cjs/loader:846:12)
    at f._load (node:electron/js2c/asar_bundle:2:13330)
    at Module.require (node:internal/modules/cjs/loader:1035:19)
    at C (/usr/lib/code/out/main.js:5:647)
    at Object.<anonymous> (/usr/lib/code/node_modules.asar/@vscode/sqlite3/lib/sqlite3-binding.js:4:17)
    at l._compile (/usr/lib/code/out/main.js:5:1257)
    at Module._extensions..js (node:internal/modules/cjs/loader:1196:10)
    at Module.load (node:internal/modules/cjs/loader:1011:32)
    at Module._load (node:internal/modules/cjs/loader:846:12)
    at f._load (node:electron/js2c/asar_bundle:2:13330)
    at Module.require (node:internal/modules/cjs/loader:1035:19)
    at C (/usr/lib/code/out/main.js:5:647)
    at Object.<anonymous> (/usr/lib/code/node_modules.asar/@vscode/sqlite3/lib/sqlite3.js:2:17)
    at l._compile (/usr/lib/code/out/main.js:5:1257)
    at Module._extensions..js (node:internal/modules/cjs/loader:1196:10)
    at Module.load (node:internal/modules/cjs/loader:1011:32)
    at Module._load (node:internal/modules/cjs/loader:846:12)
    at f._load (node:electron/js2c/asar_bundle:2:13330)
    at Module.require (node:internal/modules/cjs/loader:1035:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at r (/usr/lib/code/out/main.js:6:98)
    at n.load (/usr/lib/code/out/main.js:5:1637)
    at f.load (/usr/lib/code/out/main.js:4:13565)
    at l (/usr/lib/code/out/main.js:6:9301)
    at Object.errorback (/usr/lib/code/out/main.js:6:9420)
    at f.triggerErrorback (/usr/lib/code/out/main.js:4:13859)
    at /usr/lib/code/out/main.js:4:13610
    at n.load (/usr/lib/code/out/main.js:5:1654)
    at f.load (/usr/lib/code/out/main.js:4:13565)
    at l (/usr/lib/code/out/main.js:6:9301)
    at h._loadModule (/usr/lib/code/out/main.js:6:9429)
    at h._resolve (/usr/lib/code/out/main.js:7:452)
    at h.defineModule (/usr/lib/code/out/main.js:6:5524)
    at h._relativeRequire (/usr/lib/code/out/main.js:6:6148)
    at e (/usr/lib/code/out/main.js:6:8479)
    at /usr/lib/code/out/vs/code/electron-main/main.js:25:29169
    at new Promise (<anonymous>)
    at /usr/lib/code/out/vs/code/electron-main/main.js:25:29149
    at new Promise (<anonymous>)
    at S.p (/usr/lib/code/out/vs/code/electron-main/main.js:25:29129)
    at S.n (/usr/lib/code/out/vs/code/electron-main/main.js:25:28684)
    at new S (/usr/lib/code/out/vs/code/electron-main/main.js:25:26396)
    at b.n (/usr/lib/code/out/vs/code/electron-main/main.js:86:86891)
    at /usr/lib/code/out/vs/code/electron-main/main.js:86:85425
    at b.init (/usr/lib/code/out/vs/code/electron-main/main.js:86:85744)
    at o.value (/usr/lib/code/out/vs/code/electron-main/main.js:88:28397)
    at b.w (/usr/lib/code/out/vs/code/electron-main/main.js:18:1906)
    at b.x (/usr/lib/code/out/vs/code/electron-main/main.js:18:1976)
    at b.fire (/usr/lib/code/out/vs/code/electron-main/main.js:18:2192)
    at o.value (/usr/lib/code/out/vs/code/electron-main/main.js:88:21812)
    at b.w (/usr/lib/code/out/vs/code/electron-main/main.js:18:1906)
    at b.fire (/usr/lib/code/out/vs/code/electron-main/main.js:18:2123)
    at kt.load (/usr/lib/code/out/vs/code/electron-main/main.js:88:101787)
    at at.hb (/usr/lib/code/out/vs/code/electron-main/main.js:89:43439)
    at async at.gb (/usr/lib/code/out/vs/code/electron-main/main.js:89:42745)
    at async at.N (/usr/lib/code/out/vs/code/electron-main/main.js:89:30115)
    at async at.open (/usr/lib/code/out/vs/code/electron-main/main.js:89:26094)
    at async pt.startup (/usr/lib/code/out/vs/code/electron-main/main.js:89:52417)
    at async Re.a (/usr/lib/code/out/vs/code/electron-main/main.js:91:1106)
index.js:560 Starting React
2
workbench.desktop.main.js:sourcemap:129 [Extension Host] Running onLoad
undefined.gif:1 
 Failed to load resource: the server responded with a status of 404 ()
workbench.desktop.main.js:sourcemap:627   ERR [uncaught exception in main]: /usr/lib/libm.so.6: version `GLIBC_2.38' not found (required by /usr/lib/code/node_modules.asar.unpacked/@vscode/sqlite3/build/Release/vscode-sqlite3.node): Error: /usr/lib/libm.so.6: version `GLIBC_2.38' not found (required by /usr/lib/code/node_modules.asar.unpacked/@vscode/sqlite3/build/Release/vscode-sqlite3.node)
    at process.func [as dlopen] (node:electron/js2c/asar_bundle:2:1822)
    at Module._extensions..node (node:internal/modules/cjs/loader:1226:18)
    at Object.func [as .node] (node:electron/js2c/asar_bundle:2:2049)
    at Module.load (node:internal/modules/cjs/loader:1011:32)
    at Module._load (node:internal/modules/cjs/loader:846:12)
    at f._load (node:electron/js2c/asar_bundle:2:13330)
    at Module.require (node:internal/modules/cjs/loader:1035:19)
    at C (/usr/lib/code/out/main.js:5:647)
    at Object.<anonymous> (/usr/lib/code/node_modules.asar/@vscode/sqlite3/lib/sqlite3-binding.js:4:17)
    at l._compile (/usr/lib/code/out/main.js:5:1257)
    at Module._extensions..js (node:internal/modules/cjs/loader:1196:10)
    at Module.load (node:internal/modules/cjs/loader:1011:32)
    at Module._load (node:internal/modules/cjs/loader:846:12)
    at f._load (node:electron/js2c/asar_bundle:2:13330)
    at Module.require (node:internal/modules/cjs/loader:1035:19)
    at C (/usr/lib/code/out/main.js:5:647)
    at Object.<anonymous> (/usr/lib/code/node_modules.asar/@vscode/sqlite3/lib/sqlite3.js:2:17)
    at l._compile (/usr/lib/code/out/main.js:5:1257)
    at Module._extensions..js (node:internal/modules/cjs/loader:1196:10)
    at Module.load (node:internal/modules/cjs/loader:1011:32)
    at Module._load (node:internal/modules/cjs/loader:846:12)
    at f._load (node:electron/js2c/asar_bundle:2:13330)
    at Module.require (node:internal/modules/cjs/loader:1035:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at r (/usr/lib/code/out/main.js:6:98)
    at n.load (/usr/lib/code/out/main.js:5:1637)
    at f.load (/usr/lib/code/out/main.js:4:13565)
    at l (/usr/lib/code/out/main.js:6:9301)
    at Object.errorback (/usr/lib/code/out/main.js:6:9420)
    at f.triggerErrorback (/usr/lib/code/out/main.js:4:13859)
    at /usr/lib/code/out/main.js:4:13610
    at n.load (/usr/lib/code/out/main.js:5:1654)
    at f.load (/usr/lib/code/out/main.js:4:13565)
    at l (/usr/lib/code/out/main.js:6:9301)
    at h._loadModule (/usr/lib/code/out/main.js:6:9429)
    at h._resolve (/usr/lib/code/out/main.js:7:452)
    at h.defineModule (/usr/lib/code/out/main.js:6:5524)
    at h._relativeRequire (/usr/lib/code/out/main.js:6:6148)
    at e (/usr/lib/code/out/main.js:6:8479)
    at /usr/lib/code/out/vs/code/electron-main/main.js:25:29169
    at new Promise (<anonymous>)
    at /usr/lib/code/out/vs/code/electron-main/main.js:25:29149
    at new Promise (<anonymous>)
    at S.p (/usr/lib/code/out/vs/code/electron-main/main.js:25:29129)
    at S.n (/usr/lib/code/out/vs/code/electron-main/main.js:25:28684)
    at new S (/usr/lib/code/out/vs/code/electron-main/main.js:25:26396)
    at b.n (/usr/lib/code/out/vs/code/electron-main/main.js:86:86891)
    at /usr/lib/code/out/vs/code/electron-main/main.js:86:85425
    at b.init (/usr/lib/code/out/vs/code/electron-main/main.js:86:85744)
    at o.value (/usr/lib/code/out/vs/code/electron-main/main.js:88:28397)
    at b.w (/usr/lib/code/out/vs/code/electron-main/main.js:18:1906)
    at b.x (/usr/lib/code/out/vs/code/electron-main/main.js:18:1976)
    at b.fire (/usr/lib/code/out/vs/code/electron-main/main.js:18:2192)
    at o.value (/usr/lib/code/out/vs/code/electron-main/main.js:88:21812)
    at b.w (/usr/lib/code/out/vs/code/electron-main/main.js:18:1906)
    at b.fire (/usr/lib/code/out/vs/code/electron-main/main.js:18:2123)
    at kt.load (/usr/lib/code/out/vs/code/electron-main/main.js:88:101787)
    at at.hb (/usr/lib/code/out/vs/code/electron-main/main.js:89:43439)
    at async at.gb (/usr/lib/code/out/vs/code/electron-main/main.js:89:42745)
    at async at.N (/usr/lib/code/out/vs/code/electron-main/main.js:89:30115)
    at async at.open (/usr/lib/code/out/vs/code/electron-main/main.js:89:26094)
    at async pt.startup (/usr/lib/code/out/vs/code/electron-main/main.js:89:52417)
    at async Re.a (/usr/lib/code/out/vs/code/electron-main/main.js:91:1106)
DevTools failed to load source map: Could not load content for https://file+.vscode-resource.vscode-cdn.net/home/rayzhang/.vscode-oss/exte…ons/continue.continue-0.0.207-universal/react-app/dist/assets/index.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
workbench.desktop.main.js:sourcemap:627   ERR [uncaught exception in main]: /usr/lib/libm.so.6: version `GLIBC_2.38' not found (required by /usr/lib/code/node_modules.asar.unpacked/@vscode/sqlite3/build/Release/vscode-sqlite3.node): Error: /usr/lib/libm.so.6: version `GLIBC_2.38' not found (required by /usr/lib/code/node_modules.asar.unpacked/@vscode/sqlite3/build/Release/vscode-sqlite3.node)
    at process.func [as dlopen] (node:electron/js2c/asar_bundle:2:1822)
    at Module._extensions..node (node:internal/modules/cjs/loader:1226:18)
    at Object.func [as .node] (node:electron/js2c/asar_bundle:2:2049)
    at Module.load (node:internal/modules/cjs/loader:1011:32)
    at Module._load (node:internal/modules/cjs/loader:846:12)
    at f._load (node:electron/js2c/asar_bundle:2:13330)
    at Module.require (node:internal/modules/cjs/loader:1035:19)
    at C (/usr/lib/code/out/main.js:5:647)
    at Object.<anonymous> (/usr/lib/code/node_modules.asar/@vscode/sqlite3/lib/sqlite3-binding.js:4:17)
    at l._compile (/usr/lib/code/out/main.js:5:1257)
    at Module._extensions..js (node:internal/modules/cjs/loader:1196:10)
    at Module.load (node:internal/modules/cjs/loader:1011:32)
    at Module._load (node:internal/modules/cjs/loader:846:12)
    at f._load (node:electron/js2c/asar_bundle:2:13330)
    at Module.require (node:internal/modules/cjs/loader:1035:19)
    at C (/usr/lib/code/out/main.js:5:647)
    at Object.<anonymous> (/usr/lib/code/node_modules.asar/@vscode/sqlite3/lib/sqlite3.js:2:17)
    at l._compile (/usr/lib/code/out/main.js:5:1257)
    at Module._extensions..js (node:internal/modules/cjs/loader:1196:10)
    at Module.load (node:internal/modules/cjs/loader:1011:32)
    at Module._load (node:internal/modules/cjs/loader:846:12)
    at f._load (node:electron/js2c/asar_bundle:2:13330)
    at Module.require (node:internal/modules/cjs/loader:1035:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at r (/usr/lib/code/out/main.js:6:98)
    at n.load (/usr/lib/code/out/main.js:5:1637)
    at f.load (/usr/lib/code/out/main.js:4:13565)
    at l (/usr/lib/code/out/main.js:6:9301)
    at Object.errorback (/usr/lib/code/out/main.js:6:9420)
    at f.triggerErrorback (/usr/lib/code/out/main.js:4:13859)
    at /usr/lib/code/out/main.js:4:13610
    at n.load (/usr/lib/code/out/main.js:5:1654)
    at f.load (/usr/lib/code/out/main.js:4:13565)
    at l (/usr/lib/code/out/main.js:6:9301)
    at h._loadModule (/usr/lib/code/out/main.js:6:9429)
    at h._resolve (/usr/lib/code/out/main.js:7:452)
    at h.defineModule (/usr/lib/code/out/main.js:6:5524)
    at h._relativeRequire (/usr/lib/code/out/main.js:6:6148)
    at e (/usr/lib/code/out/main.js:6:8479)
    at /usr/lib/code/out/vs/code/electron-main/main.js:25:29169
    at new Promise (<anonymous>)
    at /usr/lib/code/out/vs/code/electron-main/main.js:25:29149
    at new Promise (<anonymous>)
    at S.p (/usr/lib/code/out/vs/code/electron-main/main.js:25:29129)
    at S.n (/usr/lib/code/out/vs/code/electron-main/main.js:25:28684)
    at new S (/usr/lib/code/out/vs/code/electron-main/main.js:25:26396)
    at b.n (/usr/lib/code/out/vs/code/electron-main/main.js:86:86891)
    at /usr/lib/code/out/vs/code/electron-main/main.js:86:85425
    at b.init (/usr/lib/code/out/vs/code/electron-main/main.js:86:85744)
    at o.value (/usr/lib/code/out/vs/code/electron-main/main.js:88:28397)
    at b.w (/usr/lib/code/out/vs/code/electron-main/main.js:18:1906)
    at b.x (/usr/lib/code/out/vs/code/electron-main/main.js:18:1976)
    at b.fire (/usr/lib/code/out/vs/code/electron-main/main.js:18:2192)
    at o.value (/usr/lib/code/out/vs/code/electron-main/main.js:88:21812)
    at b.w (/usr/lib/code/out/vs/code/electron-main/main.js:18:1906)
    at b.fire (/usr/lib/code/out/vs/code/electron-main/main.js:18:2123)
    at kt.load (/usr/lib/code/out/vs/code/electron-main/main.js:88:101787)
    at at.hb (/usr/lib/code/out/vs/code/electron-main/main.js:89:43439)
    at async at.gb (/usr/lib/code/out/vs/code/electron-main/main.js:89:42745)
    at async at.N (/usr/lib/code/out/vs/code/electron-main/main.js:89:30115)
    at async at.open (/usr/lib/code/out/vs/code/electron-main/main.js:89:26094)
    at async pt.startup (/usr/lib/code/out/vs/code/electron-main/main.js:89:52417)
    at async Re.a (/usr/lib/code/out/vs/code/electron-main/main.js:91:1106)
```

I suspect this might be related to node version ([source](https://stackoverflow.com/questions/72921215/getting-glibc-2-28-not-found))?   I'm not sure about the strict dependency version requirements

**Comment by sestinj** [comment]
@zeroAska Is there any chance this is an older version of Continue than v0.0.319? Looking at the 'Running onLoad' and 'undefined.gif' outputs, I remember removing them a while back, and double checked our current codebase where it doesn't look like they would be printed from anywhere.

This isn't certain to solve the problem, but it would be good to rule that out.

**Comment by sestinj** [comment]
@zeroAska We've recently began shipping the extension with built-in binaries made specifically for different distributions of Linux, and I believe there is a good chance this will solve your problem - if you get the chance to try Continue again, I would be curious to know if it does : )

**Comment by zeroAska** [comment]
Hi @sestinj , Sounds awesome! I'm mainly using terminal editors recently. I will check it out when I have the chance to run vscode again!

**Comment by sestinj** [comment]
@zeroAska We've now moved entirely away from the Python binary, so this error is no longer possible. If you're ever back to VS Code, please let me know how Continue ends up working for you : )
