### ISSUE TITLE
Continue Server is keep on loading in mac m1

### ISSUE THREAD

**Issue by freakycodr** [continuedev/continue#402]
**Describe the bug**
Continue server is keep on loading, tried all the troubleshooting steps

**Screenshots**
<img width="1502" alt="image" src="https://github.com/continuedev/continue/assets/30159480/c747bf46-d21d-4d06-b43f-7a3479b76b9e">

**Environment**
- Operating System: [e.g. MacOS]
- Python Version: [e.g. 3.10 and 3.11]
- Continue Version: [e.g. v0.0.327]

**Console logs**
```
workbench.desktop.main.js:sourcemap:1966 [Continue.continue]ENOENT: no such file or directory, unlink '/Users/mani-18458/.continue/server/server_version.txt'
$onExtensionRuntimeError @ workbench.desktop.main.js:sourcemap:1966
workbench.desktop.main.js:sourcemap:1966 Error: ENOENT: no such file or directory, unlink '/Users/mani-18458/.continue/server/server_version.txt'
	at Object.unlinkSync (node:fs:1793:3)
	at checkOrKillRunningServer (/Users/mani-18458/.vscode/extensions/continue.continue-0.0.327/out/extension.js:55164:8)
	at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async startContinuePythonServer (/Users/mani-18458/.vscode/extensions/continue.continue-0.0.327/out/extension.js:55215:21)
	at async /Users/mani-18458/.vscode/extensions/continue.continue-0.0.327/out/extension.js:67411:5


**Additional context**
Tried to run the local server as well, whenever i tried to run the local server and open vs code then the local server killed automatically

**Comment by sestinj** [comment]
@freakycodr Version 0.0.328 is now released and solves this problem. Is everything okay for you now?

**Comment by bcrisp4** [comment]
@sestinj working for me! Thanks! 🙂

**Comment by sestinj** [comment]
Woo! Awesome

**Comment by freakycodr** [comment]
@sestinj thanks for the quick response, it is working now, thanks 😄
