### ISSUE TITLE
Exception caught from async task: Traceback

### ISSUE THREAD

**Issue by xingguang2013** [continuedev/continue#437]
**Describe the bug**
When I open vscode, find continue, and then stop at Continue Server Starting

**To Reproduce**
1. Go to 'vscode'
2. Click on 'continue'
3. See Continue Server Starting

**Expected behavior**
Can be used normally

**Environment**
- Operating System: [Windows 11 22H2]
- Python Version: [3.11.4]
- Continue Version: [v0.0.353]

**Console logs**
```
[2023-08-31 22:36:07,357] [CRITICAL] Exception caught from async task: Traceback (most recent call last):

  File "continuedev\src\continuedev\core\autopilot.py", line 368, in _run_singular_step
    observation = await step(self.continue_sdk)

  File "continuedev\src\continuedev\core\main.py", line 359, in __call__
    return await self.run(sdk)

  File "continuedev\src\continuedev\plugins\steps\chat.py", line 109, in run
    await sdk.update_ui()

  File "continuedev\src\continuedev\core\sdk.py", line 271, in update_ui
    await self.__autopilot.update_subscribers()

  File "continuedev\src\continuedev\core\autopilot.py", line 208, in update_subscribers
    await callback(full_state)

  File "continuedev\src\continuedev\server\session_manager.py", line 81, in on_update
    await session_manager.send_ws_data(

  File "continuedev\src\continuedev\server\session_manager.py", line 162, in send_ws_data
    raise SessionNotFound(f"Session {session_id} not found")

continuedev.src.continuedev.libs.util.errors.SessionNotFound: Session 049f838a-2e87-49e2-9977-0adcff119cc4 not found


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "continuedev\src\continuedev\libs\util\create_async_task.py", line 21, in callback
    future.result()

  File "asyncio\futures.py", line 201, in result

  File "asyncio\tasks.py", line 232, in __step

  File "continuedev\src\continuedev\core\autopilot.py", line 535, in accept_user_input
    await self.run_from_step(UserInputStep(user_input=user_input))

  File "continuedev\src\continuedev\core\autopilot.py", line 472, in run_from_step
    await self._run_singular_step(next_step, is_future_step)

  File "continuedev\src\continuedev\core\autopilot.py", line 421, in _run_singular_step
    await self.update_subscribers()

  File "continuedev\src\continuedev\core\autopilot.py", line 208, in update_subscribers
    await callback(full_state)

  File "continuedev\src\continuedev\server\session_manager.py", line 81, in on_update
    await session_manager.send_ws_data(

  File "continuedev\src\continuedev\server\session_manager.py", line 162, in send_ws_data
    raise SessionNotFound(f"Session {session_id} not found")

continuedev.src.continuedev.libs.util.errors.SessionNotFound: Session 049f838a-2e87-49e2-9977-0adcff119cc4 not found

[2023-08-31 22:37:32,399] [ERROR] Error while running step: 
Traceback (most recent call last):

  File "continuedev\src\continuedev\core\autopilot.py", line 368, in _run_singular_step
    observation = await step(self.continue_sdk)

  File "continuedev\src\continuedev\core\main.py", line 359, in __call__
    return await self.run(sdk)

  File "continuedev\src\continuedev\plugins\steps\chat.py", line 109, in run
    await sdk.update_ui()

  File "continuedev\src\continuedev\core\sdk.py", line 271, in update_ui
    await self.__autopilot.update_subscribers()

  File "continuedev\src\continuedev\core\autopilot.py", line 208, in update_subscribers
    await callback(full_state)

  File "continuedev\src\continuedev\server\session_manager.py", line 81, in on_update
    await session_manager.send_ws_data(

  File "continuedev\src\continuedev\server\session_manager.py", line 162, in send_ws_data
    raise SessionNotFound(f"Session {session_id} not found")

continuedev.src.continuedev.libs.util.errors.SessionNotFound: Session 049f838a-2e87-49e2-9977-0adcff119cc4 not found

Session 049f838a-2e87-49e2-9977-0adcff119cc4 not found
[2023-08-31 22:38:14,580] [CRITICAL] Exception caught from async task: Traceback (most recent call last):

  File "continuedev\src\continuedev\core\autopilot.py", line 368, in _run_singular_step
    observation = await step(self.continue_sdk)

  File "continuedev\src\continuedev\core\main.py", line 359, in __call__
    return await self.run(sdk)

  File "continuedev\src\continuedev\plugins\steps\chat.py", line 109, in run
    await sdk.update_ui()

  File "continuedev\src\continuedev\core\sdk.py", line 271, in update_ui
    await self.__autopilot.update_subscribers()

  File "continuedev\src\continuedev\core\autopilot.py", line 208, in update_subscribers
    await callback(full_state)

  File "continuedev\src\continuedev\server\session_manager.py", line 81, in on_update
    await session_manager.send_ws_data(

  File "continuedev\src\continuedev\server\session_manager.py", line 162, in send_ws_data
    raise SessionNotFound(f"Session {session_id} not found")

continuedev.src.continuedev.libs.util.errors.SessionNotFound: Session 049f838a-2e87-49e2-9977-0adcff119cc4 not found


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "continuedev\src\continuedev\libs\util\create_async_task.py", line 21, in callback
    future.result()

  File "asyncio\futures.py", line 201, in result

  File "asyncio\tasks.py", line 232, in __step

  File "continuedev\src\continuedev\core\autopilot.py", line 535, in accept_user_input
    await self.run_from_step(UserInputStep(user_input=user_input))

  File "continuedev\src\continuedev\core\autopilot.py", line 472, in run_from_step
    await self._run_singular_step(next_step, is_future_step)

  File "continuedev\src\continuedev\core\autopilot.py", line 421, in _run_singular_step
    await self.update_subscribers()

  File "continuedev\src\continuedev\core\autopilot.py", line 208, in update_subscribers
    await callback(full_state)

  File "continuedev\src\continuedev\server\session_manager.py", line 81, in on_update
    await session_manager.send_ws_data(

  File "continuedev\src\continuedev\server\session_manager.py", line 162, in send_ws_data
    raise SessionNotFound(f"Session {session_id} not found")

continuedev.src.continuedev.libs.util.errors.SessionNotFound: Session 049f838a-2e87-49e2-9977-0adcff119cc4 not found

To get the console logs in VS Code:
1. cmd+shift+p (MacOS) / ctrl+shift+p (Windows)
2. Search for and then select "Developer: Toggle Developer Tools"
3. Select Console
4. Read the console logs
```

**Additional context**

**Comment by sestinj** [comment]
Could you try a few things to see if it fixes this? I also recognize that you aren't a brand new user, so very possible hat something new is happening here, but would be useful to know whether the usual [troubleshooting](https://continue.dev/docs/troubleshooting) resolves this: a) kill the server process b) reload VS Code

Assuming none of this works, or that you've already tried, I'll start looking into what's going on.

**Comment by sestinj** [comment]
also, a question I have: is this something new happening only on this latest version, where it was working before?

**Comment by xingguang2013** [comment]
Yes, the previous version was used very well, but after the update, it no longer works. Also tried to solve it, such as deleting the~/. connue file, but it didn't solve the problem

**Comment by sestinj** [comment]
@xingguang2013 I think I have a solution to this. Does the latest version of Continue work for you?

Issue was trying to send this message before a session was started, and it turns out this "session not found" is okay to just log a warning instead of throwing, so I made that change.

**Comment by xingguang2013** [comment]
I have updated to version v0.0.364 and the issue seems to have been resolved. Thank you very much

**Comment by sestinj** [comment]
glad to hear it!

**Comment by xingguang2013** [comment]
However, I have a small question. Previously, after type the question, the response speed was very fast, but now it is very slow. I feel like it will take about 1 minute for a response to be given. However, it is not important, as long as it can be used. Thank you

**Comment by sestinj** [comment]
Could you share which model you are using?

**Comment by xingguang2013** [comment]
I am a user in China and have used the default model after the update. Please take a screenshot.

**Comment by sestinj** [comment]
this might be due to the fact that our server is hosted in the US. If you use the OpenAI class, either directly or through a proxy, I wonder if it would speed things up.

Example: `models=Models(default=OpenAI(api_key="<API_KEY>", model="gpt-3.5-turbo"))`

And you can set the `api_base` or `proxy` arguments if you need to go through a different URL than api.openai.com

**Comment by xingguang2013** [comment]
Okay, I'll give it a try
