### ISSUE TITLE
HuggingFace TGI Codellama support

### ISSUE THREAD

**Issue by taoari** [continuedev/continue#438]
**Is your feature request related to a problem? Please describe.**

HuggingFace TGI is a standard way to serve LLMs. Is it possible to add support for HuggingFace TGI served codellama models?

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by sestinj** [comment]
Hi @taoari, I've started work on this [here](https://github.com/continuedev/continue/blob/main/continuedev/src/continuedev/libs/llm/hf_tgi.py), but haven't yet added it to the documentation. This hasn't been tested yet—there is a chance it already works, but might require a bit of debugging.

**Comment by sestinj** [comment]
Usage would look like this:

```python
from continuedev.src.continuedev.libs.llm.ht_tgi import HuggingFaceTGI
...
config=ContinueConfig(
  ...
  models=Models(
    default=HuggingFaceTGI(server_url="<SERVER_URL>")
  )
)
```

I encountered friction installing TGI on my mac, which is why I haven't fully tested yet, so would be super helpful for me if you wanted to give it a try

**Comment by taoari** [comment]
@sestinj I got the following error

ModuleNotFoundError: No module named 'continuedev.src.continuedev.libs.llm.ht_tgi'

**Comment by sestinj** [comment]
Just a typo, it should be hf_tgi

Can check the file here to be sure: https://github.com/continuedev/continue/blob/main/continuedev/src/continuedev/libs/llm/hf_tgi.py

**Comment by taoari** [comment]
@sestinj No errors this time. But it still does not work. The "Play" button blinks all the time, and get no response.

**Comment by taoari** [comment]
@sestinj I think it crashed on my computer. 

I did uninstall,
lsof -i :65432 | grep "(LISTEN)" | awk '{print $2}' | xargs kill -9
delete ~/.continue
reinstall

It still does not work, I always got "Continue Server Starting".

**Comment by sestinj** [comment]
Ok, I might just need to go back and test this myself then. I'll update you when it's ready.

Is Continue completely unable to start up again? In worst case I think that uninstalling Continue and restarting VS Code should solve things.

Another way to make sure that no servers are running is just lsof -i :65432 

You can check the logs with cmd+shift+p "View Continue Server Logs"

**Comment by abhinavkulkarni** [comment]
Thanks, any progress on this? TGI supports GPTQ quantization out of the box, so would like use it with Continue.

**Comment by abhinavkulkarni** [comment]
Thanks @sestinj, I now get a new error:

```python
Traceback (most recent call last):

  File "continuedev/src/continuedev/libs/util/create_async_task.py", line 21, in callback
    future.result()

  File "asyncio/futures.py", line 203, in result

  File "asyncio/tasks.py", line 267, in __step

  File "continuedev/src/continuedev/core/autopilot.py", line 543, in create_title
    title = await self.continue_sdk.models.medium.complete(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "continuedev/src/continuedev/libs/llm/__init__.py", line 258, in complete
    completion = await self._complete(prompt=prompt, options=options)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "continuedev/src/continuedev/libs/llm/__init__.py", line 334, in _complete
    async for chunk in self._stream_complete(prompt=prompt, options=options):

  File "/var/folders/nw/hfwjfm7n6h13ybsw6kxqh08w0000gn/T/_MEISzqrqf/continuedev/src/continuedev/libs/llm/hf_tgi.py", line 41, in _stream_complete
    args = self.collect_args(options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/var/folders/nw/hfwjfm7n6h13ybsw6kxqh08w0000gn/T/_MEISzqrqf/continuedev/src/continuedev/libs/llm/hf_tgi.py", line 37, in collect_args
    args.pop("functions")

KeyError: 'functions'
```

**Comment by sestinj** [comment]
The "functions" error is an easy one. Let me give the other a deeper look and set TGI up on my own machine (embarrassing, but I haven't gotten to this yet, I was just following the API documentation). I think it might be something about how I'm calling the streaming endpoint.

The request I'm making right now is the equivalent of

```bash
curl -X POST -H "Content-Type: application/json" -d '{"inputs": "<prompt_value>", "parameters": {"max_new_tokens": 1024}}' http://localhost:8080/generate_stream
```

**Comment by sestinj** [comment]
resuming work in the morning, has been a slight pain to setup TGI on Mac.

If there's any chance you've seen this error would be curious how you solved it. Otherwise sure I'll get it tmr

```RuntimeError: An error occurred while downloading using `hf_transfer`. Consider disabling HF_HUB_ENABLE_HF_TRANSFER for better error handling.```

**Comment by sestinj** [comment]
@abhinavkulkarni finally got it, and successfully tested on my own TGI setup. Let me know if any problems still

**Comment by abhinavkulkarni** [comment]
Thanks @sestinj, local TGI setup works and I can generate responses from it.

However, I am not able to feed it context by selecting code, please see the attached video. You can see responses being generated from the TGI in the integrated terminal window. Please note, when I switch to OpenAI maybe proxy, it does work and is able to answer questions based on the highlighted context.

![output](https://github.com/continuedev/continue/assets/1565547/a394f68a-71f8-41fe-9dae-7aa195b7fc17)

**Comment by abhinavkulkarni** [comment]
Also, the prompt formatting with `[INST]`, `[\INST]` tokens works well for me for llama2 models but not so much for codellama. The codellama model doesn't require any such special formatting.

![output](https://github.com/continuedev/continue/assets/1565547/bdec953a-d16f-439a-bbe7-95263d822fc4)

**Comment by abhinavkulkarni** [comment]
Also, for Llama 2 models, `</s>` is a special token that indicates end of text/sequence and should not be displayed.

You can see in the following attached image, that is is shown for the title.

<img width="298" alt="image" src="https://github.com/continuedev/continue/assets/1565547/26bf40b0-0768-4f76-9a8c-8db534ac3bb4">

**Comment by sestinj** [comment]
@abhinavkulkarni I have a suspicion that the code is in the prompt, but the model is ignoring it. If you try this again and hover over the response, a magnifying glass button will show up. Clicking that shows the full prompts/completions as sent to the LLM. Could you share what that looks like?

We have a stop parameter that can be set for the model, but since CodeLlama/Llama is usually the model people use, I think it would be sensible to have <s/> as the default there. Also noticing the [PYTHON] tags are probably a bit annoying. I'll make a change so they are converted to triple backticks

**Comment by abhinavkulkarni** [comment]
Thanks, @sestinj, here's a video screengrab for a simple prompt. This is the full prompt and the response:

```
This is a log of the prompt/completion pairs sent/received from the LLM during this step

############################################

Prompt: 

[INST] Tell me what this code is doing.
[/INST]

############################################

Completion: 

 This code is using the `requests` library to make a GET request to the URL `https://api.github.com/users/octocat/repos`. The `json()` method is used to parse the response as JSON data, and the `for` loop is used to iterate over the list of repositories returned in the response.

For each repository, the code is printing the repository name and the number of stars it has. The `print()` function is used to display the output.

This code is using the GitHub API to retrieve a list of repositories for the user "octocat" and then printing the name and number of stars for each repository..</s>

############################################

Prompt: 

[INST] " This code is using the `requests` library to make a GET request to the URL `https://api.github.com/users/octocat/repos`. The `json()` method is used to parse the response as JSON data, and the `for` loop is used to iterate over the list of repositories returned in the response.

For each repository, the code is printing the repository name and the number of stars it has. The `print()` function is used to display the output.

This code is using the GitHub API to retrieve a list of repositories for the user "octocat" and then printing the name and number of stars for each repository..</s>"

Please write a short title summarizing the message quoted above. Use no more than 10 words:
[/INST]

############################################

Completion: 

 ""The only way to do great work is to love what you do." ― Steve Job
```

![output](https://github.com/continuedev/continue/assets/1565547/d0175876-891b-46fb-9e74-3df720fcc45a)

**Comment by sestinj** [comment]
Thanks. My suspicion is wrong... but...I see the problem! This is actually fixable through the config file, but I'll change the default to be the correct thing and push a new version soon

There is a `template_messages` property of all LLM classes that converts chat history into a templated prompt, and the function I have as the default for HuggingFaceTGI is cutting out the chat history. The correct thing would look like this:

```python
from continuedev.src.continuedev.libs.llm.prompts.chat import llama2_template_messages
...
...
default=HuggingFaceTGI(..., template_messages=llama2_template_messages)
```

**Comment by sestinj** [comment]
@abhinavkulkarni just released a new version, this is now the default so now highlighted code will be included

**Comment by abhinavkulkarni** [comment]
Thanks, @sestinj, things work perfectly now, except for one small detail. The title generated seems to be random and has nothing to do with the prompt. I am attaching an example screengrab here. 

Here's the full prompt and the completion:

```
This is a log of the prompt/completion pairs sent/received from the LLM during this step

############################################

Prompt: 

[INST] Code in this file is highlighted (/home/abhinav/Projects/continue/continuedev/src/continuedev/libs/llm/hf_tgi.py):
```
import json
from typing import Any, Callable, List

import aiohttp
from pydantic import Field

from ...core.main import ChatMessage
from ..llm import LLM, CompletionOptions
from .prompts.chat import code_llama_template_messages
from .prompts.edit import simplified_edit_prompt


class HuggingFaceTGI(LLM):
    model: str = "huggingface-tgi"
    server_url: str = Field(
        "http://localhost:8080", description="URL of your TGI server"
    )

    template_messages: Callable[[List[ChatMessage]], str] = code_llama_template_messages

    prompt_templates = {
        "edit": simplified_edit_prompt,
    }

    class Config:
        arbitrary_types_allowed = True

    def collect_args(self, options: CompletionOptions) -> Any:
        args = super().collect_args(options)
        args = {**args, "max_new_tokens": args.get("max_tokens", 1024), "best_of": 1}
        args.pop("max_tokens", None)
        args.pop("model", None)
        args.pop("functions", None)
        return args

    async def _stream_complete(self, prompt, options):
        args = self.collect_args(options)

        async with aiohttp.ClientSession(
            connector=aiohttp.TCPConnector(verify_ssl=self.verify_ssl),
            timeout=aiohttp.ClientTimeout(total=self.timeout),
        ) as client_session:
            async with client_session.post(
                f"{self.server_url}/generate_stream",
                json={"inputs": prompt, "parameters": args},
                headers={"Content-Type": "application/json"},
            ) as resp:
                async for line in resp.content.iter_any():
                    if line:
                        text = line.decode("utf-8")
                        chunks = text.split("\n")

                        for chunk in chunks:
                            if chunk.startswith("data: "):
                                chunk = chunk[len("data: ") :]
                            elif chunk.startswith("data:"):
                                chunk = chunk[len("data:") :]

                            if chunk.strip() == "":
                                continue

                            try:
                                json_chunk = json.loads(chunk)
                            except Exception as e:
                                print(f"Error parsing JSON: {e}")
                                continue

                            yield json_chunk["token"]["text"]

``` [/INST][INST] What does this code do? [/INST]

############################################

Prompt: 

[INST] Give a short title to describe the current chat session. Do not put quotes around the title. The first message was: "What does this code do?". Do not use more than 10 words. The title is:  [/INST]

############################################

Completion: 

 "Chat Session: Code Analysis""</s>

############################################

Completion: 

 This code defines a class called `HuggingFaceTGI` that inherits from the `LLM` class. It defines several instance variables, including `model`, `server_url`, `template_messages`, and `prompt_templates`.

The `model` variable is set to "huggingface-tgi", which suggests that this class is designed to work with the Hugging Face Transformer Generator Interface (TGI) model. The `server_url` variable is set to "http://localhost:8080", which is the default URL for the TGI server.

The `template_messages` variable is a function that takes a list of `ChatMessage` objects and returns a string. It is used to generate a prompt for the TGI model.

The `prompt_templates` variable is a dictionary that maps prompt types (such as "edit") to functions that generate prompts for those types.

The `Config` class is used to configure the behavior of the `HuggingFaceTGI` class. It sets the `arbitrary_types_allowed` attribute to `True`, which allows the class to accept arbitrary types for its instance variables.

The `collect_args` method is used to collect the arguments for the TGI model. It takes a `CompletionOptions` object and returns a dictionary of arguments for the TGI model. It modifies the `max_new_tokens` and `best_of` arguments and removes the `max_tokens` and `model` arguments.

The `_stream_complete` method is used to stream the completion of the TGI model. It takes a prompt and a `CompletionOptions` object as input and returns a generator that yields the completed text. It uses the `aiohttp` library to make a POST request to the TGI server with the prompt and arguments, and it iterates over the response content to generate the completed text..</s>

############################################

Prompt: 

[INST] " This code defines a class called `HuggingFaceTGI` that inherits from the `LLM` class. It defines several instance variables, including `model`, `server_url`, `template_messages`, and `prompt_templates`.

The `model` variable is set to "huggingface-tgi", which suggests that this class is designed to work with the Hugging Face Transformer Generator Interface (TGI) model. The `server_url` variable is set to "http://localhost:8080", which is the default URL for the TGI server.

The `template_messages` variable is a function that takes a list of `ChatMessage` objects and returns a string. It is used to generate a prompt for the TGI model.

The `prompt_templates` variable is a dictionary that maps prompt types (such as "edit") to functions that generate prompts for those types.

The `Config` class is used to configure the behavior of the `HuggingFaceTGI` class. It sets the `arbitrary_types_allowed` attribute to `True`, which allows the class to accept arbitrary types for its instance variables.

The `collect_args` method is used to collect the arguments for the TGI model. It takes a `CompletionOptions` object and returns a dictionary of arguments for the TGI model. It modifies the `max_new_tokens` and `best_of` arguments and removes the `max_tokens` and `model` arguments.

The `_stream_complete` method is used to stream the completion of the TGI model. It takes a prompt and a `CompletionOptions` object as input and returns a generator that yields the completed text. It uses the `aiohttp` library to make a POST request to the TGI server with the prompt and arguments, and it iterates over the response content to generate the completed text..</s>"

Please write a short title summarizing the message quoted above. Use no more than 10 words: [/INST]

############################################

Completion: 

 ""What's a good way to learn a new language?"""</s>
 ```

![output](https://github.com/continuedev/continue/assets/1565547/d6096721-ce11-4892-998d-f9352bfaa82e)

**Comment by sestinj** [comment]
Which model are you using? I can then just test out the exact prompt here until I find something more reliable

The prompt looks ok, other than the end token. Adding a `stop_tokens` option in the LLM class and there's a small chance that fixes it, but likely not

**Comment by sestinj** [comment]
Also relevant for now might be the "disable_summaries" option in config.py depending on how bad it is: https://continue.dev/docs/reference/config#:~:text=token%20is%20provided.-,disable_summaries,-(boolean)%20%3D%20False

**Comment by abhinavkulkarni** [comment]
Hey @sestinj,

> Also relevant for now might be the "disable_summaries" option in config.py

Thanks, that works.

> Which model are you using?

I am using a 4-bit quantized version of `codellama/CodeLlama-7b-Instruct-hf`, but you won't be able to run it on CPU (I read it in one of your previous replies that you were running these on a Mac). If so, you may want to test it with 4-bit GGML/GGUF version of this model to see if you too are getting random quotes as titles.

Another problem I have observed is that the last character in the completion tends to be repeated - so if it is a period or an exclamation mark, it is repeated. If I feed the same prompt to my local TGI using `curl`, I don't get this repetition.

Here's the screengrab attached:

![output](https://github.com/continuedev/continue/assets/1565547/6aa05b73-e426-4640-afdb-6808ec696c47)

**Comment by sestinj** [comment]
Ok, cool. I'll see what I can find. Seems like Continue is just extra excited lol !!

**Comment by sestinj** [comment]
@abhinavkulkarni just wanted to update you on this since I know it's been a while - I've been planning on potentially using LiteLLM to make API calls to different providers, such as HuggingFace TGI, and this would solve the above problem, so I've decided to postpone digging into it myself. I'll let you know as soon as there's an update here!

Also thought you might want to know this since I talked to them and they mentioned that you were a contributor : )

**Comment by krrishdholakia** [comment]
👋 @abhinavkulkarni
