### ISSUE TITLE
Error in Continue Server

### ISSUE THREAD

**Issue by gecexgokyuzu** [continuedev/continue#444]
##Error:

Error in Continue server: [Errno 22] Invalid argument
 Traceback (most recent call last):

  File "asyncio\tasks.py", line 234, in __step

  File "continuedev\src\continuedev\libs\util\queue.py", line 17, in get
    return await self.queues[message_type].get()

  File "asyncio\queues.py", line 159, in get

  File "asyncio\futures.py", line 285, in __await__

  File "asyncio\tasks.py", line 304, in __wakeup

  File "asyncio\futures.py", line 196, in result

asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "asyncio\tasks.py", line 456, in wait_for

  File "asyncio\futures.py", line 196, in result

asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):

  File "continuedev\src\continuedev\server\ide.py", line 205, in _receive_json
    return await asyncio.wait_for(

  File "asyncio\tasks.py", line 458, in wait_for

asyncio.exceptions.TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "continuedev\src\continuedev\plugins\context_providers\file.py", line 15, in get_file_contents
    return (await sdk.ide.readFile(filepath))[:MAX_SIZE_IN_CHARS]

  File "continuedev\src\continuedev\server\ide.py", line 465, in readFile
    resp = await self._send_and_receive_json(

  File "continuedev\src\continuedev\server\ide.py", line 217, in _send_and_receive_json
    resp = await self._receive_json(message_type)

  File "continuedev\src\continuedev\server\ide.py", line 209, in _receive_json
    raise Exception(

Exception: IDE Protocol _receive_json timed out after 20 seconds: readFile

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "continuedev\src\continuedev\libs\util\create_async_task.py", line 21, in callback
    future.result()

  File "asyncio\futures.py", line 201, in result

  File "asyncio\tasks.py", line 232, in __step

  File "continuedev\src\continuedev\plugins\context_providers\file.py", line 56, in on_file_saved
    item = await self.get_context_item_for_filepath(filepath)

  File "continuedev\src\continuedev\plugins\context_providers\file.py", line 103, in get_context_item_for_filepath
    content = await get_file_contents(absolute_filepath, self.sdk)

  File "continuedev\src\continuedev\plugins\context_providers\file.py", line 17, in get_file_contents
    print(f"Failed to read file {filepath}: {e}")

OSError: [Errno 22] Invalid argument

**Comment by sestinj** [comment]
@gecexgokyuzu I have a fix for this on its way right now, I will update you in about 15 minutes with a new version

**Comment by sestinj** [comment]
@gecexgokyuzu A new version is ready on the marketplace that will solve this problem - please let me know if it doesn't

**Comment by gecexgokyuzu** [comment]
thanks for the quick reply!
