### ISSUE TITLE
[Errno 13] error while attempting to bind on address

### ISSUE THREAD

**Issue by lamegaton** [continuedev/continue#459]
**Describe the bug**
Server cannot start due to a permission issue
[Errno 13] error while attempting to bind on address ('127.0.0.1', 65432): an attempt was made to access a socket in a way forbidden by its access permissions

**To Reproduce**

1. Go to VScode
2. Click on Continue
4. Stuck at 'Continue Starting Server'

**Environment**

- Operating System: Win 11
- Python Version: 3.11
- Continue Version: 0.0.376

**Logs**

```
[2023-09-06 08:15:02,490] [DEBUG] Testing logs
Certificates at:  C:\Users\$USER\AppData\Local\Temp\_MEI82362\ca_bundle\cacert.pem
Running Continue server version 0.0.350
INFO:     Started server process [32376]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
ERROR:    [Errno 13] error while attempting to bind on address ('127.0.0.1', 65432): an attempt was made to access a socket in a way forbidden by its access permissions
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
[2023-09-06 08:15:02,959] [DEBUG] Cleaning up sessions
Task exception was never retrieved
future: <Task finished name='Task-1' coro=<Server.serve() done, defined at uvicorn\server.py:61> exception=SystemExit(1)>
Traceback (most recent call last):
  File "uvicorn\server.py", line 159, in startup
  File "asyncio\base_events.py", line 1519, in create_server
PermissionError: [Errno 13] error while attempting to bind on address ('127.0.0.1', 65432): an attempt was made to access a socket in a way forbidden by its access permissions

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "nest_asyncio.py", line 35, in run
  File "nest_asyncio.py", line 84, in run_until_complete
  File "nest_asyncio.py", line 120, in _run_once
  File "asyncio\events.py", line 80, in _run
  File "asyncio\tasks.py", line 315, in __wakeup
  File "nest_asyncio.py", line 196, in step
  File "asyncio\tasks.py", line 232, in __step
  File "uvicorn\server.py", line 76, in serve
  File "uvicorn\server.py", line 169, in startup
SystemExit: 1
```

Console
```
[Extension Host] stderr: [2023-09-06 08:24:19,659] [DEBUG] Testing logs
console.ts:137 [Extension Host] stderr: INFO:     Started server process [12788]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
console.ts:137 [Extension Host] stderr: ERROR:    [Errno 13] error while attempting to bind on address ('127.0.0.1', 65432): an attempt was made to access a socket in a way forbidden by its access permissions
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
console.ts:137 [Extension Host] stderr: [2023-09-06 08:24:20,137] [DEBUG] Cleaning up sessions
console.ts:137 [Extension Host] stdout: Certificates at:  C:\Users\$USER\AppData\Local\Temp\_MEI28282\ca_bundle\cacert.pem
Running Continue server version 0.0.350
console.ts:137 [Extension Host] stderr: Task exception was never retrieved
future: <Task finished name='Task-1' coro=<Server.serve() done, defined at uvicorn\server.py:61> exception=SystemExit(1)>
Traceback (most recent call last):
  File "uvicorn\server.py", line 159, in startup
  File "asyncio\base_events.py", line 1519, in create_server
PermissionError: [Errno 13] error while attempting to bind on address ('127.0.0.1', 65432): an attempt was made to access a socket in a way forbidden by its access permissions

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "nest_asyncio.py", line 35, in run
  File "nest_asyncio.py", line 84, in run_until_complete
  File "nest_asyncio.py", line 120, in _run_once
  File "asyncio\events.py", line 80, in _run
  File "asyncio\tasks.py", line 315, in __wakeup
  File "nest_asyncio.py", line 196, in step
  File "asyncio\tasks.py", line 232, in __step
  File "uvicorn\server.py", line 76, in serve
  File "uvicorn\server.py", line 169, in startup
SystemExit: 1
console.ts:137 [Extension Host] Subprocess exited with code 1 null
console.ts:137 [Extension Host] Subprocess closed with code 1 null

```

**Comment by sestinj** [comment]
@lamegaton I believe this could happen if there were another process already running on port 65432 - you can check whether this is the case with:

```
'netstat -na | grep "65432"' in Bash or
'netstat -na | find "65432"' in cmd or
'netstat -na | find """65432"""' in Powershell.
```

If you don't see a running process on 65432, I would wonder if perhaps there is some kind of special security software / firewall on your computer

**Comment by lamegaton** [comment]
Hi @sestinj, I checked `netstat -na` and could not find the port. It starts working again after the computer is rebooted.

**Comment by sestinj** [comment]
Glad it's working! - please don't hesitate to reopen if this happens again. Perhaps we'll find a deeper issue, and in that case I would love to know about it.
