### ISSUE TITLE
Cannot read properties of undefined (reading 'filter')

### ISSUE THREAD

**Issue by ahkimkoo** [continuedev/continue#465]
crush while enter "/"

Error in Continue React App
Cannot read properties of undefined (reading 'filter')

TypeError: Cannot read properties of undefined (reading 'filter')
    at https://file+.vscode-resource.vscode-cdn.net/home/cherokee/.vscode/extensions/continue.continue-0.0.380/react-app/dist/assets/index.js:576:8861
    at Array.map (<anonymous>)
    at https://file+.vscode-resource.vscode-cdn.net/home/cherokee/.vscode/extensions/continue.continue-0.0.380/react-app/dist/assets/index.js:576:8555
    at J0 (https://file+.vscode-resource.vscode-cdn.net/home/cherokee/.vscode/extensions/continue.continue-0.0.380/react-app/dist/assets/index.js:38:19538)
    at kA (https://file+.vscode-resource.vscode-cdn.net/home/cherokee/.vscode/extensions/continue.continue-0.0.380/react-app/dist/assets/index.js:40:1571)
    at S2 (https://file+.vscode-resource.vscode-cdn.net/home/cherokee/.vscode/extensions/continue.continue-0.0.380/react-app/dist/assets/index.js:40:46030)
    at v2 (https://file+.vscode-resource.vscode-cdn.net/home/cherokee/.vscode/extensions/continue.continue-0.0.380/react-app/dist/assets/index.js:40:39787)
    at b8 (https://file+.vscode-resource.vscode-cdn.net/home/cherokee/.vscode/extensions/continue.continue-0.0.380/react-app/dist/assets/index.js:40:39715)
    at I1 (https://file+.vscode-resource.vscode-cdn.net/home/cherokee/.vscode/extensions/continue.continue-0.0.380/react-app/dist/assets/index.js:40:39568)
    at mm (https://file+.vscode-resource.vscode-cdn.net/home/cherokee/.vscode/extensions/continue.continue-0.0.380/react-app/dist/assets/index.js:40:35933)

**Comment by sestinj** [comment]
Thanks for sharing the stack trace! I'm making an update with a fix right not. I'll update you once it's ready

**Comment by sestinj** [comment]
@ahkimkoo Just released a new version where this is solved. Let me know if for some reason the same problem occurs after updating

**Comment by sestinj** [comment]
Closing this issue—please re-open if needed!
