### ISSUE TITLE
"Cannot write to closing transport"

### ISSUE THREAD

**Issue by TyDunn** [continuedev/continue#469]
**Describe the bug**

When I try to use `cmd+shift+r` to understand an error, Continue tells me "Cannot write to closing transport"

**Environment**

- Operating System: MacOS
- Continue Version: Latest

**Logs**

```
Traceback (most recent call last):

  File "continuedev/src/continuedev/core/autopilot.py", line 387, in _run_singular_step
    observation = await step(self.continue_sdk)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "continuedev/src/continuedev/core/main.py", line 368, in __call__
    return await self.run(sdk)
           ^^^^^^^^^^^^^^^^^^^

  File "continuedev/src/continuedev/plugins/steps/on_traceback.py", line 163, in run
    prompt = await self.normal_traceback_prompt(sdk, tb, tb_string)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "continuedev/src/continuedev/plugins/steps/on_traceback.py", line 140, in normal_traceback_prompt
    function_bodies = await get_functions_from_traceback(tb, sdk)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "continuedev/src/continuedev/plugins/steps/on_traceback.py", line 198, in get_functions_from_traceback
    function_bodies.append(await get_function_body(frame, sdk))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "continuedev/src/continuedev/plugins/steps/on_traceback.py", line 178, in get_function_body
    document_symbols = await sdk.lsp.document_symbol(frame.filepath)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "continuedev/src/continuedev/core/lsp.py", line 311, in document_symbol
    response = await self.lsp_client.document_symbol(filepath)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "continuedev/src/continuedev/core/lsp.py", line 235, in document_symbol
    return await self.call_method(
           ^^^^^^^^^^^^^^^^^^^^^^^

  File "continuedev/src/continuedev/core/lsp.py", line 59, in call_method
    await self.send(body)

  File "continuedev/src/continuedev/core/lsp.py", line 42, in send
    await self.ws.send_json(data)

  File "aiohttp/client_ws.py", line 165, in send_json

  File "aiohttp/client_ws.py", line 151, in send_str

  File "aiohttp/http_websocket.py", line 690, in send

  File "aiohttp/http_websocket.py", line 646, in _send_frame

  File "aiohttp/http_websocket.py", line 663, in _write

ConnectionResetError: Cannot write to closing transport
```

<img width="424" alt="Screenshot 2023-09-12 at 7 33 34 PM" src="https://github.com/continuedev/continue/assets/13314504/f27f8f73-8f00-4c95-a78b-32ec1aedfb0f">

<img width="757" alt="Screenshot 2023-09-12 at 7 33 40 PM" src="https://github.com/continuedev/continue/assets/13314504/0913ffe6-eb3f-4cee-b77a-e5f6e9ce003d">

**Comment by sestinj** [comment]
This is resolved by using the VS Code language server rather than downloading and connecting to our own, so going to close this issue
