### ISSUE TITLE
Continue is throwing an error and not working on startup

### ISSUE THREAD

**Issue by MrSimmmons** [continuedev/continue#480]
**Describe the bug**
Continue doesnt work after (what im assuming) an update. Have done a full restart

**To Reproduce**

1. Start VS Code

**Environment**

- Operating System: 13.5.2, M1, 16GB ram
- Python Version: 3.11.5
- Continue Version: v0.0.392
- LLM (if needed): CodeLlama through Ollama

**Logs**

Continue server logs:

```
[2023-09-16 19:28:35,092] [DEBUG] IDE websocket disconnected
[2023-09-16 19:28:35,093] [DEBUG] Closing ide websocket
[2023-09-16 19:28:35,094] [DEBUG] GUI websocket disconnected
[2023-09-16 19:28:35,095] [DEBUG] Closing gui websocket
[2023-09-16 19:28:35,096] [DEBUG] Removing session: f33b3b0f-e7cb-4a6f-b340-cb33deb29b91
[2023-09-16 19:28:39,839] [DEBUG] Health check
[2023-09-16 19:28:39,847] [DEBUG] Accepted websocket connection from Address(host='127.0.0.1', port=59327)
[2023-09-16 19:28:39,891] [DEBUG] Received message while initializing workspaceDirectory
[2023-09-16 19:28:39,891] [DEBUG] Received message while initializing uniqueId
[2023-09-16 19:28:40,849] [DEBUG] New session: None
[2023-09-16 19:28:40,854] [DEBUG] Loaded Continue config file from /Users/simon/.continue/config.py
[2023-09-16 19:28:40,855] [DEBUG] Starting context manager
[2023-09-16 19:28:40,856] [WARNING] Failed to load saved_context_groups.json: Expecting value: line 1 column 1 (char 0). Reverting to empty list.
[2023-09-16 19:28:40,896] [DEBUG] Sending session id: 34fad3f8-2448-4a0a-addc-e66268271d56
[2023-09-16 19:28:40,901] [DEBUG] Loading Meilisearch index...
[2023-09-16 19:28:40,928] [WARNING] Error adding documents to meilisearch for context provider URLContextProvider: "URLContextProvider" object has no field "_static_url_context_items"
[2023-09-16 19:28:40,928] [DEBUG] Loaded 0 documents into meilisearch in 0.0017058849334716797 seconds for context provider code
[2023-09-16 19:28:40,930] [DEBUG] Loaded 1 documents into meilisearch in 0.0035948753356933594 seconds for context provider search
[2023-09-16 19:28:40,933] [DEBUG] Loaded 1 documents into meilisearch in 0.0067331790924072266 seconds for context provider diff
[2023-09-16 19:28:40,935] [DEBUG] Loaded 1 documents into meilisearch in 0.007858991622924805 seconds for context provider terminal
[2023-09-16 19:29:00,929] [DEBUG] Error loading meilisearch index: 
[2023-09-16 19:29:00,933] [WARNING] Failed to kill process on port 7700
[2023-09-16 19:29:00,933] [WARNING] Failed to kill process on port 7700

--- This warning gets printed another ~100 times within ~10ms ---

[2023-09-16 19:29:00,947] [WARNING] Failed to kill process on port 7700
[2023-09-16 19:29:00,947] [WARNING] Failed to kill process on port 7700
[2023-09-16 19:29:00,951] [CRITICAL] Exception caught from async task: Traceback (most recent call last):

  File "asyncio/tasks.py", line 490, in wait_for

  File "asyncio/tasks.py", line 267, in __step

  File "continuedev/src/continuedev/core/context.py", line 360, in safe_load
    num_documents = await asyncio.wait_for(
                    ^^^^^^^^^^^^^^^^^^^^^^^

  File "asyncio/tasks.py", line 466, in wait_for

  File "asyncio/futures.py", line 287, in __await__

asyncio.exceptions.CancelledError


The above exception was the direct cause of the following exception:


Traceback (most recent call last):

  File "continuedev/src/continuedev/core/context.py", line 383, in load_index
    await asyncio.wait_for(asyncio.gather(*tasks), timeout=20)

  File "asyncio/tasks.py", line 492, in wait_for

TimeoutError


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "psutil/_psosx.py", line 346, in wrapper

  File "psutil/_psosx.py", line 503, in connections

ProcessLookupError: [Errno 3] No such process (originated from proc_pidinfo(PROC_PIDLISTFDS) 1/2)


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "continuedev/src/continuedev/libs/util/create_async_task.py", line 21, in callback
    future.result()

  File "asyncio/futures.py", line 203, in result

  File "asyncio/tasks.py", line 267, in __step

  File "continuedev/src/continuedev/core/context.py", line 275, in start_meilisearch
    await self.load_index(sdk.ide.workspace_directory)

  File "continuedev/src/continuedev/core/context.py", line 388, in load_index
    await restart_meilisearch()

  File "continuedev/src/continuedev/server/meilisearch_server.py", line 175, in restart_meilisearch
    kill_proc(7700)

  File "continuedev/src/continuedev/server/meilisearch_server.py", line 166, in kill_proc
    for conns in proc.connections(kind='inet'):
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "psutil/__init__.py", line 1171, in connections

  File "psutil/_psosx.py", line 349, in wrapper

psutil.ZombieProcess: PID still exists but it's a zombie (pid=1519)
```

VS Code console logs:

```
Error handling message (listDirectoryContents) from Continue server:
  Error: EPERM: operation not permitted, scandir '/Users/simon/.Trash'
```

**Comment by sestinj** [comment]
Continue is trying to kill an old meilisearch process to set up a new one, but the old process is for some reason detached. What you can do is: `lsof -i :7700` to get the process ID of the currently running meilisearch process and then `kill -9 <PID>` to kill it. I would expect this to solve the issue

**Comment by sestinj** [comment]
And on our end there's a) better error handling to add here, and b) a need to stop zombie processes from being created

**Comment by MrSimmmons** [comment]
Ahh yep that does appear to have worked thanks!

Shall I leave this issue open for enhancement references? or would you like me to create two new feature request issues for your points?

**Comment by sestinj** [comment]
Let's leave this issue open, and I'll close once I've made the updates (they're all small enough that I'm comfortable not creating a new issue). First is already done, and I'll take a look at the second soon. A third is adding this to the troubleshooting docs

**Comment by sestinj** [comment]
Closing now that better error handling has been added, troubleshooting docs have been expanded, and I haven't spotted a zombie process since adjusting the setup of Meilisearch. If there are still problems feel free to re-open!
