### ISSUE TITLE
No module named 'continuedev.src'

### ISSUE THREAD

**Issue by danny-su** [continuedev/continue#484]
[2023-09-18 16:45:32,611] [ERROR] Failed to load config.py: ['Traceback (most recent call last):\n', '  File "/opt/homebrew/lib/python3.11/site-packages/continuedev/core/sdk.py", line 75, in create\n    sdk.config = config or sdk._load_config_dot_py()\n                           ^^^^^^^^^^^^^^^^^^^^^^^^^\n', '  File "/opt/homebrew/lib/python3.11/site-packages/continuedev/core/sdk.py", line 242, in _load_config_dot_py\n    config = ContinueConfig.from_filepath(path)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n', '  File "/opt/homebrew/lib/python3.11/site-packages/continuedev/core/config.py", line 112, in from_filepath\n    spec.loader.exec_module(config)\n', '  File "<frozen importlib._bootstrap_external>", line 940, in exec_module\n', '  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed\n', '  File "/Users/danny/.continue/config.py", line 9, in <module>\n    from continuedev.src.continuedev.core.main import Step\n', "ModuleNotFoundError: No module named 'continuedev.src'\n"]
<img width="1348" alt="image" src="https://github.com/continuedev/continue/assets/12178855/eaa61dd8-7b16-410e-91c0-f12f692f1d93">

<img width="460" alt="image" src="https://github.com/continuedev/continue/assets/12178855/3e1a77f6-c8b9-4576-b2fe-5c11b6f12e50">

- Operating System: MacOS 13.5.2
- Python Version: 3.11.5
- Continue Version: 0.1.31

**Comment by sestinj** [comment]
Hi @danny-su, there is currently a difference between the imports when running the binary and when running python -m continuedev. I plan on fixing this in the next couple days, but if you open `~/.continue/config.py` and remove the prefix `continuedev.src` from all imports (so there is only one continuedev), this will solve the problem

**Comment by sestinj** [comment]
@danny-su and everyone else who has seen this issue - we've finally merged our pre-release version into the main extension, which solves this problem for good by ensuring that the import paths are identical for both the binary and PyPI package. Furthermore, we've added an auto-migration to solve the problem in case it ever somehow shows up again. I'm going to close this issue, but please don't hesitate to comment and re-open if you are still experiencing problems!
