### ISSUE TITLE
Issues building from source with the 'install_from_source.py' script

### ISSUE THREAD

**Issue by LangLangBart** [continuedev/continue#485]
## description
- follow the documentation for [building from source](https://github.com/continuedev/continue/blob/main/continuedev/README.md#install-from-source)
  - run the `install_from_source.py` and a couple of issues occur

### issue 1

- when the script is executed, it ends up failing because it cannot find a Java runtime environment
  - related issue: https://github.com/OpenAPITools/openapi-generator-cli/issues/122

```sh

> continue@0.0.207 clientgen
> rm -rf src/client/ && npx @openapitools/openapi-generator-cli generate -i ../schema/openapi.json -g typescript-fetch -o src/client/ --additional-properties=supportsES6=true,npmVersion=8.19.2,typescriptThreePlus=true

/Users/paria/Developer/continue/extension/node_modules/@openapitools/openapi-generator-cli/main.js:673
                error ? reject(new Error(stderr)) : resolve(stdout);
                               ^

Error: No Java runtime present, requesting install.

    at /Users/paria/Developer/continue/extension/node_modules/@openapitools/openapi-generator-cli/main.js:673:32
    at ChildProcess.exithandler (node:child_process:430:5)
    at ChildProcess.emit (node:events:514:28)
    at maybeClose (node:internal/child_process:1105:16)
    at Socket.<anonymous> (node:internal/child_process:457:11)
    at Socket.emit (node:events:514:28)
    at Pipe.<anonymous> (node:net:337:12)
```

- after installing a version the issue is gone

```sh
# example using homebrew on macOS
brew install openjdk@11
```
 
> [!NOTE]
> it was not necessary to add the installed version to my `PATH` for the`install_from_source.py`script to work, but when I wanted to check if there is a runtime environment present with `javac -version`, it was necessary to add it to the `PATH`
>```sh
>#.zshrc
>export PATH="/usr/local/opt/openjdk@11/bin:$PATH"
>```

### issue 2
- the script runs into an issue because of the `get_latest_version` function in the script

```sh
Traceback (most recent call last):
  File "/Users/paria/Developer/continue/extension/scripts/install_from_source.py", line 71, in <module>
    main()
  File "/Users/paria/Developer/continue/extension/scripts/install_from_source.py", line 64, in main
    latest = get_latest_version()
             ^^^^^^^^^^^^^^^^^^^^
  File "/Users/paria/Developer/continue/extension/scripts/install_from_source.py", line 25, in get_latest_version
    return max(versions, key=version_tuple)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/paria/Developer/continue/extension/scripts/install_from_source.py", line 17, in version_tuple
    return tuple(map(int, version.split(".")))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: 'patch'
```

- the function came with 73c6827d02ff62313184e3745fd94c7591c98b61 and worked till 34f32ed5f71055ea11d4332f18e77ceba5849631 was committed
  - since that commit the produced extension is called `continue-patch.vsix`

<img src="https://github.com/continuedev/continue/assets/92653266/477eb6f2-6289-4d33-bc4c-8044acdfa00f" width="800">

### issue 3
- the popular clone of [VSCode](https://github.com/microsoft/vscode), known as [VSCodium](https://github.com/VSCodium/vscodium), utilizes the cli command `codium` instead of `code`

```py
    latest = get_latest_version()
    resp = run(f"cd ..; code --install-extension ./build/{latest}")

    print("Continue VS Code extension installed successfully. Please restart VS Code to use it.")
```

- maybe check if `code` is installed or even better make it work with `codium` as well ?

```sh
code --version
codium --version
```

**Comment by LangLangBart** [comment]
- for the `java` issue, it may not be necessary to check the `javac -version` like you do with other commands like `python`, `node`, ... a simple `Note` might be enough, similar to how you have a `Note` for installing the `Python extension` (Link: [README.md#continue-server](https://github.com/continuedev/continue/blob/main/continuedev/README.md#continue-server))

---

PS: [[Markdown] An option to highlight a "Note" and "Warning" using blockquote (Beta) #16925 ](https://github.com/orgs/community/discussions/16925)

<img src="https://github.com/continuedev/continue/assets/92653266/72f3fa88-df45-4fc9-8ac8-75d0bf88a65d" width="600">

> [!NOTE]  
> Highlights information that users should take into account, even when skimming.

> [!IMPORTANT]  
> Crucial information necessary for users to succeed.

> [!WARNING]  
> Critical content demanding immediate user attention due to potential risks.
