### ISSUE TITLE
Shows response, then crashes

### ISSUE THREAD

**Issue by mhensley-cls** [continuedev/continue#557]
### Before submitting your bug report

- [ ] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [ ] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [ ] I've seen the [troubleshooting guide](https://continue.dev/docs/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS: OSX 13.6 (22G120)
- Continue: v0.1.21
```

### Description

Displays LLM stream, then errors out unless I pre-pend a message to be concise.

Error occurs with CodeLlama running on GPU server, various versions of GPT3.5 & GPT4.

### To reproduce

1. highlight code
2. ask it to add comments

### Log output

```Shell
[2023-10-13 15:12:20,364] [DEBUG] Received GUI message {"messageType":"edit_step_at_index","data":{"user_input":"Add comments to this code","index":1}}
[2023-10-13 15:12:43,617] [ERROR] Error while running step: 
Traceback (most recent call last):

  File "server/continuedev/core/autopilot.py", line 438, in _run_singular_step

  File "server/continuedev/core/main.py", line 376, in __call__

  File "server/continuedev/plugins/steps/chat.py", line 130, in run

  File "/var/folders/9d/plt6z9y962d9hp0x6tlzv9sw0000gq/T/_MEIR3U8ZF/continuedev/libs/llm/base.py", line 374, in complete
    completion = await self._complete(prompt=prompt, options=options)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/var/folders/9d/plt6z9y962d9hp0x6tlzv9sw0000gq/T/_MEIR3U8ZF/continuedev/libs/llm/base.py", line 464, in _complete
    async for chunk in self._stream_complete(prompt=prompt, options=options):

  File "/var/folders/9d/plt6z9y962d9hp0x6tlzv9sw0000gq/T/_MEIR3U8ZF/continuedev/libs/llm/ollama.py", line 113, in _stream_complete
    j = json.loads(chunk)
        ^^^^^^^^^^^^^^^^^

  File "json/__init__.py", line 346, in loads

  File "json/decoder.py", line 337, in decode

  File "json/decoder.py", line 355, in raw_decode

json.decoder.JSONDecodeError: Expecting value: line 1 column 1444 (char 1443)

Expecting value: line 1 column 1444 (char 1443)
[2023-10-13 15:25:46,370] [DEBUG] Received GUI message {"messageType":"set_system_message","data":{"message":"Please give concise answers"}}
[2023-10-13 15:25:46,378] [DEBUG] Received GUI message {"messageType":"set_temperature","data":{"temperature":0.5}}
[2023-10-13 15:25:54,046] [DEBUG] Received GUI message {"messageType":"edit_step_at_index","data":{"user_input":"Add comments to this code","index":1}}
```

**Comment by sestinj** [comment]
@mhensley-cls thanks for sharing this - I'm going to add some extra error handling to our next pre-release that will both stop the error from being thrown and help us determine the problem. I'll message again here once it's ready!

**Comment by sestinj** [comment]
@mhensley-cls very sorry! I added the error handling but failed to update you. This is now available in the latest version of the VS Code extension and the PyPI package. Let me know if things appear to be solved or not : )

**Comment by sestinj** [comment]
This appears to have been solved from both my testing and the reports of another user with the same problem. Going to close, but feel free to re-open as needed
