### ISSUE TITLE
Timeout Error when using slower local models

### ISSUE THREAD

**Issue by lunamidori5** [continuedev/continue#560]
### Before submitting your bug report

- [] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [x] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [x] I've seen the [troubleshooting guide](https://continue.dev/docs/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS: Windows 11
- Continue: Yes (I think 1.26)
```

### Description

When requesting something to be done like 

```
Please program a just demo fight that uses these stats and does one action per person per turn, then the foe takes one action, it keeps going until all party members are dead or the foe is dead. You only need to type the new code not the old code
``` 
it is still giving a timeout error after about 10 mins, and stops. here is my ``config.py``

```python
models=Models(
        default=OpenAI(
            api_key="my-api-key",
            model="gpt-3.5-turbo",
            api_base="http://localhost:8080/v1",
            api_type="openai",
            timeout=600000
        ),
        edit=OpenAI(
            api_key="my-api-key",
            model="gpt-3.5-code",
            api_base="http://localhost:8080/v1",
            api_type="openai",
            timeout=600000
        )
    ),
```

### Log output

```txt
Traceback (most recent call last):

  File "server\continuedev\core\autopilot.py", line 438, in _run_singular_step

  File "server\continuedev\core\main.py", line 376, in __call__

  File "server\continuedev\plugins\steps\chat.py", line 105, in run

  File "C:\Users\LUNAMI~1\AppData\Local\Temp\_MEI65482\continuedev\libs\llm\base.py", line 456, in stream_chat
    async for chunk in self._stream_chat(messages=messages, options=options):

  File "C:\Users\LUNAMI~1\AppData\Local\Temp\_MEI65482\continuedev\libs\llm\openai.py", line 167, in _stream_chat
    async for chunk in await openai.ChatCompletion.acreate(

  File "openai\api_resources\abstract\engine_api_resource.py", line 230, in <genexpr>

  File "openai\api_requestor.py", line 319, in wrap_resp

  File "openai\api_requestor.py", line 634, in <genexpr>

  File "openai\api_requestor.py", line 114, in parse_stream_async

  File "aiohttp\streams.py", line 35, in __anext__

  File "aiohttp\streams.py", line 311, in readline

  File "aiohttp\streams.py", line 343, in readuntil

  File "aiohttp\streams.py", line 303, in _wait

  File "aiohttp\helpers.py", line 725, in __exit__

asyncio.exceptions.TimeoutError
```

**Comment by lunamidori5** [comment]
I again, did not add the bug label github, please stop saying I did lol

**Comment by sestinj** [comment]
@lunamidori5 thanks for adding me : )

Well either for some ridiculous reason the timeout parameter is in milliseconds (in which case 600,000 of them is exactly 10 minutes), or OpenAI simply ignores the parameter (unfortunately they are known to do this with others).

GGML class might work, since it does the same thing, calling an OpenAI-compatible API, except that we get full control over the requests.

Other thing to try might be timeout=None to get infinite timeout

**Comment by lunamidori5** [comment]
@sestinj guess I am going to add a few more 0 to it and test lol
