### ISSUE TITLE
When starting a local server, an import error is thrown.

### ISSUE THREAD

**Issue by adamzenith** [continuedev/continue#631]
### Before submitting your bug report

- [X] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [X] I've seen the [troubleshooting guide](https://continue.dev/docs/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS: ubuntu 22.04
- Continue: 0.1.98
```

### Description

When trying to manually create a continue server, immediately and import error is thrown. It seems it cannot find ''CreateCodebaseIndexChroma''

### To reproduce

`python3 -m continuedev`

### Log output

```Shell
[2023-11-16 08:25:49] [ERROR] Failed to load config.py: cannot import name 'CreateCodebaseIndexChroma' from 'continuedev.plugins.steps.codebase' (/home/matthias/.local/lib/python3.10/site-packages/continuedev/plugins/steps/codebase.py)


_________               _____ _____                       
__  ____/______ _______ __  /____(_)_______ ____  _______ 
_  /     _  __ \__  __ \_  __/__  / __  __ \_  / / /_  _ \
/ /___   / /_/ /_  / / // /_  _  /  _  / / // /_/ / /  __/
\____/   \____/ /_/ /_/ \__/  /_/   /_/ /_/ \__,_/  \___/ 


[2023-11-16 08:25:49] [DEBUG] ------ Begin Logs ------
INFO:     Started server process [1204155]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://127.0.0.1:65432 (Press CTRL+C to quit)
[2023-11-16 08:25:49] [DEBUG] Starting MeiliSearch...
[2023-11-16 08:25:49] [INFO] Meilisearch started at http://localhost:7700
INFO:     ('127.0.0.1', 45260) - "WebSocket /socket.io/?window_info=%7B%22window_id%22%3A%22de87c088-4a38-4be7-8e7b-11942dbfef29%22%2C%22workspace_directory%22%3A%22%2Fsitewalk%2Fsitewalk%2Flocalizer%22%2C%22unique_id%22%3A%22e6fe610dee64ec8d9d6bf6a63159e83864c23d9374f33ab4f783a82059b0fbfd%22%2C%22ide_info%22%3A%7B%22name%22%3A%22vscode%22%2C%22version%22%3A%221.84.2%22%2C%22remote_name%22%3A%22dev-container%22%7D%7D&EIO=4&transport=websocket" [accepted]
INFO:     connection open
[2023-11-16 08:25:49] [ERROR] Failed to load config.py: Traceback (most recent call last):

  File "/home/matthias/.local/lib/python3.10/site-packages/continuedev/server/window_manager.py", line 41, in load_config
    return ContinueConfig.load_default()

  File "/home/matthias/.local/lib/python3.10/site-packages/continuedev/core/config.py", line 187, in load_default
    return ContinueConfig.from_filepath(path)

  File "/home/matthias/.local/lib/python3.10/site-packages/continuedev/core/config.py", line 173, in from_filepath
    spec.loader.exec_module(config)

  File "<frozen importlib._bootstrap_external>", line 883, in exec_module

  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed

  File "/home/matthias/.continue/config.py", line 25, in <module>
    from continuedev.plugins.steps.codebase import CreateCodebaseIndexChroma, AnswerQuestionChroma

ImportError: cannot import name 'CreateCodebaseIndexChroma' from 'continuedev.plugins.steps.codebase' (/home/matthias/.local/lib/python3.10/site-packages/continuedev/plugins/steps/codebase.py)

INFO:     ('127.0.0.1', 45268) - "WebSocket /socket.io/?window_info=%7B%22window_id%22%3A%225bc93203-6a2c-4c84-8d79-9d52aa730cf7%22%2C%22workspace_directory%22%3A%22%2Fsitewalk%2Fsitewalk%2Frc_training%22%2C%22unique_id%22%3A%22e6fe610dee64ec8d9d6bf6a63159e83864c23d9374f33ab4f783a82059b0fbfd%22%2C%22ide_info%22%3A%7B%22name%22%3A%22vscode%22%2C%22version%22%3A%221.84.2%22%2C%22remote_name%22%3A%22dev-container%22%7D%7D&EIO=4&transport=websocket" [accepted]
INFO:     connection open
[2023-11-16 08:25:51] [ERROR] Failed to load config.py: Traceback (most recent call last):

  File "/home/matthias/.local/lib/python3.10/site-packages/continuedev/server/window_manager.py", line 41, in load_config
    return ContinueConfig.load_default()

  File "/home/matthias/.local/lib/python3.10/site-packages/continuedev/core/config.py", line 187, in load_default
    return ContinueConfig.from_filepath(path)

  File "/home/matthias/.local/lib/python3.10/site-packages/continuedev/core/config.py", line 173, in from_filepath
    spec.loader.exec_module(config)

  File "<frozen importlib._bootstrap_external>", line 883, in exec_module

  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed

  File "/home/matthias/.continue/config.py", line 25, in <module>
    from continuedev.plugins.steps.codebase import CreateCodebaseIndexChroma, AnswerQuestionChroma

ImportError: cannot import name 'CreateCodebaseIndexChroma' from 'continuedev.plugins.steps.codebase' (/home/matthias/.local/lib/python3.10/site-packages/continuedev/plugins/steps/codebase.py)

INFO:     ('127.0.0.1', 45270) - "WebSocket /socket.io/?window_info=%7B%22window_id%22%3A%2228978024-781d-4de4-b72b-1e7880a1df57%22%2C%22workspace_directory%22%3A%22%2Fsitewalk%2Fsitewalk%2Fdalux_shared%22%2C%22unique_id%22%3A%22e6fe610dee64ec8d9d6bf6a63159e83864c23d9374f33ab4f783a82059b0fbfd%22%2C%22ide_info%22%3A%7B%22name%22%3A%22vscode%22%2C%22version%22%3A%221.84.2%22%2C%22remote_name%22%3A%22dev-container%22%7D%7D&EIO=4&transport=websocket" [accepted]
INFO:     connection open
[2023-11-16 08:25:52] [ERROR] Failed to load config.py: Traceback (most recent call last):

  File "/home/matthias/.local/lib/python3.10/site-packages/continuedev/server/window_manager.py", line 41, in load_config
    return ContinueConfig.load_default()

  File "/home/matthias/.local/lib/python3.10/site-packages/continuedev/core/config.py", line 187, in load_default
    return ContinueConfig.from_filepath(path)

  File "/home/matthias/.local/lib/python3.10/site-packages/continuedev/core/config.py", line 173, in from_filepath
    spec.loader.exec_module(config)

  File "<frozen importlib._bootstrap_external>", line 883, in exec_module

  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed

  File "/home/matthias/.continue/config.py", line 25, in <module>
    from continuedev.plugins.steps.codebase import CreateCodebaseIndexChroma, AnswerQuestionChroma

ImportError: cannot import name 'CreateCodebaseIndexChroma' from 'continuedev.plugins.steps.codebase' (/home/matthias/.local/lib/python3.10/site-packages/continuedev/plugins/steps/codebase.py)
```

**Comment by sestinj** [comment]
@adamzenith This is due to us having removed the need for CreateCodebaseIndexChroma. If you delete it and any usage from your ~/.continue/config.py, then this error shouldn't happen.

And to more permanently solve this sort of thing, we've just yesterday (starting with the pre-release, soon to be in the PyPI package) migrated to a .json format for the config file

**Comment by sestinj** [comment]
@adamzenith the Continue Python server is no longer being used which makes this error inconsequential for the newest versions. Therefore closing this issue, but please open a new one if you're experiencing other problems
