### ISSUE TITLE
MeiliSearch fail to start

### ISSUE THREAD

**Issue by pando85** [continuedev/continue#637]
### Before submitting your bug report

- [x] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [x] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [x] I've seen the [troubleshooting guide](https://continue.dev/docs/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS: `Linux 6.1.62-1-MANJARO`
- Continue: `0.6.3`
```

### Description

MeiliSearch fails to install and run. I have meilisearch installed by package manager and also I tested the curl in a dir in `/tmp` and it downloads the binary and I can execute it.

### To reproduce

1. Install Ollama
2. Run a new session with Ollama worker
3. Check logs

### Log output

```Shell

[2023-11-19 07:27:38] [DEBUG] Downloading MeiliSearch with curl...
[2023-11-19 07:27:38] [CRITICAL] Exception caught from async task: Traceback (most recent call last):

  File "server/continuedev/libs/util/create_async_task.py", line 21, in callback

  File "asyncio/futures.py", line 203, in result

  File "asyncio/tasks.py", line 277, in __step

  File "server/continuedev/core/context.py", line 273, in load_index

  File "server/continuedev/server/meilisearch_server.py", line 155, in start_meilisearch

  File "server/continuedev/server/meilisearch_server.py", line 87, in ensure_meilisearch_installed

  File "asyncio/tasks.py", line 489, in wait_for

  File "asyncio/futures.py", line 203, in result

  File "asyncio/tasks.py", line 277, in __step

  File "server/continuedev/server/meilisearch_server.py", line 48, in download_meilisearch

  File "subprocess.py", line 571, in run

subprocess.CalledProcessError: Command 'curl -L https://install.meilisearch.com | sh' returned non-zero exit status 127.

[2023-11-19 07:27:38] [WARNING] Error loading meilisearch index: Command 'curl -L https://install.meilisearch.com | sh' returned non-zero exit status 127.
```

**Comment by sestinj** [comment]
@pando85 this must be either `curl` or `sh` not being found, perhaps PATH isn't correctly loaded by python subprocess on Manjaro linux. Are you able to run this successfully from a Python REPL?

```python
import subprocess

subprocess.run(
            "curl -L https://install.meilisearch.com | sh",
            shell=True,
            check=True,
        )
```

**Comment by sestinj** [comment]
You can set the meilisearch URL to state that you are running it on your own if using the PyPI package (`python -m continuedev --meilisearch-url http://localhost:7700`), but we don't yet have this option in the extension

**Comment by pando85** [comment]
```bash
» python
Python 3.11.5 (main, Sep  2 2023, 14:16:33) [GCC 13.2.1 20230801] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import subprocess
>>> 
>>> subprocess.run(
...             "curl -L https://install.meilisearch.com | sh",
...             shell=True,
...             check=True,
...         )
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  4352  100  4352    0     0  12231      0 --:--:-- --:--:-- --:--:-- 12231
Downloading Meilisearch binary v1.5.0 for linux, architecture amd64...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  113M  100  113M    0     0  27.5M      0  0:00:04  0:00:04 --:--:-- 36.1M
Meilisearch v1.5.0 binary successfully downloaded as 'meilisearch' file.

Run it:
    $ ./meilisearch
Usage:
    $ ./meilisearch --help
CompletedProcess(args='curl -L https://install.meilisearch.com | sh', returncode=0)
>>> 
```
It works perfectly from terminal.
I don't understand what could be happening.
I also tested it in `/tmp` and it works.
Do you know more about the context how is this executed inside the VScode extension?

**Comment by pando85** [comment]
With 0.7.4 is working fine. Closing this issue.
