### ISSUE TITLE
Continue tab is blank (IDEA 2023.2 Win 10)

### ISSUE THREAD

**Issue by schiebelp** [continuedev/continue#649]
### Before submitting your bug report

- [x] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [X] I've seen the [troubleshooting guide](https://continue.dev/docs/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS: Win 10 
- Continue: 0.0.20
- Python: 3.11.6
- IDE: IntelliJ IDEA 2023.2 (Community Edition)
```

### Description

I was unable to use it. The Plugin tab is visible but nothing in it. 

I noticed in idea.log an exception:
INFO - STDOUT - Starting Continue server binary
INFO - STDERR - java.nio.file.AccessDeniedException: startProcess.vbs
...
...runBinary(ContinuePluginStartupActivity.kt:244)

Found the code 244 is this:
233:            val scriptPath = Paths.get("startProcess.vbs")
244:            Files.writeString(scriptPath, script)

Which is - I believe - is all about running the server_continue.exe using that vbs code.

So I went for that server and ran it myself. That unfortunatelly did not help as tab was still empty (after IDE restart).

The server communicates though, when IDEA is opened:
INFO:     connection open
...appears. 

So there seems to be another issue. Which is frustrating, because this would be killer app. I would love to use it with local llm.

### To reproduce

1. Install plugin
2. Open IDEA IDE
3. Open tab Continue

### Log output

```Shell
continue.log

[2023-12-03 00:52:54] [WARNING] Failed to load config from C:\Users\Petr\.continue\config.py: module 'config' has no attribute 'config'
[2023-12-03 00:52:54] [DEBUG] ------ Begin Logs ------
[2023-12-03 00:52:54] [DEBUG] Downloading MeiliSearch for Windows...
[2023-12-03 00:53:05] [DEBUG] Starting MeiliSearch...
[2023-12-03 00:53:05] [INFO] Meilisearch started at http://localhost:7700
```

**Comment by sestinj** [comment]
@schiebelp sorry to see this, could you share what the tab looked like when empty?

Also one thing to be sure of, did you check the box in settings for "Manually Running Server" when you were running it yourself?

**Comment by sestinj** [comment]
@schiebelp This is now solved for good in the latest JetBrains extension. We no longer use the separate Python server, which means that whatever connection / download issue was happening here is no longer possible. Can you confirm that the tab is no longer blank?

**Comment by Rybo-W** [comment]
Installing for the first time, I get the blank tab. Clicking the + icon does nothing. No config.json file exists.

![2023-12-31_131307](https://github.com/continuedev/continue/assets/47239155/b42f0964-e33d-4228-9609-d034ac85ffdb)

- OS: Win 10 
- Continue: 0.0.25
- Python: 3.10.4
- IDE: PyCharm 2023.2 (Pro Edition)

**Comment by elabbarw** [comment]
Getting this with the Intellij IDE as well...

**Comment by sestinj** [comment]
@elabbarw Could you share what version of the extension you're running, and which IDE you have? I'm wondering whether this might be separate, especially possibly related to Android Studio

**Comment by elabbarw** [comment]
I tried with the downloads that you already have compiled and they work fine, so it must be something related to how I'm building the plugin myself.

**Comment by sestinj** [comment]
@Rybo-W We now have version 0.0.27 available with a number of fixes since 0.0.25—are you still experiencing this error? If so we're working toward a number of large improvements in 0.0.28, and I'd love to get more info here so I can make sure it gets solved

**Comment by Rybo-W** [comment]
@sestinj Thanks for responding. Unfortunately, I experience the exact same problem with version 0.0.26 and 0.0.27.

> blank tab. Clicking the + icon does nothing.

**Comment by schiebelp** [comment]
@sestinj thanks for that update! ^^ I just wanted to share, after update. The tab still empty. However! On my work win 10 laptop, it works!

**Comment by sestinj** [comment]
@schiebelp @Rybo-W thanks for trying. It would be incredibly helpful if you had the chance to check the logs (Help -> Open Logs in Editor) for anything related to Continue, but otherwise will do the best I can to find a similar environment in which to reproduce

<img width="713" alt="Screen Shot 2024-01-28 at 3 16 34 PM" src="https://github.com/continuedev/continue/assets/33237525/2d6421ff-86da-4e31-a702-c5b3a0a62448">

**Comment by Rybo-W** [comment]
@sestinj this is all I see in idea.log from PyCharm related to the continue plugin.

**Installing the continue plugin.**
```
2024-01-29 17:23:22,754 [  22234]   INFO - #c.i.i.p.DynamicPlugins - Plugin com.github.continuedev.continueintellijextension loaded without restart in 273 ms
```
---
**Disabling the continue plugin.**

![2024-01-29_172851](https://github.com/continuedev/continue/assets/47239155/a20e1e4f-0860-4342-a845-66f6d92e91f1)
```
2024-01-29 17:26:32,855 [ 212335]   INFO - #c.i.i.p.DisabledPluginsState - Plugins to disable: [com.github.continuedev.continueintellijextension]
2024-01-29 17:26:32,856 [ 212336]   INFO - #c.i.i.p.DynamicPlugins - Plugins to unload: [PluginDescriptor(name=Continue, id=com.github.continuedev.continueintellijextension, descriptorPath=plugin.xml, path=~\AppData\Roaming\JetBrains\PyCharm2023.2\plugins\continue-intellij-extension, version=0.0.27, package=null, isBundled=false)]
2024-01-29 17:26:33,287 [ 212767]   INFO - #c.i.i.p.DynamicPlugins - Successfully unloaded plugin com.github.continuedev.continueintellijextension (classloader unload checked=false)
```
---
**Enabling continue plugin.**

![2024-01-29_172913](https://github.com/continuedev/continue/assets/47239155/19e4e06f-0220-4324-a47b-e45851d89dc2)
```
2024-01-29 17:29:18,893 [ 378373]   INFO - #c.i.i.p.DisabledPluginsState - Plugins to enable: [com.github.continuedev.continueintellijextension]
2024-01-29 17:29:18,893 [ 378373]   INFO - #c.i.i.p.DynamicPlugins - Plugins to load: [PluginDescriptor(name=Continue, id=com.github.continuedev.continueintellijextension, descriptorPath=plugin.xml, path=~\AppData\Roaming\JetBrains\PyCharm2023.2\plugins\continue-intellij-extension, version=0.0.27, package=null, isBundled=false)]
2024-01-29 17:29:19,100 [ 378580]   INFO - #c.i.i.p.DynamicPlugins - Plugin com.github.continuedev.continueintellijextension loaded without restart in 205 ms
```

**Comment by sestinj** [comment]
@skydiablo the error you see here has been *sometimes* solved by changing the JDK used to load the IDE. More info [here](https://github.com/continuedev/continue/issues/596#issuecomment-1789327178) (what I said about telling the user immediately I think ended up not happening obviously)

**Comment by skydiablo** [comment]
@sestinj thx, you did it! :+1:

**Comment by vdubedout** [comment]
Changing the boot runtime did not solved my issues so I searched for more broad jcef / browser issues and found this and it solved it. 

https://github.com/flutter/flutter-intellij/issues/7000#issuecomment-1952854934

> First, update the runtime to one with JCEF following these steps:
> 
>     1. Select **Help** > **Find Action** from the Android Studio menu.
> 
>     2. Enter "**Choose Boot Java Runtime for the IDE**" and select it from the suggestion list.
> 
>     3. Select the latest bundled runtime that comes with JCEF support
> 
>     4. Click OK and restart the IDE
> 
> 
> Then, if you're getting this error: `GPU process restarts too many times and seems to be unstable. Try to restart IDE or disable GPU acceleration completely.` follow these steps:
> 
>     1. Select **Help** > **Find Action** from the Android Studio menu.
> 
>     2. Look for **Registry...**
> 
>     3. Find the `ide.browser.jcef.sandbox.enable` option in the list and disable it
> 
>     4. Restart


If it does not work an another person found this:
> For my case it was related with Markdown view. So what worked for me:
> 
>     1. Choose Boot Java Runtime for the IDE (double shift to search)
> 
>     2. Select the latest bundled runtime that comes with JCEF support, ok and restart
> 
>     3. Again search for Registry and enable `jcef.browser` and disable `markdown view`
> 
>     4. restart

**Comment by Rybo-W** [comment]
Still getting blank tab with the latest Continue version. I upgraded to 2024.1 PyCharm and now it works!

**Comment by zoobab** [comment]
I was hit by that bug on Intellij, I found that the 0.0.52 has this issue, while 0.0.50 works fine. Is there any culprit commit?

**Comment by blinkus2000** [comment]
OK, So at the time of this happening (blank UI) it looks like Continue.dev is trying to index large files. There is also some decompression going on. 

I am including 3 files. 

**DefaultDispatcher-worker-2.txt** this is a thread stack that has just read some input. 
**lastDataReadByDefaultDispatcher-worker-2.txt** is the last data that worker-2 acted upon. 
**DefaultDispatcher-worker-1.txt** is the problem thread. 
It is currently dealing with 10MB of compressed data ... Given that we have a blank UI and we are dealing with large amounts of compressed data, I would think this is what is holding up the population of the UI. 


[DefaultDispatcher-worker-1.txt](https://github.com/user-attachments/files/17316755/DefaultDispatcher-worker-1.txt)
[DefaultDispatcher-worker-2.txt](https://github.com/user-attachments/files/17316756/DefaultDispatcher-worker-2.txt)
[lastDataReadByDefaultDispatcher-worker-2.txt](https://github.com/user-attachments/files/17316757/lastDataReadByDefaultDispatcher-worker-2.txt)

**Comment by sestinj** [comment]
@blinkus2000 thanks for the detail here! Seems like it should let me pretty easily reproduce, and then what we'll probably want to do is just ignore such large files, as they would never be relevant for @ codebase anyway. I'll let you know once I've gotten the chance to try

**Comment by blinkus2000** [comment]
Just an aside. If there is file compression going on, you can really spike the cpu if the file is big and the data is not compressible. I am not familiar enough with the com.intellij.util.io.LZ4 stuff to know if you have a way to test for compressibility, but it might be worth looking into.

**Comment by blinkus2000** [comment]
In case I missed something in my heap analysis, here is the full thread dump.

[fullThreadDump.txt](https://github.com/user-attachments/files/17329437/fullThreadDump.txt)

**Comment by masoncj** [comment]
I'm also having this issue of blank Continue window in Remote Development (SSH) in PyCharm despite:

* Using latest Plugin Version 0.77
* Using latest PyCharm version 2024.2.4 (have tried both latest release version  `JBC-242.23726.102` and latest 2024.3 EAP `JBC-243.21155.22`)
* Verifying that selected JVM version has JCEF:
<img width="392" alt="Screenshot 2024-10-26 at 2 03 59 PM" src="https://github.com/user-attachments/assets/f2b25b78-1ce9-4d4d-b910-58941f3a3a18">

* Toggling the mentioned JCEF registry settings:
<img width="804" alt="Screenshot 2024-10-26 at 2 05 31 PM" src="https://github.com/user-attachments/assets/ef9dc5b9-d488-46e2-afb3-d7656b29c154">

See the following logging:

```
2024-10-26 20:59:32,664 [   9838]   INFO - STDOUT - JCEF(59:32:664): initialized stderr logger, severity=LOGSEVERITY_INFO
2024-10-26 20:59:32,665 [   9839]   INFO - STDERR - JCEF_I(59:32:665): CefApp: set state NEW
2024-10-26 20:59:40,975 [  18149]   INFO - STDOUT - Webview not initialized yet java.lang.IllegalStateException: Failed to execute the requested JS expression. The related JCEF browser in not initialized.

```

Also seeing a lot of this when the plugin loads or unloads:

```
2024-10-26 21:08:27,526 [ 425212]   INFO - #c.i.i.p.DisabledPluginsState - Plugins to enable: [com.github.continuedev.continueintellijextension]
2024-10-26 21:08:27,526 [ 425212]   INFO - #c.i.i.p.DynamicPlugins - Plugins to load: []
2024-10-26 21:08:27,741 [ 425427]   INFO - #c.i.o.p.MergingQueueGuiExecutor - Running task: (dumb mode task) Plugin loading/unloading
2024-10-26 21:08:27,742 [ 425428]   INFO - #c.i.o.p.MergingQueueGuiExecutor - Task finished: (dumb mode task) Plugin loading/unloading
2024-10-26 21:08:27,797 [ 425483]   INFO - #c.i.p.u.i.s.e.DurableEnumeratorFactory - [enumerator.mmapped]: .valueHashToId (in memory) was filled (58 records)
2024-10-26 21:08:27,846 [ 425532]   INFO - #c.i.o.p.DumbServiceImpl - exit dumb mode [document-api]
2024-10-26 21:08:27,847 [ 425533]   INFO - STDERR - ERROR: Write-unsafe context! Model changes are allowed from write-safe contexts only. Please ensure you're using invokeLater/invokeAndWait with a correct modality state (not "any"). See TransactionGuard documentation for details.
2024-10-26 21:08:27,847 [ 425533]   INFO - STDERR -   current modality=ModalityState.NON_MODAL
2024-10-26 21:08:27,847 [ 425533]   INFO - STDERR - java.lang.Throwable: Write-unsafe context! Model changes are allowed from write-safe contexts only. Please ensure you're using invokeLater/invokeAndWait with a correct modality state (not "any"). See TransactionGuard documentation for details.
2024-10-26 21:08:27,847 [ 425533]   INFO - STDERR -   current modality=ModalityState.NON_MODAL
2024-10-26 21:08:27,847 [ 425533]   INFO - STDERR -     at com.intellij.openapi.diagnostic.Logger.error(Logger.java:376)
2024-10-26 21:08:27,847 [ 425533]   INFO - STDERR -     at com.intellij.openapi.application.TransactionGuardImpl.assertWriteActionAllowed(TransactionGuardImpl.java:136)
2024-10-26 21:08:27,848 [ 425534]   INFO - STDERR -     at com.intellij.psi.impl.PsiModificationTrackerImpl.fireEvent(PsiModificationTrackerImpl.java:81)
2024-10-26 21:08:27,848 [ 425534]   INFO - STDERR -     at com.intellij.psi.impl.PsiModificationTrackerImpl.incCountersInner(PsiModificationTrackerImpl.java:87)
2024-10-26 21:08:27,848 [ 425534]   INFO - STDERR -     at com.intellij.psi.impl.PsiModificationTrackerImpl.lambda$doIncCounter$1(PsiModificationTrackerImpl.java:53)
2024-10-26 21:08:27,848 [ 425534]   INFO - STDERR -     at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.runWriteAction$lambda$4(AnyThreadWriteThreadingSupport.kt:318)
2024-10-26 21:08:27,848 [ 425534]   INFO - STDERR -     at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.runWriteAction(AnyThreadWriteThreadingSupport.kt:328)
2024-10-26 21:08:27,848 [ 425534]   INFO - STDERR -     at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.runWriteAction(AnyThreadWriteThreadingSupport.k
...
```

**Comment by realzhang** [comment]
java.lang.ClassCastException: class com.github.continuedev.continueintellijextension.autocomplete.AutocompleteService cannot be cast to class com.github.continuedev.continueintellijextension.autocomplete.AutocompleteService (com.github.continuedev.continueintellijextension.autocomplete.AutocompleteService is in unnamed module of loader com.intellij.ide.plugins.cl.PluginClassLoader @340e53c8; com.github.continuedev.continueintellijextension.autocomplete.AutocompleteService is in unnamed module of loader com.intellij.ide.plugins.cl.PluginClassLoader @27b5a07d)
	at com.github.continuedev.continueintellijextension.autocomplete.AutocompleteCaretListener.caretPositionChanged(AutocompleteEditorListener.kt:17)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at com.intellij.util.EventDispatcher.dispatchVoidMethod(EventDispatcher.java:120)
	at com.intellij.util.EventDispatcher.lambda$createMulticaster$1(EventDispatcher.java:85)
	at jdk.proxy2/jdk.proxy2.$Proxy81.caretPositionChanged(Unknown Source)
	at com.intellij.openapi.editor.impl.CaretModelImpl.fireCaretPositionChanged(CaretModelImpl.java:539)
	at com.intellij.openapi.editor.impl.CaretImpl.doMoveToVisualPosition(CaretImpl.java:593)
	at com.intellij.openapi.editor.impl.CaretImpl.lambda$moveToVisualPosition$4(CaretImpl.java:531)
	at com.intellij.openapi.editor.impl.CaretModelImpl.doWithCaretMerging(CaretModelImpl.java:413)
	at com.intellij.openapi.editor.impl.CaretImpl.moveToVisualPosition(CaretImpl.java:531)
	at com.intellij.openapi.editor.impl.CaretImpl.moveToVisualPosition(CaretImpl.java:527)
	at com.intellij.openapi.editor.CaretModel.moveToVisualPosition(CaretModel.java:68)
	at com.intellij.openapi.editor.impl.EditorImpl$MyMouseAdapter.processMousePressed(EditorImpl.java:4586)
	at com.intellij.openapi.editor.impl.EditorImpl$MyMouseAdapter.lambda$runMousePressedCommand$0(EditorImpl.java:4376)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:226)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:178)
	at com.intellij.openapi.editor.impl.EditorImpl$MyMouseAdapter.runMousePressedCommand(EditorImpl.java:4381)
	at com.intellij.openapi.editor.impl.EditorImpl$MyMouseAdapter.mousePressed(EditorImpl.java:4295)
	at java.desktop/java.awt.AWTEventMulticaster.mousePressed(AWTEventMulticaster.java:287)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6659)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3394)
	at java.desktop/java.awt.Component.processEvent(Component.java:6427)
	at java.desktop/java.awt.Container.processEvent(Container.java:2266)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5032)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4860)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4963)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4574)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4518)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2310)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2810)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4860)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:783)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:728)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:98)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:755)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:753)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:752)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.kt:675)
	at com.intellij.ide.IdeEventQueue.dispatchMouseEvent(IdeEventQueue.kt:621)
	at com.intellij.ide.IdeEventQueue._dispatchEvent$lambda$21(IdeEventQueue.kt:564)
	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.runWriteIntentReadAction(AnyThreadWriteThreadingSupport.kt:128)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.kt:564)
	at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$18$lambda$17$lambda$16$lambda$15(IdeEventQueue.kt:355)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:857)
	at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$18$lambda$17$lambda$16(IdeEventQueue.kt:354)
	at com.intellij.ide.IdeEventQueueKt.performActivity$lambda$2$lambda$1(IdeEventQueue.kt:1045)
	at com.intellij.openapi.application.WriteIntentReadAction.lambda$run$0(WriteIntentReadAction.java:24)
	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.runWriteIntentReadAction(AnyThreadWriteThreadingSupport.kt:128)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteIntentReadAction(ApplicationImpl.java:916)
	at com.intellij.openapi.application.WriteIntentReadAction.compute(WriteIntentReadAction.java:55)
	at com.intellij.openapi.application.WriteIntentReadAction.run(WriteIntentReadAction.java:23)
	at com.intellij.ide.IdeEventQueueKt.performActivity$lambda$2(IdeEventQueue.kt:1045)
	at com.intellij.ide.IdeEventQueueKt.performActivity$lambda$3(IdeEventQueue.kt:1054)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:117)
	at com.intellij.ide.IdeEventQueueKt.performActivity(IdeEventQueue.kt:1054)
	at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$18(IdeEventQueue.kt:349)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.kt:395)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)

**Comment by aukaost** [comment]
This is also affecting me on Goland on Linux.
```
GoLand 2024.3.5
Build #GO-243.26053.20, built on March 13, 2025
Runtime version: 21.0.6+8-b631.39 amd64 (JCEF 122.1.9)
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Toolkit: sun.awt.X11.XToolkit
Linux 6.13.8-301.blu.fc41.x86_64
Fedora Linux 41 (KDE Plasma); glibc: 2.4
GC: G1 Young Generation, G1 Concurrent GC, G1 Old Generation
Memory: 8192M
Cores: 32
Registry:
  ide.completion.variant.limit=500
  suggest.all.run.configurations.from.context=FALSE
  ide.experimental.ui=true
Non-Bundled Plugins:
  com.github.continuedev.continueintellijextension (1.0.6)
  com.intellij.ml.llm (243.23654.270.16)
Current Desktop: KDE

```

**Comment by speedymcs** [comment]
Same here, blank Continue tab. 
Pycharm 2023.2, Build #PC-232.8660.197
Continue 1.0.8

In the idea.log I cannot find error messages relating to Continue, only that it has been loaded:

2025-04-22 10:24:04,943 [    219]   INFO - #c.i.i.p.PluginManager - Loaded custom plugins: Continue (1.0.8)
2025-04-22 10:22:01,185 [585529184]   INFO - #c.i.i.p.DynamicPlugins - Plugin com.github.continuedev.continueintellijextension loaded without restart in 347 ms

**Comment by Rybo-W** [comment]
> Same here, blank Continue tab.
> Pycharm 2023.2, Build #PC-232.8660.197

I also had the blank tab with PyCharm 2023.2. I updated PyCharm and the tab was no longer blank. I think, at the moment the only solution for you is to update PyCharm.

**Comment by Majoramari** [comment]
I have same issue on All Jetbrains IDEs in Arch Linux

![Image](https://github.com/user-attachments/assets/9a147b1a-2c94-4d5b-a358-000edcb6c48b)

**Comment by 0rzech** [comment]
If it's of any help, then I can confirm that the tab renders fine on `IntelliJ IDEA 2025.1.1.1 (Ultimate Edition)`, but on `RustRover 2025.1.3` it has an empty body with `New Session`, `View History` etc. buttons visible, but not triggering any actions.

**Comment by 0rzech** [comment]
The workaround that helped in my case:

1. Click on `File` -> `Invalidate Caches...` from the IDE's main menu.
2. Select `Delete embedded browser engine cache and cookies`.
3. Click on `Invalidate and Restart`.

**Comment by masoncj** [comment]
Tried again. Still getting a blank Continue window when running in remote SSH development from Mac to Linux (works fine in local dev on my Mac).  Tried:

* Continue plugin 1.0.21
* Continue plugin 1.0.22 (EAP)
* PyCharm 2024.3.2 RC (243.23654.74)
* PyCharm 2025.1.2 (251.26094.141)
* PyCharm 2025.2 EAP (252.21735.39)
* boot runtime 21.0.7+895.130-jcef

Tried "Delete embedded browser engine cache and cookies".
Tried various registry settings related to JCEF


[idea.log](https://github.com/user-attachments/files/20743274/idea.log)

in particular:
```
2025-06-15 01:58:00,321 [1034391] SEVERE - #c.i.p.instanceContainer - com.github.continuedev.continueintellijextension.autocomplete.AutocompleteLookupLis
tener is already registered: com.github.continuedev.continueintellijextension.autocomplete.AutocompleteLookupListener. Failed to register: com.github.con
tinuedev.continueintellijextension.autocomplete.AutocompleteLookupListener.
com.intellij.platform.instanceContainer.internal.InstanceAlreadyRegisteredException: com.github.continuedev.continueintellijextension.autocomplete.Autoco
mpleteLookupListener is already registered: com.github.continuedev.continueintellijextension.autocomplete.AutocompleteLookupListener. Failed to register:
 com.github.continuedev.continueintellijextension.autocomplete.AutocompleteLookupListener.
```

and a bunch of:

```
2025-06-15 01:58:06,565 [1040635]   INFO - STDOUT - Webview not initialized yet java.lang.IllegalStateException: Failed to execute the requested JS expre
ssion. The related JCEF browser in not initialized.
```

**Comment by FlorianSauer** [comment]
Im having the same issue. Sometimes the UI does show something, but the elements are broken/cut off.

I also noticed that autocompletion is not possible if the UI breaks like that.

<img width="678" height="603" alt="Image" src="https://github.com/user-attachments/assets/9e3fd057-092e-4d56-bd4c-bde4487987e6" />

<img width="685" height="466" alt="Image" src="https://github.com/user-attachments/assets/4435a9b5-f225-4a5f-9415-82c4c3566299" />

PyCharm 2025.2.3
Build #PY-252.26830.99, built on October 2, 2025
Source revision: 1ca1b7cb209ae
Licensed to ME
You have a perpetual fallback license for this version.
Subscription is active until October 26, 2026.
Runtime version: 21.0.8+1-b1038.72 amd64 (JCEF 122.1.9)
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Toolkit: sun.awt.windows.WToolkit
Windows 10.0
GC: G1 Young Generation, G1 Concurrent GC, G1 Old Generation
Memory: 3996M
Cores: 12
Registry:
  ide.experimental.ui=true
  idea.islands.feedback2.enabled=false
Non-Bundled Plugins:
  com.intellij.tasks (252.26830.102)
  Batch Scripts Support (1.0.13)
  com.jetbrains.space (252.26199.7)
  Subversion (252.26830.102)
  com.khmelyuk.multirun (1.14.1)
  com.github.continuedev.continueintellijextension (1.0.52)
  Statistic (5.1)
  dev.meanmail.plugin.nginx-intellij-plugin (2025.20)
  com.leinardi.pycharm.mypy (0.16.3)
  org.jetbrains.plugins.vue (252.26830.102)

OS:
Edition	Windows 10 Pro
Version	21H2
Build	19044.3086
