### ISSUE TITLE
KeyError: context_items 

### ISSUE THREAD

**Issue by djcopley** [continuedev/continue#653]
### Before submitting your bug report

- [X] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [X] I've seen the [troubleshooting guide](https://continue.dev/docs/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS: macOS 14.1.2
- Continue: PyCharm Continue 0.0.20 Bundled
- IDE: PyCharm 2023.2.5
```

### Description

After sending any query to the continue pycharm plugin, the query fails and a KeyError is raised. This happens regardless of what AI backend is used.
![context_items](https://github.com/continuedev/continue/assets/4100965/267ff863-4ce2-4034-927a-f13ddbe7215d)

### To reproduce

1. Open PyCharm
2. Open Continue window
3. Send any query to continue (not slash commands)

### Log output

```Shell
[2023-12-03 18:47:14] [ERROR] Error while running step: 
Traceback (most recent call last):

  File "server/continuedev/core/autopilot.py", line 217, in _run_singular_step

  File "server/continuedev/plugins/steps/chat.py", line 47, in run

  File "server/continuedev/core/sdk.py", line 231, in get_chat_context

KeyError: 'context_items'

'context_items'
[2023-12-03 18:47:14] [CRITICAL] Error handling message: Traceback (most recent call last):

  File "server/continuedev/server/gui.py", line 47, in message

  File "server/continuedev/server/protocols/gui.py", line 66, in handle_json

  File "server/continuedev/server/protocols/gui.py", line 173, in get_session_title

  File "server/continuedev/core/autopilot.py", line 333, in get_session_title

  File "server/continuedev/core/sdk.py", line 231, in get_chat_context

KeyError: 'context_items'
```

**Comment by sestinj** [comment]
thanks for the logs, was already able to track down the cause of the problem. It takes a day or two for JetBrains to update the extension once we submit, but if you were using the PyPI package, then I can get this out earlier.
