### ISSUE TITLE
Generation of some requests can take several tens of minutes please remove the time limit restriction or make a time limit setting

### ISSUE THREAD

**Issue by namen3645** [continuedev/continue#654]
### Before submitting your bug report

- [X] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [X] I've seen the [troubleshooting guide](https://continue.dev/docs/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS: Windows 10
- Continue:
Traceback (most recent call last):

  File "server\continuedev\core\autopilot.py", line 217, in _run_singular_step

  File "server\continuedev\core\steps.py", line 774, in run

  File "server\continuedev\core\steps.py", line 655, in stream_rif

  File "server\continuedev\libs\llm\base.py", line 290, in stream_complete

  File "server\continuedev\libs\llm\ggml.py", line 253, in _stream_complete

  File "server\continuedev\libs\llm\ggml.py", line 113, in _raw_stream_complete

  File "aiohttp\streams.py", line 44, in __anext__

  File "aiohttp\streams.py", line 395, in readany

  File "aiohttp\streams.py", line 301, in _wait

  File "aiohttp\helpers.py", line 735, in __exit__

TimeoutError
```

### Description

Generation of some requests may take several tens of minutes, please remove the time limit restriction or configure the time limit

**Comment by sestinj** [comment]
@namen3645 We have a property called "timeout" that can achieve this. Here's an example in config.json:

```json
{
  "models": [{
    "title": "...",
    "provider": "...",
    "model": "...",
    "request_options": {
      "timeout": "1000000000000",
    }
  }],
  ...
}
```

**Comment by sestinj** [comment]
Hi @namen3645 I'm going to close this issue as there is a solution, but let me know if you're still having problems.

Also notable is that behavior here should be an infinite timeout as of the newest pre-release versions (0.7.x)
