### ISSUE TITLE
Continue can't work offline 

### ISSUE THREAD

**Issue by valoudi** [continuedev/continue#656]
### Before submitting your bug report

- [X] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [X] I've seen the [troubleshooting guide](https://continue.dev/docs/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS:Windows
- Continue: 0.7.28 (vs code)
```

### Description

Hello, 

I want to use continue in a full offline computer. I've downloaded the last version of VS CODE ext (0.7.28) and I've updated my previous installation (something like 0.7.18 / 0.7.15). 
Now with the new version Continue isn't able to start the server. 

I've tried to start manually the server and 'ive got the following error ;
[....]
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Max retries exceeded with url: /BerriAI/litellm/main/model_prices_and_context_window.json (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000002C5682436D0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
 [.....]

FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\XXXXXXXXXXXXXXX\\AppData\\Local\\Temp\\_MEI145442\\litellm\\model_prices_and_context_window_backup.json'
[19324] Failed to execute script 'continue_server' due to unhandled exception!

--> How can I patch this ? I can transfer by hand the file to my offline computer but i don't know where  i've to create it  ... 

Thanks a lot,

Regards, 

 

### To reproduce

Copy the last vsix file on an OFFLINE computer
Install it
Run continue :) (.. perhaps just try to run the server :) ) 

### Log output

```Shell
Error truncating log file: 'utf-8' codec can't decode byte 0xe8 in position 17830: invalid continuation byte
Traceback (most recent call last):
  File "urllib3\connection.py", line 174, in _new_conn
  File "urllib3\util\connection.py", line 72, in create_connection
  File "socket.py", line 962, in getaddrinfo
socket.gaierror: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "urllib3\connectionpool.py", line 703, in urlopen
  File "urllib3\connectionpool.py", line 386, in _make_request
  File "urllib3\connectionpool.py", line 1042, in _validate_conn
  File "urllib3\connection.py", line 363, in connect
  File "urllib3\connection.py", line 186, in _new_conn
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x000002C5682436D0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "requests\adapters.py", line 486, in send
  File "urllib3\connectionpool.py", line 787, in urlopen
  File "urllib3\util\retry.py", line 592, in increment
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Max retries exceeded with url: /BerriAI/litellm/main/model_prices_and_context_window.json (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000002C5682436D0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "litellm\__init__.py", line 61, in get_model_cost_map
  File "requests\api.py", line 73, in get
  File "requests\api.py", line 59, in request
  File "requests\sessions.py", line 589, in request
  File "requests\sessions.py", line 703, in send
  File "requests\adapters.py", line 519, in send
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Max retries exceeded with url: /BerriAI/litellm/main/model_prices_and_context_window.json (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000002C5682436D0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "continue_server.py", line 4, in <module>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "server\main.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "server\continuedev\__init__.py", line 4, in <module>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "server\continuedev\core\config.py", line 10, in <module>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "server\continuedev\libs\llm\__init__.py", line 2, in <module>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "server\continuedev\libs\llm\ggml.py", line 9, in <module>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "server\continuedev\libs\llm\openai.py", line 6, in <module>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "litellm\__init__.py", line 71, in <module>
  File "litellm\__init__.py", line 68, in get_model_cost_map
  File "importlib\resources\_legacy.py", line 25, in wrapper
  File "importlib\resources\_legacy.py", line 63, in open_text
  File "pathlib.py", line 1044, in open
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\XXXXXXXXXXXXXXX\\AppData\\Local\\Temp\\_MEI145442\\litellm\\model_prices_and_context_window_backup.json'
[19324] Failed to execute script 'continue_server' due to unhandled exception!
```

**Comment by sestinj** [comment]
@valoudi It might be that you just have to setup your config.json to use a local model. Could you share what your config file looks like and I can help debug?

**Comment by sestinj** [comment]
If you want to go completely local, my recommendation would be either use [LM Studio](https://lmstudio.ai) or download and run a [llamafile](https://github.com/Mozilla-Ocho/llamafile#readme), then use the "lmstudio" or "llamafile" provider in your config.json

([here](https://continue.dev/docs/reference/Model%20Providers/llamafile) is an example of how to use Llamafile)

**Comment by valoudi** [comment]
Hello,

Thanks for your help. 

Today, I host a Mistral model on an openai API (with : python & llama_cpp.server)

My config contains : `models=Models(
        default=OpenAI(
            api_key="sk-111111111111111111111111111111111111111111111111",
            model="LOCAL MIS",
            proxy = "http://xxx:xxxx",
            verify_ssl = False,
            api_base="http://xxxxxx:xxxx/v1"
        )

    )`

I've also tested to remove my config.py and I've got the same issue with continue that try to download a JSON file from Internet.


I've also checked on github for litellm, and they patch their code, now a "backup" json file is provided with the lib. 

Si I think, if continue update to a new version of litellm, my issue should be good :)  
Thanks ! 

Regards, 

Valentin

**Comment by sestinj** [comment]
@valoudi We've taken a different route to solving this problem. In the latest VS Code pre-release versions we have removed the need for the Python server and are no longer using LiteLLM. I would recommend using this version because it greatly simplifies the API calls without the Python server.

Your config.json can look something like this:
```json
{
  "models": [{
    "apiKey": "sk-......",
    "model": "LOCAL MIS",
    "apiBase": "http://...."
  }],
  ...
}
```

The version is new and a work in progress so please let me know if you run into any problems, but I expect this will be the better solution

**Comment by sestinj** [comment]
We just recently merged the new version into main which doesn't use LiteLLM anymore, which makes this exact error impossible. For this reason, I'm going to close the issue, but if you're still having separate problems, feel free to create another issue of reach out on Discord!
