### ISSUE TITLE
errors, when using @Diff in context

### ISSUE THREAD

**Issue by yaoyasong** [continuedev/continue#661]
### Before submitting your bug report

- [X] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [ ] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [ ] I've seen the [troubleshooting guide](https://continue.dev/docs/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS:windows 10
- Continue:0.7.29
```

### Description

I got error when adding context "@Diff "

[2023-12-07 19:52:15] [CRITICAL] Error handling message: Traceback (most recent call last):

  File "server\continuedev\server\gui.py", line 47, in message

  File "server\continuedev\server\protocols\gui.py", line 64, in handle_json

  File "server\continuedev\core\context.py", line 467, in get_context_item

  File "server\continuedev\plugins\context_providers\diff.py", line 68, in get_item

AttributeError: 'NoneType' object has no attribute 'strip'

**Comment by sestinj** [comment]
This has now been solved and refactored for more reliability in the pre-release versions. Closing the issue, but let me know if something similar comes back
