### ISSUE TITLE
Index error while trying to possibly save history

### ISSUE THREAD

**Issue by thecomeonman** [continuedev/continue#664]
### Before submitting your bug report

- [X] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [X] I've seen the [troubleshooting guide](https://continue.dev/docs/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS: macOS 14.1.2 
- Continue: 0.6.15
- IDE: e.g. VSCode 1.84.2
- continuedev: 0.1.104
```

### Description

I run any prompt in the VS code extension GUI, eg. "hello world" I get a response which gets erased in a split second

### To reproduce

- I've toggled on the manual server setting in VS code
- I manually installed Meilisearch and copied the binary into `~/.continue/server` as per the troubleshooting guide ( because I was getting an error about access denied to terminate the application running on port 7700 )
- I'm manually running the server with the following command - `python -m continuedev --meilisearch-url http://localhost:7700` ( because without it I was getting an SSL error about not being able to reach proxy-server ... )
- I run codellama as per the instructions here
- I run any prompt in the VS code extension GUI, eg. "hello world" I get a response which gets erased in a split second

### Log output

```Shell
python -m continuedev --meilisearch-url http://localhost:7700


_________               _____ _____                       
__  ____/______ _______ __  /____(_)_______ ____  _______ 
_  /     _  __ \__  __ \_  __/__  / __  __ \_  / / /_  _ \
/ /___   / /_/ /_  / / // /_  _  /  _  / / // /_/ / /  __/
\____/   \____/ /_/ /_/ \__/  /_/   /_/ /_/ \__,_/  \___/ 


[2023-12-10 23:09:16] [DEBUG] ------ Begin Logs ------
INFO:     Started server process [9966]
INFO:     Waiting for application startup.
[2023-12-10 23:09:16] [DEBUG] Using MeiliSearch at URL: http://localhost:7700
INFO:     Application startup complete.
INFO:     Uvicorn running on http://127.0.0.1:65432 (Press CTRL+C to quit)
INFO:     ('127.0.0.1', 59455) - "WebSocket /socket.io/?window_id=11fcae53-3bd2-4e03-b1aa-a75a57bafbb4&EIO=4&transport=websocket" [accepted]
INFO:     connection open
INFO:     ('127.0.0.1', 59456) - "WebSocket /socket.io/?window_info=%7B%22window_id%22%3A%2211fcae53-3bd2-4e03-b1aa-a75a57bafbb4%22%2C%22workspace_directory%22%3A%22%2FUsers%2Fuser_name_masked%2Fminiconda3%2Flib%2Fpython3.11%2Fsite-packages%2Fcontinuedev%22%2C%22unique_id%22%3A%22569f3b10ade3a5ca773ec24a5e251234b065e62341afb218dc4e33b3ce06c3f2%22%2C%22ide_info%22%3A%7B%22name%22%3A%22vscode%22%2C%22version%22%3A%221.84.2%22%2C%22server_url%22%3A%22http%3A%2F%2Flocalhost%3A65432%22%7D%7D&EIO=4&transport=websocket" [accepted]
INFO:     connection open
[2023-12-10 23:09:19] [INFO] There are 1 sessions currently open
fatal: not a git repository (or any of the parent directories): .git
[2023-12-10 23:09:19] [DEBUG] Using MeiliSearch at URL: http://localhost:7700
Error importing tiktoken HTTPSConnectionPool(host='openaipublic.blob.core.windows.net', port=443): Max retries exceeded with url: /encodings/cl100k_base.tiktoken (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate in certificate chain (_ssl.c:1006)')))
[2023-12-10 23:09:30] [ERROR] Error while running step: 
Traceback (most recent call last):

  File "/Users/user_name_masked/miniconda3/lib/python3.11/site-packages/aiohttp/connector.py", line 992, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "uvloop/loop.pyx", line 2084, in create_connection

  File "uvloop/loop.pyx", line 2079, in uvloop.loop.Loop.create_connection

  File "/Users/user_name_masked/miniconda3/lib/python3.11/asyncio/futures.py", line 287, in __await__
    yield self  # This tells Task to wait for completion.
    ^^^^^^^^^^

  File "/Users/user_name_masked/miniconda3/lib/python3.11/asyncio/tasks.py", line 339, in __wakeup
    future.result()

  File "/Users/user_name_masked/miniconda3/lib/python3.11/asyncio/futures.py", line 203, in result
    raise self._exception.with_traceback(self._exception_tb)

  File "uvloop/sslproto.pyx", line 517, in uvloop.loop.SSLProtocol._on_handshake_complete

  File "uvloop/sslproto.pyx", line 499, in uvloop.loop.SSLProtocol._do_handshake

  File "/Users/user_name_masked/miniconda3/lib/python3.11/ssl.py", line 979, in do_handshake
    self._sslobj.do_handshake()

ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate in certificate chain (_ssl.c:1006)


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "/Users/user_name_masked/miniconda3/lib/python3.11/site-packages/aiohttp/connector.py", line 992, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "uvloop/loop.pyx", line 2079, in uvloop.loop.Loop.create_connection

  File "/Users/user_name_masked/miniconda3/lib/python3.11/asyncio/futures.py", line 287, in __await__
    yield self  # This tells Task to wait for completion.
    ^^^^^^^^^^

  File "/Users/user_name_masked/miniconda3/lib/python3.11/asyncio/tasks.py", line 339, in __wakeup
    future.result()

  File "/Users/user_name_masked/miniconda3/lib/python3.11/asyncio/futures.py", line 203, in result
    raise self._exception.with_traceback(self._exception_tb)

  File "uvloop/sslproto.pyx", line 517, in uvloop.loop.SSLProtocol._on_handshake_complete

  File "uvloop/sslproto.pyx", line 499, in uvloop.loop.SSLProtocol._do_handshake

  File "/Users/user_name_masked/miniconda3/lib/python3.11/ssl.py", line 979, in do_handshake
    self._sslobj.do_handshake()

ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate in certificate chain (_ssl.c:1006)


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "/Users/user_name_masked/miniconda3/lib/python3.11/site-packages/aiohttp/connector.py", line 992, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "uvloop/loop.pyx", line 2079, in uvloop.loop.Loop.create_connection

  File "/Users/user_name_masked/miniconda3/lib/python3.11/asyncio/futures.py", line 287, in __await__
    yield self  # This tells Task to wait for completion.
    ^^^^^^^^^^

  File "/Users/user_name_masked/miniconda3/lib/python3.11/asyncio/tasks.py", line 339, in __wakeup
    future.result()

  File "/Users/user_name_masked/miniconda3/lib/python3.11/asyncio/futures.py", line 203, in result
    raise self._exception.with_traceback(self._exception_tb)

  File "uvloop/sslproto.pyx", line 517, in uvloop.loop.SSLProtocol._on_handshake_complete

  File "uvloop/sslproto.pyx", line 499, in uvloop.loop.SSLProtocol._do_handshake

  File "/Users/user_name_masked/miniconda3/lib/python3.11/ssl.py", line 979, in do_handshake
    self._sslobj.do_handshake()

ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate in certificate chain (_ssl.c:1006)


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "/Users/user_name_masked/miniconda3/lib/python3.11/site-packages/aiohttp/connector.py", line 992, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "uvloop/loop.pyx", line 2079, in uvloop.loop.Loop.create_connection

  File "/Users/user_name_masked/miniconda3/lib/python3.11/asyncio/futures.py", line 287, in __await__
    yield self  # This tells Task to wait for completion.
    ^^^^^^^^^^

  File "/Users/user_name_masked/miniconda3/lib/python3.11/asyncio/tasks.py", line 339, in __wakeup
    future.result()

  File "/Users/user_name_masked/miniconda3/lib/python3.11/asyncio/futures.py", line 203, in result
    raise self._exception.with_traceback(self._exception_tb)

  File "uvloop/sslproto.pyx", line 517, in uvloop.loop.SSLProtocol._on_handshake_complete

  File "uvloop/sslproto.pyx", line 499, in uvloop.loop.SSLProtocol._do_handshake

  File "/Users/user_name_masked/miniconda3/lib/python3.11/ssl.py", line 979, in do_handshake
    self._sslobj.do_handshake()

ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate in certificate chain (_ssl.c:1006)


The above exception was the direct cause of the following exception:


Traceback (most recent call last):

  File "/Users/user_name_masked/miniconda3/lib/python3.11/site-packages/continuedev/core/autopilot.py", line 217, in _run_singular_step
    async for update in step.run(self.sdk):  # type: ignore (stub type)

  File "/Users/user_name_masked/miniconda3/lib/python3.11/site-packages/continuedev/plugins/steps/chat.py", line 74, in run
    await sdk.models.summarize.complete(

  File "/Users/user_name_masked/miniconda3/lib/python3.11/site-packages/continuedev/libs/llm/base.py", line 339, in complete
    completion = await self._complete(prompt=prompt, options=options)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/Users/user_name_masked/miniconda3/lib/python3.11/site-packages/continuedev/libs/llm/openai_free_trial.py", line 86, in _complete
    return await self.llm._complete(prompt, options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/Users/user_name_masked/miniconda3/lib/python3.11/site-packages/continuedev/libs/llm/proxy_server.py", line 39, in _complete
    async with session.post(

  File "/Users/user_name_masked/miniconda3/lib/python3.11/site-packages/aiohttp/client.py", line 1187, in __aenter__
    self._resp = await self._coro
                 ^^^^^^^^^^^^^^^^

  File "/Users/user_name_masked/miniconda3/lib/python3.11/site-packages/aiohttp/client.py", line 574, in _request
    conn = await self._connector.connect(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/Users/user_name_masked/miniconda3/lib/python3.11/site-packages/aiohttp/connector.py", line 544, in connect
    proto = await self._create_connection(req, traces, timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/Users/user_name_masked/miniconda3/lib/python3.11/site-packages/aiohttp/connector.py", line 911, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/Users/user_name_masked/miniconda3/lib/python3.11/site-packages/aiohttp/connector.py", line 1235, in _create_direct_connection
    raise last_exc

  File "/Users/user_name_masked/miniconda3/lib/python3.11/site-packages/aiohttp/connector.py", line 1204, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/Users/user_name_masked/miniconda3/lib/python3.11/site-packages/aiohttp/connector.py", line 994, in _wrap_create_connection
    raise ClientConnectorCertificateError(req.connection_key, exc) from exc

aiohttp.client_exceptions.ClientConnectorCertificateError: Cannot connect to host proxy-server-l6vsfbzhba-uw.a.run.app:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate in certificate chain (_ssl.c:1006)')]

The request failed. Please check your internet connection and try again.
[2023-12-10 23:09:31] [CRITICAL] Error handling message: Traceback (most recent call last):

  File "/Users/user_name_masked/miniconda3/lib/python3.11/site-packages/aiohttp/connector.py", line 992, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "uvloop/loop.pyx", line 2084, in create_connection

  File "uvloop/loop.pyx", line 2079, in uvloop.loop.Loop.create_connection

  File "/Users/user_name_masked/miniconda3/lib/python3.11/asyncio/futures.py", line 287, in __await__
    yield self  # This tells Task to wait for completion.
    ^^^^^^^^^^

  File "/Users/user_name_masked/miniconda3/lib/python3.11/asyncio/tasks.py", line 339, in __wakeup
    future.result()

  File "/Users/user_name_masked/miniconda3/lib/python3.11/asyncio/futures.py", line 203, in result
    raise self._exception.with_traceback(self._exception_tb)

  File "uvloop/sslproto.pyx", line 517, in uvloop.loop.SSLProtocol._on_handshake_complete

  File "uvloop/sslproto.pyx", line 499, in uvloop.loop.SSLProtocol._do_handshake

  File "/Users/user_name_masked/miniconda3/lib/python3.11/ssl.py", line 979, in do_handshake
    self._sslobj.do_handshake()

ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate in certificate chain (_ssl.c:1006)


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "/Users/user_name_masked/miniconda3/lib/python3.11/site-packages/aiohttp/connector.py", line 992, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "uvloop/loop.pyx", line 2079, in uvloop.loop.Loop.create_connection

  File "/Users/user_name_masked/miniconda3/lib/python3.11/asyncio/futures.py", line 287, in __await__
    yield self  # This tells Task to wait for completion.
    ^^^^^^^^^^

  File "/Users/user_name_masked/miniconda3/lib/python3.11/asyncio/tasks.py", line 339, in __wakeup
    future.result()

  File "/Users/user_name_masked/miniconda3/lib/python3.11/asyncio/futures.py", line 203, in result
    raise self._exception.with_traceback(self._exception_tb)

  File "uvloop/sslproto.pyx", line 517, in uvloop.loop.SSLProtocol._on_handshake_complete

  File "uvloop/sslproto.pyx", line 499, in uvloop.loop.SSLProtocol._do_handshake

  File "/Users/user_name_masked/miniconda3/lib/python3.11/ssl.py", line 979, in do_handshake
    self._sslobj.do_handshake()

ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate in certificate chain (_ssl.c:1006)


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "/Users/user_name_masked/miniconda3/lib/python3.11/site-packages/aiohttp/connector.py", line 992, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "uvloop/loop.pyx", line 2079, in uvloop.loop.Loop.create_connection

  File "/Users/user_name_masked/miniconda3/lib/python3.11/asyncio/futures.py", line 287, in __await__
    yield self  # This tells Task to wait for completion.
    ^^^^^^^^^^

  File "/Users/user_name_masked/miniconda3/lib/python3.11/asyncio/tasks.py", line 339, in __wakeup
    future.result()

  File "/Users/user_name_masked/miniconda3/lib/python3.11/asyncio/futures.py", line 203, in result
    raise self._exception.with_traceback(self._exception_tb)

  File "uvloop/sslproto.pyx", line 517, in uvloop.loop.SSLProtocol._on_handshake_complete

  File "uvloop/sslproto.pyx", line 499, in uvloop.loop.SSLProtocol._do_handshake

  File "/Users/user_name_masked/miniconda3/lib/python3.11/ssl.py", line 979, in do_handshake
    self._sslobj.do_handshake()

ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate in certificate chain (_ssl.c:1006)


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "/Users/user_name_masked/miniconda3/lib/python3.11/site-packages/aiohttp/connector.py", line 992, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "uvloop/loop.pyx", line 2079, in uvloop.loop.Loop.create_connection

  File "/Users/user_name_masked/miniconda3/lib/python3.11/asyncio/futures.py", line 287, in __await__
    yield self  # This tells Task to wait for completion.
    ^^^^^^^^^^

  File "/Users/user_name_masked/miniconda3/lib/python3.11/asyncio/tasks.py", line 339, in __wakeup
    future.result()

  File "/Users/user_name_masked/miniconda3/lib/python3.11/asyncio/futures.py", line 203, in result
    raise self._exception.with_traceback(self._exception_tb)

  File "uvloop/sslproto.pyx", line 517, in uvloop.loop.SSLProtocol._on_handshake_complete

  File "uvloop/sslproto.pyx", line 499, in uvloop.loop.SSLProtocol._do_handshake

  File "/Users/user_name_masked/miniconda3/lib/python3.11/ssl.py", line 979, in do_handshake
    self._sslobj.do_handshake()

ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate in certificate chain (_ssl.c:1006)


The above exception was the direct cause of the following exception:


Traceback (most recent call last):

  File "/Users/user_name_masked/miniconda3/lib/python3.11/site-packages/continuedev/core/autopilot.py", line 217, in _run_singular_step
    async for update in step.run(self.sdk):  # type: ignore (stub type)

  File "/Users/user_name_masked/miniconda3/lib/python3.11/site-packages/continuedev/plugins/steps/chat.py", line 74, in run
    await sdk.models.summarize.complete(

  File "/Users/user_name_masked/miniconda3/lib/python3.11/site-packages/continuedev/libs/llm/base.py", line 339, in complete
    completion = await self._complete(prompt=prompt, options=options)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/Users/user_name_masked/miniconda3/lib/python3.11/site-packages/continuedev/libs/llm/openai_free_trial.py", line 86, in _complete
    return await self.llm._complete(prompt, options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/Users/user_name_masked/miniconda3/lib/python3.11/site-packages/continuedev/libs/llm/proxy_server.py", line 39, in _complete
    async with session.post(

  File "/Users/user_name_masked/miniconda3/lib/python3.11/site-packages/aiohttp/client.py", line 1187, in __aenter__
    self._resp = await self._coro
                 ^^^^^^^^^^^^^^^^

  File "/Users/user_name_masked/miniconda3/lib/python3.11/site-packages/aiohttp/client.py", line 574, in _request
    conn = await self._connector.connect(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/Users/user_name_masked/miniconda3/lib/python3.11/site-packages/aiohttp/connector.py", line 544, in connect
    proto = await self._create_connection(req, traces, timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/Users/user_name_masked/miniconda3/lib/python3.11/site-packages/aiohttp/connector.py", line 911, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/Users/user_name_masked/miniconda3/lib/python3.11/site-packages/aiohttp/connector.py", line 1235, in _create_direct_connection
    raise last_exc

  File "/Users/user_name_masked/miniconda3/lib/python3.11/site-packages/aiohttp/connector.py", line 1204, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/Users/user_name_masked/miniconda3/lib/python3.11/site-packages/aiohttp/connector.py", line 994, in _wrap_create_connection
    raise ClientConnectorCertificateError(req.connection_key, exc) from exc

aiohttp.client_exceptions.ClientConnectorCertificateError: Cannot connect to host proxy-server-l6vsfbzhba-uw.a.run.app:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate in certificate chain (_ssl.c:1006)')]


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "/Users/user_name_masked/miniconda3/lib/python3.11/site-packages/continuedev/server/gui.py", line 47, in message
    resp = await gui.handle_json(message)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/Users/user_name_masked/miniconda3/lib/python3.11/site-packages/continuedev/server/protocols/gui.py", line 58, in handle_json
    await self.run_from_state(SessionState.parse_obj(data["state"]))

  File "/Users/user_name_masked/miniconda3/lib/python3.11/site-packages/continuedev/server/protocols/gui.py", line 139, in run_from_state
    await autopilot.run(step=step)

  File "/Users/user_name_masked/miniconda3/lib/python3.11/site-packages/continuedev/core/autopilot.py", line 325, in run
    await self.run_step(next_step)

  File "/Users/user_name_masked/miniconda3/lib/python3.11/site-packages/continuedev/core/autopilot.py", line 283, in run_step
    async for update in self._run_singular_step(step):

  File "/Users/user_name_masked/miniconda3/lib/python3.11/site-packages/continuedev/core/autopilot.py", line 236, in _run_singular_step
    while self.session_state.history[index].name != step.name:
          ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^

IndexError: list index out of range

[2023-12-10 23:09:39] [WARNING] Meilisearch did not start in less than 20 seconds. Stopping polling.
```

**Comment by sestinj** [comment]
@thecomeonman I would recommend trying the newest pre-release version 0.7.x, where we have removed the need for meilisearch or the python server. So this will solve your initial setup problems, and the `self.session_state.istory[index].name` as well.

What I'm not sure about is the SSL error you're seeing. It could depend on your environment, so let me know if something similar seems to happen in the pre-release

**Comment by thecomeonman** [comment]
Yep it works now, thanks! I suspect the SSL error is something to do with my VPN client but I don't know enough about it to debug it or get out more relevant details out.
