### ISSUE TITLE
Continue with VSCode1.70.2 in Windows7 shows nothing in the left side panel when clicking the sidebar

### ISSUE THREAD

**Issue by wchli** [continuedev/continue#723]
### Before submitting your bug report

- [X] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [X] I've seen the [troubleshooting guide](https://continue.dev/docs/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS: Windows7
- Continue: 0.7.61
- IDE: VSCode 1.70.2
```

### Description

`Continue `with VSCode 1.70.2 in Windows7 shows nothing in the left side panel when clicking the sidebar.  The `Runtime Status` panel shows one uncaught error `ReadableStream is not defined` and one message `webview/context is a proposed menu identifier. It requires 'package.json#enabledApiProposals: ["contribWebviewContext"]' and is only available when running out of dev or with the following command line switch: --enable-proposed-api Continue.continue`

But when I follow the message operations , the Continue is still not working.

### Log output

```Shell
workbench.desktop.main.js:86 [Extension Host] rejected promise not handled within 1 second: ReferenceError: ReadableStream is not defined
I @ workbench.desktop.main.js:86
workbench.desktop.main.js:86 [Extension Host] stack trace: ReferenceError: ReadableStream is not defined
	at node_modules/undici/lib/fetch/response.js (c:\Users\weichao\.vscode\extensions\continue.continue-0.7.61\out\extension.js:47624:7)
	at __require (c:\Users\weichao\.vscode\extensions\continue.continue-0.7.61\out\extension.js:13:50)
	at node_modules/undici/index.js (c:\Users\weichao\.vscode\extensions\continue.continue-0.7.61\out\extension.js:52724:32)
	at __require (c:\Users\weichao\.vscode\extensions\continue.continue-0.7.61\out\extension.js:13:50)
	at src/loadConfig.ts (c:\Users\weichao\.vscode\extensions\continue.continue-0.7.61\out\extension.js:52805:29)
	at __init (c:\Users\weichao\.vscode\extensions\continue.continue-0.7.61\out\extension.js:10:56)
	at src/debugPanel.ts (c:\Users\weichao\.vscode\extensions\continue.continue-0.7.61\out\extension.js:53304:5)
	at __init (c:\Users\weichao\.vscode\extensions\continue.continue-0.7.61\out\extension.js:10:56)
	at src/commands.ts (c:\Users\weichao\.vscode\extensions\continue.continue-0.7.61\out\extension.js:53646:5)
	at __init (c:\Users\weichao\.vscode\extensions\continue.continue-0.7.61\out\extension.js:10:56)
	at src/activation/activate.ts (c:\Users\weichao\.vscode\extensions\continue.continue-0.7.61\out\extension.js:69792:5)
	at __init (c:\Users\weichao\.vscode\extensions\continue.continue-0.7.61\out\extension.js:10:56)
	at c:\Users\weichao\.vscode\extensions\continue.continue-0.7.61\out\extension.js:69838:89
	at processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async dynamicImportAndActivate (c:\Users\weichao\.vscode\extensions\continue.continue-0.7.61\out\extension.js:69838:53)
I @ workbench.desktop.main.js:86
workbench.desktop.main.js:2279 [[object Object]]ReadableStream is not defined
$onExtensionRuntimeError @ workbench.desktop.main.js:2279
workbench.desktop.main.js:2279 ReferenceError: ReadableStream is not defined
	at node_modules/undici/lib/fetch/response.js (c:\Users\weichao\.vscode\extensions\continue.continue-0.7.61\out\extension.js:47624:7)
	at __require (c:\Users\weichao\.vscode\extensions\continue.continue-0.7.61\out\extension.js:13:50)
	at node_modules/undici/index.js (c:\Users\weichao\.vscode\extensions\continue.continue-0.7.61\out\extension.js:52724:32)
	at __require (c:\Users\weichao\.vscode\extensions\continue.continue-0.7.61\out\extension.js:13:50)
	at src/loadConfig.ts (c:\Users\weichao\.vscode\extensions\continue.continue-0.7.61\out\extension.js:52805:29)
	at __init (c:\Users\weichao\.vscode\extensions\continue.continue-0.7.61\out\extension.js:10:56)
	at src/debugPanel.ts (c:\Users\weichao\.vscode\extensions\continue.continue-0.7.61\out\extension.js:53304:5)
	at __init (c:\Users\weichao\.vscode\extensions\continue.continue-0.7.61\out\extension.js:10:56)
	at src/commands.ts (c:\Users\weichao\.vscode\extensions\continue.continue-0.7.61\out\extension.js:53646:5)
	at __init (c:\Users\weichao\.vscode\extensions\continue.continue-0.7.61\out\extension.js:10:56)
	at src/activation/activate.ts (c:\Users\weichao\.vscode\extensions\continue.continue-0.7.61\out\extension.js:69792:5)
	at __init (c:\Users\weichao\.vscode\extensions\continue.continue-0.7.61\out\extension.js:10:56)
	at c:\Users\weichao\.vscode\extensions\continue.continue-0.7.61\out\extension.js:69838:89
	at processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async dynamicImportAndActivate (c:\Users\weichao\.vscode\extensions\continue.continue-0.7.61\out\extension.js:69838:53)
```

**Comment by sestinj** [comment]
@wchli This appears to be caused by an older version of Node.js. Can you check which version VS Code is running on by clicking the About menu for VS Code and copying the version info?

It should look something like this for example:

```
Version: 1.86.0-insider (Universal)
Commit: 9621add46007f7a1ab37d1fce9bcdcecca62aeb0
Date: 2023-12-20T05:38:07.020Z
Electron: 27.1.3
ElectronBuildId: 25612240
Chromium: 118.0.5993.159
Node.js: 18.17.1
V8: 11.8.172.18-electron.0
OS: Darwin arm64 21.6.0
```

A quick fix if you're looking for one is to upgrade Node, but I'd obviously love to make sure that this is the problem and then find a real fix.

**Comment by kaileysong** [comment]
same problem with windows7, but using continue 0.9.41, my vscode is running on node.js of 16.13.2 version

**Comment by wchli** [comment]
> same problem with windows7, but using continue 0.9.41, my vscode is running on node.js of 16.13.2 versio

have you work it out for windows7?
