### ISSUE TITLE
Ollama Unexpected end of JSON input

### ISSUE THREAD

**Issue by matbee-eth** [continuedev/continue#751]
### Before submitting your bug report

- [X] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [X] I've seen the [troubleshooting guide](https://continue.dev/docs/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS: Mac / WSL2 / Cloudflare tunnel
- Continue:
```

### Description

I'm running a cloudflare tunnel for my server-based ollama service. It seems like Continue errors when receiving chunked encoded JSONL responses and is expecting a full JSON object in a response, during a streamed response. It should be waiting for a `\n` in a JSONL response before it attempts to JSON.parse.

```error
[Extension Host] Error: Error parsing Ollama response: SyntaxError: Unexpected end of JSON input {"model":"phind-codellama","created_at":"2024-01-14T21:06:21.760129309Z","message":{"role":"assistant","content"
	at Ollama._streamChat (c:\Users\mail\.vscode\extensions\continue.continue-0.8.1-win32-x64\out\extension.js:35485:23)
	at _streamChat.next (<anonymous>)
	at Ollama.streamChat (c:\Users\mail\.vscode\extensions\continue.continue-0.8.1-win32-x64\out\extension.js:34521:30)
	at streamChat.next (<anonymous>)
	at f.value (c:\Users\mail\.vscode\extensions\continue.continue-0.8.1-win32-x64\out\extension.js:54527:28)
	at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Comment by matbee-eth** [comment]
https://github.com/continuedev/continue/blob/5b56150a8dc8345422f75107c899d31b87417d65/core/llm/llms/Ollama.ts#L163C1-L163C41

Seems to parse the JSON even without validating the response type. `ndjson` responses need to be newline delimited.
