### ISSUE TITLE
LMStudio "apiBase" configuration regression

### ISSUE THREAD

**Issue by jpaveg** [continuedev/continue#801]
### Before submitting your bug report

- [X] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [X] I've seen the [troubleshooting guide](https://continue.dev/docs/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS: Windows 11, Ubuntu (WSL2)
- Continue: 0.8.7
- IDE: VSCode
```

### Description

Things were working fine two days ago with my config like this:

```json
    {
      "title": "LM Studio",
      "provider": "lmstudio",
      "model": "modelname"
    }
```

However today (I'm not sure why), LM Studio started reporting `[ERROR] Unexpected endpoint or method. (POST /chat/completions). Returning 200 anyway` when I tried querying it from the continue extension. 

Adding the `"apiBase": "http://localhost:1234/v1/"` line to the config fixes the issue, however it wasn't necessary a few days ago. Seems like a regression

### To reproduce

I removed the continue extension from vscode, as well as the `.continue` folders from my WSL instance and my user directory in windows.

1. Install Continue
2. Setup an "lmstudio" provider
3. Launch lmstudio server
4. Try to query through continue chat
5. Errors reported, lm studio reports `Unexpected endpoint or method. (POST /chat/completions).`
6. add `"apiBase": "http://localhost:1234/v1/"` to the json object in configuration file
7. Query again

### Log output

```Shell
[Extension Host] Error: HTTP 500 Internal Server Error from http://localhost:1234/chat/completions

	at llm._fetch (c:\Users\user\.vscode\extensions\continue.continue-0.8.7-win32-x64\out\extension.js:172410:13)
	at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
	at async LMStudio._streamChat (c:\Users\user\.vscode\extensions\continue.continue-0.8.7-win32-x64\out\extension.js:161876:26)
	at async LMStudio.streamChat (c:\Users\user\.vscode\extensions\continue.continue-0.8.7-win32-x64\out\extension.js:160524:30)
	at async f.value (c:\Users\user\.vscode\extensions\continue.continue-0.8.7-win32-x64\out\extension.js:173469:23)
notificationsAlerts.ts:42 Continue error: HTTP 500 Internal Server Error from http://localhost:1234/chat/completions  <!DOCTYPE html> <html lang="en"> <head> <meta charset="utf-8"> <title>Error</title> </head> <body> <pre>Internal Server Error</pre> </body> </html>
```

**Comment by sestinj** [comment]
@jpaveg Yes, thank you for pointing this out so promptly. Changes on the way [here](https://github.com/continuedev/continue/actions/runs/7738484803).

**Comment by jpaveg** [comment]
@sestinj Ah I didn't realize, sorry about that. Can I remove or delete the issue?

**Comment by sestinj** [comment]
@jpaveg Oh no worries! Sorry I gave a bit of a hurried response there, but this was actually helpful (changes were on the way *because* you had raised the issue, so thank you). I'll go ahead and close the issue now assuming it is solved for you : )
