### ISSUE TITLE
Cannot use @Codebase: file was not found locally ... models/all-MiniLM-L6-v2/tokenizer.json

### ISSUE THREAD

**Issue by neongreen-sc** [continuedev/continue#895]
### Before submitting your bug report

- [X] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [X] I've seen the [troubleshooting guide](https://continue.dev/docs/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS: Windows 10
- Continue: 0.9.71
- IDE: VSCode 1.78.2
```

### Description

When asking any question with `@Codebase`, I get:

```
Error getting context items from codebase: Error: `local_files_only=true` or `env.allowRemoteModels=false` and file was not found locally at "c:\Users\[...]\.vscode\extensions\continue.continue-0.9.71-win32-x64\out/../models/all-MiniLM-L6-v2/tokenizer.json".
```

I checked and the file actually exists.

### Log output

```Shell
[Extension Host] Unable to load from local path "c:\Users\[...]\.vscode\extensions\continue.continue-0.9.71-win32-x64\out/../models/all-MiniLM-L6-v2/config.json": "ReferenceError: Headers is not defined"
I @ console.ts:137

notificationsAlerts.ts:42 Error getting context items from codebase: Error: `local_files_only=true` or `env.allowRemoteModels=false` and file was not found locally at "c:\Users\[...]\.vscode\extensions\continue.continue-0.9.71-win32-x64\out/../models/all-MiniLM-L6-v2/tokenizer.json".
c @ notificationsAlerts.ts:42
```

**Comment by sestinj** [comment]
@neongreen-sc thanks for bringing this up! I just fixed [here](https://github.com/continuedev/continue/commit/d774b75ffaf4671c5790a5aac1beba985d1e05df), but will wait to close this issue until it's been fully released and verified to work

**Comment by JaredEzz** [comment]
I've noticed this on the IntelliJ plugin as well

**Comment by Symbolk** [comment]
@sestinj Similar problem here but while indexing, could this be a problem of old VSCode versions?
- OS: Windows
- Continue: 0.9.215 (market, production)
- VSCode: VSCode-win32-x64-1.81.3 (latest is ok, but I am using a customized VSCode, which is based on 1.81.3)

F12 Log:
```
workbench.desktop.main.js:58613 [Extension Host] Unable to load from local path "d:\app\VSCode-win32-x64-1.81.3\data\extensions\continue.continue-0.9.215\models/all-MiniLM-L6-v2/tokenizer_config.json": "ReferenceError: Headers is not defined"
log @ workbench.desktop.main.js:58613
$logExtensionHostMessage @ workbench.desktop.main.js:303288
N @ workbench.desktop.main.js:303916
M @ workbench.desktop.main.js:303901
H @ workbench.desktop.main.js:303842
G @ workbench.desktop.main.js:303769
(anonymous) @ workbench.desktop.main.js:303650
w @ workbench.desktop.main.js:14644
fire @ workbench.desktop.main.js:14673
fire @ workbench.desktop.main.js:86520
port.onmessage @ workbench.desktop.main.js:336633
workbench.desktop.main.js:58613 [Extension Host] Unable to load from local path "d:\app\VSCode-win32-x64-1.81.3\data\extensions\continue.continue-0.9.215\models/all-MiniLM-L6-v2/config.json": "ReferenceError: Headers is not defined"
log @ workbench.desktop.main.js:58613
$logExtensionHostMessage @ workbench.desktop.main.js:303288
N @ workbench.desktop.main.js:303916
M @ workbench.desktop.main.js:303901
H @ workbench.desktop.main.js:303842
G @ workbench.desktop.main.js:303769
(anonymous) @ workbench.desktop.main.js:303650
w @ workbench.desktop.main.js:14644
fire @ workbench.desktop.main.js:14673
fire @ workbench.desktop.main.js:86520
port.onmessage @ workbench.desktop.main.js:336633
workbench.desktop.main.js:58613 [Extension Host] error when indexing:  Error: Failed to generate embeddings for 92 chunks with provider: _TransformersJsEmbeddingsProvider::all-MiniLM-L6-v2: Error: `local_files_only=true` or `env.allowRemoteModels=false` and file was not found locally at "d:\app\VSCode-win32-x64-1.81.3\data\extensions\continue.continue-0.9.215\models/all-MiniLM-L6-v2/tokenizer.json".
	at LanceDbIndex.getEmbeddings (d:\app\VSCode-win32-x64-1.81.3\data\extensions\continue.continue-0.9.215\out\extension.js:450142:17)
	at async LanceDbIndex.computeRows (d:\app\VSCode-win32-x64-1.81.3\data\extensions\continue.continue-0.9.215\out\extension.js:450090:28)
	at async LanceDbIndex.update (d:\app\VSCode-win32-x64-1.81.3\data\extensions\continue.continue-0.9.215\out\extension.js:450246:24)
	at async CodebaseIndexer.indexFiles (d:\app\VSCode-win32-x64-1.81.3\data\extensions\continue.continue-0.9.215\out\extension.js:518245:39)
	at async CodebaseIndexer.refresh (d:\app\VSCode-win32-x64-1.81.3\data\extensions\continue.continue-0.9.215\out\extension.js:518117:30)
	at async Core.refreshCodebaseIndex (d:\app\VSCode-win32-x64-1.81.3\data\extensions\continue.continue-0.9.215\out\extension.js:518973:26)
	at async d:\app\VSCode-win32-x64-1.81.3\data\extensions\continue.continue-0.9.215\out\extension.js:518930:11
	at async d:\app\VSCode-win32-x64-1.81.3\data\extensions\continue.continue-0.9.215\out\extension.js:559642:20
	at async UniqueContainer.value (d:\app\VSCode-win32-x64-1.81.3\data\extensions\continue.continue-0.9.215\out\extension.js:525250:32)
workbench.desktop.main.js:58613 [Extension Host] Indexing failed with error:  Error: Failed to generate embeddings for 92 chunks with provider: _TransformersJsEmbeddingsProvider::all-MiniLM-L6-v2: Error: `local_files_only=true` or `env.allowRemoteModels=false` and file was not found locally at "d:\app\VSCode-win32-x64-1.81.3\data\extensions\continue.continue-0.9.215\models/all-MiniLM-L6-v2/tokenizer.json". LanceDbIndex.getEmbeddings, async LanceDbIndex.computeRows, async LanceDbIndex.update, async CodebaseIndexer.indexFiles, async CodebaseIndexer.refresh, async Core.refreshCodebaseIndex, async d:\app\VSCode-win32-x64-1.81.3\data\extensions\continue.continue-0.9.215\out\extension.js:518930:11, async d:\app\VSCode-win32-x64-1.81.3\data\extensions\continue.continue-0.9.215\out\extension.js:559642:20, async UniqueContainer.value
```

**Comment by sestinj** [comment]
@Symbolk This is happening because of the older NodeJS version

**Comment by Symbolk** [comment]
> @Symbolk This is happening because of the older NodeJS version

Yeah I know, the dilemma is I have to use the customized VSCode for some special features, and it comes with 16.17.1. Is there any chance to have a workaround (like change the way to load local files, etc.)?
