### ISSUE TITLE
embeddings / indexing using wrong pathname when developing in WSL2

### ISSUE THREAD

**Issue by jpaveg** [continuedev/continue#902]
### Before submitting your bug report

- [X] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [X] I've seen the [troubleshooting guide](https://continue.dev/docs/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS: Windows 11 23H2
- Continue: 0.9.73
- IDE: VSCode 1.87.0
- Ollama: 0.1.27
```

### Description

When trying to use the @codebase directive, I get an error: `Error getting context items from codebase: Error: SQLITE_ERROR: no such table: lance_db_cache`

Here are the changes I've made to the default config:
```json
  "models": [
    {
      "title": "OLLAMA",
      "provider": "ollama",
      "model": "codellama:13b-instruct-q5_K_M"
    }
  ],
  "tabAutocompleteModel": {
    "title": "Tab Autocomplete Model",
    "provider": "ollama",
    "model": "deepseek-coder:6.7b-base"
  },
  "embeddingsProvider": {
    "provider": "ollama",
    "model": "codellama:13b-instruct-q5_K_M"
  },
```

I'm also receiving AST Parse errors in the dev console, not sure if they're relevant but here is an example:
```console
Failed to parse AST TypeError: (0 , import_web_tree_sitter.init) is not a function
	at getParserForFile (c:\Users\jpaveg\.vscode\extensions\continue.continue-0.9.73-win32-x64\out\extension.js:49255:41)
	at getAst (c:\Users\jpaveg\.vscode\extensions\continue.continue-0.9.73-win32-x64\out\extension.js:187759:24)
	at constructAutocompletePrompt (c:\Users\jpaveg\.vscode\extensions\continue.continue-0.9.73-win32-x64\out\extension.js:187803:23)
	at _ContinueCompletionProvider.getTabCompletion (c:\Users\jpaveg\.vscode\extensions\continue.continue-0.9.73-win32-x64\out\extension.js:194039:63)
	at async _ContinueCompletionProvider.provideInlineCompletionItems (c:\Users\jpaveg\.vscode\extensions\continue.continue-0.9.73-win32-x64\out\extension.js:194166:27)
	at async B.provideInlineCompletions (c:\Users\jpaveg\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:150:110805)
```

**UPDATE:**
I just removed my embeddingsProvider config and reloaded the window - I'm now getting the following error when asking Continue "@codebase what framework does this codebase use?"

```console
mainThreadExtensionService.ts:81 [Continue.continue]Error: ENOENT: no such file or directory, stat 'C:\home\jpaveg\code\project\backend\README.md'
$onExtensionRuntimeError @ mainThreadExtensionService.ts:81
S @ rpcProtocol.ts:458
Q @ rpcProtocol.ts:443
M @ rpcProtocol.ts:373
L @ rpcProtocol.ts:299
(anonymous) @ rpcProtocol.ts:161
y @ event.ts:1127
fire @ event.ts:1158
fire @ ipc.net.ts:650
V.onmessage @ localProcessExtensionHost.ts:376
mainThreadExtensionService.ts:82 EntryNotFound (FileSystemError): Error: ENOENT: no such file or directory, stat 'C:\home\jpaveg\code\project\backend\README.md'
	at k.e (c:\Users\jpaveg\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:149:6084)
	at Object.stat (c:\Users\jpaveg\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:149:3892)
	at async c:\Users\jpaveg\.vscode\extensions\continue.continue-0.9.73-win32-x64\out\extension.js:186943:25
	at async Promise.all (index 0)
	at async VsCodeIde.getStats (c:\Users\jpaveg\.vscode\extensions\continue.continue-0.9.73-win32-x64\out\extension.js:186941:9)
	at async CodebaseIndexer.refresh (c:\Users\jpaveg\.vscode\extensions\continue.continue-0.9.73-win32-x64\out\extension.js:157950:25)
	at async _VsCodeExtension.refreshCodebaseIndex (c:\Users\jpaveg\.vscode\extensions\continue.continue-0.9.73-win32-x64\out\extension.js:194558:26)
```

Note that `'C:\home\jpaveg\code\project\backend\README.md'` is not a valid path on my system, though `'\home\jpaveg\code\project\backend\README.md'` IS a valid path on my WSL2 Ubuntu instance.

I'm developing inside of WSL2, but I'm running Ollama on windows. It seems like Continue is applying the wrong path to the indexing / embeddings system, though I could be entirely wrong. If there's anything else I can do to help debug this issue please let me know!

### To reproduce

I'm not entirely sure how to reproduce. Using WSL2 seems to be the issue here with the indexing / embeddings system not properly setting the path to use.

### Log output

```Shell
INFO Started local extension host with pid 44412.
log.ts:417  INFO Invoking resolveAuthority(wsl)...
log.ts:417  INFO [LocalProcess0][resolveAuthority(wsl,1)][0ms] obtaining proxy...
log.ts:417  INFO [LocalProcess0][resolveAuthority(wsl,1)][0ms] invoking...
log.ts:417  INFO [LocalProcess0][resolveAuthority(wsl,1)][261ms] returned WebSocket(127.0.0.1:65081)
log.ts:417  INFO resolveAuthority(wsl) returned 'WebSocket(127.0.0.1:65081)' after 261 ms
log.ts:417  INFO Creating a socket (renderer-Management-c19d11a5-f6d7-4e4d-96a0-b0b2042b620a)...
log.ts:417  INFO Creating a socket (renderer-ExtensionHost-a8b5891d-6900-43cc-a742-a58923a7fcd9)...
log.ts:417  INFO Creating a socket (renderer-Management-c19d11a5-f6d7-4e4d-96a0-b0b2042b620a) was successful after 86 ms.
webviewElement.ts:511 An iframe which has both allow-scripts and allow-same-origin for its sandbox attribute can escape its sandboxing.
mountTo @ webviewElement.ts:511
M @ overlayWebview.ts:218
claim @ overlayWebview.ts:120
fc @ webviewViewPane.ts:163
(anonymous) @ webviewViewPane.ts:94
y @ event.ts:1127
z @ event.ts:1138
fire @ event.ts:1162
setVisible @ viewPane.ts:392
(anonymous) @ viewPaneContainer.ts:682
setVisible @ viewPaneContainer.ts:682
setVisible @ panecomposite.ts:53
vb @ compositePart.ts:278
vb @ paneCompositePart.ts:218
tb @ compositePart.ts:156
sb @ compositePart.ts:120
jc @ paneCompositePart.ts:391
openPaneComposite @ paneCompositePart.ts:371
log.ts:417  INFO Creating a socket (renderer-ExtensionHost-a8b5891d-6900-43cc-a742-a58923a7fcd9) was successful after 301 ms.
TMScopeRegistry.ts:46 Overwriting grammar scope name to file mapping for scope source.js.
Old grammar file: file:///c%3A/Users/jpaveg/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/extensions/javascript/syntaxes/JavaScript.tmLanguage.json.
New grammar file: vscode-remote://wsl%2Bubuntu/home/jpaveg/.vscode-server/extensions/mgmcdermott.vscode-language-babel-0.0.40/grammars/Babel-Language.json
register @ TMScopeRegistry.ts:46
E @ TMGrammarFactory.ts:74
S @ textMateTokenizationFeatureImpl.ts:259
TMScopeRegistry.ts:46 Overwriting grammar scope name to file mapping for scope source.yaml.
Old grammar file: file:///c%3A/Users/jpaveg/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/extensions/yaml/syntaxes/yaml.tmLanguage.json.
New grammar file: vscode-remote://wsl%2Bubuntu/home/jpaveg/.vscode-server/extensions/redhat.vscode-yaml-1.14.0/syntaxes/yaml.tmLanguage.json
register @ TMScopeRegistry.ts:46
E @ TMGrammarFactory.ts:74
S @ textMateTokenizationFeatureImpl.ts:259
log.ts:427  WARN No search provider registered for scheme: vscode-remote, waiting
log.ts:417  INFO [perf] Render performance baseline is 15ms
console.ts:137 [Extension Host] rejected promise not handled within 1 second: EntryNotFound (FileSystemError): Error: ENOENT: no such file or directory, stat 'C:\home\jpaveg\code\project\backend\README.md'
p @ console.ts:137
$logExtensionHostMessage @ mainThreadConsole.ts:39
S @ rpcProtocol.ts:458
Q @ rpcProtocol.ts:443
M @ rpcProtocol.ts:373
L @ rpcProtocol.ts:299
(anonymous) @ rpcProtocol.ts:161
y @ event.ts:1127
fire @ event.ts:1158
fire @ ipc.net.ts:650
V.onmessage @ localProcessExtensionHost.ts:376
console.ts:137 [Extension Host] stack trace: EntryNotFound (FileSystemError): Error: ENOENT: no such file or directory, stat 'C:\home\jpaveg\code\project\backend\README.md'
	at k.e (c:\Users\jpaveg\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:149:6084)
	at Object.stat (c:\Users\jpaveg\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:149:3892)
	at async c:\Users\jpaveg\.vscode\extensions\continue.continue-0.9.73-win32-x64\out\extension.js:186943:25
	at async Promise.all (index 0)
	at async VsCodeIde.getStats (c:\Users\jpaveg\.vscode\extensions\continue.continue-0.9.73-win32-x64\out\extension.js:186941:9)
	at async CodebaseIndexer.refresh (c:\Users\jpaveg\.vscode\extensions\continue.continue-0.9.73-win32-x64\out\extension.js:157950:25)
	at async _VsCodeExtension.refreshCodebaseIndex (c:\Users\jpaveg\.vscode\extensions\continue.continue-0.9.73-win32-x64\out\extension.js:194558:26)
p @ console.ts:137
$logExtensionHostMessage @ mainThreadConsole.ts:39
S @ rpcProtocol.ts:458
Q @ rpcProtocol.ts:443
M @ rpcProtocol.ts:373
L @ rpcProtocol.ts:299
(anonymous) @ rpcProtocol.ts:161
y @ event.ts:1127
fire @ event.ts:1158
fire @ ipc.net.ts:650
V.onmessage @ localProcessExtensionHost.ts:376
mainThreadExtensionService.ts:81 [Continue.continue]Error: ENOENT: no such file or directory, stat 'C:\home\jpaveg\code\project\backend\README.md'
$onExtensionRuntimeError @ mainThreadExtensionService.ts:81
S @ rpcProtocol.ts:458
Q @ rpcProtocol.ts:443
M @ rpcProtocol.ts:373
L @ rpcProtocol.ts:299
(anonymous) @ rpcProtocol.ts:161
y @ event.ts:1127
fire @ event.ts:1158
fire @ ipc.net.ts:650
V.onmessage @ localProcessExtensionHost.ts:376
mainThreadExtensionService.ts:82 EntryNotFound (FileSystemError): Error: ENOENT: no such file or directory, stat 'C:\home\jpaveg\code\project\backend\README.md'
	at k.e (c:\Users\jpaveg\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:149:6084)
	at Object.stat (c:\Users\jpaveg\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:149:3892)
	at async c:\Users\jpaveg\.vscode\extensions\continue.continue-0.9.73-win32-x64\out\extension.js:186943:25
	at async Promise.all (index 0)
	at async VsCodeIde.getStats (c:\Users\jpaveg\.vscode\extensions\continue.continue-0.9.73-win32-x64\out\extension.js:186941:9)
	at async CodebaseIndexer.refresh (c:\Users\jpaveg\.vscode\extensions\continue.continue-0.9.73-win32-x64\out\extension.js:157950:25)
	at async _VsCodeExtension.refreshCodebaseIndex (c:\Users\jpaveg\.vscode\extensions\continue.continue-0.9.73-win32-x64\out\extension.js:194558:26)
$onExtensionRuntimeError @ mainThreadExtensionService.ts:82
S @ rpcProtocol.ts:458
Q @ rpcProtocol.ts:443
M @ rpcProtocol.ts:373
L @ rpcProtocol.ts:299
(anonymous) @ rpcProtocol.ts:161
y @ event.ts:1127
fire @ event.ts:1158
fire @ ipc.net.ts:650
V.onmessage @ localProcessExtensionHost.ts:376
console.ts:137 [Extension Host] Error retrieving from FTS: Error: SQLITE_ERROR: no such table: fts
p @ console.ts:137
$logExtensionHostMessage @ mainThreadConsole.ts:39
S @ rpcProtocol.ts:458
Q @ rpcProtocol.ts:443
M @ rpcProtocol.ts:373
L @ rpcProtocol.ts:299
(anonymous) @ rpcProtocol.ts:161
y @ event.ts:1127
fire @ event.ts:1158
fire @ ipc.net.ts:650
V.onmessage @ localProcessExtensionHost.ts:376
notificationsAlerts.ts:42 Error getting context items from codebase: Error: SQLITE_ERROR: no such table: lance_db_cache
c @ notificationsAlerts.ts:42
(anonymous) @ notificationsAlerts.ts:28
y @ event.ts:1127
z @ event.ts:1138
fire @ event.ts:1162
addNotification @ notifications.ts:228
notify @ notificationService.ts:253
(anonymous) @ mainThreadMessageService.ts:86
f @ mainThreadMessageService.ts:51
$showMessage @ mainThreadMessageService.ts:45
S @ rpcProtocol.ts:458
Q @ rpcProtocol.ts:443
M @ rpcProtocol.ts:373
L @ rpcProtocol.ts:299
(anonymous) @ rpcProtocol.ts:161
y @ event.ts:1127
fire @ event.ts:1158
fire @ ipc.net.ts:650
V.onmessage @ localProcessExtensionHost.ts:376
log.ts:437   ERR [Extension Host] Failed to parse AST TypeError: (0 , import_web_tree_sitter.init) is not a function
	at getParserForFile (c:\Users\jpaveg\.vscode\extensions\continue.continue-0.9.73-win32-x64\out\extension.js:49255:41)
	at getAst (c:\Users\jpaveg\.vscode\extensions\continue.continue-0.9.73-win32-x64\out\extension.js:187759:24)
	at constructAutocompletePrompt (c:\Users\jpaveg\.vscode\extensions\continue.continue-0.9.73-win32-x64\out\extension.js:187803:23)
	at _ContinueCompletionProvider.getTabCompletion (c:\Users\jpaveg\.vscode\extensions\continue.continue-0.9.73-win32-x64\out\extension.js:194039:63)
	at async _ContinueCompletionProvider.provideInlineCompletionItems (c:\Users\jpaveg\.vscode\extensions\continue.continue-0.9.73-win32-x64\out\extension.js:194166:27)
	at async B.provideInlineCompletions (c:\Users\jpaveg\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:150:110805)
console.ts:137 [Extension Host] Failed to parse AST TypeError: (0 , import_web_tree_sitter.init) is not a function
	at getParserForFile (c:\Users\jpaveg\.vscode\extensions\continue.continue-0.9.73-win32-x64\out\extension.js:49255:41)
	at getAst (c:\Users\jpaveg\.vscode\extensions\continue.continue-0.9.73-win32-x64\out\extension.js:187759:24)
	at constructAutocompletePrompt (c:\Users\jpaveg\.vscode\extensions\continue.continue-0.9.73-win32-x64\out\extension.js:187803:23)
	at _ContinueCompletionProvider.getTabCompletion (c:\Users\jpaveg\.vscode\extensions\continue.continue-0.9.73-win32-x64\out\extension.js:194039:63)
	at async _ContinueCompletionProvider.provideInlineCompletionItems (c:\Users\jpaveg\.vscode\extensions\continue.continue-0.9.73-win32-x64\out\extension.js:194166:27)
	at async B.provideInlineCompletions (c:\Users\jpaveg\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:150:110805)
```

**Comment by jpaveg** [comment]
Just updated to 0.9.77 and am getting a similar but different error now:

```console
mainThreadExtensionService.ts:81 [Continue.continue]Unable to resolve filesystem provider with relative file path 'vscode-remote:\home\jpaveg\code\project\backend\README.md'
$onExtensionRuntimeError @ mainThreadExtensionService.ts:81
mainThreadExtensionService.ts:82 Error (FileSystemError): Unable to resolve filesystem provider with relative file path 'vscode-remote:\home\jpaveg\code\project\backend\README.md'
	at k.e (c:\Users\jpaveg\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:149:7189)
	at Object.stat (c:\Users\jpaveg\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:149:3892)
	at async c:\Users\jpaveg\.vscode\extensions\continue.continue-0.9.77-win32-x64\out\extension.js:183798:25
	at async Promise.all (index 0)
	at async VsCodeIde.getStats (c:\Users\jpaveg\.vscode\extensions\continue.continue-0.9.77-win32-x64\out\extension.js:183792:9)
	at async CodebaseIndexer.refresh (c:\Users\jpaveg\.vscode\extensions\continue.continue-0.9.77-win32-x64\out\extension.js:147525:25)
	at async _VsCodeExtension.refreshCodebaseIndex (c:\Users\jpaveg\.vscode\extensions\continue.continue-0.9.77-win32-x64\out\extension.js:184665:26)
$onExtensionRuntimeError @ mainThreadExtensionService.ts:82
console.ts:137 [Extension Host] Error retrieving from FTS: Error: SQLITE_ERROR: no such table: fts
p @ console.ts:137
notificationsAlerts.ts:42 Error getting context items from codebase: Error: SQLITE_ERROR: no such table: lance_db_cache
```

**Comment by jpaveg** [comment]
As of 0.9.79, I still receive the error `Error: SQLITE_ERROR: no such table: lance_db_cache` / `fts` in VSCode's dev tools log when trying to use the `@codebase` directive


Full output:
```console
[Extension Host] Error retrieving from FTS: Error: SQLITE_ERROR: no such table: fts
p @ console.ts:137
$logExtensionHostMessage @ mainThreadConsole.ts:39
S @ rpcProtocol.ts:458
Q @ rpcProtocol.ts:443
M @ rpcProtocol.ts:373
L @ rpcProtocol.ts:299
(anonymous) @ rpcProtocol.ts:161
y @ event.ts:1127
fire @ event.ts:1158
fire @ ipc.net.ts:650
V.onmessage @ localProcessExtensionHost.ts:376
notificationsAlerts.ts:42

Error getting context items from codebase: Error: SQLITE_ERROR: no such table: lance_db_cache
c @ notificationsAlerts.ts:42
(anonymous) @ notificationsAlerts.ts:28
y @ event.ts:1127
z @ event.ts:1138
fire @ event.ts:1162
addNotification @ notifications.ts:228
notify @ notificationService.ts:253
(anonymous) @ mainThreadMessageService.ts:86
f @ mainThreadMessageService.ts:51
$showMessage @ mainThreadMessageService.ts:45
S @ rpcProtocol.ts:458
Q @ rpcProtocol.ts:443
M @ rpcProtocol.ts:373
L @ rpcProtocol.ts:299
(anonymous) @ rpcProtocol.ts:161
y @ event.ts:1127
fire @ event.ts:1158
fire @ ipc.net.ts:650
V.onmessage @ localProcessExtensionHost.ts:376
```

**Comment by majuansari** [comment]
@jpaveg  is this fixed for you? I am still getting SQLITE_ERROR: no such table: lance_db_cache

**Comment by jpaveg** [comment]
Delete the .continue folder and go to pre-release, idk what else you could
try
