### ISSUE TITLE
Failed to parse AST TypeError

### ISSUE THREAD

**Issue by Sinan-Karakaya** [continuedev/continue#905]
### Before submitting your bug report

- [ ] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [X] I've seen the [troubleshooting guide](https://continue.dev/docs/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS: MacOS Sonoma 14.3
- Continue: v0.9.73 (pre-release)
- IDE: VSCode 1.87.0

Ollama (deepseek-coder 6.7b for FIM) hosted on a server that uses https + Bearer token.
```

### Description

When adding a character to the code, this error will trigger. FIM are still working, but sometimes the line will be cut short, even when the limit of generated token is far from being reached.

### To reproduce

1. Setup a Ollama instance on a protected https server
2. Write any character in a file
3. Voila

### Log output

```Shell
Failed to parse AST TypeError: (0 , import_web_tree_sitter.init) is not a function
	at getParserForFile (/Users/username/.vscode/extensions/continue.continue-0.9.73-darwin-arm64/out/extension.js:49257:41)
	at getAst (/Users/username/.vscode/extensions/continue.continue-0.9.73-darwin-arm64/out/extension.js:187760:24)
	at constructAutocompletePrompt (/Users/username/.vscode/extensions/continue.continue-0.9.73-darwin-arm64/out/extension.js:187804:23)
	at _ContinueCompletionProvider.getTabCompletion (/Users/username/.vscode/extensions/continue.continue-0.9.73-darwin-arm64/out/extension.js:194040:63)
	at async _ContinueCompletionProvider.provideInlineCompletionItems (/Users/username/.vscode/extensions/continue.continue-0.9.73-darwin-arm64/out/extension.js:194167:27)
	at async B.provideInlineCompletions (/Users/username /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:150:110805)
```

**Comment by sestinj** [comment]
@Sinan-Karakaya thanks for the quick report! this should now be resolved in 0.9.74, but I'll wait to close the issue until you've confirmed

**Comment by Sinan-Karakaya** [comment]
Thanks for the fix, I confirm that the error went away after 0.9.74. Thanks, and closing now
