### ISSUE TITLE
Pycharm fails

### ISSUE THREAD

**Issue by josephwinston** [continuedev/continue#907]
### Before submitting your bug report

- [ ] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [ ] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [X] I've seen the [troubleshooting guide](https://continue.dev/docs/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS:Windows 11
- Continue: 0.0.33
- IDE:PyCharm 
PyCharm 2023.3.3 (Community Edition)
Build #PC-233.13763.11, built on January 25, 2024
Runtime version: 17.0.9+7-b1087.11 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 11.0
GC: G1 Young Generation, G1 Old Generation
Memory: 4096M
Cores: 20
Registry:
  ide.experimental.ui=true
Non-Bundled Plugins:
  com.github.continuedev.continueintellijextension (0.0.33)
  MatlabSupport (0.8.5)
  com.intellij.grazie.pro (0.3.287)
```

### Description

java.lang.Throwable: An editable copy of Default has not been initialized.
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:376)
	at com.intellij.openapi.editor.colors.impl.EditorColorsManagerImpl.getDefaultScheme(EditorColorsManagerImpl.kt:368)
	at com.intellij.openapi.editor.colors.impl.EditorColorsManagerImpl.getGlobalScheme(EditorColorsManagerImpl.kt:360)
	at com.github.continuedev.continueintellijextension.continue.GetTheme.getTheme(GetTheme.kt:14)
	at com.github.continuedev.continueintellijextension.activities.ContinuePluginStartupActivity.initializePlugin(ContinuePluginStartupActivity.kt:146)
	at com.github.continuedev.continueintellijextension.activities.ContinuePluginStartupActivity.runActivity$lambda$0(ContinuePluginStartupActivity.kt:112)
	at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:249)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:840)

**Comment by sestinj** [comment]
@josephwinston Thank you for the report! I will aim to fix this for the next release on Monday

**Comment by RomneyDa** [comment]
@josephwinston do you still see this with recent versions of Continue?

**Comment by sestinj** [comment]
I'm going to close this since it's solved to the best of our knowledge and I haven't heard anything, but on the chance I'm overlooked something please re-open!
