### ISSUE TITLE
Crashes extension host on Ubuntu

### ISSUE THREAD

**Issue by G-Cyrille** [continuedev/continue#911]
Type: <b>Bug</b>

Crashes extension host on Ubuntu (new ubuntu & vscode install) install.
Installed from sync account settings

Extension version: 0.9.74
VS Code version: Code 1.87.0 (019f4d1419fbc8219a181fab7892ebccf7ee29a2, 2024-02-27T23:42:16.599Z)
OS version: Linux x64 6.5.0-21-generic snap
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-2600K CPU @ 3.40GHz (8 x 3511)|
|GPU Status|2d_canvas: unavailable_software<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>opengl: disabled_off<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software<br>webgpu: disabled_off|
|Load (avg)|2, 1, 1|
|Memory (System)|15.59GB (13.00GB free)|
|Process Argv|--no-sandbox --force-user-env --unity-launch --crash-reporter-id 21fc2607-06ed-496c-92ee-91a79c28047d|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|wayland|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:30899288
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
pythontbext0:30879054
accentitlementsc:30887149
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
pydisww2:30959801
d34g3935:30971562
edj9j583:30969295
fegfb526:30973843
bg6jg535:30958357
78248357:30976999
dsvsc020:30976470

```

</details>

**Comment by sestinj** [comment]
@G-Cyrille Thank you for the report. Do you find any error logs if you do ctrl+shift+P, "Toggle Developer Tools" and look in the console? This is the most likely place to shed light on the problem

**Comment by Lucki** [comment]
I think I have the same problem.
The crashes only happen inside workspaces. Editing single files is fine.
When it crashes the host, it's at an "indexing" step.

~~~ txt
Version: 1.87.0
Commit: 019f4d1419fbc8219a181fab7892ebccf7ee29a2
Datum: 2024-03-01T14:16:19.238Z
Electron: 27.3.4
ElectronBuildId: undefined
Chromium: 118.0.5993.159
Node.js: 18.17.1
V8: 11.8.172.18-electron.0
Betriebssystem: Linux x64 6.7.8-arch1-1
~~~

<details>
<summary>The following lines are related to the crash or this extension visible in the dev console</summary>

~~~ txt
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'title') https://file+.vscode-resource.vscode-cdn.net/home/lucki/.vscode/extensions/continue.continue-0.8.14-linux-x64/gui/assets/index.js
    at setConfig (index.js:400:3418)
    at index.js:285:28771
    at produce (index.js:285:10336)
    at index.js:285:28743
    at Array.reduce (<anonymous>)
    at oI (index.js:285:28631)
    at reducer (index.js:285:30000)
    at index.js:285:16741
    at index.js:3391:9798
    at GI (index.js:285:15496)
~~~
~~~ txt
Extension host (LocalProcess pid: 33135) terminated unexpectedly. Code: 132, Signal: unknown
~~~
~~~ txt
ERR Extension host (LocalProcess pid: 33135) terminated unexpectedly. No extensions were activated.
~~~
~~~ txt
INFO Automatically restarting the extension host.
~~~
~~~ txt
INFO Started local extension host with pid 33951.
~~~
~~~ txt
localProcessExtensionHost.ts:274 [Error: ENOENT: no such file or directory, open '/home/lucki/.config/Code/clp/8c2a02529fc8c1ad67791b0bf1e0b17c.de/corrupted.info'] {  errno: -2,  code: 'ENOENT',  syscall: 'open',  path: '/home/lucki/.config/Code/clp/8c2a02529fc8c1ad67791b0bf1e0b17c.de/corrupted.info'}
~~~
~~~ txt
console.ts:137 [Extension Host] Error listing models:  TypeError: fetch failed
at Object.fetch (node:internal/deps/undici/undici:11576:11)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
at async OpenAI.listModels (/home/lucki/.local/share/vscode-oss/extensions/continue.continue-0.8.14-linux-x64/out/extension.js:147507:26)
at async intermediateToFinalConfig (/home/lucki/.local/share/vscode-oss/extensions/continue.continue-0.8.14-linux-x64/out/extension.js:162768:30)
at async loadFullConfigNode (/home/lucki/.local/share/vscode-oss/extensions/continue.continue-0.8.14-linux-x64/out/extension.js:162928:23)
at async VsCodeConfigHandler.loadConfig (/home/lucki/.local/share/vscode-oss/extensions/continue.continue-0.8.14-linux-x64/out/extension.js:172286:30)
at async vsCodeIndexCodebase (/home/lucki/.local/share/vscode-oss/extensions/continue.continue-0.8.14-linux-x64/out/extension.js:179240:18)
p @ console.ts:137
$logExtensionHostMessage @ mainThreadConsole.ts:39
S @ rpcProtocol.ts:458
Q @ rpcProtocol.ts:443
M @ rpcProtocol.ts:373
L @ rpcProtocol.ts:299
(anonymous) @ rpcProtocol.ts:161
y @ event.ts:1127
fire @ event.ts:1158
fire @ ipc.net.ts:650
V.onmessage @ localProcessExtensionHost.ts:376
~~~

</details>

**Comment by G-Cyrille** [comment]
Hi,

Thank you for answering on this.

My console says in a loop 3 times before stopping all extensions :
```
log.ts:417
   - INFO Automatically restarting the extension host.
webWorkerExtensionHostIframe.html:1
   - An iframe which has both allow-scripts and allow-same-origin for its sandbox attribute can escape its sandboxing.
log.ts:417
   - INFO Started local extension host with pid 6609.
console.ts:137
   - [Extension Host] swdc-tracker initialized and ready to send events to snow.software.com
   abstractExtensionService.ts:790 Extension host (LocalProcess pid: 6609) terminated unexpectedly. Code: 132, Signal: unknown
   yb @ abstractExtensionService.ts:790
   yb @ nativeExtensionService.ts:167
   xb @ abstractExtensionService.ts:782
   (anonymous) @ abstractExtensionService.ts:755
   y @ event.ts:1127
   fire @ event.ts:1158
   J @ localProcessExtensionHost.ts:521
   (anonymous) @ localProcessExtensionHost.ts:282
   y @ event.ts:1127
   fire @ event.ts:1158
   le @ ipc.ts:675
   t @ ipc.ts:743
   s @ ipc.ts:732
   (anonymous) @ ipc.ts:549
   y @ event.ts:1127
   z @ event.ts:1138
   fire @ event.ts:1162
   he @ event.ts:559
   emit @ VM114 sandbox_bundle:2
   onMessage @ VM114 sandbox_bundle:2
log.ts:437
   - ERR Extension host (LocalProcess pid: 6609) terminated unexpectedly. No extensions were activated.
```

![image](https://github.com/continuedev/continue/assets/59730588/4cd47dd0-a033-480b-a27a-ba6a50d8a7f1)

If there anything I can do to provide more information let me know.

**Comment by Lucki** [comment]
Ref: https://discord.com/channels/1108621136150929458/1219331252629536799

It's somewhere crashing in LanceDB.

**Comment by r-o-n-i** [comment]
Any updates? This makes continue unusable on Ubuntu.

**Comment by Lucki** [comment]
Workarounds until this is fixed:
* Add `"disableIndexing": true,` to your config.
* Only edit single files instead of workspaces.

**Comment by sttzr** [comment]
Same issue here on Ubuntu 22.04. At least the workaround by @Lucki helps.

**Comment by cdenovo** [comment]
@sestinj any updates? There are quite a few open issues regarding this problem.

**Comment by apmcodes** [comment]
@sestinj any updates? There are quite a few open issues regarding this problem.

**Comment by sestinj** [comment]
@cdenovo @apmcodes can you provide any more details on what error logs you are seeing? Given the time between this issue originally being opened and now it's important to be sure that they are actually the same problem

**Comment by cdenovo** [comment]
@sestinj the logs have almost no information (including when using the Developer Console). My logs are identical to those posted by @G-Cyrille above:
https://github.com/continuedev/continue/issues/911#issuecomment-1981528094

**Comment by G-Cyrille** [comment]
It might be worth noting that I since changed my computer and unix distribution -> I don't have any issue (still using the same vscode account).

**Comment by Lucki** [comment]
Since around version `v0.9.194 (pre-release)` the previously mentioned workarounds (https://github.com/continuedev/continue/issues/911#issuecomment-2051956123) don't work anymore. This extension is now always crashing the host and I have to deactivate to use any extensions at all.

**Comment by cdenovo** [comment]
> It might be worth noting that I since changed my computer and unix distribution -> I don't have any issue (still using the same vscode account).

Do you mean you switched to a non-Ubuntu-based distro?

**Comment by cdenovo** [comment]
> Since around version `v0.9.194 (pre-release)` the previously mentioned workarounds ([#911 (comment)](https://github.com/continuedev/continue/issues/911#issuecomment-2051956123)) don't work anymore. This extension is now always crashing the host and I have to deactivate it to use any extensions at all.

I just tried again today and I'm still getting the crashing extension host. Tried setting `"continue.pauseCodebaseIndexOnStart": true` but that didn't change anything.

**Comment by G-Cyrille** [comment]
> > It might be worth noting that I since changed my computer and unix distribution -> I don't have any issue (still using the same vscode account).
> 
> Do you mean you switched to a non-Ubuntu-based distro?

I switched to popOS which is based on Ubuntu.

**Comment by RickySupriyadi** [comment]
any luck mine still the same :/

**Comment by cdenovo** [comment]
On Kubuntu 22.04 today, still crashes on a fresh VSCode install after removing all global and user config files.

**Comment by ButlerJoseph** [comment]
I have the same issue on vscode 1.931, the last working version of the extension is 0.8.23

**Comment by synth-mania** [comment]
I'm on fedora 41 workstation on my laptop and it crashes every time as well. I use fedora 41 workstation on my desktop with this extension with zero issues.

Software versions
 - Continue v0.8.60
 - Fedora Linux 41 - kernel 6.11.4-301.fc41.x86_64

 Hardware:
 - Make/Model: Lenovo Thinkpad T400
 - Memory: 8gb
 - CPU: 2 core, 2 thread Intel Core2Duo
 - Architecture: x86_64

**Comment by cdenovo** [comment]
Tested this again today on Kubuntu 22.04, and it no longer crashes! I'm using the same OS install, but the hardware is completely different.

**Comment by lucasnewkirk** [comment]
Still getting this error on **Pop OS 22.04** using **VS Code 1.96.2** and **Continue 0.9.250**. The extension host crashes and fails to restart.

**Comment by crashr** [comment]
I also still get the error on Ubuntu 22.04 using VSCodium 1.96.2. Last usable version is 0.8.44.

**Comment by lucasnewkirk** [comment]
I was able to get it working on my laptop with the same OS, Pop OS 22.04. However, the machine it does not work on is a VM hosted on Proxmox, so it uses hardware virtualization. Could this be an issue? Is anyone else with an issue using a VM or LXC?

**Comment by lucasnewkirk** [comment]
> I was able to get it working on my laptop with the same OS, Pop OS 22.04. However, the machine it does not work on is a VM hosted on Proxmox, so it uses hardware virtualization. Could this be an issue? Is anyone else with an issue using a VM or LXC?

Yep! The VM was my issue. I created a VM in Proxmox and had to change my processor type to `host` so the VM knew what CPU I was using. I'm speculating that Continue couldn't determine what hardware I had. Please let me know if this was the case for anyone else. Hopefully this comment helps someone 😃

**Comment by apunkt** [comment]
I still have this problem on a bare metal Ubuntu 22.04
My Workstation is using old Intel Xeon X5670 w/out AVX support. This has been recently the cause of multiple issues, could this be related?

**Comment by copyrighthero** [comment]
> I still have this problem on a bare metal Ubuntu 22.04
> 
> My Workstation is using old Intel Xeon X5670 w/out AVX support. This has been recently the cause of multiple issues, could this be related?

Oh I think that might be it; I was running it on a Debian system with Pentium chip that doesn't have some instructions sets, and both Continue as well as MongoDB won't work.

It might be that LanceDB requires those instruction sets.

**Comment by crashr** [comment]
> > I still have this problem on a bare metal Ubuntu 22.04
> > My Workstation is using old Intel Xeon X5670 w/out AVX support. This has been recently the cause of multiple issues, could this be related?
> 
> Oh I think that might be it; I was running it on a Debian system with Pentium chip that doesn't have some instructions sets, and both Continue as well as MongoDB won't work.
> 
> It might be that LanceDB requires those instruction sets.

Yeah, seems to be it.
https://github.com/lancedb/lancedb/issues/1437#issuecomment-2216951701
My CPU lacks AVX2

**Comment by cdenovo** [comment]
> > > I still have this problem on a bare metal Ubuntu 22.04
> > > My Workstation is using old Intel Xeon X5670 w/out AVX support. This has been recently the cause of multiple issues, could this be related?
> > 
> > 
> > Oh I think that might be it; I was running it on a Debian system with Pentium chip that doesn't have some instructions sets, and both Continue as well as MongoDB won't work.
> > It might be that LanceDB requires those instruction sets.
> 
> Yeah, seems to be it. [lancedb/lancedb#1437 (comment)](https://github.com/lancedb/lancedb/issues/1437#issuecomment-2216951701) My CPU lacks AVX2. There is a workaround as to my understanding. [lancedb/lancedb#1018](https://github.com/lancedb/lancedb/issues/1018) Good find @lucasnewkirk

Yes, I think that's it. My old CPU had AVX (not AVX2) and my new one has AVX2.

**Comment by NerdyShawn** [comment]
This happens for me as well on ubuntu 22.04 and reformatted fresh 24.04. Its on a 12 year old laptop i7 (AVX not AVX2) cpu.

**Comment by aoliva71** [comment]
I got indexing working on an old i3 without "avx2" and "fma" following these steps:
1) build lancedb (the nodejs part) with just the relevant cpu features (in my case "avx");
2) patch the code @Patrick-Erichsen added to detect old cpu (or rather cpu with missing features): core/config/util.ts function isSupportedLanceDbCpuTarget to make it return true;
3) build continue as per CONTRIBUTING.md;
4) unzip the packaged .vsix file (which is just a zipfile) and replace "extension/out/node_modules/@lancedb/vectordb-linux-x64-gnu/index.node" with lancedb/nodejs/dist/lancedb.linux-x64-gnu.node from step 1 (renamed to index.node);
5) zip back the unzipped .vsix;
6) install the extension and enjoy lastest continue (0.9.259 at the time I'm writing this) with indexing working nicely.

There are much clever ways to deal with the dependency than forcing the lancedb nodejs binary but I'm not a nodejs person myself, however the steps above can easily be scripted or turned into ci/cd tasks.

**Comment by crashr** [comment]
For me personally it's not worth the effort, I'll just stick with v0.8.44 until it's fixed. Although it should already be fixed, according to the changelog in https://github.com/continuedev/continue/releases/tag/v0.9.251-vscode
So it would be much more interesting to know why the fix obviously doesn't work.

**Comment by aoliva71** [comment]
Hi @erikerosev, I would only add that if you don't remove the cpu detection from `isSupportedLanceDbCpuTarget`, indexing will be disabled, which will be a shame, considering you just built a working lancedb for your system... ;)

Also note (@crashr) to my understanding, the point of the patch Patrick-Erichsen created is to disable lancedb on old systems, new versions of continue.dev will not crash but they won't index your codebase on old cpus.

**Comment by crashr** [comment]
I just tried the newest pre-release version. Looks good. i don't expierience any issues so far. Thanks!

**Comment by NerdyShawn** [comment]
just tried 1.1.11
handling the cpu detection better for me on my ~12year old laptop now and I'm able to get in and configure things like a remote k8s ollama now, thanks!

![Image](https://github.com/user-attachments/assets/d1580fc6-4807-42bd-af97-aaeed7fd880d)
