### ISSUE TITLE
Dev containers compatibility

### ISSUE THREAD

**Issue by Cianidos** [continuedev/continue#928]
### Before submitting your bug report

- [X] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [X] I've seen the [troubleshooting guide](https://continue.dev/docs/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS: macOS 14.3.1
- Continue: v0.9.79 (pre-release)
- IDE: VSCode

ollama 0.1.27
using devcontainer
```

### Description

While using tab autocomplete inside dev container, got next message:
```
Unable to read file '/workspaces/path-to-in-dev-container/main.go' (Error: Unable to resolve nonexistent file '/workspaces/path-to-in-dev-container/main.go')
```

I think it tries get context, but looks on host, instead real path to volume
When I use chat with file as context, everything ok

thanks in advance

### To reproduce

open folder in dev container
enable tab complete
typing

### Log output

```Shell
[Extension Host] Error generating autocompletion:  Error: Unable to read file '/workspaces/go-templ-ctl/src/cli/main.go' (Error: Unable to resolve nonexistent file '/workspaces/go-templ-ctl/src/cli/main.go')
    at n.F (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:657:19968)
    at n.D (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:657:19763)
    at async f.M (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2203:42897)
    at async f.readStream (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2203:42654)
    at async L.Cb (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2192:13459)
    at async L.resolve (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2192:11906)
    at async s.W (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2203:39048)
    at async h.r (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2192:25544)
    at async C.acquire (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:37:3392)
    at async u.createModelReference (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2192:27121)
p @ console.ts:137
```

**Comment by LTangaF** [comment]
I've seen this, too. I disabled tab-completion to avoid it, though I was hoping to try using it. Containers and remote containers is my normal operating mode.

**Comment by aharonamir** [comment]
I also that the option for remote-container/linux will be available as I am developing from windows on a remote linux, and the ollama runs on windows

**Comment by LTangaF** [comment]
Local containers just seems like a directory mapping issue. Remote containers may just be that, but it may also be that the extension is largely running in the local chromium environment, but the file browser (etc) is being served up by a remote vscode server

**Comment by aharonamir** [comment]
My issue is that the extension runs on the local machine, which is windows but the code is on the remote machine, which is linux.
So it cannot access the file on the remote or cannot handle the linux file path (the '/' instead of \')

**Comment by jpaveg** [comment]
Also having this issue. Seeing this error:
```console
Unable to read file '\jpaveg\code\tutorials\nextjs\app\lib\data.ts' (Error: Unable to resolve nonexistent file '\jpaveg\code\tutorials\nextjs\app\lib\data.ts')
```
The correct filePath should be prepended with `home/`. Seems similar to a previous issue involving remote containers.

**Comment by kicedz** [comment]
I'm using WSL2 Ubuntu (with Docker too) on my Windows machine, also dockerized containers. 
I'm getting the same error Unable to read file >> from my wsl2 ubuntu. 
Any fixes?

**Comment by jpaveg** [comment]
> I'm using WSL2 Ubuntu (with Docker too) on my Windows machine, also dockerized containers. I'm getting the same error Unable to read file >> from my wsl2 ubuntu. Any fixes?

make sure you're on pre-release

**Comment by platform-kit** [comment]
Is this solved?

**Comment by olecsys** [comment]
Hey guys, any updates on this issue?

**Comment by sanderbollen-clockworks** [comment]
Any updates on this? We are experiencing similar behaviour on remote development feature in Jetbrains products.

**Comment by ansible42** [comment]
I got it working in VSCode by opening up the proxy. Still having issues getting it working with clion 

```json
			"settings": {
				"extensions.verifySignature": false,
				"http.proxy": "(your_proxy_host:port)", //This is because of issues with the corp proxyhttps://stackoverflow.com/questions/55992660/vscode-remote-container-extensions-not-installing-on-dev-container-using-docke
				"http.proxyStrictSSL": false
			}
```

**Comment by samrocketman** [comment]
This does not appear to be completed for VS Code Dev Containers.

* ✅ Can chat
* ✅ Can read and write files when loaded in devcontainer.  Only if extension is installed in the devcontainer.
* ❌ Runs on the host if installed on host. In devcontainer should only run within devcontainer.
*  ❌ Cannot ask the agent to do any shell commands when in devcontainer.  e.g. ask agent to run `ls` and it cannot.

My host is PopOS 24.04 Linux (not Mac).
