### ISSUE TITLE
Plugin fails to load in IntelliJ IDEA

### ISSUE THREAD

**Issue by callumbirks** [continuedev/continue#973]
### Before submitting your bug report

- [X] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [X] I've seen the [troubleshooting guide](https://continue.dev/docs/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS: Linux 6.7.9-arch1-1, KDE Plasma 6.0.2
- Continue: 0.0.38
- IDE: IntelliJ IDEA 2023.3.5 (Community Edition)
Build #IC-233.14808.21, built on March 13, 2024
Runtime version: 17.0.10+7 amd64
```

### Description

Plugin fails to load

### To reproduce

1. Attempt to load the plugin

### Log output

```Shell
java.lang.Throwable: An editable copy of Default has not been initialized.
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:376)
	at com.intellij.openapi.editor.colors.impl.EditorColorsManagerImpl.getDefaultScheme(EditorColorsManagerImpl.kt:369)
	at com.intellij.openapi.editor.colors.impl.EditorColorsManagerImpl.getGlobalScheme(EditorColorsManagerImpl.kt:361)
	at com.github.continuedev.continueintellijextension.continue.GetTheme.getTheme(GetTheme.kt:15)
	at com.github.continuedev.continueintellijextension.activities.ContinuePluginStartupActivity.initializePlugin(ContinuePluginStartupActivity.kt:146)
	at com.github.continuedev.continueintellijextension.activities.ContinuePluginStartupActivity.runActivity$lambda$0(ContinuePluginStartupActivity.kt:112)
	at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:249)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:840)
```
```

**Comment by RomneyDa** [comment]
@callumbirks are you able to use more recent versions of continue?
